### ISSUE TITLE
[FEATURE REQUEST] Validate submol.yaml before running the pipeline and improved error messages

### ISSUE THREAD

**Issue by MrTomRod** [ncbi/pgap#101]
I've had to run PGAP for others quite often now. I had to instruct them how to create `submol.yaml` files, and we ran into errors often. The errors were often not very helpful. (Example: if "street" is missing from "contact_info".) Also, the pipeline tends to take a few moments to notice errors in yamls, which was a bit annoying.

So I decided to write these scripts:

-  `pgap_yaml_creator.py`: enables the semi-automatic creation of `submol.yaml`-files using the Jinja2 templating language.
-  `pgap_yaml_validator.py`: I converted the instructions on [PGAP wiki](https://github.com/ncbi/pgap/wiki/Input-Files) into code that can check whether the formatting is correct. I found a fantastic library that enables this very easily: [schema](https://pypi.org/project/schema/).

This is the repository: [PGAP Yaml Creator](https://gitlab.bioinformatics.unibe.ch/troder/pgap_yaml_creator)

I think having an input check, such as `pgap_yaml_validator.py`, would be an improvement, especially from a design-by-contract perspective.

BTW: Thanks for the last update! It really improved RAM usage!

**Comment by azat-badretdin** [comment]
Thank you for your support and suggestion! The main guiding principle behind the code of current `pgap.py` is to be "easy" on package dependencies, so the users won't have to get lost in installation procedure of dependence packages. That principle puts certain limitations on what this script can do. We are discussing various ways of improving that in our group.

**Comment by MrTomRod** [comment]
I think the Jinja2 dependency could be replaced relatively easily with F-strings.

Before I found the `schema` library, I actually implemented it myself! [See here.](https://gitlab.bioinformatics.unibe.ch/troder/pgap_yaml_creator/-/blob/f0c3b9a26fc760f3a44d97fd7f556691b8f3e487/pgap_yaml_creator.py)

The only problem I see is parsing YAML. It's probably not straightforward given that it's not in the Python standard library (as opposed to JSON) and there are two competing parsers (pyyaml and ruamel.yaml)...

**Comment by whlavina** [comment]
Thank you for your suggestions. However, we believe that maintaining minimal dependencies is a priority. We will try to improve error messages in our software, but our validation shall remain as part of the execution within the Docker container.

For end-user convenience when editing YAML, we recommend using industry-standard YAML tooling, such as a schema-aware text editor. We intended to pursue this, but the maturity of YAML tooling has been a hindrance.

The most promising solution is probably to publish a JSON Schema (also applies to the subset of YAML that is JSON-compatible), via the [JSON Schema Store](https://www.schemastore.org/) and/or via Microsoft’s [YAMLMime](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-yaml) extension (currently undocumented and possibly internal to Microsoft). Doing so would provide autocomplete and validation during editing in Visual Studio Code and other editors.

We will investigate this option of publishing schemas. In the meanwhile, we are closing this issue.

**Comment by MdUmar-tech** [comment]
suppose the bacteria is novel, mena novel unkown genus under rhodobactereceae family,  then in that case how to enter the genus_species name on submole file

**Comment by azat-badretdin** [comment]
You have to register it in NCBI Taxonomy first.

**Comment by thibaudnis** [comment]
PGAP requires the genus to determine which genetic code to use when predicting genes. You can put your best guess for a genus in the genus_species field of the YAML, and then run PGAP with --taxcheck-only first. (Please see our documentation for the [input files](https://github.com/ncbi/pgap/wiki/Input-Files)). [The results of taxcheck](https://github.com/ncbi/pgap/wiki/Taxonomy-Check) will hopefully give you a sense of the genus, if not the species. Use the information to adjust the genus_species name in the yaml and run PGAP again (no taxcheck needed this time).
