### ISSUE TITLE
[BUG] <title> pgapx_yaml_ctl throws an Exception ：No default  input topology specified in JSON file, presuming linear

### ISSUE THREAD

**Issue by zhengxinchang** [ncbi/pgap#103]
**Describe the bug**
Dear Developers,
I have a problem when I run pgap without topology record in submol.yaml. I have a fasta in which the seqs have different topologies. So I reformat the seq header as >seqid [topology=linear/circular] as described in pgap wiki page. When I check the cwllog.txt, the pgapx_yaml_ctl throws "No default input topology specified in JSON file, presuming linear" but the pgap was still running. I am asking for your help to verify whether this exception would influence the results.
 
Thank you very much!
 
Xinchang Zheng
 
**To Reproduce**
I got the exception first in my own genome but i repeated it in the example MG37 genome. I just removed the topology in the MG37 submo.yaml, and got the same maessage. 
 
**Expected behavior**
I expected that the pgapx_yaml_ctl will deal with this situation in a better way.

**Software versions (please complete the following information):**
 - OS: CentOS Linux release 7.4.1708 (Core)
 - pgap.py version 2020-07-09.build4716
 - Docker (or other container runner) version： Docker version 19.03.9, build 9d988398e7

**Log Files**
[2020-10-16 10:21:08] INFO [workflow prepare_input_template] starting step pgapx_yaml_ctl
[2020-10-16 10:21:08] INFO [step pgapx_yaml_ctl] start
[2020-10-16 10:21:08] INFO [job pgapx_yaml_ctl] /tmp/4inmw6j4$ pgapx_yaml_ctl \
    -ifmt \
    JSON \
    -input \
    /tmp/tmpd1dp6sod/stgdd5971d2-5253-4533-9c87-f67e1232c9ad/submol.json \
    -input-fasta \
    /tmp/tmpd1dp6sod/stg5be411a1-1066-4459-ad9c-27e8469323bb/GWHAAAE00000000.genome.with_Example_header.fasta \
    -ofmt \
    JSON \
    -output-annotation \
    input.asn \
    -output-asn-type \
    input_asn_type.txt \
    -output-ltp \
    genome.ltp.txt \
    -output-taxid \
    taxid.txt \
    -taxon-db \
    /tmp/tmpd1dp6sod/stg91d71c08-c0c1-464d-91b1-38185961d55d/taxonomy.sqlite3
ignoring failure of pgapx_yaml_input.GetFasta
No default  input topology specified in JSON file, presuming linear
Error: (308.5) [some bogus value]  Service not found
Error: (315.2) CConn_Streambuf::CConn_Streambuf():  NULL connector: Unknown
Error: (802.5) CObjectOStream: error at byte 6: stack is empty: write fault
Error: (308.5) [some bogus value]  Service not found
Error: (315.2) CConn_Streambuf::CConn_Streambuf():  NULL connector: Unknown
Error: (802.5) CObjectOStream: error at byte 6: stack is empty: write fault
DEBUG: ! taxid_genus == 1993, Streptomyces : is_complete = 0
DEBUG: GetOrgRef returned: Org-ref ::= {
  taxname "Bacillus licheniformis",
  db {
    {
      db "taxon",
      tag id 1402
    }
  },
  orgname {
    name binomial {
      genus "Bacillus",
      species "licheniformis"
    },
    attrib "specified",
    lineage "Bacteria; Firmicutes; Bacilli; Bacillales; Bacillaceae; Bacillus",
    gcode 11,
    div "BCT"
  }
}
Error: can't get biosample
Error: can't get bioproject
Error: ignoring failure to GetUserObjectDBLink
DEBUG: molinfo_found=true
DEBUG: CSeqdesc::e_Molinfo: Seqdesc ::= molinfo {
  biomol genomic,
  tech wgs,
  completeness partial
}
removing cit_sub from individual seq-entries in seq-submit
Seq-submit composed
[2020-10-16 10:21:19] INFO [job pgapx_yaml_ctl] Max memory used: 28MiB
[2020-10-16 10:21:19] INFO [job pgapx_yaml_ctl] completed success
[2020-10-16 10:21:19] INFO [step pgapx_yaml_ctl] completed success

**Additional context**

**Comment by azat-badretdin** [comment]
According to the log file you posted (we appreciate greatly that you followed the format, BTW! Thanks!) the CWL step that produced the error finished successfully, so, despite the word Error in the output, this was not a deal breaker error. 

Please confirm that you were able to produce the annotation results for your input.

**Comment by zhengxinchang** [comment]
> According to the log file you posted (we appreciate greatly that you followed the format, BTW! Thanks!) the CWL step that produced the error finished successfully, so, despite the word Error in the output, this was not a deal breaker error.
> 
> Please confirm that you were able to produce the annotation results for your input.

Thank you very much for your kind reply. 
We have checked the results and confirmed that we had the annotation results despite this exception.

Sincerely,
Xinchang Zheng
2020-10-17
