### ISSUE TITLE
Using Singularity instead of docker!

### ISSUE THREAD

**Issue by as7a5** [ncbi/pgap#105]
Hi we dont have docker installed on our cluster and because of its security features we have singularity. Is it possible to modify/add pgap to use Singularity instead
Thank you

**Comment by azat-badretdin** [comment]
There is an option to use Singularity. See https://github.com/ncbi/pgap/wiki/Quick-Start


-D <path>, --docker <path> | Docker-compatible executable (e.g. docker, podman, singularity), which may include a full path like /usr/bin/docker
-- | --
