### ISSUE TITLE
Allow use of alternative directory for temporary files

### ISSUE THREAD

**Issue by jhodrien** [ncbi/pgap#106]
If you are running on a system with a small /tmp, it'd be useful for PGAP to use another directory for temporary files, else you'll get warnings of it being too small, or failures if it really is too small.  This is quite common on HPC systems.

Either you should be able to provide a parameter telling it where to use for temporary files, or as a generally usable solution, TMPDIR could be used, with a default of /tmp if it's not found.  Obviously providing both would do no harm.

I've tried a quick fix using an extra bind for singularity only, and this seems to work fine.

Most basic kludge doing just the TMPDIR bit, this is just a case of adding:

`'--bind', '{}:/tmp:rw'.format(os.getenv("TMPDIR", "/tmp")),`

to the singularity calls.

**Comment by azat-badretdin** [comment]
Thank you for your interesting suggestion!

**Comment by azat-badretdin** [comment]
We are planning to implement this.

**Comment by azat-badretdin** [comment]
Update. We have implemented this in development version of code by honoring your `$TMPDIR`. This should be available in the next release. For now, we haven't decided yet when we are going to release this. 

We are preparing significant performance improvements in our internals that will drastically reduce the processing time for a lot of popular genomes in vast taxonomic corners which will even increase the major version of PGAP from 4 to 5.
