### ISSUE TITLE
PGAP failed, docker exited with rc = 1, Connenction to www.ncbi.nlm.nih.gov failed

### ISSUE THREAD

**Issue by mrztm** [ncbi/pgap#108]
Hi,

I have freshly installed the software package following your instructions. However, when I try to test the installation using the provided information for M. genitalium, the program fails with the error message "PGAP failed, docker exited with rc = 1". In the printed log, see the attached cwltool.log file for details, two messages or blocks of messages stand out:
1. something went wrong during execution of pgapx_yaml_input.GetFasta
2. in a series of error messages. it is stated that the host www.ncbi.nlm.nih.gov cannot be found or that no connection to services provided by this server can be established

Here some details about the system:
OS: Ubuntu 16.04.7 LTS (GNU/Linux 4.4.0-193-generic x86_64) 
CPUs: 24 (12 cores with 2 threads per core) Intel Xeon E5-2690 v3 @ 2.60 GHz
Memory: 62 GB
Used Memory: 6GB
Free Disk Space: 2.6TB

In addition, I have attached the information stored in the debug folder.

Many thanks for your help
Thomas

[cwltool.log](https://github.com/ncbi/pgap/files/5440082/cwltool.log)
[test_pgap.tar.gz](https://github.com/ncbi/pgap/files/5440099/test_pgap.tar.gz)

**Comment by mrztm** [comment]
A little update, in the mean time I run the test using the no-internet flag. It finished succesfully.

**Comment by azat-badretdin** [comment]
Thanks for your report, Thomas! I was going to suggest to run it with `-no-internet` flag as well. Is this (internet connectivity) issue something that you expected from your system setup?

**Comment by mrztm** [comment]
My suspecion is that the connectivity issue is caused by a collision of a server running on the machine and the port used by the request in PGAP. As far as I can interpret the error messages, the request is using port 443. We have a server running listing on this port which I cannot change to another one. That is my current working hypothesis. That the NCBI server is actually not reachable I found quite unlikely.

**Comment by azat-badretdin** [comment]
I must agree with you. The outage of NCBI servers are quite rare, we have a nuclear catastrophe level backup defense the details of which I am not at liberty to disclose.

**Comment by mrztm** [comment]
That's a shame, but very understandable. I guess that is really interesting from a technological perspective.

Ok, back to the actual topic. It basically means I have two options:
1. run the pipeline without internet access and check for updates manually
2. write a little script which first calls the update and then runs  the pipeline without internet

I can work with that. A question just came into my mind, is there a way just to check for an updated version? The update process might take a while. knowing that there is a newer version might allow a scheduled approach.

Many thanks for your rapid and helpfull response
Thomas

**Comment by azat-badretdin** [comment]
> A question just came into my mind, is there a way just to check for an updated version? 

Other than periodically visiting this URL? I do not know. `pgap.py` does have a self-update mechanism. So far we are banking on users getting, unconditionally, newer versions.

**Comment by mrztm** [comment]
That's fine.

May I ask which checks are skipped when running the pipeline without internet access.

**Comment by azat-badretdin** [comment]
The no-internet option has an effect is in the fetching of the blobs for publications. If the user provides a publication in the yaml and sets the no-internet option, the results only contain the pmid instead of full information on publication. 

The rest works the same.

**Comment by mrztm** [comment]
OK, that is not really an issue for new sequences.

During my preparation for a first run using a new sequence, I came along a key in the submol.yaml file for M. genitalium which is not explained on the wiki, tp_assembly which seemingly can be true or false. Could you tell me what this switch is about?

**Comment by azat-badretdin** [comment]
This is a flag that is currently used exclusively by our internal user of PGAP, our acclaimed Pathogen group. It produces the vast majority of all annotations in the world made by PGAPx and some of their assemblies generated by our internal SKESA algorithms (check out our coming new exciting project called RAPT that combines assembly and annotation in one nifty package!) are marked by this flag. We are having it in a test genome setup for the mere purpose of testing it internally before we hand this to Pathogen group. 

In short, please ignore it.

**Comment by mrztm** [comment]
I will check your new project and in particular tell my colleagues about your new project RAPT. Genome assembly and annotation is more of a side project of mine, but I strongly rely on reliable and standardized results.

Many thanks for your prompt and efficient help
Thomas

**Comment by azat-badretdin** [comment]
You are welcome, Thomas!
