### ISSUE TITLE
Unic genes "not" working

### ISSUE THREAD

**Issue by lucaspompeun** [ncbi/pgap#11]
I'm trying to run a analysis with identity 70% and coverage 80% with 4 strains. The problem is that some unic genes comes in output as a shared gene. What can I do?

**Comment by azat-badretdin** [comment]
I am afraid I do not understand the essence of your problem. Could you please post a snippet of the output that illustrates it? What analysis are you running?

**Comment by evolarjun** [comment]
Hi Lucas,
Is your question about [AMRFinder](https://github.com/ncbi/amr)? I'm guessing because AMRFinder has coverage and identity cutoff command-line options.
