### ISSUE TITLE
Annotating plasmids

### ISSUE THREAD

**Issue by vappiah** [ncbi/pgap#110]
Hi NCBI,

I have plasmid sequence of M. ulcerans. I would like to perform annotation but I am a bit confused as to how I should name the organism in the submol.yaml file. Since M. ulcerans, has a separate sequence file for chromosome as well as plasmid.  The plasmid is called pMUM001.

Vincent

**Comment by thibaudnis** [comment]
Do you wish to annotate a M. ulcerans plasmid that is different from pMUM001 already in GenBank and RefSeq? This is not an issue. You can annotate any sequence you wish, whether or not it is already in the NCBI databases, (but please don't submit the sequence to GenBank, if an identical sequence is already in GenBank). 
You can annotate a chromosome and one or multiple plasmids together, by concatenating the fasta files for the chromosomes and the plasmid(s). Or, if you prefer, annotate the plasmid on its own, using 'Mycobacterium ulcerans' as the genus_species. If you annotate the plasmid on its own, set `--ignore-all-errors`, so the results of the size check for the genome are ignored (see https://github.com/ncbi/pgap/wiki/FAQ, "What if PGAP fails in the validation of the input FASTA?")

**Comment by vappiah** [comment]
Hi @thibaudnis  @azat-badretdin . Thanks for the response. This time we have sequence our own isolates. But I suspect both plasmid and chromosome are bundled up the draft assembly contigs. 
So if I annotate with PGAP, can you suggest how I can identify genes for both the chromosome and plasmid in the annotation files?

**Comment by thibaudnis** [comment]
PGAP will automatically annotate all the sequences provided on input, whether plasmid and chromosome. With the [January release](https://github.com/ncbi/pgap/releases/tag/2021-01-11.build5132), if the plasmid is distantly related to the chromosomal sequence, the annotation may be a bit better if you mark the plasmid sequences by adding `[location=plasmid]` to their definition lines as suggested in [the wiki](https://github.com/ncbi/pgap/wiki/Input-Files#definition-lines), but the annotation differences will be small.
