### ISSUE TITLE
Finding Pseudogenes

### ISSUE THREAD

**Issue by jotes35** [ncbi/pgap#111]
Hi @thibaudnis @azat-badretdin 

I would like to know if pgap identifies pseudogenes ?

**Comment by thibaudnis** [comment]
Yes, PGAP identifies pseudogenes.

**Comment by jotes35** [comment]
Hi @azat-badretdin . How are the pseudogenes labelled in the pgap results?

**Comment by azat-badretdin** [comment]
In flat file format (Genbank format), the features that are pseudo are marked by the string "/pseudo".

**Comment by vappiah** [comment]
Hi @thibaudnis @azat-badretdin . I was able to find the pseudogenes using artemis. But what caught my attention was that out of 5290 genes identified, 3947 of them were flagged as pseudo which is quite a high number.  There were flagged /pseudo.
Is there anything I am doing wrong ?

**Comment by azat-badretdin** [comment]
> Is there anything I am doing wrong ?

So far, I do not see anything wrong on your side. A lot of genomes have a lot of pseudos. Sequencing errors, transposon bombing, monomer runs, frameshifts - these first come to my mind.

**Comment by thibaudnis** [comment]
Hi! I suspect the genome sequence is low quality. For example, the sequence accuracy of PacBio or Oxford Nanopore is fairly low, so if you have used one of these technologies to sequence the genome and no polishing afterward, your genome may have a lot of indels, leading to frameshifts in the annotated genes.

**Comment by vappiah** [comment]
Thanks everyone.  Its true the sequence is nanopore and I will check the polishing and reannotate.

**Comment by azat-badretdin** [comment]
The flat file (.gbk) output contains a structured comment summary with the statistics of various annotations on the genome. Number of frameshifts, in addition to number of pseudos, is another good indication of sequence defects.
