### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by dikshyantg** [ncbi/pgap#112]
Hi , while annotating a single contig I ran into this error. I don't have any idea on how to debug it.
Printing log starting from failed job:

[2020-11-17 16:46:52] INFO [step pgapx_yaml_ctl] start
[2020-11-17 16:46:52] INFO [job pgapx_yaml_ctl] /tmp/z3r9aif_$ pgapx_yaml_ctl \
    -ifmt \
    JSON \
    -input \
    /tmp/tmpv0_dykkx/stg91218e92-3888-4301-9cf1-50e13dec98d9/submol.json \
    -input-fasta \
    /tmp/tmpv0_dykkx/stg54c4e4ad-f707-4d44-8b27-399399731cb8/contig_51.fasta \
    -ofmt \
    JSON \
    -output-annotation \
    input.asn \
    -output-asn-type \
    input_asn_type.txt \
    -output-ltp \
    genome.ltp.txt \
    -output-taxid \
    taxid.txt \
    -taxon-db \
    /tmp/tmpv0_dykkx/stgde6c435e-1542-404c-8ec8-44e13fd2a6c4/taxonomy.sqlite3
terminate called after throwing an instance of 'ncbi::CSerialException'
  what():  NCBI C++ Exception:
    Error: SERIAL(CSerialException::eInvalidData) "/export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/enumerated.cpp", line 120: UNK_FUNC --- invalid value of enumerated type: not published
    Error: SERIAL(CSerialException::eInvalidData) "/export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/enumerated.cpp", line 413: ncbi::CEnumeratedTypeInfo::ReadEnum() --- invalid enum value
    Error: SERIAL(CSerialException::eInvalidData) "/export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/member.cpp", line 770: ncbi::CMemberInfoFunctions::ReadWithSetFlagMember() --- error while reading status ( at JsonValue.publications.[].[].publication.status)
     Stack trace:
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/corelib/ncbi_stack_libbackward.cpp:82 ncbi::CStackTraceImpl::CStackTraceImpl() offset=0x0 addr=0x7fbcf40661f9
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/corelib/ncbi_stack.cpp:79 ncbi::CStackTrace::CStackTrace(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) offset=0x0 addr=0x7fbcf40670e6
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/corelib/ncbiexpt.cpp:583 ncbi::CException::x_GetStackTrace() offset=0x0 addr=0x7fbcf40f4220
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/corelib/ncbiexpt.cpp:208 ncbi::CException::CException(ncbi::CDiagCompileInfo const&, ncbi::CException const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ncbi::EDiagSev, int) offset=0x0 addr=0x7fbcf40f3dd4
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libtaxon1.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/exception.hpp:67 ncbi::CSerialException::CSerialException(ncbi::CDiagCompileInfo const&, ncbi::CException const*, ncbi::CSerialException::EErrCode, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ncbi::EDiagSev) offset=0x0 addr=0x7fbcfb43b575
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/enumerated.cpp:119 ncbi::CEnumeratedTypeValues::FindValue(ncbi::CTempString const&) const offset=0x0 addr=0x7fbcf4a6a9fb
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/objistrjson.cpp:747 ncbi::CObjectIStreamJson::ReadEnum(ncbi::CEnumeratedTypeValues const&) offset=0x0 addr=0x7fbcf4afe27a
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/enumerated.cpp:409 ncbi::CEnumeratedTypeInfo::ReadEnum(ncbi::CObjectIStream&, ncbi::CTypeInfo const*, void*) offset=0x0 addr=0x7fbcf4a68149
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/objistr.inl:95 ReadData offset=0x0 addr=(nil)
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/member.cpp:740 ReadObject offset=0x0 addr=(nil)
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/typeinfo.inl:69 ncbi::CMemberInfoFunctions::ReadWithSetFlagMember(ncbi::CObjectIStream&, ncbi::CMemberInfo const*, void*) offset=0x0 addr=0x7fbcf4a786dd
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/objistr.cpp:1367 ReadMember offset=0x0 addr=(nil)
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/member.inl:104 ncbi::CObjectIStream::ReadClassRandom(ncbi::CClassTypeInfo const*, void*) offset=0x0 addr=0x7fbcf4a87c11
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/objistr.inl:95 ReadData offset=0x0 addr=(nil)
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/member.cpp:727 ReadObject offset=0x0 addr=(nil)
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/typeinfo.inl:69 ncbi::CMemberInfoFunctions::ReadSimpleMember(ncbi::CObjectIStream&, ncbi::CMemberInfo const*, void*) offset=0x0 addr=0x7fbcf4a7634d
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/objistr.cpp:1367 ReadMember offset=0x0 addr=(nil)
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/member.inl:104 ncbi::CObjectIStream::ReadClassRandom(ncbi::CClassTypeInfo const*, void*) offset=0x0 addr=0x7fbcf4a87c11
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/objistr.inl:95 ReadData offset=0x0 addr=(nil)
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/objistr.cpp:1148 ReadObject offset=0x0 addr=(nil)
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/typeinfo.inl:69 ncbi::CObjectIStream::ReadPointer(ncbi::CTypeInfo const*) offset=0x0 addr=0x7fbcf4a8a7ba
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/ptrinfo.cpp:225 ncbi::CPointerTypeInfo::ReadPointer(ncbi::CObjectIStream&, ncbi::CTypeInfo const*, void*) offset=0x0 addr=0x7fbcf4a6be2f
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/stltypes.hpp:256 ReadData offset=0x0 addr=(nil)
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libpgap_yaml_input_reader.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/typeinfo.inl:69 ncbi::CStlClassInfoFunctions<std::__cxx11::list<ncbi::CRef<ncbi::objects::pgapx::CPgapYamlInputReader_Base::C_Publications::C_E_, ncbi::CObjectCounterLocker>, std::allocator<ncbi::CRef<ncbi::objects::pgapx::CPgapYamlInputReader_Base::C_Publications::C_E_, ncbi::CObjectCounterLocker> > > >::AddElementIn(ncbi::CContainerTypeInfo const*, void*, ncbi::CObjectIStream&) offset=0x0 addr=0x7fbd0fbb1d25
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/objistr.cpp:1315 AddElement offset=0x0 addr=(nil)
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/continfo.inl:246 ncbi::CObjectIStream::ReadContainer(ncbi::CContainerTypeInfo const*, void*) offset=0x0 addr=0x7fbcf4a85ed7
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/classinfo.cpp:303 ncbi::CClassTypeInfo::ReadImplicitMember(ncbi::CObjectIStream&, ncbi::CTypeInfo const*, void*) offset=0x0 addr=0x7fbcf4a7c02a
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/objistr.inl:95 ReadData offset=0x0 addr=(nil)
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/objistr.cpp:1148 ReadObject offset=0x0 addr=(nil)
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/typeinfo.inl:69 ncbi::CObjectIStream::ReadPointer(ncbi::CTypeInfo const*) offset=0x0 addr=0x7fbcf4a8a7ba
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/ptrinfo.cpp:225 ncbi::CPointerTypeInfo::ReadPointer(ncbi::CObjectIStream&, ncbi::CTypeInfo const*, void*) offset=0x0 addr=0x7fbcf4a6be2f
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/objistr.inl:95 ReadData offset=0x0 addr=(nil)
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/member.cpp:727 ReadObject offset=0x0 addr=(nil)
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/typeinfo.inl:69 ncbi::CMemberInfoFunctions::ReadSimpleMember(ncbi::CObjectIStream&, ncbi::CMemberInfo const*, void*) offset=0x0 addr=0x7fbcf4a7634d
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/objistr.cpp:1367 ReadMember offset=0x0 addr=(nil)
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/member.inl:104 ncbi::CObjectIStream::ReadClassRandom(ncbi::CClassTypeInfo const*, void*) offset=0x0 addr=0x7fbcf4a87c11
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/objistr.inl:95 ReadData offset=0x0 addr=(nil)
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/objistr.cpp:944 ReadObject offset=0x0 addr=(nil)
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/typeinfo.inl:69 ncbi::CObjectIStream::Read(void*, ncbi::CTypeInfo const*, ncbi::CObjectIStream::ENoFileHeader) offset=0x0 addr=0x7fbcf4a8e669
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/serialobject.cpp:781 ncbi::ReadObject(std::istream&, void*, ncbi::CTypeInfo const*) offset=0x0 addr=0x7fbcf4b03b95
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/bin/pgapx_yaml_ctl :0  offset=0x0 addr=0x417a49
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/corelib/ncbiapp.cpp:626 ncbi::CNcbiApplicationAPI::x_TryMain(ncbi::EAppDiagStream, char const*, int*, bool*) offset=0x0 addr=0x7fbcf407a1b2
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/corelib/ncbiapp.cpp:893 ncbi::CNcbiApplicationAPI::AppMain(int, char const* const*, char const* const*, ncbi::EAppDiagStream, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) offset=0x0 addr=0x7fbcf407c4ac
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/bin/pgapx_yaml_ctl :0  offset=0x0 addr=0x40c773
      /usr/lib64/libc-2.17.so :0  offset=0x0 addr=0x7fbcf2dae554
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/bin/pgapx_yaml_ctl :0  offset=0x0 addr=0x40c914
       :0  offset=0x0 addr=0xffffffffffffffff

Stack trace (most recent call last):
#14   Object "", at 0xffffffffffffffff, in 
#13   Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/bin/pgapx_yaml_ctl", at 0x40c914, in _start
#12   Object "/usr/lib64/libc-2.17.so", at 0x7fbcf2dae554, in __libc_start_main
#11   Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/bin/pgapx_yaml_ctl", at 0x40c773, in main
#10   Source "/export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/corelib/ncbiapp.cpp", line 893, in AppMain [0x7fbcf407c4ac]
#9    Source "/export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/corelib/ncbiapp.cpp", line 626, in x_TryMain [0x7fbcf407a1b2]
#8    Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-06-10.build4646/arch/x86_64/bin/pgapx_yaml_ctl", at 0x417a49, in CPgapxYamlCtlApplication::Run()
#7    Source "/export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/serialobject.cpp", line 781, in ReadObject [0x7fbcf4b03b95]
#6    Source "/export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/objistr.cpp", line 948, in Read [0x7fbcf4a8e7cc]
#5    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/eh_throw.cc", line 131, in __cxa_rethrow [0x7fbcf362e2b5]
#4    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/eh_terminate.cc", line 57, in terminate [0x7fbcf362e020]
#3    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/eh_terminate.cc", line 47, in __cxa_begin_catch [0x7fbcf362dfd5]
#2    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/vterminate.cc", line 95, in __verbose_terminate_handler [0x7fbcf36301e4]
#1    Object "/usr/lib64/libc-2.17.so", at 0x7fbcf2dc3a77, in abort
#0    Object "/usr/lib64/libc-2.17.so", at 0x7fbcf2dc2387, in raise
Aborted (Signal sent by tkill() 246 1005)
[2020-11-17 16:46:53] INFO [job pgapx_yaml_ctl] Max memory used: 34MiB
[2020-11-17 16:46:53] ERROR [job pgapx_yaml_ctl] Job error:
("Error collecting output for parameter 'input_asn_type':\npgap/progs/pgapx_yaml_ctl.cwl:75:13: Did not find output file with glob pattern: '['input_asn_type.txt']'", {})
[2020-11-17 16:46:53] WARNING [job pgapx_yaml_ctl] completed permanentFail
[2020-11-17 16:46:53] ERROR [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/output_annotation
[2020-11-17 16:46:53] ERROR [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/output_ltp
[2020-11-17 16:46:53] ERROR [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/input_asn_type
[2020-11-17 16:46:53] ERROR [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/taxid
[2020-11-17 16:46:53] WARNING [step pgapx_yaml_ctl] completed permanentFail
[2020-11-17 16:46:53] INFO [workflow prepare_input_template] completed permanentFail
[2020-11-17 16:46:53] WARNING [step prepare_input_template] completed permanentFail
[2020-11-17 16:46:53] INFO [workflow ] completed permanentFail
[2020-11-17 16:46:53] WARNING Final process status is permanentFail
{
    "calls": null,
    "final_asndisc_error_diag": null,
    "final_asnval_error_diag": null,
    "gbk": null,
    "gff": null,
    "initial_asndisc_error_diag": null,
    "initial_asnval_error_diag": null,
    "input_fasta": {
        "class": "File",
        "location": "file:///pgap/output/contig_51.fasta",
        "size": 27884,
        "basename": "contig_51.fasta",
        "checksum": "sha1$2e3a931d3539f0a5fd021dfc0407f1a14ab72c15",
        "path": "/pgap/output/contig_51.fasta"
    },
    "input_submol": {
        "class": "File",
        "location": "file:///pgap/output/pgap_submol_l_86lv05.yaml",
        "size": 1480,
        "basename": "pgap_submol_l_86lv05.yaml",
        "checksum": "sha1$c8afacf23a33ab0d3727fd20ad6c9ed149d10fb6",
        "path": "/pgap/output/pgap_submol_l_86lv05.yaml"
    },
    "nucleotide_fasta": null,
    "protein_fasta": null,
    "sqn": null
}

**Comment by azat-badretdin** [comment]
Could you please post your input `submol.yaml` file?

**Comment by dikshyantg** [comment]
Here it is .

**Comment by azat-badretdin** [comment]
https://help.github.jp/enterprise/2.11/user/articles/file-attachments-on-issues-and-pull-requests/

**Comment by dikshyantg** [comment]
[yaml& input.docx](https://github.com/ncbi/pgap/files/5555814/yaml.input.docx)

**Comment by azat-badretdin** [comment]
I see at least one problem: 

````
authors::
    -     author:: 'Acaryochloris Marina'
```
double colons instead of single colons
Could you please review your `submol.yaml` so it conforms to YAML standard?

**Comment by thibaudnis** [comment]
This document may help: https://github.com/ncbi/pgap/wiki/Input-Files

**Comment by dikshyantg** [comment]
[yaml& input.docx](https://github.com/ncbi/pgap/files/5556569/yaml.input.docx)

**Comment by dikshyantg** [comment]
Even with the change in the .yaml file, I am  getting the same output. It is strange because I have used the same .yaml file few months back I didn't get any error.

**Comment by azat-badretdin** [comment]
Could you please upload your `submol.yaml` file as a .txt file? Word can modify text on its own.

**Comment by dikshyantg** [comment]
[input.txt](https://github.com/ncbi/pgap/files/5561049/input.txt)
[submol.txt](https://github.com/ncbi/pgap/files/5561050/submol.txt)

Here it is .

**Comment by azat-badretdin** [comment]
Your submol.text has publication.status=not published

It's not a valid status. Valid statues are:

```
                                "enum": [
                                    "published",
                                    "in-press",
                                    "unpublished"
                                ]
```

**Comment by azat-badretdin** [comment]
We created an internal ticket PGAP-3747 to review the documentation to make sure that we made this part clear.

**Comment by dikshyantg** [comment]
I am not getting the same error again so I believe this changes worked. Thanks a lot! 
I also wanted to know ( should I  make different thread? )whether --CPU and --memory  or similar option worked ( previously this option didn't work) for pgap because I have 23 GB memory and 16 virtual CPU. I ran the pgap default option for around 6 MB bacterial genome and the pipeline  was running for little over a week, which is a lot of time. My aim is to decrease the number of cpu to increase the ratio of total memory per cpu .

**Comment by azat-badretdin** [comment]
> I am not getting the same error again so I believe this changes worked. Thanks a lot!

Glad to hear that and you are welcome!

>  ( should I make different thread? )

Yes, please.
