### ISSUE TITLE
[BUG] PGAP sometimes fails, sometimes doesnt

### ISSUE THREAD

**Issue by marieleoz** [ncbi/pgap#113]
**Describe the bug**
When trying to annotate a series of E.coli genomes, PGAP sometimes succeeds and sometimes fails. When it does, I get the message: "docker exited with rc = 1". Re-trying to run was usually enough, but now I have one genome that always fails. I ensured that another one that was successfully annotated before could be submitted again, and it could. I also looked at the log files from several tris with my problematic genome, and all don't look alike (some are way longer than others) suggesting that the step at which pgap fails is not the same everytime?

**To Reproduce**
If you are having trouble with your genome, please ensure that you can run the pipeline with one of our test genomes first. If your installation works fine with the sample input, please tell us if you are willing and able to share your genome with us, if asked.
=> Most of my genomes are ok (even though I sometimes need several tries); I can send the one that systematically fails.

**Expected behavior**
docker exiting with rc = 0, and me getting all my annot files :)

**Software versions (please complete the following information):**
 - OS: Ubuntu 2019-08-22.build3958
 - pgap.py --version: 2019-08-22.build3958 (I know I could update but I'd rather annotate all my genomes with a single version) 
 - docker --version: 19.03.13, build 4484c46d9d

**Log Files**
Please rerun pgap.py with the ``--debug`` flag and attach an archive (e.g. zip or tarball) of the logs in the directory: ``debug/tmp-outdir/*/*.log``.
There are 3 rep in debug/tmp-outdir:
0z9hepvm (empty)
1t0kxk30 (contains only one file: fastaval.xml) 
35t0v_zm (empty)
So I send you the full debug repertory.
[debug.zip](https://github.com/ncbi/pgap/files/5566298/debug.zip)

THANKS!!!

**Additional context**

**Comment by azat-badretdin** [comment]
Thanks for following the template! I opened an internal ticket: PGAP-3758 

Could you please post `cwltool.log` as well?

**Comment by azat-badretdin** [comment]
`fastaval.xml` contains this error:

```

<message fasta_seq_id="lcl|contig_00125" seq_id="contig_00125" severity="ERROR" tool="fastaval" code="SEQ_SHORT_LENGTH">Sequence is shorter than 200 nucleotides</message>

```

Please try eliminating all short contigs and run again. 

As for irreproducible behavior/instability of your docker runs, I am afraid this might be your local peculiarities of the system. Generally, this happens when there is something with memory allocation - total memory low, docker settings give too low memory, etc.

**Comment by marieleoz** [comment]
Sure! Here are some of the cwltool.log files I got from several trials with that genome:
[cwltool_1.log](https://github.com/ncbi/pgap/files/5566857/cwltool_1.log)
[cwltool_2.log](https://github.com/ncbi/pgap/files/5566859/cwltool_2.log)
[cwltool_3.log](https://github.com/ncbi/pgap/files/5566875/cwltool_3.log)
[cwltool_4.log](https://github.com/ncbi/pgap/files/5566877/cwltool_4.log)

Now that I saw your 2nd message, I'm trying rerunning without the short contig (it's weird that it even got there!). So far so good, I will let you if it does make it to the end of the process!

Thanks a lot :)

**Comment by azat-badretdin** [comment]
> I'm trying rerunning without the short contig

I must apologize. I completely forgot about much easier option: `./pgap.py -ignore-all-errors` 

Sorry about that.

**Comment by marieleoz** [comment]
Haha it does sound pretty easy, thanks! What would happen to my short contig then? it would be discarded? 
The run without it did just fine. Thanks again :)

Le Jeudi, Novembre 19, 2020 14:52 CET, Azat Badretdin <notifications@github.com> a écrit:

**Comment by azat-badretdin** [comment]
> it would be discarded?

No, it won't. We are on a strict policy of non-editorializing on assemblies, focusing only on annotation.

**Comment by marieleoz** [comment]
Ok! Thanks a lot, you were very helpful.
 
Le Vendredi, Novembre 20, 2020 14:01 CET, Azat Badretdin <notifications@github.com> a écrit:
