### ISSUE TITLE
Decreasing cpu and increasiong memory per cpu

### ISSUE THREAD

**Issue by dikshyantg** [ncbi/pgap#114]
Hi, I  wanted to know whether --CPU and --memory or similar option worked ( previously this option didn't work) for pgap because I have 23 GB memory and 16 virtual CPU. I ran the pgap default option for around 6 MB bacterial genome and the pipeline was running for little over a week, which is a lot of time. My aim is to decrease the number of cpu to increase the ratio of total memory per cpu . Do you think we can decrease the amount of cpu to allocate more number of memory per cpu?

**Comment by azat-badretdin** [comment]
I am actually testing, in this Sprint, how CPU option works. You can definitely try, but the fact that pipeline runs on a single genome for a week, indicates that you might need a more powerful computer. 

We are working full speed right now on one of the most significant optimizations in the history of PGAPx, but that will come later.

**Comment by whlavina** [comment]
I will confirm, we did test the options and they should work. However, we can't test under all scenarios and all system platforms. I just reconfirmed the behavior is as expected, using the currently public PGAP release (reran a test on Linux with Docker).

Given your available memory, I'd recommend trying 6 CPU, maybe as little as 3 CPU although that would indeed be slow. Still, a week seems unexpectedly long. I recommend avoiding use of the memory limit, unless there is a specific need such as running in a shared compute cluster.

I did note that the warning message for insufficient memory per CPU may appear, even if limiting CPU, but that's merely a pre-flight informative check; actual execution should be correctly throttled.

For further assistance, please use the debug option and send us log files (or try inspecting the logs yourself) - see the FAQ. The top of the `cwltool.log` file will provide information about your command line, and if you `grep` the detailed log files, the parameter to search for is `cpu_available`.

If you care about internal details:
The mechanism for limiting CPU is "good enough" but not ideal. Some of the applications will not use the CPU optimally (more total threads than CPU but only the specified number of threads running concurrently). However, the known memory-hungry applications have been suitably adjusted to honor the CPU limit.

**Comment by sabrinaelias** [comment]
Hello, in the latest release of pgap the --cpus and --memory option is not working. Can anyone help please? thank you

**Comment by azat-badretdin** [comment]
@sabrinaelias please open a new issue. Thank you! Please specify what is exactly not working
