### ISSUE TITLE
PGAP genome size check: fail

### ISSUE THREAD

**Issue by ChinPok23** [ncbi/pgap#115]
Hi,
I hope this is a simple question with a simple answer I just fail to see.
I want to annotated an Escherichia coli genome via PGAP problem is my sequence fails the genome size check since it is too small. The sequence is supposed to be that small. Is there an easy work around to that problem? to just allow that failed size check.
I am new here so I am sorry If I violated any rules, I hope you can forgive me that.

Best wishes

**Comment by thibaudnis** [comment]
Hi! Welcome! You can use the flag `--ignore-all-errors`, and PGAP will happily ignore the size check and continue on.

**Comment by azat-badretdin** [comment]
> The sequence is supposed to be that small

Are you specifying correct taxonomy?

**Comment by SynBioFranz** [comment]
thank you very much! That really helped for now. Just curious does the option "strain" effect minimum genome size?

Franz L. Böge
PhD Student, University of Cambridge
Chin Group, MRC Laboratory of Molecular Biology
Phone: +44 (0)1223 267604




________________________________

**Comment by SynBioFranz** [comment]
--ignore-all-errors works very well, but I am afraid that this masks other errors that effect the quality of my output. I tried to annotate the right strain(MDS42), but it still checks for the regular E. coli genomem size. Is there a less invasive option to bypass this?

**Comment by thibaudnis** [comment]
You could try setting the organism to 'Escherichia' (just the genus without the species), without the `--ignore-all-errors` flag. That may get you through the genome size check. But, what kind of errors are you concerned about? Vector or adaptor contamination will be reported in the calls.tab file if found, even with the `--ignore-all-errors` flag.

**Comment by azat-badretdin** [comment]
> but I am afraid that this masks other errors that effect the quality of my output

It only "masks" them, the errors are all there, and they are preserved if you run it with `pgap.py --debug` option. Look for `.xml` files and the words ERROR, REJECT, FATAL in them.

**Comment by SynBioFranz** [comment]
I am new to PGAP and this new annotation is really important, for the future of couple of projects, so in conclusion, I have no Idea what kind of error there might be, since I dont know a lot. But I am afraid that this would affect projects of multiple people not just my own.
