### ISSUE TITLE
inconsistent protein/gene orders in faa, gff and gbk files

### ISSUE THREAD

**Issue by wangdi2014** [ncbi/pgap#118]
In the new version 2020-09-24, the protein sequence order in faa is not consistent with those in gff and gbk files.
In the previous version 2020-03-30, it is OK.

For example,
in faa file, it starts at ABC-001_000749 but in gff and gbk files, it is ABC-001_000001 for ABC-001 sample.

Thanks!

**Comment by thibaudnis** [comment]
Hello! Thank you for reporting the issue. We will take a look at this issue, and try to have it fixed in the next release.
