### ISSUE TITLE
APPRECIATION

### ISSUE THREAD

**Issue by vappiah** [ncbi/pgap#123]
Hello PGAP, developers @azat-badretdin @thibaudnis . Thanks for all the hardwork.  I made a video tutorial on how to install,setup and use PGAP. I would like to know if its OK to acknowledge NCBI by displaying the name / logo of NCBI.  The video can be found here https://youtu.be/Iuzr5v9bjJ8

**Comment by thibaudnis** [comment]
Hi Vincent! Thanks for making the video. I don't see any issue with you acknowledging NCBI, quite the opposite in fact. We would be very interested in talking to you about how you discovered PGAP, why you use it, and what improvement we could make that would help. Please contact me at thibaudf@ncbi.nlm.nih.gov, and we can set up a time for a short conversation. Thanks in advance - Francoise

**Comment by vappiah** [comment]
Thanks @thibaudnis . I will contact you
