### ISSUE TITLE
 WARNING Final process status is permanentFail[BUG] <title>

### ISSUE THREAD

**Issue by vappiah** [ncbi/pgap#124]
Dear Developers. Thanks for  your support.

I attempted to run pgap on mydata. And had some errors displayed by pgap. I will be grateful if I can be helped to pinpoint what the issue was. Below are the error logs. 
[pgap.log.txt](https://github.com/ncbi/pgap/files/5958504/pgap.log.txt)
[pgap.log2.txt](https://github.com/ncbi/pgap/files/5958510/pgap.log2.txt)

PS. PGAP worked successfully on some of the genomes and for others it not work.

**Comment by azat-badretdin** [comment]
Thanks for your report, Vincent. It failed at screen_evaluate stage which indicate contamination. If you run it with `-debug` option the directory with results for this stage will be preserved at this step and you could view the results inside that directory.

**Comment by thibaudnis** [comment]
Alternatively: is there a calls.tab file in the output directory? This file contains the vector or adaptor spans that were detected by the PGAP process. If this file is present, you can either remove these spans from the assembly before trying PGAP again, or you can run on the current assembly with the flag `--ignore-all-errors` for PGAP to keep running despite the contamination.

**Comment by azat-badretdin** [comment]
> Alternatively: is there a calls.tab file in the output directory? 

It should be there, indeed: we do pass it all the way to the output from internal CWL calls.

**Comment by vappiah** [comment]
> Alternatively: is there a calls.tab file in the output directory?

Hi @azat-badretdin Apologies for late response. I can confirm the calls.tab file is there. And I was able to see the adaptor sequence. Thanks for the help.

**Comment by azat-badretdin** [comment]
You are welcome, Vincent!
