### ISSUE TITLE
[BUG]  WARNING Final process status is permanentFail running the example test

### ISSUE THREAD

**Issue by mglgc** [ncbi/pgap#126]
First of all, thank you for this developing.

After some time running the command line ./pgap.py -r --debug -o test test_genomes/MG37/input.yaml
with the data provided by the installation the program is ending with the error message:
"WARNING Final process status is permanentFail"

Attached you will find a zip file containing the log files under the debug directory. Please, could you help us to fix it?
Thank you very much in advance for your support.
[debug.zip](https://github.com/ncbi/pgap/files/5982268/debug.zip)

**Comment by azat-badretdin** [comment]
Thank you for your report, user mglgc! 

Could you please post the contents (file list) of `output/` directory and the file `output/cwltool.log`?

**Comment by mglgc** [comment]
> Thank you for your report, user mglgc!
> 
> Could you please post the contents (file list) of `output/` directory and the file `output/cwltool.log`?

Thank you for your reply. Below my replies.

[cwltool.log](https://github.com/ncbi/pgap/files/6025888/cwltool.log)

File list of 'output/':
ASM2732v1.annotation.nucleotide.1.fasta
calls.tab
cwltool.log
debug/
pgap_submol_rp7ahxi3.yaml

**Comment by azat-badretdin** [comment]
Looking at `cwltool.log`

Looks like you have Internet connectivity problems from the instantiated docker container, as indicated here:

```
Warning: (302.106) [SOCK_gethostbyname]  Failed gethostbyname_r("www.ncbi.nlm.nih.gov") {error=200001,Host not found}
Error: (302.22) SSOCK#1000[?]@:443: [SOCK::Connect]  Failed SOCK_gethostbyname("www.ncbi.nlm.nih.gov")
Error: (303.7) [URL_Connect; https://www.ncbi.nlm.nih.gov/Service/getenv.cgi]  Failed to connect: Unknown
Error: (301.23) [CONN_Read(HTTP; https://www.ncbi.nlm.nih.gov/Service/getenv.cgi)]  Unable to read data: Unknown
```

I suggest that you consult your local system help to fix these problems.
