### ISSUE TITLE
pgap.cwl not found

### ISSUE THREAD

**Issue by marieleoz** [ncbi/pgap#129]
Hi,

I previously used pgap version 2019-08-22.build3958 and updated yesterday to 2021-01-11.build5132, using:
$ ./pgap.py --update

Now that the update has completed, annotations fail with cwltool.log indicating: schema_salad.exceptions.ValidationException: Not found: 'pgap.cwl'

Can you help me fix this please? I attach the full log file in case it helps.

Thanks!
Marie

[cwltool.log](https://github.com/ncbi/pgap/files/6041629/cwltool.log)

**Comment by azat-badretdin** [comment]
Thanks for this report, Marie! Nice to hear from you again!

Do you have the same system setup as before? (picking https://github.com/ncbi/pgap/issues/113)

> Software versions 
> 
> -    OS: Ubuntu 2019-08-22.build3958
> -    docker --version: 19.03.13, build 4484c46d9d
>

**Comment by marieleoz** [comment]
Hey Azat! Nice to hear from you too :)

Here are the current versions:
- Ubuntu: 18.04.5
- Docker: 20.10.3

 
Le Jeudi, Février 25, 2021 13:22 CET, Azat Badretdin <notifications@github.com> a écrit:

**Comment by azat-badretdin** [comment]
Thanks, Marie. Looks like the Docker version changed and the Ubuntu version  - not clear if it changed or not, because in the #113 you accidentally posted PGAPx version instead of Ubuntu version 

Can you try to use the `docker` command directly to find the "missing" file at your system? It will be something like `docker run -i <pgapx-docker-image> find / -name pgap.cwl`

**Comment by marieleoz** [comment]
My mistake!

I tried the command you suggest and got:
bash: pgapx-docker-image: no such file or directory

 

Le Jeudi, Février 25, 2021 14:53 CET, Azat Badretdin <notifications@github.com> a écrit:

**Comment by azat-badretdin** [comment]
No, mistake is mine, I should have been more clear in here

> docker run -i <pgapx-docker-image> find / -name pgap.cwl

where `<pgapx-docker-image>` was meant to be substituted by the correct image you posted (see body of Issue above)

**Comment by marieleoz** [comment]
I suspected something of sort :)
But I'm really bad with docker and have trouble understanding what is actually the correct "image" to mention. Can you help me figure it out?

Thanks Azat!

**Comment by marieleoz** [comment]
Ok wait; I listed docker images and found the right image ID. When using it in your command I got:
/pgap/pgap/pgap.cwl

**Comment by azat-badretdin** [comment]
Sure: `docker run -i ncbi/pgap:2021-01-11.build5132 find / -name pgap.cwl` you will get something like: 

```
$ docker run -i ncbi/pgap:2021-01-11.build5132 find / -name pgap.cwl
/pgap/pgap/pgap.cwl
```

Also, you might try to download `pgap.py` from scratch again (see Quick Start)

**Comment by marieleoz** [comment]
Hi Azat,

I downloaded pgap.py again and it looks like it solved this issue. I'm still struggling though, because now I have memory issues, but at least we got one step closer to success!

Thanks a lot :)
Marie

**Comment by azat-badretdin** [comment]
Glad to hear that you are moving forward, Marie!

Happy landings!
