### ISSUE TITLE
pgap.py with no arguments does a stack trace

### ISSUE THREAD

**Issue by tseemann** [ncbi/pgap#13]
If you run `pgap.py` with no arguments it gives a stack trace.

It would be good if it showed the help ie. behaved like `-h`

**Comment by whlavina** [comment]
Without arguments, `pgap.py` tries to do some work, such as check for Docker and/or install the reference data. It's possible that there was some error executing those tasks, but this may not have been obvious with the stack trace.

We have improved the script to avoid the stack trace, unless the debug option is used. This should improve usability. The commit is on the master branch, for testing:
```
curl -OL https://github.com/ncbi/pgap/raw/master/scripts/pgap.py
```

If you think this doesn't adequately address the problem, please let us know.
