### ISSUE TITLE
bacterial_hit_mapping terminate called after throwing an instance of 'ncbi::CIOException'

### ISSUE THREAD

**Issue by pirale** [ncbi/pgap#130]
Hi there,

I hope you're doing well.

I'm trying to run PGAP, but it fails after a writing exception.
terminate called after throwing an instance of 'ncbi::CIOException'
```
  what():  NCBI C++ Exception:
    Error: UTIL(CIOException::eWrite) "../../../ncbi_cxx/src/util/strbuffer.cpp", line 892: ncbi::COStreamBuffer::FlushBuffer() --- write fault
    Error: SERIAL(CIOException::eWrite) "../../../ncbi_cxx/src/serial/objostr.cpp", line 612: ncbi::CObjectOStream::Write() ---  Frame type= eFrameNamed, Object type= Seq-annot
     Stack trace:
       ../../../ncbi_cxx/include/util/util_exception.hpp:73 CUtilException offset=0x0 addr=(nil)
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2021-01-11.build5132/arch/x86_64/lib/libxutil.so ../../../ncbi_cxx/include/util/util_exception.hpp:57 ncbi::CIOException::CIOException(ncbi::CDiagCompileInfo const&, ncbi::CException const*, ncbi::CIOException::EErrCode, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ncbi::EDiagSev) offset=0x0 addr=0x7ff683967b0d
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2021-01-11.build5132/arch/x86_64/lib/libxutil.so ../../../ncbi_cxx/src/util/strbuffer.cpp:892 ncbi::COStreamBuffer::FlushBuffer(bool) offset=0x0 addr=0x7ff68396522b
       ../../../ncbi_cxx/src/serial/objostr.cpp:552 FlushBuffer offset=0x0 addr=(nil)
       ../../../ncbi_cxx/src/serial/objostr.cpp:610 EndOfWrite offset=0x0 addr=(nil)
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2021-01-11.build5132/arch/x86_64/lib/libxser.so ../../../ncbi_cxx/include/serial/impl/objostr.inl:54 ncbi::CObjectOStream::Write(void const*, ncbi::CTypeInfo const*) offset=0x0 addr=0x7ff683d2baeb
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2021-01-11.build5132/arch/x86_64/bin/bacterial_hit_mapping :0  offset=0x0 addr=0x40e8bd
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2021-01-11.build5132/arch/x86_64/lib/libxncbi.so ../../../ncbi_cxx/src/corelib/ncbiapp.cpp:700 ncbi::CNcbiApplicationAPI::x_TryMain(ncbi::EAppDiagStream, char const*, int*, bool*) offset=0x0 addr=0x7ff68313ed62
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2021-01-11.build5132/arch/x86_64/lib/libxncbi.so ../../../ncbi_cxx/src/corelib/ncbiapp.cpp:978 ncbi::CNcbiApplicationAPI::AppMain(int, char const* const*, char const* const*, ncbi::EAppDiagStream, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) offset=0x0 addr=0x7ff683141014
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2021-01-11.build5132/arch/x86_64/bin/bacterial_hit_mapping :0  offset=0x0 addr=0x4082b9
      /usr/lib64/libc-2.17.so :0  offset=0x0 addr=0x7ff68039f554
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2021-01-11.build5132/arch/x86_64/bin/bacterial_hit_mapping :0  offset=0x0 addr=0x408436
      /usr/lib64/ld-2.17.so :0  offset=0x0 addr=0xffffffffffffffff

```

Could you please help me spot the cause of the problem? I'm attaching a log file.

Thanks so much!
[cwltool.log](https://github.com/ncbi/pgap/files/6079910/cwltool.log)

**Comment by azat-badretdin** [comment]
Thanks for your report, Alejandro!

This seems like input-specific problem which needs to be examined at our premises with input to the node that failed. 

The node that failed is `bacterial_hit_mapping` application with the following command line that I extracted from the supplied `cwltool.log`:

```
[2021-02-27 15:31:08] INFO [job Map_Naming_Hits] /tmp/tf4s88dx$ bacterial_hit_mapping \
    -align-fmt \
    seq-align-set \
    -asn-cache \
    /tmp/n1n1_4in/stgd9fcb1c4-e95c-4ff3-a09b-f4eb95fb9b38/sequence_cache,/tmp/n1n1_4in/stg2a0ac1c4-99da-43c8-b0e6-72d5aee954d4/cache \
    -expansion-ratio \
    1.1 \
    -aligns-manifest \
    aligns.mft \
    -nogenbank \
    -o \
    mapped-hmm-hits.asn \
    -sequences \
    /tmp/n1n1_4in/stgd5b8ba1f-5875-4028-939e-91c4f4ad3a33/entries.asnb

```

The input to this program includes information about your genomic sequences (parameter `-sequences`) which you might or might not be willing to give to us privately to reproduce this problem locally, at NCBI. 

Without this information our options to investigate this case are quite limited. 

Would you be willing to rerun this case with `pgap.py --debug` flag specified and give us some of the contents of `debug-extra` subdirectory that contains this information?

**Comment by pirale** [comment]
Thanks a lot for your prompt answer, Azat.

Please let me ask my collaboration partners. What's the best way to send you a private message?

Alejandro

**Comment by azat-badretdin** [comment]
You can send it to me at my NIH email. Not sure if I should publish it here, but it is available on https://ned.nih.gov/search/ through search.

**Comment by azat-badretdin** [comment]
Françoise reminded me of another option: prokaryote-tools@ncbi.nlm.nih.gov

**Comment by pirale** [comment]
Thanks a ton Azat!

Alejandro

Am Fr., 5. März 2021 um 11:07 Uhr schrieb Azat Badretdin <
notifications@github.com>:

**Comment by azat-badretdin** [comment]
You are welcome!

Have you sent anything? (I had to ask because I have to allow-list external email addresses at work and this increases a chance for an email to slide unnoticed).

**Comment by pirale** [comment]
Hi Azat,

Thanks a ton for your e-mail. You know, I think it might be our HPC that is
causing the trouble, because things run in interactive mode, but I can only
annotate one genome at once. I'm trying to find out what the problem is.

Thanks again for your willingness to help.

Best,

Alejandro

Am Mo., 8. März 2021 um 09:10 Uhr schrieb Azat Badretdin <
notifications@github.com>:

**Comment by azat-badretdin** [comment]
You are welcome, Alejandro!
