### ISSUE TITLE
[BUG] Error installing PGAP: no space left on device

### ISSUE THREAD

**Issue by Ghepardo** [ncbi/pgap#131]
**Describe the bug**
Installing PGAP by running 'pgap.py --update'.  The downloads complete, then the error for "no space left on device" is shown, then the installation continues.  However, the output suggests that only a partial installation was performed, because not all the "Download complete" entries changed to "Pull complete".  The full output is:
```
# ./pgap.py --update
The latest version of PGAP is 2021-01-11.build5132, you have nothing installed locally.
Downloading (as needed) Docker image ncbi/pgap:2021-01-11.build5132
2021-01-11.build5132: Pulling from ncbi/pgap
ab5ef0e58194: Pull complete
d572fe06c486: Pull complete
614601d301cf: Pull complete
9039cac4b369: Pull complete
dd66831d0101: Pull complete
ec99737da8cf: Pull complete
888b9ca0532a: Pull complete
d7e0b7a80583: Pull complete
19bfcf20e3f5: Pull complete
41bfee536c4f: Pull complete
e2002e0cc038: Pull complete
4d417a55fdd4: Pull complete
50ee9a3f8d21: Extracting [==================================================>]  715.1MB/715.1MB
73da46c0b51b: Download complete
11f1f7d1c4ac: Download complete
b2c83b97e2d9: Download complete
bbd6d68c58e0: Download complete
25c51ff9fdb0: Download complete
dce27e4bb0ab: Download complete
df19eb353288: Download complete
d110c67d3826: Download complete
8e03dc66990d: Download complete
c7456df81d0f: Download complete
652137f40f18: Download complete
8d2a75366740: Download complete
b462e9ab6917: Download complete
c65a5db344e7: Download complete
9e98e62f6842: Download complete
99b726d117ac: Download complete
186bc2d883eb: Download complete
171da6c45d6b: Download complete
failed to register layer: Error processing tar file(exit status 1): write /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2021-01-11.build5132/arch/x86_64/lib/libxblast.so: no space left on device
None
Downloading and extracting tarball: https://s3.amazonaws.com/pgap/input-2021-01-11.build5132.tgz
Downloaded 16655129122 of 16655129122 bytes (100.00%)
Installing PGAP test genomes
./test_genomes-2021-01-11.build5132
https://s3.amazonaws.com/pgap-data/test_genomes-2021-01-11.build5132.tgz
Downloading and extracting tarball: https://s3.amazonaws.com/pgap-data/test_genomes-2021-01-11.build5132.tgz
Downloaded 23089558 of 23089558 bytes (100.00%)
```

**To Reproduce**
Run 'pgap.py --update'.

**Expected behavior**
No error message to be shown.

**Software versions (please complete the following information):**
 - OS: CentOS 7
 - pgap.py --version: 2021-01-11.build5132
 - docker --version: 18.09.6, build 481bc77156

**Log Files**
I have rerun this using the --debug flag, and the behaviour was exactly the same.  No 'debug' directory was created however, so I cannot attach any log files.  

**Additional context**
I have sufficient disk space:
```
# df -Th .
Filesystem               Type  Size  Used Avail Use% Mounted on
/dev/mapper/SDVol-LVapps xfs   200G   60G  141G  30% /apps
```

**Comment by azat-badretdin** [comment]
I suggest that you treat this as installation error and find larger space area. 

Meanwhile we will be looking into the issue of why we are not properly handling failure of the docker to install in this case

**Comment by azat-badretdin** [comment]
Could you please post the output of command `docker info`?

**Comment by Ghepardo** [comment]
Hi @azat-badretdin, thanks.  Here is the 'docker info' output:
```
# docker info
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 36
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.12.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 94.24GiB
Name: babvs73.rothamsted.ac.uk
ID: BRHD:R3XE:YRHZ:NE5G:57C2:I3LB:VUR4:WEYC:2NH3:NSE7:4HC5:JUZ5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: mbrandizi
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: IPv4 forwarding is disabled
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
Our Docker filesystem, /var/lib/docker, has 6G free, and I have the feeling this is not enough.  I am about to increase this and I shall rerun the installation.  I am reluctant to increase any further the size of the PGAP installation area in /apps, since this now has 171G free.

**Comment by azat-badretdin** [comment]
This is the first time I am seeing this parameter and I see that we do have it hefty in one of our docker-capable hosts:

```
$ df2 -h /var/lib/docker
Filesystem                 Size  Used Avail Use% Mounted on
/dev/mapper/usrvg1-docker  4.8T  3.6T  1.1T  78% /var/lib/docker
```

and

```
$ df -h /var/lib/docker
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p1  985G  649G  336G  66% /var/lib/docker
```
on the other. 

Looking at the utility of this directory it seems that it serves not only as a buffer for a downloaded image, but a storage for all images and containers, with versions, etc. It seems that even 32G would be a very small storage for these unless you are planning to use tiny images. I would recommend to bump it at least to a hundred Gb. 

[The storage location of Docker images and containers](https://www.freecodecamp.org/news/where-are-docker-images-stored-docker-container-paths-explained/)

**Comment by Ghepardo** [comment]
Thanks for your advice @azat-badretdin .  I'll look at doing that very soon.  For now, with /var/lib/docker at 32G, it seems happy enough: the installation and the test run both ran without errors.  Many thanks for your prompt responses.

**Comment by azat-badretdin** [comment]
You are welcome, user Ghepardo!
