### ISSUE TITLE
[BUG] Still attempting to connect to NCBI despite --no-internet flag

### ISSUE THREAD

**Issue by chmaraj** [ncbi/pgap#133]
I have tried running PGAP on my dataset a number of times but runs keep failing as a result of failing to connect to NCBI. This has been happening regardless of using the --no-internet flag, as well as with the -r, -n, and --ignore-all-errors flags. I have tried every combination of these, to no avail. Unfortunately we have been having issues contacting ncbi servers from my facility (pinging ncbi produces 100% packet loss, but pinging other sites works just fine). I should also note that the MG37 test data ran to completion. 

I am not sure why it is necessary for the pipeline to contact NCBI despite the --no-internet flag being used, but any information you could provide would be greatly appreciated. My supervisor is very keen on using the PGAP pipeline locally for annotation and comparisons to reference genomes. 

I am running on Ubuntu 16, with Python3.7, 32GB RAM and 12 logical processors. 
PGAP version is 2021-01-11.build5132
Docker version 18.09.7, build 2d0083d

Log file is attached (from run with --no-internet, -n, and --ignore-all-errors)
[cwltool.log](https://github.com/ncbi/pgap/files/6205943/cwltool.log)

**Comment by azat-badretdin** [comment]
Would you mind sending us data? It looks like a input specific issue, since you mentioned that textbook example MG37 went through just fine.

The data could be sent privately to NCBI.

**Comment by chmaraj** [comment]
It appears that you are correct. After attempting to run a reference sequence which completed successfully, I surmised that the issue was likely coming from the sequence headers. After adjusting the headers, the pipeline ran to completion. I suspect that the culprit was the use of "|" (pipe) characters in the headers (which were old carry-overs). 

I will close the ticket now. Thank you.

**Comment by azat-badretdin** [comment]
Thanks! Would you mind posting this offending header by replacing private information (like taxonomic identity, etc) with substitute characters (retaining spaces and special characters that are not part of this identification, of course)?  

We can see what we can do to notify the users more clearly when this happens again. 

Thanks!

**Comment by chmaraj** [comment]
Sure, like I said they were basically hold-overs that were never adjusted. And example header is as follows:

>gnl|OLF|NAODLLOP_1

As I mentioned, I suspect that the issue was the use of the "|" characters. Once the headers were adjusted, the pipeline ran to completion.

**Comment by azat-badretdin** [comment]
Thanks! This looks like a completely benign header...

... for all the things we do internally, at NCBI. 

My first suspect is that deep inside the core of our binaries some generic code sees: "hay,  NCBI id! let's go to NCBI and check if it is valid one/makes sense/other things that the core might want to do with such ids". 

Typically, PGAPX is not ready yet to identify "we are outside NCBI, do not try to resolve this ID" situation (it's deep in the core).

**Comment by chmaraj** [comment]
Oh interesting! Thanks for the info, I've certainly been informed of strange interactions in my own code before, so I definitely understand. For now I'll just stick to running PGAP with adjusted headers to avoid any further weirdness.

**Comment by azat-badretdin** [comment]
Note that at this point it is only primary hypothesis, not a fact. 

The safest NCBI-compliant IDs are "local" IDs, like here `>lcl|mylocalid` or `>lcl|42`

**Comment by thibaudnis** [comment]
Please see the [wiki](https://github.com/ncbi/pgap/wiki/Input-Files) for information on the inputs, including the FASTA def line. "|" are not allowed in sequence identifiers.

**Comment by azat-badretdin** [comment]
Thanks, Françoise. My mind was preoccupied with this puzzle and I completely forgot about our own Wiki instructions. 

Apologies for the confusion I caused.
