### ISSUE TITLE
PGAP failed, docker exited with rc = 1, while running test genome files

### ISSUE THREAD

**Issue by ankit12593** [ncbi/pgap#135]
I ran this command on test genome files (Mycoplasma genitalium):

sudo ./pgap.py -r -d -o test_out MG37/input.yaml
ran with sudo to avoid docker permission issue

After running for a while prompted with this error:
PGAP failed, docker exited with rc = 1

**Software versions (please complete the following information):**
 - OS: Ubuntu 18.04
 - pgap.py version:  2021-01-11.build5132 
 - Docker version: 19.03.13, build 4484c46d9d

**Machine Configuration**
CPU core: 40
CPU model: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz
memory (GiB): 251.5
memory per CPU core (GiB): 6.3
tmp disk space (GiB): 646.1
work disk space (GiB): 6559.9

I checked initial threads of the same issue and tried few solutions but nothing worked for me.

I am not able to troubleshoot through this. Please help me to resolve this issue. Attaching all log files from debug step along with cwltool.log.

Converted yaml genome input files to txt for attachment purpose.

Many thanks in advance
[all_logs.tar.gz](https://github.com/ncbi/pgap/files/6262528/all_logs.tar.gz)
[cwltool.log](https://github.com/ncbi/pgap/files/6262529/cwltool.log)
[input.yaml.txt](https://github.com/ncbi/pgap/files/6262542/input.yaml.txt)
[submol.yaml.txt](https://github.com/ncbi/pgap/files/6262543/submol.yaml.txt)

**Comment by azat-badretdin** [comment]
Thank you for posting detailed report, Ankit! While analyzing the plethora of data you provided, I found an indication that you are using old example of input data. Please let me know if you obtained it during the release mentioned by you and, if this is the case, how - in this case it would be an error.

**Comment by ankit12593** [comment]
@azat-badretdin Thank you for your quick reply. As you indicated correctly that I was using the old example data. 
After downloading the new test genome data I ran the same command and this time program ran for a little longer and then exited with the same error.
I am sorry but I am attaching all-new debug and cwl logs along with new input files again. 

Thank you

[cwltool.log](https://github.com/ncbi/pgap/files/6269210/cwltool.log)
[input.yaml.txt](https://github.com/ncbi/pgap/files/6269212/input.yaml.txt)
[logs.tar.gz](https://github.com/ncbi/pgap/files/6269213/logs.tar.gz)
[submol.yaml.txt](https://github.com/ncbi/pgap/files/6269214/submol.yaml.txt)

**Comment by azat-badretdin** [comment]
> then exited with the same error.

Actually, it goes further now in executing a workflow graph for your input (this information is in cwltool.log):

```
Critical: (307.10) [NCBI-MESSAGE]  [DISPD#MedArch@sutils101] Please make sure your firewall does not block ports 4444-4544 bound for 130.14.29.112
Error: (302.26) SOCK#3000[11]@130.14.29.112:22: [SOCK::Connect]  Failed pending connect(): Timeout[30.000000]
Error: (308.6) [MedArch]  Stateful relay connection failure (Closed) usually indicates possible firewall configuration problem(s); please consult <https://www.ncbi.nlm.nih.gov/IEB/ToolBox/NETWORK/dispatcher.html#Firewalling>
Error: (301.5) [CONN_Open(MedArch/SOCK; 130.14.29.112:22)]  Failed to open connection: Closed
Error: (315.4) CConn_Streambuf::overflow():  CONN_Write() failed (MedArch/SOCK; 130.14.29.112:22): Closed
Error: (315.4) CConn_Streambuf::overflow():  CONN_Write() failed (MedArch/SOCK; 130.14.29.112:22): Closed
Error: (315.4) CConn_Streambuf::overflow():  CONN_Write() failed (MedArch/SOCK; 130.14.29.112:22): Closed
Error: (802.5) CObjectOStream: error at byte 6: stack is empty: cannot close output stream
```

It looks like we are trying to verify input pubmed ids that are passed to the node `bacterial_prepare_unannotated` as sequence descriptors and we are unable to do that because of some Internet problem. It is not clear if the problem is related to some settings on your side, or something else. 

If the problem is reproducible, then it could be something in system settings (Docker settings, for example) that restrict Internet access.

**Comment by ankit12593** [comment]
@azat-badretdin I ran the same command with no internet usage parameter and it ran successfully. 

So is it okay to run PGAP with no internet parameter even for user-defined genome files? 
Does this parameter make any difference in the final output?

Kind regards

**Comment by azat-badretdin** [comment]
> I ran the same command with no internet usage parameter and it ran successfully.

Great1!

> So is it okay to run PGAP with no internet parameter even for user-defined genome files?

Yes. You can run it with that parameter. It is currently use in two leaf nodes of workflow graph, that test validity of publications by connecting to PubMed. That has no effect on annotation
