### ISSUE TITLE
Genome size check fail

### ISSUE THREAD

**Issue by Biomedinformatics** [ncbi/pgap#136]
I have assembled fastq paired end reads using spades and when running pgap genome size check fails. What can I do to improve the assembly so that it is within the range of accepted genome size. I removed the unaligned contigs but still getting same error.
Please suggest solution to this.

**Comment by azat-badretdin** [comment]
You can always try to run it with the option to ignore all errors (check out `./pgap.py -help`).

**Comment by Biomedinformatics** [comment]
But then can that assembly be submitted to ncbi if pgap runs with --ignore
errors??

**Comment by thibaudnis** [comment]
Yes, you can submit the genome to GenBank even if the assembly is declared too small/too big. However, I would encourage you to look more deeply at why the genome size is outside of the range expected for the species. Have you confirmed that the organism is correct? You can run `pgap.py` with `--taxcheck `or `--taxcheck-only` to do that. Did you align the assembly to another assembly in the same species to see what is missing or extra in yours?

**Comment by Biomedinformatics** [comment]
I have run pgap with --taxcheck-only but it exits with error. Does it means
there is problem in sequencing or assembly. what can be the solution?
Can it be rectified by improving assembly or resequencing is required?

**Comment by Biomedinformatics** [comment]
I also ran pgap with ignore errors, it completed successfully and annot.faa
files shows all proteins from Mycobacterium tuberculosis which is correct
then why taxcheck-only exited with error?
How to rectify this?

**Comment by azat-badretdin** [comment]
> Does it means there is problem in sequencing or assembly. what can be the solution?

... or biological oddity. 

Unfortunately, our software can't tell if the small genome size is a consequence of inadequate coverage or something else. 

We do detect presence of "universal" proteins (about 100 different housekeeping proteins) and RNAs involved in protein synthesis apparatus (rRNA, tRNAs). That would be one of the places indicating to inadequacy of coverage, but even if you have all of these, the "lack" of sequence could be elsewhere. 

You are a better expert on your organism, so maybe you could check if other proteins that "must" be present on that species are missing?

**Comment by azat-badretdin** [comment]
> I have run pgap with --taxcheck-only but it exits with error

Could you please post `cwltool.log` produced by that run?

**Comment by Biomedinformatics** [comment]
x-special/nautilus-clipboard
copy
file:///home/omicsworkstation/Desktop/Kulsum/NER_Omics/PGAP_ANNOTATION/cwltool.log

**Comment by Biomedinformatics** [comment]
[cwltool.log](https://github.com/ncbi/pgap/files/6270623/cwltool.log)

**Comment by azat-badretdin** [comment]
Thank you, user Biomedinformatics! 

I looked at the file your posted and it provided us with more hints on what happened. 

Could you please post the header of your input FASTA file (first line)? Feel free to replace organism name with `Klebsiella foobarensis` to conceal your private information about your research subject. We are interested in particular with "seq-id" part of the header, before the first whitespace in the header.

**Comment by azat-badretdin** [comment]
Actually, it was a red herring. Real error is this:

```
terminate called after throwing an instance of 'ncbi::CSQLITE_Exception'
  what():  NCBI C++ Exception:
    Error: SQLITE(CSQLITE_Exception::eStmtPrepare) "../../../../ncbi_cxx/src/db/sqlite/sqlitewrapp.cpp", line 193: ncbi::s_ProcessErrorCode() --- Error from sqlite3: [11] database disk image is malformed
    Error: SQLITE(CSQLITE_Exception::eStmtPrepare) "../../../../ncbi_cxx/src/db/sqlite/sqlitewrapp.cpp", line 676: ncbi::CSQLITE_Statement::x_Prepare() --- Error preparing statement for "PRAGMA journal_mode = OFF"
```

**Comment by azat-badretdin** [comment]
> Error from sqlite3: [11] database disk image is malformed

This usually indicates to some lack of disk space on user side that resulted in incomplete download. Could you please check the disk space on the filesystem where you have directory "input-...."?

**Comment by Biomedinformatics** [comment]
Disk space:

Filesystem      Size  Used Avail Use% Mounted on
udev            135G     0  135G   0% /dev
tmpfs            27G  2.3M   27G   1% /run
/dev/sda2       1.2T  576G  544G  52% /
tmpfs           135G     0  135G   0% /dev/shm
tmpfs           5.3M     0  5.3M   0% /run/lock
tmpfs           135G     0  135G   0% /sys/fs/cgroup
/dev/sda1       536M  8.2M  528M   2% /boot/efi
/dev/loop1       59M   59M     0 100% /snap/core18/1988
/dev/loop0       59M   59M     0 100% /snap/core18/1997
/dev/loop3       73M   73M     0 100% /snap/lxd/19823
/dev/loop2      105M  105M     0 100% /snap/core/10908
/dev/loop5      105M  105M     0 100% /snap/core/10958
/dev/loop4       75M   75M     0 100% /snap/lxd/19009
tmpfs            27G  8.2k   27G   1% /run/user/1000

**Comment by azat-badretdin** [comment]
Which of them you used for pgap?

**Comment by Biomedinformatics** [comment]
/dev/sda1

**Comment by Biomedinformatics** [comment]
/dev/sda2

**Comment by azat-badretdin** [comment]
This particular step involves reading two sqlite files:

- GCExtract2.sqlite
- uniColl_path/taxonomy.sqlite3

They are located in the `input..../` directory created when you ran `./pgap.py`

Could you please try to run `sqlite3 $f .schema` on both files and see if any of them returns errors? 

Please also post the sizes of the files as reported by `ls -l` 

Another avenue of fixing this is to wipe the input.../ directory and try to repeat Quick Start steps to see if the problem is reproducible on your system.

**Comment by Biomedinformatics** [comment]
ls -l of both the files gives:
-rw-r--r-- 1 omicsserver omicsserver 180224 Apr  7 11:24 GCExtract2.sqlite
-rw-r--r-- 1 omicsserver omicsserver 1024000000 Jan 12 14:07
taxonomy.sqlite3

When I run
sqlite3 $f GCExtract2.sqlite .schema
Error: database disk image is malformed

When I run
sqlite3 $f taxonomy.sqlite3 .schema
CREATE TABLE TaxidInfo (    taxid int NOT NULL,     scientific_name
varchar(128) NOT NULL,     rank varchar(32) NULL,     parent int NOT NULL,
    genetic_code smallint NOT NULL,     org_ref_asn varchar(1024) NULL);
CREATE TABLE Synonym (    taxid int NOT NULL,     scientific_name
varchar(128) NOT NULL);
CREATE UNIQUE INDEX UidxTaxid ON TaxidInfo (taxid);


*./pgap.py runs perfectly well but when I do --taxcheck-only error occurs.*

*If there is a problem in ANI, will PGAP still produce results?*

**Comment by azat-badretdin** [comment]
Thank you.

This size is wrong:
```
-rw-r--r-- 1 omicsserver omicsserver 180224 Apr  7 11:24 GCExtract2.sqlite
```
this is the correct size:
```

-rw-rw-r-- 1 .....  332824576 Apr  9 06:55 input-2021-01-11.build5132/GCExtract2.sqlite
```

Something happened during the installation of PGAPx on your computer that truncated the reference data without triggering alarms in the standard python libraries and UNIX executables used. 

I suggest to follow this recommendation then:


> wipe the input.../ directory and try to repeat Quick Start steps to see if the problem is reproducible on your system.

**Comment by Biomedinformatics** [comment]
I wiped off the input..... directory and did the quick start steps. Now
--taxcheck running properly.
THank you

**Comment by azat-badretdin** [comment]
You are welcome, user Biomedinformatics!

Glad that this is resolved!
