### ISSUE TITLE
Muti-chromosome contigs

### ISSUE THREAD

**Issue by vappiah** [ncbi/pgap#137]
Hi NCBI,

I have a vibro cholerae assembly contigs  which we suspect has both chromosome 1 and 2  but we have not separated them yet.
If the contigs are annotated  with pgap, is there a way to identify which features are for chromosome 1 and chromosome 2 ? 

Thanks in advance.

**Comment by thibaudnis** [comment]
Align your contigs to this V. cholerae assembly in RefSeq: https://www.ncbi.nlm.nih.gov/assembly/GCF_900185995.1 ?

**Comment by vappiah** [comment]
Thanks @thibaudnis. I now have a plan now. I will align and reorder the contigs to generate a draft genome for each chromosome.  Then annotate from there.
