### ISSUE TITLE
[Error] Final process status is permanentFail

### ISSUE THREAD

**Issue by junwkim42** [ncbi/pgap#139]
Dear Dr. Badretin,

I was trying to annotate Clostridium sordelli sequences (fasta) using the pgap pipeline while following the tutorial video on youtube  but I kept getting "Final process status is permanentFail" error. 
I believe I am making a format error somewhere, but I couldn't correct it myself.
Could help me interpret the log file and the error messages please?

Attached is the .yaml files and the cwlog file from the failed run. 
[input_and_log.zip](https://github.com/ncbi/pgap/files/6338741/input_and_log.zip)

test.yaml was my input to pgap.py and test_test.yaml was my submol file.
OS: Ubuntu LTS 20.0.4

I appreciate your help in advance and please let me know if you need more information.

Thank you,

Junwon (Scott) Kim
junwon.kim@uconn.edu

**Comment by azat-badretdin** [comment]
Thank you for posting this issue. 

We will look at this shortly.

**Comment by azat-badretdin** [comment]
In your input file test_test.yaml:

```

authors:
    author:
        first_name: 'test'
        last_name: 'test'

```

please add a hyphen before `author:` in `authors:` section.  `Authors:` is a section that can have multiple authors and to distinguish that in YAML this "hyphen" construct is used for elements of the array.

**Comment by thibaudnis** [comment]
Adding to Azat's comment: please make sure to look at the example YAML file in [the wiki](https://github.com/ncbi/pgap/wiki/Input-Files) to avoid other mistakes. Thanks!

**Comment by junwkim42** [comment]
Thank you @azat-badretdin  and @thibaudnis !!
I read the wiki and changed my submol yaml accordingly and was able to annotate my clostridium contigs.

However, aside from output files stated in the wiki, the pipeline also generated four empty .xml files which are
- initial_asnval_diag.xml
- final-asnval_diag.xml
- initial_asndisc_val.xml
- final_asndisc_diag.xml

with error message in cwtool.log : severity="ERROR" or severity="REJECT" and not contains "GENERIC_MissingPubRequirements"
I couldn't find information about this on wiki. I did find that asndisc is a commandline program from NCBI and I assume it is included in this pipeline but I'm having difficulties understanding how it is used and what I'm suppose to correct to make it work.

Would it be better if I open another case with this?

Again, Thank you for your help.

**Comment by azat-badretdin** [comment]
> the pipeline also generated four empty .xml files 

You can ignore these if they are empty. 

```
with error message in cwtool.log : severity="ERROR" or severity="REJECT" and not contains "GENERIC_MissingPubRequirements"

```
Most likely you see a snippet from logical condition for which we are testing the XML output. Please ignore. 

> but I'm having difficulties understanding how it is used 

unless you see "permanentFail" in cwltool.log and cwltool.log ends with "success" messages, you are OK. Do not worry about it.

`asndisc` is a general diagnostic program that finds various problems with our output.  

> Would it be better if I open another case with this?

I do not see another case here unless you have "permanentFail" in cwltool.log

**Comment by junwkim42** [comment]
Thank you very much! Have a wonderful day.
