### ISSUE TITLE
Forcing use of a specific version of PGAP

### ISSUE THREAD

**Issue by kneubehl** [ncbi/pgap#140]
Hi there,

Is there a way to use a specific version of PGAP (or a way to uninstall a specific version)? I use the docker strategy to install and completely cleared that out and all PGAP associated files/folders and reinstalled the specific version I wanted and pulled the docker image. I went to run PGAP and it still finds the latest version and tries to update even with the --no-self-update option. Any guidance would be appreciated, thanks.

**Comment by thibaudnis** [comment]
Hi! Yes, there is a way. Please try setting the parameter `--use-version <version>`, with version something like 2020-09-24.build4894. However, we generally recommend using the newest version of PGAP, as it contains incremental improvements to the code and the data. This particularly true with 2021-01-11.build5132, which is ~twice as fast at the previous release.

**Comment by kneubehl** [comment]
Thanks! I realize I should use the newest version but this is a goofy situation.
