### ISSUE TITLE
Prepare_Unannotated_Sequences_asnvalidate_evaluate: completed permanentFail

### ISSUE THREAD

**Issue by anilchauhanhp9** [ncbi/pgap#143]
Hi, 
I ran the tool, using command mention below, and got an error
**python /home/hamlab/PGAP/pgap.py -D /usr/local/bin/singularity -r --taxcheck --debug --cpus 10 -o PGAP_result /media/hamlab/c191ebf9-60f8-475d-8435-8193920ec7ed
/Srijana/nanopore_data/Sri_whole_genome_sikkim_25032021/analysis/Error_correction/after_QC_trimming/canu/medaka_barcode10/barcode10.yaml**
The error message was as follows 
**WARNING Final process status is permanentFail** 
The log file is attached
[cwltool.log.gz](https://github.com/ncbi/pgap/files/6428998/cwltool.log.gz)
please help me in resolving the issue
Thanks

**Comment by azat-badretdin** [comment]
> [2021-05-05 18:16:58] WARNING [job Prepare_Unannotated_Sequences_asnvalidate_evaluate] completed permanentFail

Do you see the XML file in `output/` directory?

**Comment by anilchauhanhp9** [comment]
Hi,
there are three XML files in the output directory named ani-tax-report.xml,  errors.xml and initial_asnval_diag.xml
the errors.xmal is empty, the other two are attached
[ani-tax-report.xml.gz](https://github.com/ncbi/pgap/files/6429108/ani-tax-report.xml.gz)
[initial_asnval_diag.xml.gz](https://github.com/ncbi/pgap/files/6429110/initial_asnval_diag.xml.gz)

**Comment by azat-badretdin** [comment]
Thanks.

The XML file for initial_asnval_diag.xml says:

```
<message severity="ERROR" seq-id="lcl|tig00000001" code="SEQ_DESCR_NoPubFound">No publications anywhere on this entire record.</message>
```

We will find out what is going on with this diagnostics. Meanwhile, I suggest to rerun `pgap.py` with option `--ignore-all-errors` that should help you to go through this bureaucratic hurdle.

**Comment by anilchauhanhp9** [comment]
Ok
thanks for the quick response
good day
