### ISSUE TITLE
FATAL:   Unable to handle docker://ncbi/pgap:2021-01-11.build5132 uri: failed to get checksum for docker://ncbi/pgap:2021-01-11.build5132: 

### ISSUE THREAD

**Issue by mdabalkey** [ncbi/pgap#145]
The following error shows after I process certain number of records around 100.   

FATAL:   Unable to handle docker://ncbi/pgap:2021-01-11.build5132 uri: failed to get checksum for docker://ncbi/pgap:2021-01-11.build5132: Error reading manifest 2021-01-11.build5132 in docker.io/ncbi/pgap: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

The error doesn't depend on specific records.   I have repeated the run after few hours and I get the results of the following 100 records but I have a large dataset and I expect that one batch submission will complete the whole set.

**Comment by azat-badretdin** [comment]
Thank you for your report. 

> and I get the results of the following 100 records but I have a large dataset and I expect that one batch submission will complete the whole set.

Are you doing exactly all the steps from Quick Start in a cycle? That certainly might upset dockerhub. 

The downloading of input data needs to be done only once (the first time). For your other input genomes all you need is to run `pgap.py` in the same directory with different input and output para
meters.

**Comment by azat-badretdin** [comment]
Apologies, a mixup on my part. It looks like every run of your input (one of 100 records) is done with obligatory pull from docker. 

Are  you running these records from different hosts?

**Comment by azat-badretdin** [comment]
Could you please post entire log that contains the subject error?

**Comment by azat-badretdin** [comment]
>  I had to run it from the shell

Could you please post the snippet of the shell command that involves looping over execution?
