### ISSUE TITLE
Install works with Internet access but not without

### ISSUE THREAD

**Issue by emdyess** [ncbi/pgap#149]
Hello,

Thanks for making the PGAP pipeline available for running locally.  We want to use it not for submitting to GenBank but for annotations in our standard workflow as an alternative to Prokka.  We do not have perpetual Internet access, but the firewall can be opened transiently for installations.  Also, we actually would prefer to lock down the version that we use.  On 05/10/21, I downloaded the files listed on the Installation page.  I also ran the pgap.py script to do the Quick Start installation.  I was able to annotate both the MG37 genome as well as my own genome.

For the past two days, I have attempted to run the same script, but I get network connection issues regardless of what flags I use.   I have tried with and without --use-version, --no-internet, and --no-self-update.  I also see no debugging output (despite using -d), and even just trying to get the version (./pgap.py -V) fails with the same error.

There is a VERSION file in the scripts directory from which I am running ./pgap.py, and I have an input-2021-01-11.build5132 directory also within that same directory.

I am happy to tweak the pgap.py script, but there is so much version checking that I was afraid of breaking it.

I also tried the run_pgap_standalone.sh script, but I get an error with 'wf_pgap_simple.cwl' not found, despite the fact that it is present in the calling directory.

Any help would be much appreciated!

Thanks!

**Comment by azat-badretdin** [comment]
> I am happy to tweak the pgap.py script, but there is so much version checking that I was afraid of breaking it.

I think it was a healthy feeling on your part. This script is under a serious constraint of using only very basic Python functionality to avoid imposition on users and some solutions in that script could be quite convoluted.

**Comment by azat-badretdin** [comment]
Could you please add back the Python stack trace? 

I have a question about it: it did not show any references to `pgap.py`. Why is that? Did you post complete Stack?
