### ISSUE TITLE
I can't download reference data 

### ISSUE THREAD

**Issue by nzx9581** [ncbi/pgap#15]
Hi, 
When I run `./pgap.py --update`, I need to download the reference data (almost 26G), but I can't get whole reference data. I don't know if it is the website problem or my network connection (I think it may be due to the Great Wall Firewall set up in China), I don't have way to download the complete data. So I wan't ask you if I can have other way to download reference data. Thank you!

**Comment by whlavina** [comment]
Thank you for your feedback. The reference data is large, and there may be issues downloading if you don't have a fast and reliable network connection. Currently, our script does not implement retry/resume logic, but this is something we have considered.

We will try to look into the issue within about a week.

If you need something sooner, you may be able to perform the step manually, as the ```pgap.py`` script is trying to download a tarball and extract it. It should have logged a message giving the version of PGAP; using that version:
* Download the file with the correct URL (adjusted for the version) and using a command that allows resuming on interruption: ```wget -c https://s3.amazonaws.com/pgap/input-2019-05-13.build3740.tgz```
* Extract that tarball: ```tar zxvf input-2019-05-13.build3740.tgz```

If downloading this tarball is problematic, this would be useful information to share with us.

Having extracted the correct reference data, ```pgap.py`` should see it and continue to the next step.

**Comment by whlavina** [comment]
Did you have success downloading the reference data manually? If no, do you have any logs to help us diagnose the issue?

In the meanwhile, we have improved the reliability of the download by adding retry, as well as explicitly allowing for a manual download (with hints in the error message for how to do this). The change is currently in the master branch, for testing:
```
curl -OL https://github.com/ncbi/pgap/raw/master/scripts/pgap.py
```
