### ISSUE TITLE
[BUG] <tmp disk space location>

### ISSUE THREAD

**Issue by bowmanjeffs** [ncbi/pgap#150]
Apologies for putting this question here as it's not a bug report (I think!).  PGAP was running well for me but has started reporting this warning before exiting with an error:

`WARNING: tmp disk space (GiB) is less than the recommended value of 10`

There is plenty of space left in the working drive, swap disk, user home directory, etc.  Searching through the log and docs I can't find anything that points to where PGAP stores temporary files during analysis to investigate further, or a way to specify a location with plenty of space.  Any guidance you can provide would be much appreciated.  Here are the system details from the cwtool.log file:

--- Start Runtime Report ---
{
    "CPU cores": 72,
    "Docker image": "ncbi/pgap:2021-01-11.build5132",
    "cpu flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d",
    "cpu model": "Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz",
    "max user processes": "unlimited",
    "memory (GiB)": 251.8,
    "memory per CPU core (GiB)": 3.5,
    "open files": 1048576,
    "tmp disk space (GiB)": 0.1,
    "virtual memory": "unlimited",
    "work disk space (GiB)": 5383.3
}
--- End Runtime Report ---

Log file from run with --debug attached.
[debug.tar.gz](https://github.com/ncbi/pgap/files/6509615/debug.tar.gz)

**Comment by azat-badretdin** [comment]
You can set env variable TMPDIR to your preferred location before executing `pgap.py`:

```

export TMPDIR=/my/fav/tmp
./pgap.py ...

```

**Comment by bowmanjeffs** [comment]
Thanks!  Interestingly PGAP still issues a warning but does not exit with error when I assign a value to TEMPDIR.  I've also located where the temp files and directories were being stored (naturally /tmp).  It seems that files and directories were not being deleted on exit.  Is this behavior expected?

**Comment by azat-badretdin** [comment]
>  It seems that files and directories were not being deleted on exit. Is this behavior expected?

`--debug` implies that _some_ ordinarily transient information is definitely preserved.

Could you please try to run without `--debug` option and see if temporary files are purged?

**Comment by bowmanjeffs** [comment]
It appears that PGAP only deletes the intermediate files if the run completes successfully.  We're running a large number of annotations in parallel and some fraction of those inevitably don't complete, which leads to the build up of a many intermediate files/directories.  Because those directories have randomly generated names we haven't found an expedient way to delete them programmatically when a run fails to complete (we'll troubleshoot these runs individually later).  I recognize this is not a PGAP bug but let me know if you're aware of a workaround.  Otherwise we'll simply periodically scrub TMPDIR of old files.

**Comment by azat-badretdin** [comment]
> I recognize this is not a PGAP bug but let me know if you're aware of a workaround. Otherwise we'll simply periodically scrub TMPDIR of old files.

That's what I would do.
