### ISSUE TITLE
WARNING Final process status is permanent Fail

### ISSUE THREAD

**Issue by Bessem06** [ncbi/pgap#151]
Hi,

I am trying to annotate a small genome but I keep getting this message
"WARNING Final process status is permanent Fail."
Until last week pgap worked fine and I used it to annotate several genomes but now it is not working anymore. I tried it with one of the test genomes and I had the same error message. 

I am running pgap version 2021-01-11.build5132 on an Ubuntu 18.04 machine with 8 CPUs and 128 Gb of RAM.
I am attaching a folder containing the output directory and the yaml files
[output.tar.gz]
(https://github.com/ncbi/pgap/files/6538208/output.tar.gz)

Thanks for your help

**Comment by azat-badretdin** [comment]
Thank you for your report! We will look at the data shortly.

**Comment by azat-badretdin** [comment]
Could you please post `pgap.py` script you are using?

**Comment by azat-badretdin** [comment]
I noticed that the posted tarball/cwltool.log contains an error message: `Unknown organism Candidatus Bessemia` 

The organism must be registered in NCBI Taxonomy in order to be processed. 

Could you please post the error data (similar to what you posted for Bessemia input) for the test genome run (MG37)?

Thanks!

**Comment by Bessem06** [comment]
Hi,

Thank for the reply. I am sequencing a novel genus and did not know that pgap needed a known/registered NCBI Taxonomy to proceed. I changed the taxonomy to E. coli and now its working. The test run with MG37 is working just fine but in my rush I used C_jejuni from the test genome folder and its that genome that gives me the error message.

Thanks again!

**Comment by azat-badretdin** [comment]
>  I used C_jejuni from the test genome folder and its that genome that gives me the error message

Correct behavior. Internally we use this genome for "negative" testing. We have three tests that must produce for "success":

- fail with normal execution
- fail taxcheck
- succeed with -ignore-all-errors flag
