### ISSUE TITLE
General question about pseudogene identification

### ISSUE THREAD

**Issue by kneubehl** [ncbi/pgap#153]
Hi there,
I just have a basic question about how PGAP identifies pseudogenes. This question comes up a lot for me and folks want a technical answer that I can't seem to find. Could you please provide me with some details on how PGAP identifies a pseudogene? Thanks.

**Comment by thibaudnis** [comment]
Thank you for your interest in PGAP. Essentially pseudos are rejects of the coding protein prediction process.
Predicted open reading frames (ORFs) are searched with Blast against a database of representative of prokaryotic protein clusters, and then against the genome using the global aligner ProSplign, which helps determine frameshifts (likely indels in the genome). We also search the ORFs against a collection of HMMs with hmmsearch, and predict ab initio models with GeneMarkS-2+. All these pieces are evaluated together to determine the most likely model at each locus, and whether it should be coding and complete or pseudo or partial. We use the majority rule to determine start sites of protein coding models from the protein alignments and GeneMark if there’s no protein alignments (just HMM evidence, or nothing at all). If no continuous coding model can be called, and if the protein alignments indicate there may be indels in the genomic sequence the model may be called pseudo with frameshifts or partial pseudo.    
(The latest pub where we describe the process fully is https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5001611/. This pub described modification made more recently: https://pubmed.ncbi.nlm.nih.gov/33270901/, but doesn’t address your question fully.)
I hope this helps a little!
