### ISSUE TITLE
Error running test data: job Run_GeneMark_Training permanentFail

### ISSUE THREAD

**Issue by eddykay310** [ncbi/pgap#156]
Hi,

I have been trying to use PGAP but it keeps ending with an error even for the test data. Please find the cwltool.log for the test data below.

[cwltool.log](https://github.com/ncbi/pgap/files/6636610/cwltool.log)

Thank you

**Comment by azat-badretdin** [comment]
Could you please post all the data in `output/` and `debug*/` directory?

**Comment by eddykay310** [comment]
Here is everything in the output folder
[mg37_results.zip](https://github.com/ncbi/pgap/files/6638422/mg37_results.zip)

**Comment by azat-badretdin** [comment]
Thank you, Edwin! 

Could you please post the output of the commands on your system

- `docker run -i ncbi/pgap:2021-05-19.build5429 ls -latr /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/ThirdParty/GeneMark/API_2.2/` 
- `cat /etc/os-release`
- `docker --version`

Thanks!

**Comment by eddykay310** [comment]
Each of the outputs respectively. Thanks

##########################################
total 47984
drwxrwsrwx 2 12970 37231     4096 Oct 17  2018 ver2
dr-xr-xr-x 2 12970 37231     4096 Jul  3  2019 ver2.110
drwxr-xr-x 2 12970 37231     4096 Dec 13  2019 ver2.110_114
-rw-r--r-- 1  9015   562 10433318 May 19 11:02 mgm_4.mod
-rw-r--r-- 1  9015   562 10433400 May 19 11:02 mgm_11.mod
-rwxr-xr-x 1  9015   562    50873 May 19 11:02 gms2.pl
-rw-r--r-- 1  9015   562     8063 May 19 11:02 README_GMS2.txt
-rw-r--r-- 1  9015   562      659 May 19 11:02 INSTALL
-rw-r--r-- 1  9015   562 10433400 May 19 11:02 mgm_25.mod
-rw-r--r-- 1  9015   562 10433400 May 19 11:02 mgm_15.mod
-rwxr-xr-x 1  9015   562      966 May 19 11:02 gmsn.pl
-rwxr-xr-x 1  9015   562  1867056 May 19 11:02 gmhmmp2.orig
-rwxr-xr-x 1  9015   562      116 May 19 11:02 gmhmmp2
-rwxr-xr-x 1  9015   562      869 May 19 11:02 gmhmmp
-rwxr-xr-x 1  9015   562  1576498 May 19 11:02 compp
-rwxr-xr-x 1  9015   562  3839349 May 19 11:02 biogem
-rw-r--r-- 1  9015   562     2837 May 19 11:02 LICENSE
drwxr-sr-x 5  9015   562     4096 May 19 11:02 .
drwxr-xr-x 3 root  root      4096 May 19 11:26 ..
#########################################################

NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
#############################################

Docker version 20.10.7, build f0df350

**Comment by eddykay310** [comment]
Please use the output below. I had to rerun pgap due to some issues with docker. Still getting errors.

[mg37_results.zip](https://github.com/ncbi/pgap/files/6640209/mg37_results.zip)

Thank you

**Comment by azat-badretdin** [comment]
Thanks, Edwin! I still have no clue. 

> I had to rerun pgap due to some issues with docker

Forgive me for prying, what kind of issues? we have potentially related ticket #155 that also happens exclusively to Ubuntu users only.

**Comment by azat-badretdin** [comment]
Have you tried previous version(s) of PGAP?

**Comment by jonathonthill** [comment]
Has this been resolved? I am getting the same error.

**Comment by eddykay310** [comment]
I have not tried previous versions of PGAP. Sorry for the late response.

**Comment by iaconogi** [comment]
Also in my case it fails with the test dataset. Any progress ?
[cwltool.log](https://github.com/ncbi/pgap/files/6732410/cwltool.log)

**Comment by azat-badretdin** [comment]
We are working on addressing this problem, thanks for contributing, user @iaconogi !

**Comment by azat-badretdin** [comment]
Could you please try to reproduce this with new release (released yesterday)?

Thanks!

**Comment by iaconogi** [comment]
Dear Azat, to me not. Here is
[cwltool (1).log](https://github.com/ncbi/pgap/files/6739964/cwltool.1.log)
 the file. Let me know how I can be of further help.

**Comment by azat-badretdin** [comment]
Thanks, but that's  a different error from this ticket, could you please open a different issue for this? Please post your specs as requested, in this case they are of crucial importance.

**Comment by azat-badretdin** [comment]
Edwin, could you please try new version?

**Comment by eddykay310** [comment]
Sure I will do that and get back to you. Thanks

**Comment by azat-badretdin** [comment]
Issue is gone in June release, instead #160 materialized.
