### ISSUE TITLE
xxx_feature_table.txt file

### ISSUE THREAD

**Issue by AnikaTheFox** [ncbi/pgap#157]
Is it possible to generate the xx_feature_table.txt file with PGAP?
I have a new assemled genome. And for further analysis with my pipelines I need a this feature_table file. Which is 19 column based if you use one from a already published organism and download it fro RefSeq or GenBank.

**Comment by azat-badretdin** [comment]
What is the format of this file? Could you please attach a sample? What is this format called when you download it from RS or GB?

**Comment by thibaudnis** [comment]
@AnikaTheFox is requesting the file that is provided on the FTP site for released GenBank and RefSeq assembly.  
At this time we are not planning to have PGAP produce this file. The information that it contains should be obtainable from the gff file that PGAP produces though.
