### ISSUE TITLE
[FEATURE REQUEST] please set input-<VERSION>.<BUILD> loaction under environnement variable control

### ISSUE THREAD

**Issue by EricDeveaud** [ncbi/pgap#158]
**Is your feature request related to a problem? Please describe.**

we are installing PGAP on a cluster with nodes without internet access, on a NFS read only drive and would like to separate binaries and data and respect unix conventions
our install scheme will be 
```
$PREFIX/bin/pgap.py 
$PREFIX/libexec/pgap.py
$PREFIX/libexec/pgap_<VERSION>.<BUILD>.sif
$PREFIX/share/input-<VERSION>.<BUILD>
``` 

NB `$PREFIX/bin/pgap.py` will just exec `$PREFIX/libexec/pgap.py` with `--no-internet --no-self-update` 

**Describe the solution you'd like**

pgap.py download//check for datas files first based on environement variable and fallback to default if not
something like 
while updating
```
if PGAP_INPUT_DIR is defined ias env variable
  then 
      if update//creation:  download data to PGAP_INPUT_DIR location.
      if runtime: use data from PGAP_INPUT_DIR location
  else
     if update//creation: download data to default location
     ir runtime: use data from default location
```
hope it's understable

regards

Eric

**Comment by george-coulouris** [comment]
Hi Eric,
Thank you for your feedback. In the next release, pgap.py will download to $PGAP_INPUT_DIR if specified, or ~/.pgap/ if not.
Regards,
George Coulouris
