### ISSUE TITLE
Wrong link for input data

### ISSUE THREAD

**Issue by laxeye** [ncbi/pgap#16]
On the page https://github.com/ncbi/pgap/wiki/Installation there is a link for input data: https://s3.amazonaws.com/pgap-data/input-[version].tgz which doesn't work for the latest version (2019-05-13.build3740).
In #15 @whlavina gives another link https://s3.amazonaws.com/pgap/input-2019-05-13.build3740.tgz which works.
I suggest to edit https://github.com/ncbi/pgap/wiki/Installation for the latest version compatibility.

Thanks!

**Comment by azat-badretdin** [comment]
Thanks for spotting this, Aleksei! I fixed that in documentation:

> I suggest to edit https://github.com/ncbi/pgap/wiki/Installation
