### ISSUE TITLE
Fails with testing dataset after fresh installation.

### ISSUE THREAD

**Issue by iaconogi** [ncbi/pgap#160]
Fails with testing dataset after running:

wget https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py
chmod +x pgap.py
./pgap.py --update
./pgap.py -r -o mg37_results test_genomes/MG37/input.yaml 

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian

[cwltool (1).log](https://github.com/ncbi/pgap/files/6740479/cwltool.1.log)

**Comment by iaconogi** [comment]
iacongi@PROD-WGS-FASTQ1:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
iacongi@PROD-WGS-FASTQ1:~$ docker --version
Docker version 19.03.12, build 48a66213fe

**Comment by iaconogi** [comment]
Docker version 19.03.12, build 48a66213fe

**Comment by azat-badretdin** [comment]
Thanks for opening this ticket! 

What are you CPU characteristics?

**Comment by iaconogi** [comment]
Here you are:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       46 bits physical, 48 bits virtual
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  2
Core(s) per socket:  8
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
Stepping:            7
CPU MHz:             2593.907
BogoMIPS:            5187.81
Virtualization:      VT-x
Hypervisor vendor:   Microsoft
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            36608K
NUMA node0 CPU(s):   0-15
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology
 cpuid pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single tpr_shadow vnmi ept vpid ept_ad fsgsbase
 bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_vnni md_clear arch_capabilitie
s

**Comment by azat-badretdin** [comment]
Thanks!

**Comment by azat-badretdin** [comment]
> Model name: Intel(R) Xeon(R) Platinum 8272CL CPU 

according to https://en.wikipedia.org/wiki/List_of_Intel_Cascade_Lake-based_Xeon_microprocessors

this model is relatively recent (circa 2019).

**Comment by iaconogi** [comment]
It is a VM in the Microsoft Azure Cloud.

**Comment by azat-badretdin** [comment]
Interesting. I wonder if you will be willing to try to run it in some other environments available to you. This hardware configuration is not available for us right now - we are testing our software on Google and Amazon platforms...

**Comment by iaconogi** [comment]
I am contacting you from the EFSA, European Food Safety Authority. We are testing PGAP for the use in our risk assessment pipelines. The pipeline must run on the Cloud Environment, and we have no other environment. So far we have tested dozens of tools and the VM never created issues (The most complicated is that some code must be compiled from source, as an instruction in the Dockerfile).

**Comment by azat-badretdin** [comment]
Thank you! This is very useful for our plans to improve the breadth of our testing platforms. 

> as an instruction in the Dockerfile

I am confused. What is the relationship of this Dockerfile to the VM?

**Comment by azat-badretdin** [comment]
Also, it looks like we are currently temporarily do not support Debian 10. See https://github.com/ncbi/pgap/wiki/FAQ

**Comment by azat-badretdin** [comment]
We have a new pre-release that fixed a different Debian 10 issue. Could you please try it (2021-07-01.build5508)?

Thanks!

**Comment by iaconogi** [comment]
Hello! I tried the new version,but it still fails.
It seems to me that maybe it passes more time compared to the previous file, like maybe it can do something more ?
[cwltool (2).log](https://github.com/ncbi/pgap/files/6789331/cwltool.2.log)

**Comment by azat-badretdin** [comment]
It says: 

```
Critical: (307.10) [NCBI-MESSAGE]  [DISPD#MedArch@sutils101] Please make sure your firewall does not block ports 4444-4544 bound for 130.14.29.112
Error: (302.26) SOCK#3000[11]@130.14.29.112:22: [SOCK::Connect]  Failed pending connect(): Timeout[30.000000]
Error: (308.6) [MedArch]  Stateful relay connection failure (Invalid argument) usually indicates possible firewall configuration problem(s); please consult <https://www.ncbi.nlm.nih.gov/IEB/ToolBox/NETWORK/dispatcher.html#Firewalling>
Error: (301.5) [CONN_Open(MedArch/SOCK; 130.14.29.112:22)]  Failed to open connection: Invalid argument
Error: (315.4) [CConn_Streambuf::overflow(MedArch/SOCK; 130.14.29.112:22)]  CONN_Write() failed: Invalid argument
```
which indicates to your local system Internet connection settings. Could you please try it with `--no-internet` option?

**Comment by iaconogi** [comment]
Hi, thanks for your help. It is still crashing. Giovanni.
[cwltool (3).log](https://github.com/ncbi/pgap/files/6814104/cwltool.3.log)

**Comment by azat-badretdin** [comment]
Giovanni, would you mind trying if you are consistently failing in the same place with other test genomes (see neighboring directories to MG37?

**Comment by thibaudnis** [comment]
Hi @iaconogi: we were able to reproduce the issue you experience on an Azure Debian 10 machine. The program that fails is a third-party tool, GeneMarkS2+ compiled under Linux kernel 2.x . New distributions compiled under Linux kernel 3.x or Linux kernel 4.x succeeds where the current version fails. We are now looking at updating PGAP with a newer distribution.

**Comment by iaconogi** [comment]
Thats is very god news! Thank you so much!

**Comment by iaconogi** [comment]
Hello, any update on the issue ?
Best

**Comment by thibaudnis** [comment]
Hi - We are hoping to push out a new release with GeneMarkS2+ compiled under Linux kernel 3 in a 2 to 3 weeks.

**Comment by azat-badretdin** [comment]
Hi, user @iaconogi 

Would you mind be among the first users that will have a taste of the new release? Specifically, that would be only GeneMark part that required the transition to Linux kernel 3.

Passing the test successfully will reassure that the coming release will indeed help you to finally be able to start running PGAPx. 

If you agree, feel free to download a tarball from my FTP site at NCBI:

ftp://ftp.ncbi.nlm.nih.gov/pub/badrazat/pgapx/issues/160/test1.tgz

The instructions how to run the test are inside.

**Comment by iaconogi** [comment]
Hello, I downloaded the file but when I try to decompress it I have issues. 
iacongi@PROD-WGS-FASTQ1:/data/nextflow_pipeline/mops/PGAP$ tar -zxvf test1.tgz 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by azat-badretdin** [comment]
Could you please try to remove "z" from command line? It is possible that I might have made a typo and did not actually zip it. Sorry about that.

**Comment by iaconogi** [comment]
Seems fine!
iacongi@PROD-WGS-FASTQ1:/data/nextflow_pipeline/mops/PGAP/input-dir$ ./testme.sh
+ image=ncbi/pgap:2021-07-01.build5508
+ rm -rf GMS2.mod fasta.fna.lst log GeneMark_hmm_combined.mod
++ pwd
++ readlink -f ../API_2.2-k3
++ id -u
++ id -g
+ docker run -i -w /tmp --volume /data/nextflow_pipeline/mops/PGAP/input-dir:/tmp/:rw --volume /data/nextflow_pipeline/mops/PGAP/API_2.2-k3:/API_2.2.fixed:ro,z --user 302415607:302400513 ncb
i/pgap:2021-07-01.build5508 /API_2.2.fixed/gmsn.pl --prok --ncbi --gcode 4 --ext genemark-input.gff --incomplete_at_gaps 10 fasta.fna

real0m16.295s
user0m0.044s
sys0m0.021s
+ echo EXIT CODE = 0
EXIT CODE = 0
iacongi@PROD-WGS-FASTQ1:/data/nextflow_pipeline/mops/PGAP/input-dir$ ls
GMS2.mod                   alignments.mft  fasta-orig.fna  fasta.fna.lst       genemark-non-input.gff  marked-annotation.asn  ncbiapp.perf            sequences.mft
GeneMark_hmm_combined.mod  annotation.mft  fasta.fna       genemark-input.gff  log                     ncbiapp.log            preliminary-models.asn  testme.sh

**Comment by azat-badretdin** [comment]
Thanks! This is confirmation that the release we are in the process of preparing is going to fix your problem.

**Comment by thibaudnis** [comment]
@iaconogi : there is a [new release of pgap](https://github.com/ncbi/pgap/releases/tag/2021-11-29.build5742) available. Would you be able to try it and let us now how it works for you? Thanks!

**Comment by iaconogi** [comment]
Sorry but thre is no "pgap.py" in this release, how am I supposed to quick start ?

**Comment by azat-badretdin** [comment]
> Sorry but thre is no "pgap.py" in this release, how am I supposed to quick start ?

According to quick start recommendations pgap.py is downloaded directly from github. Have you tried that? What happens?
