### ISSUE TITLE
PGAP failed, docker exited with rc = 1

### ISSUE THREAD

**Issue by aini-bio** [ncbi/pgap#161]
Hello,
I am using the test data of PGAP. when ever I run E.coli Plasmid test it shows the following error

PGAP failed, docker exited with rc = 1
Printing log starting from failed job:
[2021-07-22 04:58:59] DEBUG [step Prepare_Unannotated_Sequences_pgapx_input_check] job input {
    "file:///pgap/pgap/wf_common.cwl#Prepare_Unannotated_Sequences_pgapx_input_check/ignore_all_errors": null,
    "file:///pgap/pgap/wf_common.cwl#Prepare_Unannotated_Sequences_pgapx_input_check/input": {
        "location": "file:///tmp/tan2w4g8/sequences.asn",
        "basename": "sequences.asn",
        "nameroot": "sequences",
        "nameext": ".asn",
        "class": "File",
        "checksum": "sha1$5252620fa08c4b42b104b86e9cb626d2214c2541",
        "size": 17701,
        "http://commonwl.org/cwltool#generation": 0
    },
    "file:///pgap/pgap/wf_common.cwl#Prepare_Unannotated_Sequences_pgapx_input_check/max_size": 15000000,
    "file:///pgap/pgap/wf_common.cwl#Prepare_Unannotated_Sequences_pgapx_input_check/min_size": 300,
    "file:///pgap/pgap/wf_common.cwl#Prepare_Unannotated_Sequences_pgapx_input_check/species_genome_size": {
        "class": "File",
        "location": "file:///pgap/input/species_genome_size.txt",
        "basename": "species_genome_size.txt",
        "size": 96614,
        "nameroot": "species_genome_size",
        "nameext": ".txt"
    },
    "file:///pgap/pgap/wf_common.cwl#Prepare_Unannotated_Sequences_pgapx_input_check/taxon_db": {
        "class": "File",
        "location": "file:///pgap/input/uniColl_path/taxonomy.sqlite3",
        "basename": "taxonomy.sqlite3",
        "size": 1044185088,
        "nameroot": "taxonomy",
        "nameext": ".sqlite3"

The error is longer.  I ran the other test files they are running.
The command I used is:   C:\Users> python ./pgap.py -r -o 'Output_file_path' 'Input_file_path/input.yaml'
 Kindly help me out with it.
Thank you.

**Comment by azat-badretdin** [comment]
Thank you for your report, user @aini-bio 

Could you please post `cwtool.log` file?

**Comment by aini-bio** [comment]
[cwltool.log](https://github.com/ncbi/pgap/files/6866359/cwltool.log)

**Comment by aini-bio** [comment]
Sure, here is the file.

**Comment by azat-badretdin** [comment]
Thank you! Here is the relevant part of `cwltool.log` (the rule of thumb is that it is the part of the log file that is before the first occurrence of  `permanentFail`) 

```

[2021-07-22 04:58:59] INFO [job Prepare_Unannotated_Sequences_pgapx_input_check] /tmp/294sd8vq$ pgapx_input_check \
    -nogenbank \
    -input \
    /tmp/lf41jlpf/stg9fac9d85-5e1c-4e84-8685-4173acf8df90/sequences.asn \
    -max-size \
    15000000 \
    -min-size \
    300 \
    -species-genome-size \
    /tmp/lf41jlpf/stgb4c1e90c-8080-4bba-b700-c20b188007ae/species_genome_size.txt \
    -taxon-db \
    /tmp/lf41jlpf/stgc0b68ec2-5461-4b5a-8ba5-fcb1aba3866f/taxonomy.sqlite3
choosing min/max for populated genome for species: 562, ngenomes = 125409
min = 4182000
max = 6274000
genome_size = 66053
genome size check: fail
verify-only-n-sequences check: pass
[2021-07-22 04:58:59] DEBUG Could not collect memory usage, job ended before monitoring began.
[2021-07-22 04:58:59] WARNING [job Prepare_Unannotated_Sequences_pgapx_input_check] completed permanentFail

```
as you can see, your genome is too small for the given taxonomy. The way to go around this is to run it as `pgap.py --ignore-all-errors ....`

**Comment by aini-bio** [comment]
Thank you for your correspondence. The issue is resolved.
