### ISSUE TITLE
Plastid annotation

### ISSUE THREAD

**Issue by sivico26** [ncbi/pgap#163]
Hi, Thanks for developing `pgap`!

I am wondering if `pgap` can be used to annotate plastid genomes (_i.e_ chloroplasts, mitochondria). I have conflicting thoughts here: on the one hand, those genomes share a lot of similarities to prokaryotic genomes. On the other hand, there still are some differences. More importantly, I worry that plastid genomes could break some taxonomic assumptions/tools used under the hood.

So what do you think? It is viable? Would it need some tweaking? Does it qualify as a feature request?

Regards
Sivico

**Comment by azat-badretdin** [comment]
Thank you for interesting question, Sivico! 

Unfortunately, the answer is no. There are very basic differences between euk and prok biological mechanisms of translation that needed to be deep in code. Prokaryotic pipeline does not have these reflected.

Even with eukaryotic reference data supplied, you will get wrong results even if it will manage to finish without permanentFails

**Comment by sivico26** [comment]
Thanks for the quick answer!
