### ISSUE TITLE
[BUG] Failed genome annotation

### ISSUE THREAD

**Issue by kevinwkeating** [ncbi/pgap#165]
**Describe the bug**
Attempted to run PGAP on a de novo bacterial genome assembly. Error message began with "PGAP failed, docker exited with rc = 1 Printing log starting from failed job:"

**To Reproduce**
I have run the MG37 genome and saw the output message "PGAP completed successfully," so I am assuming that it works correctly. I am willing and able to share the genome if asked.

**Expected behavior**
I expected to see "PGAP completed successfully" and to produce annotated genome files.

**Software versions (please complete the following information):**
Amazon Linux 2 AMI (HVM) SSD Volume Type - ami-087c17d1fe0178315 (64-bit x86)
m5.2xlarge (8 cores, 32 GB RAM), 150 GiB storage
Docker image ncbi/pgap:2021-07-01.build5508
I had to terminate the server and did not grab the docker version, but it was the most recent version installed on 9/16/201.

**Log Files**
Attached

**Additional context**
Genome was assembly from ONT long and Illumina short reads with Unicycler. BUSCO and QUAST metrics attached.

[ds12_debug_logs.zip](https://github.com/ncbi/pgap/files/7198300/ds12_debug_logs.zip)
[short_summary.specific.rhodospirillales_odb10.busco_score_DS12.txt](https://github.com/ncbi/pgap/files/7198364/short_summary.specific.rhodospirillales_odb10.busco_score_DS12.txt)
[quast_report.txt](https://github.com/ncbi/pgap/files/7198366/quast_report.txt)

**Comment by azat-badretdin** [comment]
Thank you for your report! Could you please post `cwltool.log` file it produced?

**Comment by kevinwkeating** [comment]
Thank you for responding so quickly! Please see attached
[cwltool.log](https://github.com/ncbi/pgap/files/7198932/cwltool.log)
.

**Comment by azat-badretdin** [comment]
Thanks!

The log says: 

```

ncbi::CObjectIStream::ExpectedMember() --- line 1: member city expected ( at JsonValue.contact_info)

```

Please have a look at the contact info in your `submol.yaml` file, do you have the city specified?

**Comment by azat-badretdin** [comment]
> 'm not sure if the others were "required"

No need to guess any more, Kevin :-) 

Here is the Wiki that describes the optional and what is not:

https://github.com/ncbi/pgap/wiki/Input-Files

See `contact_info` section for example. 

Glad it was resolved. Happy landings, Kevin!
