### ISSUE TITLE
Fail to annotate a sequence construct by GATK

### ISSUE THREAD

**Issue by JakeSLLeung** [ncbi/pgap#167]
Dear all,

I tried to annotate a sequence of A. baumannii which is construct by GATK, but I eventually fail and get the log file attached below. Could you please offer a help, or point out whats wrong? Thank you for your kindly attention
[cwltool.log](https://github.com/ncbi/pgap/files/7222153/cwltool.log)

Best regards,
Jake

**Comment by azat-badretdin** [comment]
Thank you for your report, user JakeSLLeung!

The first occurrence of "permanentFail" message is in "fastaval" node. 

Please examine your output directory for a corresponding XML file (fastaval.xml) it should contain useful hints on what was wrong in the input file.

**Comment by JakeSLLeung** [comment]
sorry, my output folder only contains 3 file.
1. cwltool.log
2. MDRA_21M1005170_GCF_008632635.1_renamed_header_chromosome.consensus.fasta
3. pgap_submol_6mj0jc_x.yaml
I cannot see any XML file. (fastaval.xml)

And this is my command line to work for.
./pgap.py -r -o Results/20210822_MDRA_pyneh/compare/21M1005170_GCF_008632635.1 Input/20210822_MDRA_pyneh/compare/MDRA_21M1005170_GCF_008632635.1_input.yaml

**Comment by thibaudnis** [comment]
Hi! Do the inputs conform to the guidelines in the [wiki](https://github.com/ncbi/pgap/wiki/Input-Files) ?

**Comment by azat-badretdin** [comment]
Thanks! Could you please rerun it with `--debug` flag? The output should be under a directory that starts with `debug*`, please use `find debug* --name \*.xml`

> Hi! Do the inputs conform to the guidelines in the wiki ?

That's not a prime suspect right now.

**Comment by JakeSLLeung** [comment]
Thanks. I found out the failure is due to my fasta header, so the problem is solved.

However, I would like to ask one more question. If my sequence has a number of N at either beginning or end, is there any alternate way to annotate it? Thank you.

**Comment by azat-badretdin** [comment]
You can try `--ignore-all-errors` parameter

**Comment by JakeSLLeung** [comment]
Thank you for your help, @azat-badretdin 
All problems are well solved. If there is a new issue, I will raise it again.
Thank you again!

**Comment by azat-badretdin** [comment]
You are welcome!
