### ISSUE TITLE
[BUG] Recurring permanentFail

### ISSUE THREAD

**Issue by dlhuseby** [ncbi/pgap#169]
I am having some trouble with getting pgap to run consistently. When it fails to run, it goes for about 15 minutes and then suffers a permanent failure for some reason I can't puzzle out.

I finally had the pipeline up and running, and successfully ran it on the test genome and 4 assemblies of my own, but now it has encountered an error on the 5th genome. Since I have had some trouble before, I have put together a couple of .yaml files that I only have to change minimal fields on to run pgap on a new sequence. I can go back and successfully run pgap on the previously successful fasta files using the .yaml files with the correct fields, so perhaps it is something unacceptable in my current fasta file?

macOS 10.13.6
pgap.py version 2021-07-01.build5508
Docker version 20.10.8, build 3967b7d

Log and files from failed run:
[4797 cwltool.log](https://github.com/ncbi/pgap/files/7311656/4797.cwltool.log)
[debug.zip](https://github.com/ncbi/pgap/files/7311659/debug.zip)

**Comment by azat-badretdin** [comment]
Thank you, user dlhuseby, for continuous use of PGAPx!

Let's see what's what here:

`cwltool.log` says at first mention of `permanentFail`:

```

[2021-10-08 11:33:42] INFO [job screen_evaluate] /pgap/output/debug/tmp-outdir/2qliw_m5$ screen_evaluate \
    -ifmt \
    seq-annot \
    -tab \
    /pgap/output/debug/tmpdir/dyxb58dw/stg1df74914-78b2-4cdd-891f-1c772551d3ca/calls.tab
[2021-10-08 11:33:43] DEBUG Could not collect memory usage, job ended before monitoring began.
[2021-10-08 11:33:43] WARNING [job screen_evaluate] completed permanentFail

```

that means that input sequence is contaminated. I see from the log file you posted that you have `calls.tab` reported in the output directory - it contains information about contaminated genomic ranges
