### ISSUE TITLE
Fail test annotation

### ISSUE THREAD

**Issue by scubapenn** [ncbi/pgap#17]
I get this error when running test genome:
[2019-06-03 18:50:07] [workflow ] start
[2019-06-03 18:50:07] [workflow ] starting step passdata
[2019-06-03 18:50:07] [step passdata] start
[2019-06-03 18:50:07] [step passdata] completed success
[2019-06-03 18:50:07] [workflow ] starting step fastaval
[2019-06-03 18:50:07] [step fastaval] start
[2019-06-03 18:50:07] [step fastaval] completed success
[2019-06-03 18:50:07] [workflow ] starting step prepare_input_template
[2019-06-03 18:50:07] [step prepare_input_template] start
[2019-06-03 18:50:07] [workflow prepare_input_template] start
[2019-06-03 18:50:07] [workflow prepare_input_template] starting step yaml2json
[2019-06-03 18:50:07] [step yaml2json] start
[2019-06-03 18:50:07] [step yaml2json] completed success
[2019-06-03 18:50:07] [workflow prepare_input_template] starting step pgapx_yaml_ctl
[2019-06-03 18:50:07] [step pgapx_yaml_ctl] start
[2019-06-03 18:50:08] [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/output_annotation
[2019-06-03 18:50:08] [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/output_ltp
[2019-06-03 18:50:08] [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/input_asn_type
[2019-06-03 18:50:08] [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/taxid
[2019-06-03 18:50:08] [step pgapx_yaml_ctl] completed permanentFail
[2019-06-03 18:50:08] [workflow prepare_input_template] completed permanentFail
[2019-06-03 18:50:08] [step prepare_input_template] completed permanentFail
[2019-06-03 18:50:08] [workflow ] completed permanentFail
docker exited with rc = 1

**Comment by azat-badretdin** [comment]
Could you please run this with `--debug` option and post the content of the file `submol.json` and `pgapx_yaml_ctl.*.log`. You might want to use `find`, but before running please `chmod -R u+rx .`

Thanks!

**Comment by azat-badretdin** [comment]
Internal ticket PGAPX-429 opened

**Comment by scubapenn** [comment]
topology: circular
organism:
    taxon:  243273
    strain: 'replaceme'
contact_info:
    last_name: 'Doe'
    first_name: 'Jane'
    email: 'jane_doe@gmail.com'
    organization: 'Institute of Klebsiella foobarensis research'
    department: 'Department of Using NCBI'
    phone: '301-555-0245'
    street: '1234 Main St'
    city: 'Docker'
    postal_code: '12345'
    country: 'Lappland'
    
authors:
    -     author:
            first_name: 'Arnold'
            last_name: 'Schwarzenegger'
            middle_initial: 'T800'
    -     author:
            first_name: 'Linda'
            last_name: 'Hamilton'
bioproject: 'PRJNA9999999'
biosample: 'SAMN99999999'      
# -- Locus tag prefix - optional. Limited to 9 letters. Unless the locus tag prefix was officially assigned by NCBI, ENA, or DDBJ, it will be replaced upon submission of the annotation to NCBI and is therefore temporary and not to be 
used in publications. If not provided, pgaptmp will be used.
locus_tag_prefix: 'tmp'
publications:
    - publication:
        pmid: 16397293
        title: 'Discrete CHARMm of Klebsiella foobarensis. Journal of Improbable Results, vol. 34, issue 13, pages: 10001-100005, 2018'
        status: published  # this is enum: controlled vocabulary
        authors:
            - author:
                first_name: 'Arnold'
                last_name: 'Schwarzenegger'
                middle_initial: 'T800'
            - author:
                  first_name: 'Linda'
                  last_name: 'Hamilton'

**Comment by scubapenn** [comment]
more ./mg37_results.2/debug/log/pgapx_yaml_ctl.1502.log 
00184/000/0000/PB DCBE00B8CF678141 0001/0001 2019-06-04T13:54:28.109697 59830e92b933    UNK_CLIENT      UNK_SESSION              pgapx_yaml_ctl start         /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2019-05-1
3.build3740/arch/x86_64/bin/pgapx_yaml_ctl -ifmt JSON -input /tmp/tmpksgcayt2/stg65cfc086-9c3a-4d7c-a85d-919ed58e1a7b/submol.json -input-fasta /tmp/tmpksgcayt2/stgc7bdbf29-53b2-406d-9c58-d62a489ab08d/ASM2732v1.annotation.nucleotide.1.
fasta -ofmt JSON -output-annotation input.asn -output-asn-type input_asn_type.txt -output-ltp genome.ltp.txt -output-taxid taxid.txt -taxon-db /tmp/tmpksgcayt2/stg048e1799-576e-4f29-8c21-652ae604acb9/taxonomy.sqlite3
00184/000/0000/PB DCBE00B8CF678141 0002/0002 2019-06-04T13:54:28.111951 59830e92b933    UNK_CLIENT      UNK_SESSION              pgapx_yaml_ctl extra         ncbi_app_username=&ncbi_app_path=/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/ba
cterial_pipeline/system/2019-05-13.build3740/arch/x86_64/bin/pgapx_yaml_ctl&ncbi_app_build_date=May+13+2019+12:55:23&ncbi_app_version=0.0.0&ncbi_app_sc_version=22&ncbi_app_vcs_revision=586246
00184/000/0000/P  DCBE00B8CF678141 0003/0003 2019-06-04T13:54:28.119035 59830e92b933    UNK_CLIENT      UNK_SESSION              pgapx_yaml_ctl Error: CORELIB(106.16) "ncbiapp.cpp", line 529: ncbi::CNcbiApplication::x_TryMain() --- Ap
plication's execution failed (CSerialException::eFormatError) line 1: '}' expected ( at JsonValue.organism)
00184/000/0000/PE DCBE00B8CF678141 0004/0004 2019-06-04T13:54:28.125527 59830e92b933    UNK_CLIENT      UNK_SESSION              pgapx_yaml_ctl stop          3 0.054496049

**Comment by scubapenn** [comment]
more ./mg37_results.3/debug/log/pgapx_yaml_ctl.1502.log
00182/000/0000/PB AEC700B6CF6789C1 0001/0001 2019-06-04T13:56:44.719894 62dafcb80f9d    UNK_CLIENT      UNK_SESSION              pgapx_yaml_ctl start         /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2019-05-1
3.build3740/arch/x86_64/bin/pgapx_yaml_ctl -ifmt JSON -input /tmp/tmp7f52gsqh/stg86d1f0cf-ef4e-4cfa-b32e-ab4b6ce16022/submol.json -input-fasta /tmp/tmp7f52gsqh/stg3ee35762-cf22-47df-b0a7-360d0d62e82d/ASM2732v1.annotation.nucleotide.1.
fasta -ofmt JSON -output-annotation input.asn -output-asn-type input_asn_type.txt -output-ltp genome.ltp.txt -output-taxid taxid.txt -taxon-db /tmp/tmp7f52gsqh/stg474e3300-ccbe-4a9c-b563-2ba804881282/taxonomy.sqlite3
00182/000/0000/PB AEC700B6CF6789C1 0002/0002 2019-06-04T13:56:44.721278 62dafcb80f9d    UNK_CLIENT      UNK_SESSION              pgapx_yaml_ctl extra         ncbi_app_username=&ncbi_app_path=/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/ba
cterial_pipeline/system/2019-05-13.build3740/arch/x86_64/bin/pgapx_yaml_ctl&ncbi_app_build_date=May+13+2019+12:55:23&ncbi_app_version=0.0.0&ncbi_app_sc_version=22&ncbi_app_vcs_revision=586246
00182/000/0000/P  AEC700B6CF6789C1 0003/0003 2019-06-04T13:56:44.728124 62dafcb80f9d    UNK_CLIENT      UNK_SESSION              pgapx_yaml_ctl Error: CORELIB(106.16) "ncbiapp.cpp", line 529: ncbi::CNcbiApplication::x_TryMain() --- Ap
plication's execution failed (CSerialException::eFormatError) line 1: '}' expected ( at JsonValue.organism)
00182/000/0000/PE AEC700B6CF6789C1 0004/0004 2019-06-04T13:56:44.734471 62dafcb80f9d    UNK_CLIENT      UNK_SESSION              pgapx_yaml_ctl stop          3 0.051583051

**Comment by scubapenn** [comment]
Any word on this error yet?

**Comment by azat-badretdin** [comment]
`taxon: 243273` presence of the input field in your input `submol.yaml` file indicates that you are using a bit outdated format for YAML. We are using now combo: ```organism:
    genus_species: 'Mycoplasma genitalium' 
    strain: 'replaceme'
```
under `organism` field in input `submol.yaml`

I suggest to freshen up your installation as it is suggested in https://github.com/ncbi/pgap/wiki/Quick-Start

```
curl -OL https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py
time nohup ./pgap.py --update  > pgap.py.update.log &
watch -n 1 tail -c40 pgap.py.update.log

```

**Comment by scubapenn** [comment]
I am still getting this same error. I just ran ./pgap.py --update  > pgap.py.update.log & and it says: 
PGAP version 2019-05-13.build3740 is up to date.

**Comment by scubapenn** [comment]
time nohup ./pgap.py --update  > pgap.py.update.log &
[1] 48662
(11:44 kpenn@ActinodeC ~/bin/PGAP.dir) $ nohup: ignoring input and redirecting stderr to stdout

real	0m0.271s
user	0m0.113s
sys	0m0.031s

**Comment by slottad** [comment]
Please delete the old files and try again. 

`rm -rf test_genomes* input*`

**Comment by scubapenn** [comment]
This did not fix the problem

**Comment by YU-DENG** [comment]
I encountered the same problem, has this been solved yet?
