### ISSUE TITLE
PGAP with SLURM or AWS

### ISSUE THREAD

**Issue by kpenn88** [ncbi/pgap#172]
I am attempting to run PGAP on many bacterial genomes but running more than two PGAP.py jobs seems to fail. 
**Describe the bug**
When I try to run multiple PGAP.py the script fails, this occurs if I try to run it on the head node or if I try to spread my jobs out on multiple worker nodes.

**Comment by kpenn88** [comment]
Update: This is the error I get when I try to run PGAP via slurm, PGAP works fine if I use two worker nodes but on the 3rd worker node I get:
```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.26/images/create?fromImage=ncbi%2Fpgap&tag=2021-07-01.build5508: dial unix /var/run/docker.sock: connect:
 permission denied
The latest version of PGAP is 2021-07-01.build5508, you have nothing installed locally.
Downloading (as needed) Docker image ncbi/pgap:2021-07-01.build5508
None
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.26/images/create?fromImage=ncbi%2Fpgap&tag=2021-07-01.build5508: dial unix /var/run/docker.sock: connect:
 permission denied
The latest version of PGAP is 2021-07-01.build5508, you have nothing installed locally.
Downloading (as needed) Docker image ncbi/pgap:2021-07-01.build5508
None

```

**Comment by azat-badretdin** [comment]
I want to double check if the "third node" is somehow configured differently. Have you tried to reproduce it with a different combination of three nodes? (different hosts)

**Comment by kpenn88** [comment]
The third node is the same as the other nodes. As long as I only run 2 nodes with PGAP they run no matter what node I use. There are several other nodes I could use too but I have only been able to use 2. Thanks.

**Comment by azat-badretdin** [comment]
Thanks! This looks like limitation of licensing (prime suspect for now). Let me see what we can do

**Comment by kpenn88** [comment]
Hmm. Licensing of what piece? Thanks. Let me know what you find.

**Comment by azat-badretdin** [comment]
I do not know yet. This is new for us.

**Comment by kpenn88** [comment]
More errors while trying to run PGAP with SLURM:

[2021-11-18 16:13:56] ERROR [job cluster_blastp_wnode_2] Job error:
[2021-11-18 19:51:07] ERROR [job cluster_blastp_wnode] Job error:
[2021-11-18 19:52:55] ERROR [job cluster_blastp_wnode] Job error:
    "file:///pgap/pgap/pgap.cwl#standard_pgap/final_asndisc_error_diag": null,
    "file:///pgap/pgap/pgap.cwl#standard_pgap/final_asnval_error_diag": null
    "file:///pgap/pgap/pgap.cwl#standard_pgap/initial_asndisc_error_diag": {
    "file:///pgap/pgap/pgap.cwl#standard_pgap/initial_asnval_error_diag": {
  File "/usr/lib64/python3.7/urllib/request.py", line 569, in error
  File "/usr/lib64/python3.7/urllib/request.py", line 649, in http_error_default
    "final_asndisc_error_diag": null,
    "final_asnval_error_diag": null,
    "initial_asndisc_error_diag": {
    "initial_asnval_error_diag": {
slurmstepd: error: If munged is up, restart with --num-threads=10
slurmstepd: error: Munge encode failed: Failed to access "/var/run/munge/munge.socket.2": No such file or directory
Unable to find error in log file.
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded

**Comment by kpenn88** [comment]
I have also notice that PGAP makes multiple versions of annotation of one genome when running it via slurm.

**Comment by azat-badretdin** [comment]
That seems like a slurm issue. Are you sure you separated the input data for different jobs on slurm?

**Comment by kpenn88** [comment]
What do you mean by separated? Do the fasta files and yaml for each genome need to be in a separate directory for each genome? Currently all the fasta files and yaml files for all the genomes are in the same directory.

**Comment by azat-badretdin** [comment]
> Do the fasta files and yaml for each genome need to be in a separate directory for each genome? 

We currently do not have this requirement, we have not investigated concurrency yet. Please try to separate the inputs into completely separate directories (that includes separate copies of `pgap.py`)

We run internally PGAPx in parallel but this parallelism is tuned to the cloud where nodes are completely independent and do not share any common file space.

**Comment by kpenn88** [comment]
I am interested to know how you use pgap on the cloud? Is there a preconfigured way to submit via aws? We have access to aws.

**Comment by azat-badretdin** [comment]
We use very basic layer of AWS: `aws` command to spawn machines, to `ssh` to them, to upload/download data, and to run jobs. As organization we are solidifying on the ways "to cloud" on a higher level like Kubernetes, etc. but for now that's that. 

The commands are specific to us and we are not ready to productify them yet (not sure if this is in plans or not)
