### ISSUE TITLE
Taxonomy input from taxcheck

### ISSUE THREAD

**Issue by kpenn88** [ncbi/pgap#173]
I am wondering if there are any plans to take the results from TaxCheck and apply them to the Genus species required by the Yaml, this would help automate large scale annotations efforts.

**Comment by thibaudnis** [comment]
Hello - thank you for the suggestion. We have considered making this an option, but don't have a timeline for implementing it. It is nice to hear that there is support for it!

**Comment by silvtal** [comment]
> Hello - thank you for the suggestion. We have considered making this an option, but don't have a timeline for implementing it. It is nice to hear that there is support for it!

I would be interested as well!

**Comment by thibaudnis** [comment]
@kpenn88 and @silvtal : we added this feature in [2022-02-10.build5872](https://github.com/ncbi/pgap/releases/tag/2022-02-10.build5872) . There is a `--auto-correct-tax` flag in `pgap.py` to override the organism provided in the input YAML file, if the taxcheck predicts a different organism with high confidence. You will need to use  `--auto-correct-tax` in combination with `--taxcheck`. Please let us know how that works for you! Thanks
