### ISSUE TITLE
[BUG] PGAP failed on WSL2 Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Suang4608** [ncbi/pgap#174]
Hello:
I had a similar failed with #170 and #162, but I run on my Windows PC with WSL2. And the failed had been reproduced with test_genomes/MG37.

##### Failed report #####

PGAP version 2021-07-01.build5508 is up to date.
Output will be placed in: /mnt/d/Sequence_ubuntu/PGAP/test_genomes-2021-07-01.build5508/MG37/KEKW
PGAP failed, docker exited with rc = 1
Printing log starting from failed job:

< ....... log information ...... >

##### Software versions #####

-OS: Windows 10 21H1
-WSL: WSL2 Ubuntu 20.04 LTS
-python: python3.9 (3.9.0-5~20.04)
-Docker: Docker Desktop 4.1.1 (69879)

##### Log files #####

Command: /mnt/d/Sequence_ubuntu/PGAP/pgap.py -r -o KEKW --ignore-all-errors input.yam
[cwltool.log](https://github.com/ncbi/pgap/files/7533676/cwltool.log)

##########

I will try on another machine with CentOS 7 next week. But I still curious about what's wrong.
Thank you!!

Best regards.

Wei-An Shih
s46081040@gs.ncku.edu.tw

**Comment by azat-badretdin** [comment]
This particular issue is indeed the same as the tickets you posted, albeit on a different system. We have a fix for this particular issue and we are ad hoc testing new release on Ubuntu 20

**Comment by azat-badretdin** [comment]
#162 is not related.

**Comment by Suang4608** [comment]
Thanks for your response.

Regards!

Wei-An Shih

**Comment by azat-badretdin** [comment]
Note that although we were able to reproduce this particular problem on Ubuntu, we are having some other issues with Ubuntu 20. For now we recommend to try to downgrade Ubuntu to 18 if you can.

**Comment by Suang4608** [comment]
I am now trying install 18.04 as 2nd subsystem. But it can not connect to docker and my working driver. I will report below if I solve these problem and have an attempt. Thanks for your suggestion!

Regards!

Wei-An Shih

**Comment by Suang4608** [comment]
Hello!
I had fixed the connection problem. It produced similar reports in Ubuntu 18.04. Log file attached.

[cwltool.log](https://github.com/ncbi/pgap/files/7546799/cwltool.log)

I noticed that the first call of "permanentFail" of all log files are all like this:

[ "time_stamp" ] WARNING [job Run_GeneMark_Training] completed permanentFail

Hope it helps!

Regards!

Wei-An Shih

**Comment by azat-badretdin** [comment]
> I noticed that the first call of "permanentFail" of all log files are all like this:

This is expected. The fix for that is only coming, we haven't released it yet.

**Comment by Suang4608** [comment]
Thanks for your response! I will follow closely! 

Regards,

Wei-An Shih

**Comment by thibaudnis** [comment]
@Suang4608 : There is a [new pgap release](https://github.com/ncbi/pgap/releases/tag/2021-11-29.build5742) available. Would you be able to try it on this genome?

**Comment by Suang4608** [comment]
Thank you for mention that! It works well! Thanks a lot!

**Comment by azat-badretdin** [comment]
Did it work on WSL2?

**Comment by Suang4608** [comment]
Yes!! Here's some other information.

Windows 10 21H1
Ubuntu 20.04 LTS
Docker desktop version 4.2.0 
Docker engine version 20.10.10, build b485636
[cwltool.log](https://github.com/ncbi/pgap/files/7667443/cwltool.log)

**Comment by azat-badretdin** [comment]
Thanks!

**Comment by audjoselo** [comment]
> Hello! I had fixed the connection problem. It produced similar reports in Ubuntu 18.04. Log file attached.
> 
> [cwltool.log](https://github.com/ncbi/pgap/files/7546799/cwltool.log)
> 
> I noticed that the first call of "permanentFail" of all log files are all like this:
> 
> [ "time_stamp" ] WARNING [job Run_GeneMark_Training] completed permanentFail
> 
> Hope it helps!
> 
> Regards!
> 
> Wei-An Shi

Hello, maybe could you tell me how to fix this problem?

**Comment by Suang4608** [comment]
Well...I did not fixed it. It just worked after update with a new release.
I will suggest you to check your cwltool.log carefully and try to use the example files side by side to find out if you are just using a wrong format.

good luck!

WAS
241027

**Comment by audjoselo** [comment]
> Well...I did not fix it. It just worked after update with a new release. I will suggest you to check your cwltool.log carefully and try to use the example files side by side to find out if you are just using a wrong format.
> 
> good luck!
> 
> WAS 241027

Ooh, Hehe, I think I will have to wait until the next update. Thanks for your help.
