### ISSUE TITLE
Repeated “completed permanentFail” messages

### ISSUE THREAD

**Issue by gdp3** [ncbi/pgap#18]
My last few runs have all ended with  multiple “completed permanentFail” messages and “docker exited with rc = 1” and yet all the output files were created. The timestamps on the output files indicate that they were created fairly early in the process compared to the full runtime, so I am confused. I have the all the files for the most recent such run, including a console log. If they would be useful, do I just attach the files here?

**Comment by slottad** [comment]
We are sorry for the trouble you have had. We'd be happy to look at any files you wish to send to us, especially cwltool.log. You might also want to run pgap.py with the --debug option enabled, this will place more useful files in the output directory. I am not sure of the file size limits on github, but if they fit, attaching them works well.

**Comment by gdp3** [comment]
Attaching the console output as a start. The github file size limit appears to be 10MB, and cwitool.log is almost 450MB. If other files would be useful I can try my Box account.
[console log.txt](https://github.com/ncbi/pgap/files/3290979/console.log.txt)

**Comment by slottad** [comment]
Thank you, however I don't see any helpful info in the console log. More files would be useful please.

**Comment by gdp3** [comment]
Output files are here:
[(https://uwmadison.box.com/s/m1fva94jtanq2hwj5xuy1dmt3nh16461)]

**Comment by slottad** [comment]
It looks like there is a bad locus tag in the Final_Bacterial_Package_asndisc_evaluate step, but I can't see what it is. Would you please run it with the debug flag enabled, and provide that output directory?

**Comment by gdp3** [comment]
I don't have remote access to the machine in question -- I'm offsite until Monday, but will try then.

**Comment by azat-badretdin** [comment]
@slottad . Douglas. FYI: input locus tag in input yaml file is 

locus_tag_prefix: 'S'

**Comment by gdp3** [comment]
That is in fact the locus tag prefix -- this is one of the older locus_tagged genomes; I want to add some plasmids that never got deposited with the chromosome back in the day.

**Comment by gdp3** [comment]
I reran the job with the debug flag; full output is here:
[https://uwmadison.box.com/s/zkqxpsdoww01zewxrjfbftybshe66384]

**Comment by azat-badretdin** [comment]
Our standard diagnostic software (which is used in many areas of sequence analysis at NCBI, not only for PGAP) detected that PGAP software generated invalid locus tags. At this moment we are not sure what is wrong with these locus tags.

We are planning to add an exception for BAD_LOCUS_TAG_FORMAT in the future (internal ticket PGAPX-411). This will allow users to ignore bad locus tags. 

For now, please just ignore it. Please have in mind that you do have all the necessary results in the output despite this error.

PS. I understand that receiving subject messages is unsettling.
