### ISSUE TITLE
work disk space (GiB) is less than the recommended value of 80 

### ISSUE THREAD

**Issue by utpalh** [ncbi/pgap#180]
I run in windows cygwin and have the following problem.  how do i increase the workspace and any other error that you can see in the log file.

$ ./pgap.py -r -o k_pneu_results k_pneu.yaml
PGAP version 2021-11-29.build5742 is up to date.
Output will be placed in: /cygdrive/e/analysis/pgap/k_pneu_results.1
WARNING: work disk space (GiB) is less than the recommended value of 80
PGAP failed, docker exited with rc = 1
Unable to find error in log file.
-------------------------

Cwtool.log
------------

Original command: ./pgap.py -r -o k_pneu_results k_pneu.yaml

Docker command: /cygdrive/c/Program Files/Docker/Docker/resources/bin/docker run -i --rm --user 197609:197121 --volume /cygdrive/e/analysis/pgap/input-2021-11-29.build5742:/pgap/input:ro,z --volume /cygdrive/e/analysis/pgap:/pgap/user_input:z --volume /cygdrive/e/analysis/pgap/pgap_input__nd9wi_x.yaml:/pgap/user_input/pgap_input.yaml:ro,z --volume /tmp:/tmp:rw,z --volume /cygdrive/e/analysis/pgap/k_pneu_results.1:/pgap/output:rw,z ncbi/pgap:2021-11-29.build5742 cwltool --timestamps --debug --disable-color --preserve-entire-environment --outdir /pgap/output pgap/pgap.cwl /pgap/user_input/pgap_input.yaml

--- Start YAML Input ---
fasta:
    class: File
    location: k_pneu.fasta
submol:
    class: File
    location: pgap_submol_a94kb_kg.yaml
supplemental_data: { class: Directory, location: /pgap/input }
report_usage: true
--- End YAML Input ---

--- Start Runtime Report ---
{
    "CPU cores": 8,
    "Docker image": "ncbi/pgap:2021-11-29.build5742",
    "cpu flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves md_clear flush_l1d arch_capabilities",
    "cpu model": "Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz",
    "max user processes": "unlimited",
    "memory (GiB)": 24.9,
    "memory per CPU core (GiB)": 3.1,
    "open files": 1048576,
    "tmp disk space (GiB)": 228.5,
    "virtual memory": "unlimited",
    "work disk space (GiB)": 12.5
}
--- End Runtime Report ---

[2022-01-22 06:07:56] INFO /pgap/venv/bin/cwltool 3.1.20211107152837
[2022-01-22 06:07:56] INFO Resolved 'pgap/pgap.cwl' to 'file:///pgap/pgap/pgap.cwl'
[2022-01-22 06:07:56] ERROR Tool definition failed validation:
[Errno 21] Is a directory: '/pgap/user_input/pgap_input.yaml'
Traceback (most recent call last):
  File "/pgap/venv/lib/python3.9/site-packages/schema_salad/fetcher.py", line 85, in fetch_text
    with open(
IsADirectoryError: [Errno 21] Is a directory: '/pgap/user_input/pgap_input.yaml'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/pgap/venv/lib/python3.9/site-packages/cwltool/main.py", line 1071, in main
    job_order_object, input_basedir, jobloader = load_job_order(
  File "/pgap/venv/lib/python3.9/site-packages/cwltool/main.py", line 355, in load_job_order
    job_order_object, _ = loader.resolve_ref(
  File "schema_salad/ref_resolver.py", line 518, in resolve_ref
  File "schema_salad/ref_resolver.py", line 980, in fetch
  File "/pgap/venv/lib/python3.9/site-packages/schema_salad/fetcher.py", line 92, in fetch_text
    raise ValidationException(str(err)) from err
schema_salad.exceptions.ValidationException: [Errno 21] Is a directory: '/pgap/user_input/pgap_input.yaml'

**Comment by azat-badretdin** [comment]
Thank you for your report!

The output complains about lack of space, could you please run it on a filesystem with enough space (80gb)?

Thanks

**Comment by utpalh** [comment]
Thanks, i found the solution of  copying the image to different location
