### ISSUE TITLE
[FEATURE REQUEST] PGAP - ANI  taxonomic module

### ISSUE THREAD

**Issue by JayanthiGangiredla** [ncbi/pgap#182]
Hi ,

We are interested in creating a Galaxy tool on ANI taxonomic module. Is there a better way to split the PGAP tool and create a sub tool version where we can just get the ANI Taxa match info that we needed? Any suggestions would be helpful!

Thanks,
Jayanthi Gangiredla

**Comment by thibaudnis** [comment]
Hi Jayanthi - this is great! We'd love to have ANI in Galaxy. I see you contacted us via Stacy too, so we will be in touch via email. Thanks!

**Comment by JayanthiGangiredla** [comment]
Thank you for your reply. Can you please help us in adding a sub tool version of ANI taxonomy module in github which we can use to create a galaxy tool. We need a package with scripts and the database to download.

Any suggestions could be very helpful in this process!

Thanks,
Jayanthi

From: Francoise Thibaud-Nissen ***@***.***>
Reply-To: ncbi/pgap ***@***.***>
Date: Friday, February 4, 2022 at 8:15 AM
To: ncbi/pgap ***@***.***>
Cc: "Jayanthi. Gangiredla" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [ncbi/pgap] [FEATURE REQUEST] PGAP - ANI taxonomic module (Issue #182)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi Jayanthi - this is great! We'd love to have ANI in Galaxy. I see you contacted us via Stacy too, so we will be in touch via email. Thanks!
