### ISSUE TITLE
WARNING Final process status is permanentFail

### ISSUE THREAD

**Issue by dgutierrezcastillo** [ncbi/pgap#185]
Greetings,

I am having problems running PGAP on an HPC that runs with singularity. Similar to issue #86, I get these scores during the runtime report:

--- Start Runtime Report ---
{
    "CPU cores": 24,
    "Docker image": "ncbi/pgap:2022-02-10.build5872",
    "cpu flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts md_clear spec_ctrl intel_stibp flush_l1d",
    "cpu model": "Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz",
    "max user processes": 4096,
    "memory (GiB)": 125.8,
    "memory per CPU core (GiB)": 5.2,
    "open files": 1048576,
    "tmp disk space (GiB)": 1.0,
    "virtual memory": "unlimited",
    "work disk space (GiB)": 142.2
}
--- End Runtime Report ---

Even though I am using the `--cpus 24` flag in my command, the tmp disk space and memory per CPU core are not reflecting it. Attached is the cwl.log as well.

[cwltool.log](https://github.com/ncbi/pgap/files/8103495/cwltool.log)

Thanks,
Diego

**Comment by azat-badretdin** [comment]
Thank you for your report, Diego!

I see that you are trying the C.jejuni case provided in our test_genomes package. This genome is supposed to fail as a test of our functionality to detector adaptor contamination. 

See first instance of `permanentFail` message in the `cwltool.log` you provided:

```

[2022-02-20 05:39:42] INFO [job screen_evaluate] /tmp/7zdsoxk9$ screen_evaluate \
    -ifmt \
    seq-annot \
    -tab \
    /tmp/u_pg3dqq/stg59a8acc4-9105-4a5e-825c-dd152bfbc7a5/calls.tab

```

The output directory contains the file `calls.tab` which lists the adaptor regions that are discovered to the sequence indicating to contamination by adaptors (adaptors are not properly removed)
