### ISSUE TITLE
Final process status is permanentFail

### ISSUE THREAD

**Issue by Nirmal2310** [ncbi/pgap#186]
Hi, first of all, a great tool for bacterial annotation. I am using this to annotate my genome assembly but I am getting this error of while running this pipeline for my assembled genome. I am attaching the log file of cwltool, can you please help me out with this?
Thank you so much.

[cwltool.log](https://github.com/ncbi/pgap/files/8104835/cwltool.log)

**Comment by thibaudnis** [comment]
Hi - the clue in the log file is this: 
```
min = 3767000
max = 5652000
genome_size = 10159515
verify-genome-size: fail
```
It means that for the species associated with this genome, we expect the assembly to be between ~3.77 and 5.65 Mb. However the genome you provided is 10.16 Mb. 
If you are confident that the species is correct and want to run PGAP anyway, try again with the flag `--igenore-all-errors`. If not you can run with `--taxcheck` and `--auto-correct-tax`; with these flags, the process will first run the [Average Nucleotide Identity (ANI)](https://github.com/ncbi/pgap/wiki/Taxonomy-Check) tool on the genome, and run PGAP with the species ANI predicts.
