### ISSUE TITLE
[BUG] WARNING Final process status is permanentFail

### ISSUE THREAD

**Issue by dgutierrezcastillo** [ncbi/pgap#188]
Greetings,

I am not able to run PGAP with my assembled genomes. I ran it with the MG37 test genome and it ran successfully although it gave me the warning of having low space in the tmp outdir (1 Gb). However I set the outdir from the singularity cache in the sratch folder of our HPC so I should have more space than that. I can provide our draft genome if necessary.

**Software versions **
 - Red Hat Enterprise Linux 7
 - pgap.py -- 2022-02-10.build5872
 - Singularity/3.7.4

Thanks,
Diego
[cwtool.log.zip](https://github.com/ncbi/pgap/files/8143001/cwtool.log.zip)

**Comment by azat-badretdin** [comment]
Thank you for your report, Diego. 

The first `permanentFail` message indicate to the error output that says: 

```

    Error: CWL(CException::eUnknown) "/export/home/gpipe/TeamCity/Agent3/work/427aceaa834ecbb6/ncbi_cxx/src/internal/gpipe/app/cloud/cwl/pgapx_yaml_ctl.cpp", line 246: CPgapxYamlCtlApplication::Run() --- Unknown organism Xanthomonas tranlucens

```

I suspect you wanted [Xanthomonas translucens](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=343&lvl=3&lin=f&keep=1&srchmode=1&unlock), with "s" between N and L.

**Comment by dgutierrezcastillo** [comment]
Thank you for your response Azat! I was able to run one of my genomes successfully after fixing the typo but the other one keeps giving me an error. It is a Xanthomonas translucens as well

[cwltool (3).log](https://github.com/ncbi/pgap/files/8147062/cwltool.3.log)
.

**Comment by azat-badretdin** [comment]
> although it gave me the warning of having low space in the tmp outdir (1 Gb). 

The output still shows low tmp space. Could you please try to address that in your setup?

**Comment by abdziz** [comment]
Greetings,
I am facing a similar problem. The test genome works but my query sequence reports permanent failure. I am annotating plasmids.
[cwltool.log](https://github.com/ncbi/pgap/files/8160232/cwltool.log)

**Comment by azat-badretdin** [comment]
The report says: `Unknown organism Baccillus thuringiensis` 

You made a typo in Baccillus. It's Bacillus.

**Comment by dgutierrezcastillo** [comment]
Hi Azat,

Thank you for your response. I have tried different combinations with the slurm nodes, ntasks, memory allocated but the program still gives me the same output of having low tmp disk even though I should have more than 6,4TB in the scratch directory where my singularity cache dir is set to.

Diego

**Comment by abdziz** [comment]
Thank you for the response Azat! I fixed the name but it still failed. I am using 16gb RAM and 8 cpu cores computer. I used --cpu 4 flag, that also failed. Attached are cwltool files.
[cwltool.log](https://github.com/ncbi/pgap/files/8164549/cwltool.log)
[cwltool.log](https://github.com/ncbi/pgap/files/8164553/cwltool.log)

**Comment by abdziz** [comment]
Thank you very much, it worked.

**Comment by azat-badretdin** [comment]
You are welcome!

**Comment by jjsanchez22** [comment]
Hello there,

I am having the same issue. I could run the pipeline on the Mycoplasma genitalium genome provided with the installation. Despite of using a Linux OS, 8gb RAM and only 2 cores. However, I can't run the pipeline with my own genome. Any suggestions would be appreciated.

[cwltool.log](https://github.com/ncbi/pgap/files/9464018/cwltool.log)

**Comment by azat-badretdin** [comment]
@jjsanchez22  from the look of it: 

```
line 1: '[' expected ( at JsonValue.authors.[])
```
there is a problem in the input YAML file.
