### ISSUE TITLE
[BUG] <title>A warning Warning: Field `location` contains undefined reference to `file:///pgap/pgap/input`, then after run 15 min, it reports permanent FAIL!

### ISSUE THREAD

**Issue by minhtrung1997** [ncbi/pgap#189]
**I've downloaded and run successfully PGAP in the November 2021. After then I move pgap folder to 2.Tool folder. Recently when I return to run pgap on a Salmonella dataset, it consistently fails. This is the last attempt cwl.log**

**Software versions **
 I run PGAP on Linux Ubuntu RAM 32 GB and 251GB Disk. CPU is Intel® Xeon(R) CPU E5-2620 0 @ 2.00GHz × 24
the docker is the latest image: ncbi/pgap 2022-02-10.build5872
Could you please take a glance at those input and log files and give us recommendations
Thanks

**Debug zip Files**
`.
[debug.zip](https://github.com/ncbi/pgap/files/8168533/debug.zip)

**CWL log file**
[](url
[cwltool.log](https://github.com/ncbi/pgap/files/8168522/cwltool.log)
)

**Comment by azat-badretdin** [comment]
Thank you for your report! Do you see any errors in `debug/tmp-outdir/m5gw6ux2/fastaval.xml`?

**Comment by azat-badretdin** [comment]
I see that you posted the whole thing. 

Your fastaval.xml output has lines like: 

```

[<message fasta_seq_id="lcl|NODE_100_length_155_cov_95.935897" code="SEQ_SHORT_LENGTH" seq_id="NODE_100_length_155_cov_95.935897" severity="ERROR" tool="fastaval">]()Sequence is shorter than 200 nucleotides</message>

```

Contigs less than 200 bases are not allowed. You can either try to bypass this error by specifying `pgap.py --ignore-all-errors` or you can edit your input assembly.

**Comment by minhtrung1997** [comment]
thank you, I've fix that bug ^^. I'll close now

**Comment by azat-badretdin** [comment]
You are welcome!
