### ISSUE TITLE
Inconsistent annotations

### ISSUE THREAD

**Issue by gdp3** [ncbi/pgap#19]
We ran the same E. coli genome with the same versions of PGAP and data -- one on a Mac an d one on a Linux box. The same Features were predicted in both cases (Feature type, coordinates, etc.) but there were numerous differences in qualifier annotations; out of 4420 CDS features, 302 had different annotations: 276 differed in /product, 32 differed in /gene, 22 differed in /EC_number, and 15 differed in /note (some CDS features differed in more than one qualifier). This sort of variation makes assessing the output less certain as we look into adopting pgap.

**Comment by thibaudnis** [comment]
Thank you for the report. Can you please look in the annot.gbk output file and verify that the value for the "Annotation Software revision" in the comment provided for each annotated contig is the same for both runs?

**Comment by gdp3** [comment]
both files are the same:
Annotation Software revision      :: 2019-05-13.build3740

**Comment by gdp3** [comment]
We saw something similar with the MG37 test file, but I don't have all those files handy. At the time we assumed that the data files must have been different.

**Comment by thibaudnis** [comment]
Thanks for the additional information. We will perform some tests ourselves and report back. 
Our testing has mainly been on Linux so far, and we have verified correctness and consistency on this platform. However, we have only verified that the software runs on OSX.

**Comment by slottad** [comment]
I just completed a run of MG37 on both OSX and Linux, and saw no difference in the annotation files, other than dates/time. Would you be willing to provide you E. coli input files, so I may try it on them as well?

**Comment by gdp3** [comment]
Attached -- had to add the ,txt extension for github to allow upload, so just rename the file.
[chr_final.fas.txt](https://github.com/ncbi/pgap/files/3293314/chr_final.fas.txt)
If you could share back the output .gbk file I can compare the annotations to our two runs (I have a spreadsheet I'm doing the comparisons in).

**Comment by slottad** [comment]
I ran chr_final.fas on both platforms, however they both seemed to stop processing during the Find_ProSplign_Alignments_I_prosplign_wnode step. I am investigating further to figure out why. In the meantime, are you sure your runs completed successfully? Just because they output annotation files does not guarantee a successful run.

**Comment by slottad** [comment]
So I successfully re-ran the annotations on both Linux and OSX. I am still unsure why the previous runs failed, and need to look into that. However, these runs also had no difference, except for dates:

```
$ diff ecoli_results.linux.debug/annot.gbk ecoli_results.osx.debug/annot.gbk 
35c35
<             Annotation Date                   :: 06/17/2019 18:30:06
---
>             Annotation Date                   :: 06/18/2019 01:13:05
```
I am attaching both gbk files in a zip file for you: [annot.zip](https://github.com/ncbi/pgap/files/3299781/annot.zip)

**Comment by gdp3** [comment]
Thanks; I’ll compare them to our runs.

Dr. Guy Plunkett III
Senior Scientist Emeritus, UW-Madison
Senior Scientist, DNASTAR, Inc.
http://www.genome.wisc.edu/information/gplunkett.html





On Jun 17, 2019, at 11:44 PM, Douglas Slotta <notifications@github.com<mailto:notifications@github.com>> wrote:


So I successfully re-ran the annotations on both Linux and OSX. I am still unsure why the previous runs failed, and need to look into that. However, these runs also had no difference, except for dates:

$ diff ecoli_results.linux.debug/annot.gbk ecoli_results.osx.debug/annot.gbk
35c35
<             Annotation Date                   :: 06/17/2019 18:30:06
---
>             Annotation Date                   :: 06/18/2019 01:13:05


I am attaching both gbk files in a zip file for you: annot.zip<https://github.com/ncbi/pgap/files/3299781/annot.zip>

**Comment by slottad** [comment]
Any update on the comparisons?

**Comment by gdp3** [comment]
Sorry ... Thanks for the files. It looks like our Mac run was the odd one out -- our Linux result was essentially the same as both of your runs. So I'm guessing our Mac setup has some issue(s). If you could provide some documentation on how your Mac version is set up, we can try to see what the difference(s) might be. That would be handy for me offsite; onsite we'll use our Linux setup since it is giving reproducible and consistent answers.

**Comment by slottad** [comment]
When running in debug mode, the RUNTIME.json file is created in the debug directory. Here are the contents of mine:

```
{
    "CPU cores": 3,
    "Docker image": "ncbi/pgap:2019-05-13.build3740",
    "cpu model": "Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz",
    "max user processes": "unlimited",
    "memory (GiB)": 15.6,
    "memory per CPU core (GiB)": 5.2,
    "open files": 1048576,
    "tmp disk space (GiB)": 47.0,
    "virtual memory": "unlimited",
    "work disk space (GiB)": 33.8
}
```
We are still trying to verify this, but I suspect the minimum requirements are 4GB/per CPU. It is possible that some of our applications (sometimes) fail silently when this is not the case.

**Comment by Buuntu** [comment]
@slottad What would you recommend for users running it on computers that go above that threshold?

**Comment by slottad** [comment]
@Buuntu Sorry, I missed this comment while I was away on vacation, and only noticed it now as I was belatedly reviewing our issues.

The behavior you are describing usually happens when you are running the pipeline remotely over ssh, and then the connection is interrupted. Not everything is cleaned up nicely when this happens. We have added some checks to mitigate this, but it is recommend that you invoke the pipeline under a terminal multiplexer, such as tmux, or GNU screen since the run times can be long.

**Comment by Buuntu** [comment]
@slottad Maybe it should be added to the Wiki that `nohup` will have weird behaviors?  I know it recommends using tmux already but just for those who think nohup will do the trick as well, like me.

**Comment by tseemann** [comment]
Using `screen`, `tmux` or `mosh` should yield the same behaviour as
```
nohup ./run_my_tools.sh 1> out 2> err &
```
But given this is `docker` who knows!

**Comment by Buuntu** [comment]
What I've experienced is the run times are very long with nohup and if I disconnect, I can't find a trace of the running program yet it still is outputting logs.  This is running on an EC2 instance on Amazon.  I think it does eventually finish but it's very weird behavior where the docker process seems to just disappear entirely, `docker ps` shows nothing.  Still trying to double check whether this affects annotations at all (it may not), but it definitely takes longer in my experience with `nohup` than with `tmux`, and is much harder to debug at the very least.

And yes, maybe it's a docker+nohup thing?

**Comment by azat-badretdin** [comment]
```nohup ./run_my_tools.sh 1> out 2> err &```

I would follow this up with `disown PID`, just in case.
