### ISSUE TITLE
[BUG] PGAP failed, docker exited with rc = 1 WARNING Final process status is permanentFail

### ISSUE THREAD

**Issue by devikarajk** [ncbi/pgap#190]
**Describe the bug**
I have updated PGAP to the latest version of 2022-02-10.build5872. The test genome is working fine and I got the output.
But for my genome the result is "PGAP failed, docker exited with rc = 1" and at the end its showing "WARNING Final process status is permanentFail"

Please help me to solve the issue and annotate my genome.

**To Reproduce**
sure I am ready to share the data

**Expected behavior**
I expected an output like I got for the test genome. I need to annotate my whole genome data

**Software versions (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - pgap.py --version : 2022-02-10.build5872.
 - Docker (or other container runner) version : Docker version 20.10.11, build dea9396e18

**Log Files**
Please rerun pgap.py with the ``--debug`` flag and attach an archive (e.g. zip or tarball) of the logs in the directory: ``debug/tmp-outdir/*/*.log``.

**Additional context**
I tried with --no-internet option as well, but not solved
[ncbiapp.log](https://github.com/ncbi/pgap/files/8205714/ncbiapp.log)
[ncbiapp.log](https://github.com/ncbi/pgap/files/8205716/ncbiapp.log)
[cwltool.log](https://github.com/ncbi/pgap/files/8205717/cwltool.log)

**Comment by azat-badretdin** [comment]
Thank you for your report, Devika! 

The first thing to look in cwltool.log is for the _first_ instance of permanentFail and the error above it.

Your log says: 

```

line 213: ncbi::CObjectIStreamJson::UnexpectedMember() --- line 1: "publication.status": unexpected member, should be one of: "publication"  ( at JsonValue.publications.[].[])

```

Please verify that your input submol YAML file is correct.
