### ISSUE TITLE
Unable to complete annotation

### ISSUE THREAD

**Issue by AerdnaIttualoc** [ncbi/pgap#196]
Hi, 

I am trying to annotate prokaryotic genomes via PGAP, installed following this tutorial
https://github.com/ncbi/pgap/wiki/Quick-Start

testing with the command works, so there should be no installation problems
`./pgap.py -r -o mg37_results test_genomes/MG37/input.yaml`

However by running the command
`./pgap.py -r path/to/Strain.yaml -o path/to/output`

the terminal reports "WARNING Final process status is permanentFail"

this is my .log file
[cwltool.log](https://github.com/ncbi/pgap/files/8443286/cwltool.log)

what am I doing wrong?....

Thanks

**Comment by azat-badretdin** [comment]
Please try to add ` [tech=wgs]` to all your FASTA headers and run again through PGAP?

**Comment by AerdnaIttualoc** [comment]
Is there a tutorial reporting these information besides the github wiki?
https://github.com/ncbi/pgap/wiki/Input-Files

 therefore this parameter must be modified in the fasta and not in the metadata.yaml?

**Comment by azat-badretdin** [comment]
> Is there a tutorial reporting these information 

I believe that there is somewhere a reference on adding these modifiers to FASTA headers. I haven't used it for a while, so now I discovered that it is moved somewhere else. I asked somebody else for help.

> therefore this parameter must be modified in the fasta and not in the metadata.yaml?

That is true. You can't set this file in metadata right now, I believe.

**Comment by azat-badretdin** [comment]
>  I asked somebody else for help.

Karen Clark from GenBank team helped and here is an NCBI reference resource describing different modifiers to FASTA headers: https://www.ncbi.nlm.nih.gov/genbank/mods_fastadefline/

**Comment by AerdnaIttualoc** [comment]
Thanks for the precious help, even that of Karen who has kindly replied to my emails on several occasions

One last question......
If I recive **Internal N's chunk (size:100)** error from fastaval.xlm output what should I do? 


`<message tool="fastaval" severity="WARNING" seq_id="NODE_2_length_437575_cov_23.224847" code="SEQ_INTERNAL_N" fasta_seq_id="lcl|NODE_2_length_437575_cov_23.224847">Internal N's chunk (size:100) from 483</message> `

**Comment by azat-badretdin** [comment]
> If I recive Internal N's chunk (size:100) error from fastaval.xlm output what should I do?

You can break the contig into two, or drop the contig, or drop the small part of it, or simply edit it. 

You can also try to run it with `--ignore-all-errors` option which will get you through the fastaval guard dog, but the subsequent events are unpredictable.
