### ISSUE TITLE
Failed PGAP & Memory Issues

### ISSUE THREAD

**Issue by MacsPack** [ncbi/pgap#197]
Hello,

I'm trying to use PGAP however I keep running into issues and I was hoping someone might have an idea or solution.
I tried to run the command: ./pgap.py -r -o ERR4189738_Results -m 50g test_genomes/ERR4189738_C_tarantellae/input.yaml, but I run into this error within: WARNING: memory per CPU core (GiB) is less than the recommended value of 2
PGAP failed, docker exited with rc = 1 Printing log starting from failed job. The output always ends with: WARNING Final process status is permanentFail

The first few lines in the output are "WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap."

Another individual working with me was able to get the test example running but the code is ignoring the --cpus flag and trying to use all 40 cores on the server I am using. I am working with the lastest PGAP version 2022-02-10.build5872.

If anyone can help shine some light on these errors and propose any advice, I would be extremely grateful.

**Comment by azat-badretdin** [comment]
Thank you for your report, user [MacsPack](https://github.com/MacsPack)!

Could you please post `cwltool.log`?

**Comment by MacsPack** [comment]
Here is the file that got outputted from my command

[cwltool.log](https://github.com/ncbi/pgap/files/8455398/cwltool.log)

**Comment by azat-badretdin** [comment]
Thanks. Apparently, parser does not like tabulation character in your input here:


```

yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 2, column 1:
    	genus_species: 'Clostridium tar ... 

```
