### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by awalling** [ncbi/pgap#198]
Hello, 

After successfully running PGAP for several years on a queued shared memory server, I was prompted upon attempting to use the pipeline this week to update to version 2022-02-10. 

When running ./pgap.py --update, instead of downloading and extracting supplemental directory into my working directory, PGAP attempted to install this data into my home directory, thus exceeding my disk quota. I have manually downloaded this data and placed it in my working directory, and attempted to place this working directory in my path, but upon trying to run pgap.py on either test data or my own data, I receive the message:

`The latest version of PGAP is 2022-02-10.build5872, you have nothing installed locally.
Downloading (as needed) Docker image ncbi/pgap:2022-02-10.build5872
Downloading and extracting tarball: https://s3.amazonaws.com/pgap/input-2022-02-10.build5872.tgz`

etc, and it attempts to install the supplemental data in my home directory again.

Is it possible to point pgap.py in the direction of the supplemental data downloaded into my working directory?

**Comment by azat-badretdin** [comment]
> Is it possible to point pgap.py in the direction of the supplemental data downloaded into my working directory?

Yes. Please use env var `PGAP_INPUT_DIR` for that

**Comment by awalling** [comment]
Hello, 

Thank you very much for your assistance. I was able to successfully install and run PGAP on two complete genome assemblies. However, I have a third very fragmented assembly that I am having some issues with.


Here is [cwltool.log](https://github.com/ncbi/pgap/files/8565717/cwltool.log)

The relevant snippet appears to be this:

`[2022-04-25 23:28:48] INFO [job cluster_blastp_wnode] Max memory used: 32MiB
[2022-04-25 23:28:49] WARNING [job cluster_blastp_wnode] was terminated by signal: SIGKILL
[2022-04-25 23:28:52] WARNING [job cluster_blastp_wnode] completed permanentFail
[2022-04-25 23:28:52] DEBUG [job cluster_blastp_wnode] outputs {
    "outdir": {
        "location": "file:///tmp/mbal52ca/output",
        "basename": "output",
        "nameroot": "output",
        "nameext": "",
        "class": "Directory"
    }
}
[2022-04-25 23:28:52] DEBUG [step cluster_blastp_wnode] produced output {
    "file:///pgap/pgap/task_types/tt_cluster_and_qdump.cwl#cluster_blastp_wnode/outdir": {
        "location": "file:///tmp/mbal52ca/output",
        "basename": "output",
        "nameroot": "output",
        "nameext": "",
        "class": "Directory"
    }
}
[2022-04-25 23:28:52] WARNING [step cluster_blastp_wnode] completed permanentFail
[2022-04-25 23:28:52] DEBUG [job cluster_blastp_wnode] Removing input staging directory /tmp/br8dele8
[2022-04-25 23:28:52] DEBUG [job cluster_blastp_wnode] Removing temporary directory /tmp/0kuipcpi
[2022-04-25 23:28:53] INFO [workflow cluster_and_qdump] completed permanentFail
[2022-04-25 23:28:53] DEBUG [workflow cluster_and_qdump] outputs {
    "blast_align": null
}
[2022-04-25 23:28:53] DEBUG [step cluster_and_qdump] produced output {
    "file:///pgap/pgap/task_types/tt_blastp_wnode_naming.cwl#cluster_and_qdump/blast_align": [
        null
    ]
}
`

Any assistance would be gratefully received!

**Comment by Isaias1108** [comment]
If I have not enough space in my principal disk where is $HOME, how can I put the directory in my suplementary disk with 1 TB spaces?

**Comment by azat-badretdin** [comment]
Absolutely. Please use https://github.com/ncbi/pgap/wiki/Quick-Start instructions on how to set up environmental variable PGAP_INPUT_DIR
