### ISSUE TITLE
Failure to complete annotation 

### ISSUE THREAD

**Issue by bharat1912** [ncbi/pgap#199]
Hi,
Thank you for the WGS annotation tool. I have installed and run the example data (MG37) with only one issue  "WARNING: open files is less than the recommended value of 8000" though the annotation went to completion.

I had some problems relating to structure of the YAML file, the sequence fasta file, out of memory etc. I had looked through the log file to correct the issues. However, I am not sure where the problem lies with the current error noted in the log file which is attached. 

[cwltool.log](https://github.com/ncbi/pgap/files/8539788/cwltool.log)

Thanks in advance for looking into the issue.

**Comment by azat-badretdin** [comment]
This part of the cwltool.log is relevant:

```

    Error: SERIAL(CSerialException::eFormatError) "/export/home/gpipe/TeamCity/Agent3/work/427aceaa834ecbb6/ncbi_cxx/src/serial/objistrjson.cpp", line 213: ncbi::CObjectIStreamJson::UnexpectedMember() --- line 1: "location": unexpected member, should be one of: "strain" "genus_species"  ( at JsonValue.organism.genus_species)

```

Looks like there is a formatting problem in your `submol.yaml` file. The line `location:` got probably misidented.
