### ISSUE TITLE
Issue with 'docker exited with rc = 1'

### ISSUE THREAD

**Issue by dipsaha** [ncbi/pgap#20]
Hello,
I am trying to run NCBI PGAP program in Ubuntu 14.04 LTS OS with Python3. After struggling with installing and running PGAP, I could able to install the program. But while running the program with the below command:
"icar@icar-crijaf:~/Programs/pgap-master$ sudo python3 pgap.py -n -D /usr/local/bin/docker -o /home/icar/Programs/pgap-master/PJRB1 /home/icar/Programs/pgap-master/user_genome/genome.simple2.yaml -d
[sudo] password for icar:"
I am getting the following error: 
PGAP version 2019-05-13.build3740 is up to date.
/home/icar/Programs/pgap-master/PJRB1
docker exited with rc = 1

The cwltool.log is below:
Original command: pgap.py -n -D /usr/local/bin/docker -o /home/icar/Programs/pgap-master/PJRB1 /home/icar/Programs/pgap-master/user_genome/genome.simple2.yaml -d

Docker command: /usr/local/bin/docker run -i --user 0:0 --volume /home/icar/Programs/pgap-master/input-2019-05-13.build3740:/pgap/input:ro,z --volume /home/icar/Programs/pgap-master/user_genome:/pgap/user_input:z --volume /home/icar/Programs/pgap-master/user_genome/pgap_input.yaml:/pgap/user_input/pgap_input.yaml:ro,z --volume /home/icar/Programs/pgap-master/PJRB1:/pgap/output:rw,z --volume /home/icar/Programs/pgap-master/PJRB1/debug/log:/log/srv:z ncbi/pgap:2019-05-13.build3740 cwltool --timestamps --outdir /pgap/output --tmpdir-prefix /pgap/output/debug/tmpdir/ --leave-tmpdir --tmp-outdir-prefix /pgap/output/debug/tmp-outdir/ --copy-outputs pgap.cwl /pgap/user_input/pgap_input.yaml

[2019-06-18 11:21:27] /usr/bin/cwltool 1.0.20190228155703
[2019-06-18 11:21:27] Resolved 'pgap.cwl' to 'file:///pgap/pgap.cwl'
[2019-06-18 11:21:48] Failed to create directory: [Errno 30] Read-only file system: '/pgap/output/debug/tmpdir'

RUNTIME.json log looks like this:
{
    "CPU cores": 16,
    "Docker image": "ncbi/pgap:2019-05-13.build3740",
    "cpu model": "Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz",
    "max user processes": 524288,
    "memory (GiB)": 62.7,
    "memory per CPU core (GiB)": 3.9,
    "open files": 524288,
    "tmp disk space (GiB)": 1740.6,
    "virtual memory": "unlimited",
    "work disk space (GiB)": 1740.6
}

Please help me to troubleshoot the issue and suggest a measure to run the program successfully.

Thanking you.

-Dip

**Comment by slottad** [comment]
You are running this via sudo because your regular user account (icar? ) does not have permission to run docker? This is causing problems. PGAP is trying to map to the user account which runs it, so it doesn't create files that can't be accessed. Since it is run under sudo, it is mapping to user 0, group 0. However, it looks like this violates docker's security construct.

If at all possible, allow your user account to run docker, and then do not use sudo to run it.

**Comment by dipsaha** [comment]
Hi slottad,

Thanks for your suggestion. I have tried to add icar as a 'group' to docker:
$ sudo groupadd docker
[sudo] password for icar: 
groupadd: group 'docker' already exists
icar@icar-crijaf:~/Programs/pgap-master$ sudo usermod -aG docker icar
docker run hello-world
Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
So, till this step to me, the docker is working fine by non-root user

Once I use the following script to run pgap again I get an error:
icar@icar-crijaf:~/Programs/pgap-master$ python3 pgap.py -r -o mg37_results test_genomes/MG37/input.yaml
PGAP version 2019-05-13.build3740 is up to date.
/home/icar/Programs/pgap-master/mg37_results.1
[Errno 13] Permission denied: '/home/icar/Programs/pgap-master/test_genomes/MG37/pgap_input.yaml'

Please help me to troubleshoot the error again. 
Thanks
-Dip

**Comment by slottad** [comment]
Are there old files there, owned by root, created when you ran via sudo? You might want to start with a clean directory.

**Comment by dipsaha** [comment]
Hello slottad,

Yes there were some old files generated via the earlier sudo use. Now I have removed them using 'sudo rm -rf file/name' (cause they weren't easily removable).

Then once again, I ran the pgap.py but no respite. It showed error once again:

icar@icar-crijaf:~/Programs/pgap-master$ python3 pgap.py -n -o /home/icar/Programs/pgap-master/PJRB1 /home/icar/Programs/pgap-master/user_genome/genome.simple2.yaml -d
PGAP version 2019-05-13.build3740 is up to date.
/home/icar/Programs/pgap-master/PJRB1
docker exited with rc = 1

The cwltool log is:
Original command: pgap.py -n -o /home/icar/Programs/pgap-master/PJRB1 /home/icar/Programs/pgap-master/user_genome/genome.simple2.yaml -d

Docker command: /usr/local/bin/docker run -i --user 1000:1000 --volume /home/icar/Programs/pgap-master/input-2019-05-13.build3740:/pgap/input:ro,z --volume /home/icar/Programs/pgap-master/user_genome:/pgap/user_input:z --volume /home/icar/Programs/pgap-master/user_genome/pgap_input.yaml:/pgap/user_input/pgap_input.yaml:ro,z --volume /home/icar/Programs/pgap-master/PJRB1:/pgap/output:rw,z --volume /home/icar/Programs/pgap-master/PJRB1/debug/log:/log/srv:z ncbi/pgap:2019-05-13.build3740 cwltool --timestamps --outdir /pgap/output --tmpdir-prefix /pgap/output/debug/tmpdir/ --leave-tmpdir --tmp-outdir-prefix /pgap/output/debug/tmp-outdir/ --copy-outputs pgap.cwl /pgap/user_input/pgap_input.yaml

[2019-06-25 06:19:29] /usr/bin/cwltool 1.0.20190228155703
[2019-06-25 06:19:29] Resolved 'pgap.cwl' to 'file:///pgap/pgap.cwl'
[2019-06-25 06:19:50] Failed to create directory: [Errno 30] Read-only file system: '/pgap/output/debug/tmpdir'

NOW, I am clueless! What's happening is not very clear to me as I am not a very good expert in using Docker and pgap. Are there more files to be cleaned? Is there any command or input files (.yaml), I am wrongly using? I do not know how to address these. Please, help me in detail stepwise manner to execute the program.

Regards
-Dip

**Comment by slottad** [comment]
Were you able to get at least one run with the provided test data working?

**Comment by Asylulan** [comment]
I have the same problem. Can anybody help me, please.
I downloaded Supplemental reference data for PGAP direct from amazon.S3 independetly (input-2019-08-22.build3958), then installed Docker and downloaded source code from https://github.com/ncbi/pgap/releases.
After installing Docker i have been abort Docker's downloading "input-2019-08-22.build3958" (because i have one). Then while i run in console:
$ sudo ./pgap.py -r -o mg37_results test_genomes/MG37/input.yaml
I get:
>docker exited with rc = 1
Then, I writed: $sudo usermod -a -G docker $USER, and checked it by $groups.
By still I get: $[Errno 13] Permission denied:

Please, explan to me how to correct install and run pgap.py pipeline.
Thanks

**Comment by rkruegs123** [comment]
I am running into this same issue - did anyone ever fix it?
