### ISSUE TITLE
Completed permanentFail when using test_genomes/C_jejuni/input.yaml 

### ISSUE THREAD

**Issue by zhuofeih** [ncbi/pgap#200]
**Describe the bug**
Firstly thank you so much for offering PGAP!
I downloaded the latest 2022-04-14.build6021 following https://github.com/ncbi/pgap/wiki/Quick-Start .
I ran it on a Linux HPC cluster at our institution. It completed successfully when I ran pgap.py with test_genomes/MG37/input.yaml . However, when I ran it with test_genomes/C_jejuni/input.yaml , it failed with "completed permanentFail" at [step screen_evaluate] and [step vecscreen]. 

My command lines are:
pwd
/scratch/zhuofei/PGAP

export PGAP_INPUT_DIR=/scratch/zhuofei/PGAP

./pgap.py --update
PGAP version 2022-04-14.build6021 is up to date.

./pgap.py --version
PGAP version 2022-04-14.build6021 is up to date.

./pgap.py -r -c 8 -o ./cjejuni_results ./test_genomes-2022-04-14.build6021/C_jejuni/input.yaml

Before the first permanentFail, in cwltool.log I received a debug info:
"DEBUG Could not collect memory usage, job ended before monitoring began"
After I started my command line, I received a warning message:
"WARNING: open files is less than the recommended value of 8000"

Could you please help to take a look at cwltool.log attached in this ticket? Any help would be greatly appreciated!

**Software versions (please complete the following information):**
 - OS: cat /etc/centos-release
   CentOS Linux release 7.9.2009 (Core)
 - ./pgap.py --version
   PGAP version 2022-04-14.build6021 is up to date.
 - SIF image version:
   pgap_2022-04-14.build6021.sif
 - singularity --version
   singularity version 3.8.6-1.el7

**Log Files**
[cwltool.log](https://github.com/ncbi/pgap/files/8542198/cwltool.log)

**Comment by azat-badretdin** [comment]
It's OK. Some of the test genomes are for testing if we detect their failure, so is, for example, C_jejuni. 

If you look at the first permenanetFail in the posted cwltool.log you will see that screen_evaluate failed and the result is in the `calls.tab` that lists regions contaminated by sequences that are foreign to it.

```

**Comment by zhuofeih** [comment]
I see. I will let our user know.
Thank you so much for your prompt response. Have a good day!
