### ISSUE TITLE
PGAP failed, docker exited with rc = 1

### ISSUE THREAD

**Issue by abdziz** [ncbi/pgap#201]
I am running pgap on plasmid sequences. It completed successfully with the --ignore-all-errors flag, and works successfully on the trial genome as well. However I will be submitting the sequences to NCBI so I run without --ignore-all-errors and it fails. Attached is the cwltool.log.

**Comment by thibaudnis** [comment]
`--ignore-all-errors` includes ignoring a verification that the genome is in the size range for the species. If the set of sequences provided is too small and the flag is not set, PGAP fails in the size verification, as you can see in the log you attached:
```
min = 4549000
max = 7572000
genome_size = 1081913
verify-genome-size: fail
```
Please submit the annotated sequences to GenBank as is.

**Comment by abdziz** [comment]
Thank you very much, I will do so.
