### ISSUE TITLE
[BUG] March 30th update broke our ability to run on Windows

### ISSUE THREAD

**Issue by bstew3** [ncbi/pgap#203]
"Windows uses USERPROFILE, instead of HOME. Windows doesn't have HOME and other OSs don't have USERPROFILE, so using either of these drops platform independence." From https://stackoverflow.com/questions/14742064/python-os-environhome-works-on-idle-but-not-in-a-script

**To Reproduce**
Run PGAP on Windows 10. Follow the quick start guide on the PGAP wiki. 

**Expected behavior**
Expected PGAP to successfully update and run.

**Software versions (please complete the following information):**
 - OS: Windows 10
 - pgap.py 2022-04-14.build6021
 - Docker Desktop 4.8.2

**Log Files**
Unable to generate log files because PGAP does not run.

**Additional context**
We believe the problem was created with the below update, line 489.
(https://github.com/ncbi/pgap/commit/17bae57a1f00f5c6db8f3a82d86262f12b8153cf)

**Comment by azat-badretdin** [comment]
Thank you for your report! This indeed sounds like a mistake on our side. Is there a way to meaningfully apply the following workaround from Quick Notes on Windows?

> but this location can be changed by setting environmental variable PGAP_INPUT_DIR.

**Comment by bstew3** [comment]
It seems as though we have managed to make it work after using --no-self-update and explicitly specifying the "self.install_dir." Is this something that we will have to do with every update to enable us to use a Windows 10 OS. Thank you for your help.

**Comment by azat-badretdin** [comment]
You are welcome. We are planning to see what we can do on the software side and opened an internal ticket for this.

**Comment by george-coulouris** [comment]
Hi @bstew3,
pgap.py should now use %USERPROFILE% when appropriate, please give it a try. We'll also investigate how PGAP_INPUT_DIR works on Windows. Thank you for your report!
