### ISSUE TITLE
Difficulty running PGAP with singularity

### ISSUE THREAD

**Issue by stitam** [ncbi/pgap#206]
After consulting the manual I still have difficulty running the pipeline. I would like to run PGAP on a system where I do not have `sudo` access but I can run a singularity container and have full access to a number of directories. I pulled the build6021 singularity image from docker hub and downloaded pgap.py from the link provided in the manual. After putting the two files in the same directory and running `./pgap.py --container-name pgap_2022-04-14.build6021.sif --container-path ./pgap_2022-04-14.build6021.sif --docker /usr/local/bin/singularity --version` PGAP indicates `The latest version of PGAP is 2022-04-14.build6021, you have nothing installed locally` so I am unsure I managed to tell PGAP the image is already downloaded, what am I doing wrong? Also when I run the pipeline on the Mycoplasma genitalium genome provided with the installation it starts downloading the databases: is it possible to tell PGAP where to download the databases? I didn't find such option for `pgap.py`. Many thanks.

**Comment by tbazilegith** [comment]
Hello Azat,
Could you help me figure out what's wrong with this? I converted the docker image into singularity as my system only supports singularity. Also pgap is available on the system as a module. I ran this in slurm script
#SBATCH --cpus-per-task=16
#SBATCH --mem=160gb
module load pgap/20220414
pgap.py --cpu $SLURM_CPUS_ON_NODE -n -o pgap_testDir/test_output pgap_testDir/MG37_input/input.yaml --container-path /apps/staphb-toolkit/containers/pgap_2022-04-14.build6021.sif --docker singularity

My cwltool.log file looks like this 

Original command: /apps/pgap/20220414/pgap/scripts/pgap.py --docker /apps/singularity/latest/singularity --container-path /apps/pgap/20220414/pgap/scripts/pgap_2022-04-14.build6021.sif --no-self-update --report-usage-false --cpu 16 -n -o pgap_testDir/test_output pgap_testDir/MG37_input/input.yaml --container-path /apps/staphb-toolkit/containers/pgap_2022-04-14.build6021.sif --docker singularity
-bash: Docker: command not found
Thanks!

**Comment by azat-badretdin** [comment]
Hello, Tassy, I noticed that output replay lists some duplication of command line arguments with different specs. Could you please put positional parameters in the end of the command line and try again like this?
```
./pgap.py --cpu $SLURM_CPUS_ON_NODE -n -o pgap_testDir/test_output --container-path /apps/staphb-toolkit/containers/pgap_2022-04-14.build6021.sif --docker singularity  pgap_testDir/MG37_input/input.yaml 
```

**Comment by azat-badretdin** [comment]
Tassy, this sounds different from the problem described in this ticket, would you mind opening a new Issue?

Thanks!
