### ISSUE TITLE
[BUG] <PGAP failed, docker exited with rc = 1>

### ISSUE THREAD

**Issue by Kartikj112** [ncbi/pgap#211]
**PGAP is not running when I use my own data**

I successfully ran the M. genitalium test genome but when I try to run my own genome it says "PGAP failed, docker exited with rc = 1".
I have attached the log file and the .yaml files below.

I'm new to this so a little guidance would be helpful.

Thankyou in advance.

**Software versions **
 - OS: [Ubuntu 20.04.4 LTS]
 - Intel® Core™ i7-10700 CPU @ 2.90GHz × 16 
 - 64-bit
 - 31.1 GiB
 - pgap.py --version: 2022-04-14.build6021
 - docker image version: 20.10.17

[input.yaml.txt](https://github.com/ncbi/pgap/files/8900470/input.yaml.txt)
[submol.yaml.txt](https://github.com/ncbi/pgap/files/8900472/submol.yaml.txt)
[cwltool.log](https://github.com/ncbi/pgap/files/8900683/cwltool.log)

**Comment by azat-badretdin** [comment]
Thank you for your report, Kartik!

the log says:

```
line 246: CPgapxYamlCtlApplication::Run() --- Unknown organism Kocuria_sp

```

**Comment by thibaudnis** [comment]
Hi @Kartikj112 in submol.yaml.text: `genus_species: 'Kocuria_sp'`. Please try `genus_species: 'Kocuria sp.'` instead. Thanks! See https://github.com/ncbi/pgap/wiki/Input-Files

**Comment by Kartikj112** [comment]
> Thank you for your report, Kartik!
> 
> the log says:
> 
> ```
> line 246: CPgapxYamlCtlApplication::Run() --- Unknown organism Kocuria_sp
> ```

It worked.
Thankyou again for the help.
