### ISSUE TITLE
Failure due to species name ?

### ISSUE THREAD

**Issue by ap1438** [ncbi/pgap#212]
Hi sir,
I have a run failure due to the species name.
I have a novel genome and i have named it accordingly.
But i cannot proceed with the annotation as it is not accepting the new name, most probably because the name is not present in the NCBI taxonomy database (as per previous queries answered).
And i want to submit this genome in the GenBank.

Please suggest me how should i proceed with the annotation?

Thanks

**Comment by azat-badretdin** [comment]
Thank you for your question, Akash

> most probably because the name is not present in the NCBI taxonomy database (as per previous queries answered).

As far as I know the standard procedure of genbank submission is that the taxonomy needs to be registered first.

**Comment by ap1438** [comment]
Thank you for your valuable time and suggestion.
