### ISSUE TITLE
[BUG] <title> HTTP Error 403: rate limit exceeded

### ISSUE THREAD

**Issue by Gahyeon-K** [ncbi/pgap#213]
I tried to run PGAP, but error message: 'HTTP Error 403: rate limit exceeded' popped up. Is there any way to solve it? 
Thank you.

**Comment by Gahyeon-K** [comment]
There are no log files...:(
Only 'HTTP Error 403: rate limit exceeded' lines appeared, and I can't find any log files sorry.

**Comment by Gahyeon-K** [comment]
- My command line: sudo ./pgap.py -n -o Input.yam
Output ls -latr .:
bedtools2
Anaconda3-2020.11-Linux-x86_64.sh
pyani-0.2.11
miniconda.sh
bedtools-2.29.1.tar.gz
pilon-1.23.jar
SPAdes-3.15.4-Linux.tar.gz
.
.profile
examples.desktop
.bash_logout
.conda
miniconda
.bashrc
quast
gfapy
assembly_graph.gfa
NIBR_79
AGB
agb_output
NIBR_87
Porechop
.test.vimrc.swp
test.vimrc
Flye
index.html
llvmorg-13.0.1
index.html.1
.ncftp
development
miniconda.html
barrnap
.ssh
37_Streptomyces
.cpan
.basespace
Illumina
cmake-3.23.2.tar.gz
racon
cmake-3.23.2
ALE
Unicycler
SPAdes-3.15.4-Linux
.viminfo
.config
.cache
220705_pyani.txt
220705_ANIm_test
.condarc
v0.2.11.tar.gz
BiG-SCAPE-master.zip
Pfam-A.hmm
Pfam-A.hmm.h3p
Pfam-A.hmm.h3m
Pfam-A.hmm.h3f
Pfam-A.hmm.h3i
.wget-hsts
anaconda3
bin
pgap.py
.pgap
.bash_history
.Xauthority

**Comment by azat-badretdin** [comment]
Hmm.. Something is off with your command line: `./pgap.py -n -o Input.yam` 

`-o` parameter requires output directory following it, but it seems that `Input.yam` follows it. Not sure how this would work...

**Comment by azat-badretdin** [comment]
I also do not see `Input.yam` in the listing you posted... Thanks for posting it, BTW!

**Comment by Gahyeon-K** [comment]
When I ran before, this command did well! But, maybe after upgrade pgap it goes into trouble.
I ran this command in the directory where 'Input.yam' is located.
And when I use that command, outputs were saved at home.

**Comment by azat-badretdin** [comment]
> this command did well! 

That's what evil wants us to think when we do wrong :-) 

I suspect that this sort of invocation leads to unpredictable results.

Could you please try to run it as specified in Quick Start notes https://github.com/ncbi/pgap/wiki/Quick-Start

`./pgap.py -n -o some_output_dir your_input.yaml_file`

?

Thanks!
