### ISSUE TITLE
WARNING Final process status is permanentFail

### ISSUE THREAD

**Issue by tbazilegith** [ncbi/pgap#214]
I have pgap installed as a module
module load pgap/20220414
pgap.py -h
usage: pgap.py [-h] [-V] [-v] [--prod] [--taxcheck | --taxcheck-only] [-l | -u] [-r | -n] [--container-name CONTAINER_NAME] [--container-path CONTAINER_PATH] [--ignore-all-errors] [--no-internet] [--auto-correct-tax] [-D path]
               [-o path] [-q] [--no-self-update] [-c CPUS] [-m MEMORY] [-d]
               [input]

After I ran the test  like this
pgap.py --cpus $SLURM_CPUS_ON_NODE \
-n -o pgap_testDir/test_output \
--container-path /apps/staphb-toolkit/containers/pgap_2022-04-14.build6021.sif \
--docker singularity \
pgap_testDir/MG37_input/input.yaml

The cwltool.log shows this
Original command: /apps/pgap/20220414/pgap/scripts/pgap.py --docker /apps/singularity/latest/singularity --container-path /apps/pgap/20220414/pgap/scripts/pgap_2022-04-14.build6021.sif --no-self-update --report-usage-false --cpus 16 -n -o pgap_testDir/test_output --container-path /apps/staphb-toolkit/containers/pgap_2022-04-14.build6021.sif --docker singularity pgap_testDir/MG37_input/input.yaml
[2022-07-19 09:10:57] WARNING Final process status is permanentFail

Could anybody help figure out what's wrong in command?
Thanks!
TJ

**Comment by azat-badretdin** [comment]
Thanks, I see that cwltool.log has way more data thhan you posted, could you please attach the whole file? Thanks!

**Comment by tbazilegith** [comment]
Sorry, I wanted to show what I thought essential.

**Comment by azat-badretdin** [comment]
Understood. The essential part is a bit tricky. Sure PermanentFail line is important. But the essential details are in the "error" messages preceding the first occurance of PermenentFail in the log.

**Comment by tbazilegith** [comment]
working on that

**Comment by tbazilegith** [comment]
Hello Azat,
I attached the cwltool.log file as text file.
[cwltool.txt](https://github.com/ncbi/pgap/files/9143924/cwltool.txt)

**Comment by azat-badretdin** [comment]
```
ncbi::CObjectIStreamJson::UnexpectedMember() --- line 1: "taxon": unexpected member, should be one of: "strain" "genus_species"  ( at JsonValue.organism)
 ```
Something wrong with your input YAML file, could you please attach it? (please do not copy paste it, quite often copy-paste into github comments screws up indentation which is paramount for YAML input). 

BTW, I do not understand why this file `pgap_testDir/MG37_input/input.yaml` is not seen in the output of `ls -alR` I have requested.

Did you edit it out?

**Comment by tbazilegith** [comment]
No I didn't edit it. Here it is . I have also attached the submol file.
[input-yaml.txt](https://github.com/ncbi/pgap/files/9149867/input-yaml.txt)
[submol-yaml.txt](https://github.com/ncbi/pgap/files/9149868/submol-yaml.txt)
Thanks

**Comment by azat-badretdin** [comment]
Thanks, your submol file seems very outdated, could you please review the Quick Start/Input Files section of Wiki?

**Comment by tbazilegith** [comment]
I got the submol updated with the content on the Quick Start/Input Files, and I ran this on the terminal

./pgap.py -n -o mg37_results pgap_testDir/MG37_input/input.yaml

While still running, here is the triggered message
WARN[0000] "/run/user/6210" directory set by $XDG_RUNTIME_DIR does not exist. Either create the directory or unset $XDG_RUNTIME_DIR.: stat /run/user/6210: no such file or directory: Trying to pull image in the event that it is a public image.
WARNING: tmp disk space (GiB) is less than the recommended value of 10
PGAP failed, docker exited with rc = 1
Unable to find error in log file.

The process stopped with this error
 WARNING Final process status is permanentFail

The cwtool.log shows this
--- Start Runtime Report ---
{
    "CPU cores": 64,
    "Docker image": "ncbi/pgap:2022-04-14.build6021",
    "cpu flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl xtopology nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb cat_l3 cdp_l3 invpcid_single hw_pstate sme retpoline_amd ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif umip pku ospke vaes vpclmulqdq overflow_recov succor smca",
    "cpu model": "AMD EPYC 75F3 32-Core Processor",
    "max user processes": 2057511,
    "memory (GiB)": 502.5,
    "memory per CPU core (GiB)": 7.9,
    "open files": 131072,
    "tmp disk space (GiB)": 7.3,
    "virtual memory": "unlimited",
    "work disk space (GiB)": 3868065.8
}
--- End Runtime Report ---
........
WARNING Final process status is permanentFai

updated submol
[submol-yaml.txt](https://github.com/ncbi/pgap/files/9150741/submol-yaml.txt)


Thanks

**Comment by azat-badretdin** [comment]
Thanks!

This

```
WARN[0000] "/run/user/6210" directory set by $XDG_RUNTIME_DIR does not exist. Either create the directory or unset $XDG_RUNTIME_DIR.: stat /run/user/6210: no such file or directory: Trying to pull image in the event that it is a public image.
```
Looks like something on your side, please consult your local system folks to figure this out. 

This

```
WARNING: tmp disk space (GiB) is less than the recommended value of 10
```
Also requires attention of a person who can bump the tmp disk space size for you. The tmp is the dir specified in "TMPDIR" envar or  "/tmp" by default.

New submol input file you attached looks better taxonomy wise. 

Could you please post the cwltool.log file again from your latest run?

Thanks

**Comment by tbazilegith** [comment]
Hello Azat,
Sorry for the tardiness, the file took time to download. Had poor network connection.
I attached the cwtool.log file as text file
[cwltool_log.txt](https://github.com/ncbi/pgap/files/9154613/cwltool_log.txt)

Thanks

**Comment by azat-badretdin** [comment]
Tassy, it looks like the problem is much easier to fix: please ditch fake biosample and bioproject lines from your submol.txt
