### ISSUE TITLE
[BUG] urlopen error

### ISSUE THREAD

**Issue by srsfishbein** [ncbi/pgap#219]
Even though I specify no internet, I'm getting an error about the python package urlopen.
Below is the input code
`+ pgap.py -D singularity -n --no-self-update --ignore-all-errors -o /scratch/gdlab/skye.f/EIACD/220819_pgap/out_CDFMT-SF110_assembly_filtered --no-internet /scratch/gdlab/skye.f/EIACD/220819_pgap/filtered/CDFMT-SF110_assembly_filtered_input.yaml`
and error message: 
`<urlopen error [Errno -3] Temporary failure in name resolution>`

**Comment by azat-badretdin** [comment]
Thank you for  your report! This sounds like something that could be a transient error or some network setup on your side. Is this reproducible?
