### ISSUE TITLE
installation of some or all of components failed.

### ISSUE THREAD

**Issue by Ahmer1122** [ncbi/pgap#220]
Hello I am trying to install PGAP however i am getting this issue. 

The latest version of PGAP is 2022-08-11.build6275, you have nothing installed locally.
installation directory: /home/szweda/.pgap
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/nvme0n1p5 452444768 78240396 351147988  19% /
Skipping already installed tarball: https://s3.amazonaws.com/pgap/input-2022-08-11.build6275.tgz
Downloading (as needed) Docker image ncbi/pgap:2022-08-11.build6275
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=ncbi%2Fpgap&tag=2022-08-11.build6275": dial unix /var/run/docker.sock: connect: permission denied
None
installation of some or all of components failed. Please remove /home/szweda/.pgap/input-2022-08-11.build6275, /home/szweda/.pgap/test_genomes, /home/szweda/.pgap/test_genomes-2022-08-11.build6275 directories and try again.

Using ./pgap.py -h command is working but have no other directories like input and test data.

**Comment by azat-badretdin** [comment]
Thank you, Ahmer, for your report!

It looks like you tried this over existing installation. Have you tried to clean the disk space occupied by the previous attempt to install 2022-08-11 release and install it again?

Actually, I see that you created an issue #221 which implies that you successfully installed PGAPx. Please let me know if that is true, so I resolve this.

**Comment by Ahmer1122** [comment]
Dear Azat, thank you for your response.

Yes, I managed to solve the issue.

Thanks :)

**Comment by azat-badretdin** [comment]
You are welcome! :-)
