### ISSUE TITLE
PGAP failed, docker exited with rc = 1

### ISSUE THREAD

**Issue by Ahmer1122** [ncbi/pgap#221]
Hi All,

I am facing error message (docker exited with rc=1). What baffles me is the test_genomes/MG37/input.yaml executed properly. But the error comes when I am running my data.
This is the error message

PGAP version 2022-08-11.build6275 is up to date.
Output will be placed in: /home/szweda/Downloads/pgap/SZA14_results.2
PGAP failed, docker exited with rc = 1
Printing log starting from failed job:
[cwltool.txt](https://github.com/ncbi/pgap/files/9584301/cwltool.txt)

Attached is the cwl log

**Comment by azat-badretdin** [comment]
Thank you, Ahmer, for your report!

Your log contains this:

```
Error: VerifySeqids: invalid seqid is used, containing non-local NCBI-style seqid: lcl|16length59293_fdepth=1.00x
Error: VerifySeqids: invalid seqid is used, containing non-local NCBI-style seqid: lcl|46length636_depth=2.15x
Error: VerifySeqids: invalid seqid is used, containing non-local NCBI-style seqid: lcl|48length400_depth=1.13x
verify-seqids: fail
```

this means that there is something wrong with your seqids. Try to separate `lcl|16` from the rest of the FASTA header by space, and the other seqids

**Comment by Ahmer1122** [comment]
Dear Azat, many thanks for your guidance.

It actually worked after I replaced the headers :)

Thanks :)

**Comment by azat-badretdin** [comment]
You are welcome, Ahmer! :-)
