### ISSUE TITLE
PGAP failed, docker exited with rc = 1

### ISSUE THREAD

**Issue by JuanAranguiz** [ncbi/pgap#222]
Hello! First of all, thanks for PGAP. I've tried to run my file and no matter how hard I try I can't. If anyone could advise me I would really appreciate it.
[PGAP_failed.zip](https://github.com/ncbi/pgap/files/9595071/PGAP_failed.zip)

**Comment by azat-badretdin** [comment]
Than you for your report, @JuanAranguiz !

The file you sent says: 
```
    Error: CWL(CException::eUnknown) "/export/home/gpipe/TeamCity/Agent2/work/427aceaa834ecbb6/ncbi_cxx/src/internal/gpipe/app/cloud/cwl/pgapx_yaml_ctl.cpp", line 246: CPgapxYamlCtlApplication::Run() --- Unknown organism Arthrobacter sp
```

Notice the missing dot in the end. Please add a dot to the organism line in submol YAML input and try again

**Comment by JuanAranguiz** [comment]
Thank you for your response and kindness. I don't understand where I should write the dot. I attach my submol YAML input file and if you could clarify me I would appreciate it


topology: 'linear'
location: 'chromosome'
organism:
    genus_species: 'Arthrobacter sp.'

**Comment by azat-badretdin** [comment]
Thanks! You already have the dot. Hmmm... We will have a look!

**Comment by azat-badretdin** [comment]
Just to confirm: you are using latest, August, release, correct?

**Comment by JuanAranguiz** [comment]
I downloaded PGAP with this command url -OL https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py
I really don't know what version it is
I'm sorry for the doubts, I really don't know much about the area

**Comment by azat-badretdin** [comment]
If you downloaded that recently, then it is the latest version

**Comment by azat-badretdin** [comment]
I opened an internal ticket (see Label) and we will address this issue, hopefully in the current process of releasing September version of PGAPx. 

Cheers!

**Comment by azat-badretdin** [comment]
@JuanAranguiz I failed to reproduce this failure locally using as an input FASTA one of our Arthrobacter sp  assemblies. 

Could you please send me an example of the FASTA header you used as an input? (the lines that start with `>`)
