### ISSUE TITLE
[BUG] Unclear error messages

### ISSUE THREAD

**Issue by MrTomRod** [ncbi/pgap#224]
I tried to run pgap using Python's `subprocess.run`. I got return code 1, STDOUT=`'HOME'` and no STDERR.

The reason was that on line 493 of pgap.py, `os.environ['HOME']` is called, which raises an error because I didn't define the `HOME` variable. Because of lines 936-940, only `'HOME'` is printed:

```python
    except (Exception, KeyboardInterrupt) as exc:
        if args.debug:
            raise
        retcode = 1
        print(exc)
```

I propose that you change the code to something like this:

```python
    except (Exception, KeyboardInterrupt) as exc:
        if args.debug:
            raise
        retcode = 1
        import traceback
        traceback.print_exc()
```

Then, the whole stack trace is printed and I would have quickly found the problem.

**Comment by azat-badretdin** [comment]
Thank you for your report, Thomas!

Let's address first the missing HOME issue.

We fixed the missing HOME problem for Windows platform by using USERPROFILE for these cases for August release. Looks like more fixes are needed.

What is the HOME equivalent on your platform (output of `platform.system()` call in Python)?

**Comment by azat-badretdin** [comment]
As for your traceback enhancement, looks reasonable to me. I opened an internal new feature ticket for this (See labels)

**Comment by MrTomRod** [comment]
I'm using Centos 7. `HOME` is defined, normally, except when I start a command through Python via `subprocess.run`. I just added this environment variable manually, that fixed the problem.

**Comment by azat-badretdin** [comment]
>  I just added this environment variable manually

Note that this option (PGAP_INPUT_DIR) is documented in Wiki. 

Glad it worked out for you, Thomas!

**Comment by MrTomRod** [comment]
True, but the error would have happened anyway:

```python
class Setup:

    def __init__(self, args):
        ...
        if platform.system() == 'Windows':
            self.install_dir     = os.environ.get('PGAP_INPUT_DIR',os.environ['USERPROFILE']+'/.pgap')
        else:
            self.install_dir     = os.environ.get('PGAP_INPUT_DIR',os.environ['HOME']+'/.pgap')
```

`os.environ['HOME']` is executed even if `PGAP_INPUT_DIR` is in os.environ.

To demonstrate, run this:

```
import os
print(os.environ['HOME'])  # should work
os.environ.get('HOME', os.environ['DOES_NOT_EXIST'])  # will produce error even though HOME exists
```

**Comment by azat-badretdin** [comment]
This will go in the coming release (in the next few days)
