### ISSUE TITLE
Error in annotation of test genome using latest version of PGAP

### ISSUE THREAD

**Issue by GanPENG-git** [ncbi/pgap#232]
When I finished installing PGAP and docker I did a test genome annotation, here is my command line, but something went wrong and I don't know how to fix it, would really like someone to help me
 /home/GP/NCBI/pgap_v2/pgap.py -r -o 1234 input.yaml --no-self-update
[cwltool.log](https://github.com/ncbi/pgap/files/10114769/cwltool.log)

**Comment by azat-badretdin** [comment]
Thank you for your report, user @GanPENG-git ! This is a known issue that I just mitigated by modifying our test case, could you please try to wipe installation and install it again? The other quick fix is to eliminate publications: section in input submol.yaml file under test_genomes/MG37 directory.

**Comment by GanPENG-git** [comment]
Thank you,@azat-badretdin， I have solved it, thanks again for your help
