### ISSUE TITLE
Issue while running on data

### ISSUE THREAD

**Issue by hb660** [ncbi/pgap#236]
Hi,

I think this issue may have already been resolved but I cannot find what is exactly wrong with this run. I already have had several issues I succeeded to fix with previous reported issues but cannot find what's really wrong now ... Can you help me ? 
[cwltool.log](https://github.com/ncbi/pgap/files/10383902/cwltool.log)

The test on MG37 runs fine, but with the same issue of open files < 8000... I run the ulimit -n 8192 command and now ulimit is on "unlimited" but still have this comment showing up

Thanks a lot in advance
Helene

**Comment by azat-badretdin** [comment]
Thank you, Helene, for your report!

The `cwltool.log` says: 
```
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 1, column 1:
    organism:
    ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 8, column 2:
     authors:
     ^
```
It looks like something happened to your input YAML file (submol.yaml).

**Comment by hb660** [comment]
Thank you for your very fast answer !

I think I fixed it ? I copied/pasted a file I primarly made from the example on the Wiki that uses "-" in front of "author'. I removed it and I think the new issue is not from that ? 


Sorry to take up your time again but I think you will point out the issue much faster than me... ( and I am to my 30st try at least so starting to give up  a bit..).
My submol file is very light for now (hope that's not the issue ?) as I just want it to run and I will do it more properly with all of the information once it finally runs.

Thanks a lot,
Helene

[cwltool.log](https://github.com/ncbi/pgap/files/10384432/cwltool.log)

**Comment by azat-badretdin** [comment]
Could you please post here as attachment your submol YAML file (you can rename it to have .txt if github gives you hard time)?

**Comment by hb660** [comment]
There. I kept it to the strict minimum but may have chopped too much ? 
[pgap_submol.txt](https://github.com/ncbi/pgap/files/10384511/pgap_submol.txt)

**Comment by azat-badretdin** [comment]
Thank you for sharing your submol file, Helene.

the "authors: " line should start from the first position in the line, not the second. Please also restore dashes before each "author:"

**Comment by hb660** [comment]
Ok thanks a lot for your help and your reactivity, I take the liberty to close this issue as my case is resolved.

Helene
