### ISSUE TITLE
Strategy for unknown species

### ISSUE THREAD

**Issue by aboffin** [ncbi/pgap#237]
Hi,

Is there a strategy/way to obtain PGAP annotation for unknown species? For example, there are many instances where the taxonomy is only known at family or order level but not genus level. One way that I am trying to work with such genomes is to use a generic species name, say _Pyrococcus furiosus_ in the `submol.yaml` file and use `--taxcheck --auto-correct-tax` options to ask PGAP to correct the genus species as it sees fit. Is this the right way or is there a better/more sensible way?

Thank you for the new release that includes nucleotide gene CDS, I appreciate the update!

**Comment by azat-badretdin** [comment]
Thank you for your question, Senthil! 

> use --taxcheck --auto-correct-tax options to ask PGAP to correct the genus species as it sees fit

seems like a good idea to try
