### ISSUE TITLE
WARNING Final process status is permanentFail

### ISSUE THREAD

**Issue by Ahmer1122** [ncbi/pgap#239]
Hello, I am trying to run PGAP however, it ends with permanent fail. I have attached the CWLtool file.

Best regards,

Ahmer

[errorCWLtool.txt](https://github.com/ncbi/pgap/files/10426577/errorCWLtool.txt)

**Comment by azat-badretdin** [comment]
Thank you for your report, Ahmer!

The report says at the first permanentFail message:

```
[2023-01-16 14:10:45] DEBUG Could not collect memory usage, job ended before monitoring began.
[2023-01-16 14:10:45] WARNING [job fastaval] exited with status: 255
[2023-01-16 14:10:45] WARNING [job fastaval] completed permanentFail

```

The file `fastaval.xml` in the `output/` directory should provide you with information about what failed. This stage tests genome nucleotide sequence for basic errors. Please let me know if you have trouble interpreting this file contents.

**Comment by Ahmer1122** [comment]
Dear Sir, many thanks for your response.

I have looked in the output folder as well as the each and every directory. However, I could not locate this file. Most probably the file does not exist. Secondly, I have run PGAP previously without any problem. This problem occurred yesterday after i updated PGAP.

Looking forward,

Best regards,

Ahmer

**Comment by azat-badretdin** [comment]
> However, I could not locate this file

Could you please post the listing `ls -l output/`?

**Comment by azat-badretdin** [comment]
Hang on, I see already that you indeed do not have it. Could you please rerun your genome with `./pgap.py -d` option? This will preserve intermediate files, include `fastaval.xml`.

**Comment by Ahmer1122** [comment]
![Screenshot from 2023-01-17 13-05-01](https://user-images.githubusercontent.com/98017313/212894571-0d45fae2-7e0d-4937-871e-a1dac61f2626.png)

Here is the screenshot.

**Comment by azat-badretdin** [comment]
Thanks for the screenshot, Ahmer, now please rerun your genome with `./pgap.py -d` option. Thanks!

**Comment by Ahmer1122** [comment]
![Screenshot from 2023-01-17 13-08-08](https://user-images.githubusercontent.com/98017313/212895162-b90ded86-9b6f-4a9d-8458-6ad3aa8aeac9.png)

After running the command. I did not recover any files.

**Comment by azat-badretdin** [comment]
My apologies for not posting a complete line, I mean addition of `-d` parameter of course. Here is the complete line: `./pgap.py -r -d -o strain10_results /home/szweda/.pgap/strain10/input.yaml`

**Comment by Ahmer1122** [comment]
Dear Sir, Here is the fastaval file.

[fastaval.txt](https://github.com/ncbi/pgap/files/10434871/fastaval.txt)

**Comment by azat-badretdin** [comment]
Thanks! That was fast!

Here is the relevant part of this file

```

  <message tool="fastaval" severity="ERROR" seq_id="NODE34" code="SEQ_SHORT_LENGTH" fasta_seq_id="lcl|NODE34">Sequence is shorter than 200 nucleotides</message>
  <message tool="fastaval" severity="ERROR" seq_id="NODE35" code="SEQ_SHORT_LENGTH" fasta_seq_id="lcl|NODE35">Sequence is shorter than 200 nucleotides</message>
  <message tool="fastaval" severity="ERROR" seq_id="NODE36" code="SEQ_SHORT_LENGTH" fasta_seq_id="lcl|NODE36">Sequence is shorter than 200 nucleotides</message>
  <message tool="fastaval" severity="ERROR" seq_id="NODE37" code="SEQ_SHORT_LENGTH" fasta_seq_id="lcl|NODE37">Sequence is shorter than 200 nucleotides</message>
  <message tool="fastaval" severity="ERROR" seq_id="NODE38" code="SEQ_SHORT_LENGTH" fasta_seq_id="lcl|NODE38">Sequence is shorter than 200 nucleotides</message>
  <message tool="fastaval" severity="ERROR" seq_id="NODE39" code="SEQ_SHORT_LENGTH" fasta_seq_id="lcl|NODE39">Sequence is shorter than 200 nucleotides</message>
  <message tool="fastaval" severity="ERROR" seq_id="NODE40" code="SEQ_SHORT_LENGTH" fasta_seq_id="lcl|NODE40">Sequence is shorter than 200 nucleotides</message>
  <message tool="fastaval" severity="ERROR" seq_id="NODE41" code="SEQ_SHORT_LENGTH" fasta_seq_id="lcl|NODE41">Sequence is shorter than 200 nucleotides</message>

```

as you can see, some of your input sequences (contigs) are too short. You can either edit your genome or run pgap.py with addition of `--ignore-all-errors` flag.
