### ISSUE TITLE
Any parameters or ways to speed up annotation process?

### ISSUE THREAD

**Issue by Buuntu** [ncbi/pgap#24]
Are there any multi-threading options or other parameters to make the process faster?  I couldn't find anything in the README for this.

**Comment by slottad** [comment]
Those subprograms in the pipeline which are multithreaded already try to use all available processors. Any flags we might add would just be to limit the resources (slowing it down more).

Unfortunately, the pipeline is just slow.

**Comment by Buuntu** [comment]
Got it!
