### ISSUE TITLE
determine the number of cores from the scheduler and not from the node

### ISSUE THREAD

**Issue by vdejager** [ncbi/pgap#240]
**Is your feature request related to a problem? Please describe.**
When submitting a PGAP singularity job using SLURM to a node slice, PGAP grabs all cores, which leads to problems for the other jobs running on that node

(our nodes have 128 cores /256 GB and a slice is 32 cores / 64GB, more than enough for our average PGAP job)

**Describe the solution you'd like**
determine the number of cores from the scheduler info, see additional context

**Describe alternatives you've considered**
provide the --cpus option similar to the node job settings. The PGAP logs still show 128 cores.

**Additional context**
https://stackoverflow.com/questions/56267313/determine-number-of-processors-assigned-to-job

```
import os
#for SGE:
nslots = int(os.environ['NSLOTS']))

# for SLURM:
nslots = int(os.environ['SLURM_CPUS_PER_TASK']))

```

**Comment by azat-badretdin** [comment]
Thank you for your user request, Vic! I have opened an internal ticket to fulfill this request.

**Comment by vdejager** [comment]
Thanks,
I will try to test it this week.

Best Victor

**Comment by vdejager** [comment]
Thanks, works perfectly

Op di 15 aug. 2023 om 16:44 schreef george-coulouris <
***@***.***>
