### ISSUE TITLE
[FEATURE REQUEST] Provide genome assembly/FASTA file name in ani-tax-report.txt

### ISSUE THREAD

**Issue by aboffin** [ncbi/pgap#241]
**Is your feature request related to a problem? Please describe.**
The generated ANI report has a generic id for the assembly/FASTA file:
```
ANI report for assembly: my_gc_assm_name
Submitted organism: Pyrococcus furiosus (taxid = 2261, rank = species, lineage = Archaea; Euryarchaeota; Thermococci; Thermococcales; Thermococcaceae; Pyrococcus)
Predicted organism: (none)
Submitted organism has type: Yes
Status: INCONCLUSIVE
Confidence: LOW
```
**Describe the solution you'd like**
It will be useful for debugging, if instead of `my_gc_assm_name`, the name of the input genome FASTA file is provided in the `ani-tax-report.txt` file.

**Describe alternatives you've considered**
Redirecting the console output to a file, then identifying the annotations that failed due to ANI/taxa check, opening the ANI report file indicated there to see why the taxonomy cannot be assigned confidently.

**Additional context**
None.

**Comment by thibaudnis** [comment]
Hi @aboffin , sorry for the delay in responding; this ticket fell through the cracks. Your request is something we should have done already. We will try to add this to our next release. Thanks!
