### ISSUE TITLE
problem with pipeline installation

### ISSUE THREAD

**Issue by Khabibullin543** [ncbi/pgap#244]
Hello! I have some issues with pipeline installation. I have installed Podman instead of Docker.

(base) khabibullinnr@microbgenome:~$ ./pgap.py --update
The latest version of PGAP is 2022-12-13.build6494, you have nothing installed locally.
installation directory: /home/khabibullinnr/.pgap
Файловая система  1K-блоков Использовано  Доступно Использовано% Cмонтировано в
/dev/sda2        1051982548     62619080 935895992            7% /
Skipping already installed tarball: https://s3.amazonaws.com/pgap/input-2022-12-13.build6494.tgz
Downloading (as needed) Docker image docker.io/ncbi/pgap:2022-12-13.build6494
ERRO[0000] cannot find UID/GID for user khabibullinnr: no subuid ranges found for user "khabibullinnr" in /etc/subuid - check rootless mode in man pages.
WARN[0000] Using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding sub*ids if not using a network user
Trying to pull docker.io/ncbi/pgap:2022-12-13.build6494...
Getting image source signatures
Copying blob ed62ad76a6f5 [=========>----------------------------] 77.8MiB / 283.9MiB
Copying blob 4a8d2d92de30 done
Copying blob 2d473b07cdd5 done
Copying blob 206618282c76 [=======================>--------------] 91.6MiB / 144.4MiB
Copying blob ed62ad76a6f5 done
Copying blob 4a8d2d92de30 done
Copying blob 2d473b07cdd5 done
Copying blob 206618282c76 done
Copying blob dad113e15abf done
Copying blob 15d7a8ee6eee done
Copying blob 4123d9bb3322 done
Copying blob 41dcd5d63cd0 done
Copying blob b4b7fc807910 done
Copying blob 1ba828eb9b47 done
Copying blob 91cbdf082260 done
Copying blob 09ed79857c84 done
Copying blob 38d8de8ad550 done
Copying blob 2f884d5a63ab done
Copying blob a6918c666ade done
Copying blob 34a6a3d64c7c done
Copying blob 13cf09811889 done
Copying blob 13c546a1f78c done
Copying blob 0cf36674d0ba done
Copying blob 401bec1e8127 done
Copying blob f2ccc6a4120b done
Copying blob 7cf7605d94ea done
Copying blob 60bd65ca9551 done
Copying blob 274b26140fae done
Copying blob 3b5bdd654d81 done
Copying blob 6bcb5b39e206 done
Copying blob cfedd6dc85a8 done
Copying blob c00df5355b0e done
Copying blob ea0e41d49915 done
Copying blob d29ae7ed6abe done
Copying blob ca93b6008cdb done
Copying blob e88c24438217 done
Copying blob 39186871fd84 done
Copying blob 1579818e33df done
Copying blob 7930919e23da done
Copying blob 475b7570bea5 done
Copying blob e2be04db6164 done
Copying blob a135e58665ef done
Copying blob aaa64ba8278f done
Copying blob f48186ca5d8a done
Copying blob 699a6a2c6779 done
Copying blob 5511716f0cdc done
Copying blob 4be5f599def2 done
Copying blob e8da709461e9 done
Copying blob 0fa9507c2a03 done
Copying blob a92e594f7481 done
Copying blob 676a9faf00f8 done
Copying blob e3bd80251ad3 done
Error: writing blob: adding layer with blob "sha256:2d473b07cdd5f0912cd6f1a703352c82b512407db6b05b43f2553732b55df3bc": ApplyLayer stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:54 for /run/lock/lockdev): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /run/lock/lockdev: invalid argument exit status 1
None
Traceback (most recent call last):
  File "/home/khabibullinnr/./pgap.py", line 917, in main
    params = Setup(args)
  File "/home/khabibullinnr/./pgap.py", line 547, in __init__
    self.update()
  File "/home/khabibullinnr/./pgap.py", line 713, in update
    raise Exception(f'installation of some or all of components failed. Please remove {self.data_path}, {self.install_dir}/test_genomes, {self.test_genomes_path} directories and try again.')
Exception: installation of some or all of components failed. Please remove /home/khabibullinnr/.pgap/input-2022-12-13.build6494, /home/khabibullinnr/.pgap/test_genomes, /home/khabibullinnr/.pgap/test_genomes-2022-12-13.build6494 directories and try again.

**Comment by azat-badretdin** [comment]
Thank you for your report! 

Based on the messages you got - the fact that they referring to what looks like details of your local podman setup, e.g:
> potentially insufficient UIDs or GIDs available in user namespace 
this looks like an issue related to your local configuration of `podman`. Have you tried contacting your local system administrator on this subject?

It could be also some `podman` bug that reveals itself in your specific environment
