### ISSUE TITLE
Running pgap from dockerHub

### ISSUE THREAD

**Issue by tbazilegith** [ncbi/pgap#246]
I tried run pgap from the docker container like this
apptainer exe --cleanenv docker://ncbi/pgap:2022-12-13.build6494 -n --no-internet --ignore-all-errors -o ggap_sinDock ../../pgap_filegrouping/asb_met_dir/brucey_v2/input_brucey_v2.yaml

But I ran into this error
"pgap.py": executable file not found in $PATH

Questions:
- How to I provide the executable file when I run Pgap from the container?
- May I run Pgap this way at all?
Thanks!

**Comment by azat-badretdin** [comment]
> May I run Pgap this way at all?

I do not think we support this way.

**Comment by tbazilegith** [comment]
This container is available on dockerHub
docker://ncbi/pgap:2022-12-13.build6494
I wanted run it with singularity (apptainer)
Basically,  this command works fine
 ${PGAP_INPUT_DIR}/pgap.py -n --no-internet --ignore-all-errors --container-path ${PGAP_INPUT_DIR}pgap_2022-04-14.build6021.sif -o ggap_mod_out ../pgap_filegrouping/asb_met_dir/brucey_v2/input_brucey_v2.yaml --docker singularity

-But was trying to run pgap directly from dockerHub to skip a local installation
Is that something pgap support?

**Comment by azat-badretdin** [comment]
> Is that something pgap support?

I do not think so.

**Comment by tbazilegith** [comment]
Thanks!
________________________________
