### ISSUE TITLE
Error in ./pgap.py --update

### ISSUE THREAD

**Issue by nbutyrate** [ncbi/pgap#248]
i am trying to install pgap in my directory in HPC (slurum based)

here is the error I got

Writing manifest to image destination
Storing signatures
FATAL:   While making image from oci registry: error fetching image to cache: while building SIF from layers: conveyor failed to get: Error writing blob: rename /home/sangwan/beegfs/tmp/bundle-temp-374066563/oci-put-blob847668213 /home/sangwan/beegfs/tmp/bundle-temp-374066563/blobs/sha256/4123d9bb3322650f55f2a2aa012b62af92fae241726d392a0d17373c919eb6a6: device or resource busy
None
Traceback (most recent call last):
  File "/mnt/beegfs/sangwan/pgap/./pgap.py", line 917, in main
    params = Setup(args)
  File "/mnt/beegfs/sangwan/pgap/./pgap.py", line 547, in __init__
    self.update()
  File "/mnt/beegfs/sangwan/pgap/./pgap.py", line 713, in update
    raise Exception(f'installation of some or all of components failed. Please remove {self.data_path}, {self.install_dir}/test_genomes, {self.test_genomes_path} directories and try again.')
Exception: installation of some or all of components failed. Please remove /home/sangwan/beegfs/pgap_final/input-2022-12-13.build6494, /home/sangwan/beegfs/pgap_final/test_genomes, /home/sangwan/beegfs/pgap_final/test_genomes-2022-12-13.build6494 directories and try again.

**Comment by azat-badretdin** [comment]
Thank you for your report!

Seems like you are using `singularity` and the error seems to be related to some specifics of your system interaction with `singularity` 

Have you trying rerunning installation process? Are you able to reproduce the result? 

Do you know if there are particular peculiarities of "slurum" HPC clusters?
