### ISSUE TITLE
PGAP error with my own data

### ISSUE THREAD

**Issue by junkim83** [ncbi/pgap#249]
Hello, 

I had a problem using PGAP to analyze my own data.
test genome worked, but not my data. 
I've attached the yaml files (changed file name extension to txt for uploading here) I used and log file I got.

Anyone help?
Thanks,

[cwltool.log](https://github.com/ncbi/pgap/files/11008170/cwltool.log)
[input.txt](https://github.com/ncbi/pgap/files/11008171/input.txt)
[submol.txt](https://github.com/ncbi/pgap/files/11008172/submol.txt)

**Comment by azat-badretdin** [comment]
Thank you for your report!

The error preceding first `permanentFail` in `cwltool.log` file is

```
terminate called after throwing an instance of 'ncbi::CException'
  what():  NCBI C++ Exception:
    Error: CWL(CException::eUnknown) "/export/home/gpipe/TeamCity/Agent2/work/427aceaa834ecbb6/ncbi_cxx/src/internal/gpipe/app/cloud/cwl/pgapx_yaml_ctl.cpp", line 246: CPgapxYamlCtlApplication::Run() --- Unknown organism Lactobacillus Plantarum
```

Looks like you have an organism unregistered in Taxonomy. But `gettax` (an NCBI command) for your input informs us that the official name is `Lactiplantibacillus plantarum`

Could you please replace the name with this one and try again?

Thanks

**Comment by junkim83** [comment]
It works!

Thanks so much!

**Comment by azat-badretdin** [comment]
You are welcome!
