### ISSUE TITLE
Missing "/gene=" names in genbank annotations vs. Prokka

### ISSUE THREAD

**Issue by Buuntu** [ncbi/pgap#25]
I'll start off by saying that this may not necessarily be an issue, just something I've noticed.  Compared to [Prokka](https://github.com/tseemann/prokka) annotations of genomes, PGAP seems to not assign a lot of `/gene=` names in the genbank file it produces.  The total number of features is pretty similar, it's the short gene names that are missing (ie `/gene="rpoB"`).  These are often not well studied/annotated genomes in the literature.

Is this something you guys have noticed on your end?  In most cases, the features that have `/gene=some_gene` in Prokka and not in PGAP still correspond pretty well in the `/product=` line, which makes me think that PGAP is a lot more conservative about providing a good `/gene` name for the CDS feature than Prokka.  If this is the case, are there any parameters I can change to make it less conservative so that it aligns a little closer to Prokka and is more lenient on assigning /gene names?

I'm putting in the genus/species in to the YAML file and `topology: circular` (not sure if this matters), but that's about it for settings.

**Comment by tseemann** [comment]
@Buuntu just to clarify, the term "calling genes" often refers to determining the coordinates of the CDS on the contig. Here you mean "providing a good `/gene` name for the CDS feature".

**Comment by Buuntu** [comment]
@tseemann, _rpoB_ is just an example in this case, sorry if I wasn't clear.  There are hundreds of genes that are not getting a `/gene` name assigned but are in Prokka.  I can't get too specific about species unfortunately.

**Comment by tseemann** [comment]
The fact you don't want to reveal the species suggests it is not a commonly studied one. If that is the case, then it's probably that PGAP has no annotation examples of those proteins in your species, and can't confidently assign gene names because it has no evidence of their use in that species or genus OR the protein identity is too low to assign it?  Try using `organism: Escherichia coli` and annotate with PGAP.

**Comment by Buuntu** [comment]
@tseemann I thought the genus species name was purely for submission metadata purposes.  If the pipeline is using these to get protein information then you very well may be right and I will try setting it to a more well studied organism like E. coli.  I also set strain to something that probably does not exist thinking that it was also just genbank metadata so I'll change that as well just in case.

**Comment by thibaudnis** [comment]
@Buuntu: the genus declared in the YAML file is used to select a set of higher weight reference proteins that are used for structural annotation only. The gene symbols come from protein-family HMMs, BLAST-based annotation rules, and another semi-curated set of proteins used for functional annotation. We have been working hard on supplementing the evidence used for functional annotation with gene symbols and publications (and EC numbers when relevant), but this is work in progress. If you'd like to help us fill some gaps, please send us some information on the organism your are working on at: 
https://support.nlm.nih.gov/support/create-case/

**Comment by Buuntu** [comment]
@thibaudnis Thanks, good to know you guys are looking into it!  I've noticed there are also several hundred gene symbols that are actually there, just under `/product`, not `/gene`.  I feel like those would be good candidates to add to `/gene` first right?

**Comment by thibaudnis** [comment]
Without seeing the details of the annotation it is hard to address the specifics, but I could see how a significant number of symbols may be missing from the /gene field but part of the product names in the /product field. The gene symbols (in the /gene field) are derived from the naming evidence that are used for the functional annotation. We use a hierarchical system naming evidence to assign names, EC numbers and gene symbols to predicted proteins. It includes HMM models, BlastRules (BLAST-based annotation rules), conserved domain architectures and BLAST hits to protein cluster representatives. Currently, HMMs, BlastRules and protein clusters can carry a gene symbol attribute that is then propagated to the /gene field of annotated features. We are trying our best to add missing symbols to evidence that are specific enough that they represent a single gene, but this work is not complete. In addition, currently, the conserved domain architectures don’t have associated gene symbol attributes, so the best option for proteins named by conserved domain architectures is to have the capitalized symbol as part of the product name.

**Comment by tseemann** [comment]
Many years ago I parsed `/product` lines from Refseq for patterns `\s[A-Z][a-z][a-z][A-Z]$` to extract these gene symbols!

**Comment by Buuntu** [comment]
@tseemann This does work for a fair amount of genes!  Unfortunately even when I parse for these gene symbols it still comes out to significantly less than Prokka.  Maybe we are just accustomed to Prokka's overconfidence and this isn't necessarily a bad thing, just feels like a step backwards to have less gene symbols ha.

**Comment by tseemann** [comment]
@Buuntu I agree. PGAP and Prokka have different use-cases. NCBI/RefSeq needs to be consistent and conservative. Prokka can afford to be more wild, as we want as many hints as possible to help inform the research. I think the BlastRules and hierarchy and HMM cutoffs in PGAP is excellent, but it could benefit from a "loose" mode.
