### ISSUE TITLE
TaxCheck and last release

### ISSUE THREAD

**Issue by tbazilegith** [ncbi/pgap#250]
Hi Azat,
Does the last release (2022-12-13) of pgap support the flag --taxcheck-only ?

I ran this command (in python)
for sample_id in pgdirlist:
    subprocess.run('${PGAP_INPUT_DIR}pgap.py -n --no-internet --ignore-all-errors --container-path ${PGAP_INPUT_DIR}pgap_20-22-12-13.build6494.sif --taxcheck-only -o ' + sample_id+'_taxCheck '+ pg_dir +'/'+ sample_id+'/input_'+ sample_id + '.yaml --docker singularity', shell = True, check = True)

I encountered this error
Exception: installation of some or all of components failed. Please remove /pgap//input-2022-12-13.build6494, pgap//test_genomes, /pgap//test_genomes-2022-12-13.build6494 directories and try again.

- This raised another question, (about the installation of pgap):
Should we create the path variable  PGAP_INPUT_DIR before downloading the file (wget https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py) of after?

- Imagined that why the installation of some components has failed...

Thanks,
TJ

**Comment by tbazilegith** [comment]
I noticed that issue was addressed through issue #183
Thanks!

**Comment by azat-badretdin** [comment]
Thank you for your report, Tassy! Many apologies for not replying earlier. 

Please let us know if this fixes your problem now
