### ISSUE TITLE
[FEATURE REQUEST] Additional check: if sequence is circular, it must also be either chromosome, plasmid, or extrachromosomal

### ISSUE THREAD

**Issue by MrTomRod** [ncbi/pgap#251]
**Is your feature request related to a problem? Please describe.**
I wanted to submit some genomes I annotated using PGAP on GenBank. I got this error:

```
ERROR: valid [SEQ_INST.CircBactGenomeProblem] Circular Bacteria or Archaea should be chromosome, or plasmid, or extrachromosomal BIOSEQ: lcl|STRAIN_scf1: raw, dna len= 2345678
```

**Describe the solution you'd like**

PGAP should have aborted with the same error message.

**Describe alternatives you've considered**

I have simply added the following line to the appropriate place in the .sqn/ASN.1 file:

```
...
      seq-set {
        set {
          class nuc-prot,
          descr {
            source {
              genome chromosome, <<< this is the line I added
...
```

Thanks for your nice pipeline!

**Comment by azat-badretdin** [comment]
Thank you for your report, Thomas! Glad to see you back!

> I have simply added the following line to the appropriate place in the .sqn/ASN.1 file

Current input to PGAPX is a FASTA file. It would be nice to reproduce this from FASTA input.

**Comment by MrTomRod** [comment]
You remember me! :smiley: Happy to work with you again, too, Azat.

Not sure what PGAPX is. The FASTA for PGAP looked like this, it had only one, circular contig:

```
>STRAIN_scf1 [topology=circular][completeness=complete]
[...DNA...]
```

It the genome was annotated using PGAP `2020-02-06.build4373`.

Actually, you can download the data here: [assembly](https://opengenomebrowser.bioinformatics.unibe.ch/files_html/organisms/FAM23877/genomes/FAM23877-p1-1.1/1_assembly/FAM23877-p1-1.fna), [gbk](https://opengenomebrowser.bioinformatics.unibe.ch/files_html/organisms/FAM23877/genomes/FAM23877-p1-1.1/2_cds/FAM23877-p1-1.1.gbk), [sqn](https://opengenomebrowser.bioinformatics.unibe.ch/files_html/organisms/FAM23877/genomes/FAM23877-p1-1.1/2_cds/pgap/FAM23877-p1-1.1.sqn.tar.xz). (For submission, I had to remove all `-p1-1.1` and `-p1-1` from the file.)

**Comment by azat-badretdin** [comment]
> Not sure what PGAPX 

PGAPX is a flavor of PGAP that is the product of this github repo. 

> Actually, you can download the data here: [assembly](https://opengenomebrowser.bioinformatics.unibe.ch/files_html/organisms/FAM23877/genomes/FAM23877-p1-1.1/1_assembly/FAM23877-p1-1.fna), [gbk](https://opengenomebrowser.bioinformatics.unibe.ch/files_html/organisms/FAM23877/genomes/FAM23877-p1-1.1/2_cds/FAM23877-p1-1.1.gbk), [sqn](https://opengenomebrowser.bioinformatics.unibe.ch/files_html/organisms/FAM23877/genomes/FAM23877-p1-1.1/2_cds/pgap/FAM23877-p1-1.1.sqn.tar.xz)

Thanks for the data, so I presume this does not fail when you run `./pgap.py` on "assembly" file, but the essentially same genome fails the genome submission when you post ASN.1 file - the output of running `./pgap.py`?

**Comment by MrTomRod** [comment]
> I presume this does not fail when you run `./pgap.py` on "assembly" file, but the essentially same genome fails the genome submission when you post ASN.1 file - the output of running `./pgap.py`?

Exactly.

**Comment by azat-badretdin** [comment]
Thanks, Thomas. I opened an internal ticket for this, we will address this issue.

**Comment by azat-badretdin** [comment]
Thomas, we actually need the input FASTA file as well.

**Comment by MrTomRod** [comment]
I already posted it:

> Actually, you can download the data here: [assembly](https://opengenomebrowser.bioinformatics.unibe.ch/files_html/organisms/FAM23877/genomes/FAM23877-p1-1.1/1_assembly/FAM23877-p1-1.fna), [gbk](https://opengenomebrowser.bioinformatics.unibe.ch/files_html/organisms/FAM23877/genomes/FAM23877-p1-1.1/2_cds/FAM23877-p1-1.1.gbk), [sqn](https://opengenomebrowser.bioinformatics.unibe.ch/files_html/organisms/FAM23877/genomes/FAM23877-p1-1.1/2_cds/pgap/FAM23877-p1-1.1.sqn.tar.xz). (For submission, I had to remove all `-p1-1.1` and `-p1-1` from the file.)

Am I missing something?

**Comment by azat-badretdin** [comment]
My apologies, Thomas, internally we use the term "assembly" for a separate object that is a collection of sequence _references_ and associated metadata, so I skipped over your link.

**Comment by azat-badretdin** [comment]
I just noticed that you are using a three year old release version: `2020-02-06.build4373`.

Have you tried using a newer version to see if this is reproducible?

**Comment by MrTomRod** [comment]
No worries.

Here's the [submol.yaml](https://opengenomebrowser.bioinformatics.unibe.ch/files_html/organisms/FAM23877/genomes/FAM23877-p1-1.1/2_cds/pgap/submol.yaml), and here [cwltool.log](https://opengenomebrowser.bioinformatics.unibe.ch/files_html/organisms/FAM23877/genomes/FAM23877-p1-1.1/2_cds/pgap//cwltool.log.tar.xz).

How should I reproduce it? Annotate it with the new pipeline and re-submit it? Or just check if the `genome chromosome` is present in `ASN.1`? Sorry, I don't have the time to install the old pipeline or make a fake submission of an already-submitted genome...

**Comment by azat-badretdin** [comment]
> Annotate it with the new pipeline and check if the genome chromosome is present in ASN.1?

Feel free to post the ASN.1 here and we will run our standard validation tools on it. 

> I don't have the time to install the old pipeline

I am not sure I understand. You posted that you were using "old pipeline" of 2020, no?

**Comment by azat-badretdin** [comment]
I examined your FASTA file and YAML file - with this input, it should be treated as `chromosome`. 

Suggesting to use most recent version is our own practice since we do not support older versions.
