### ISSUE TITLE
[BUG] dnaA truncated by PGAP gene calling

### ISSUE THREAD

**Issue by tuspjo** [ncbi/pgap#252]
**Describe the bug**
Depositing some bacterial genomes, I noticed that 9 of them come back with a /pseudo tag on the dnaA gene after PGAP annotation. They all have this field
                      /note="incomplete; partial on complete genome; missing
                     N-terminus; Derived by automated computational analysis
                     using gene prediction method: Protein Homology."
However these genes were not truncated in a prodigal annotation of the genes, and the closest database reference determined by autoMLST also has the full dnaA sequence (see AA alignment below). 
![image](https://user-images.githubusercontent.com/54983329/229753963-06df8748-3384-4f69-97d6-7f461018d7ef.png)

For most of the strains with the /pseudo tag, Streptomyces niveus strains have the highest %ANI from autoMLST (Streptomyces_niveus_GCF_002009175, Streptomyces_niveus_NCIMB_11891_GCF_000497425, )

The submitted genomes are not yet publicly available but I can supply you with the genbank files if necessary.

Since this is annotation performed at NCBI, I don't have the log files and software versions requested in the bug report form. 
The issue in 9 genomes is not consistent as many of the Streptomyces genomes I deposited do not have the /pseudo tag. 

Best

Tue Sparholt Jørgensen

**Comment by azat-badretdin** [comment]
Thank you, Tue, for your report. We will investigate this issue in internal ticket.

**Comment by azat-badretdin** [comment]
> I'm thinking this could be relevant information

Agreed. Thanks!

**Comment by azat-badretdin** [comment]
Could you please post some of the input genomes?

**Comment by tuspjo** [comment]
I can 't post them here unfortunately, as they are "embargoed" but I can send a safe download link to your email address? Do you want only the ones with /pseudo or also some of the ones with the same gene calling but not /pseudo on dnaA?

**Comment by tuspjo** [comment]
Great, I'll collect and send you a link to the genomes tomorrow wednesday.
Best,
Tue

tir. 4. apr. 2023 kl. 18.42 skrev Azat Badretdin ***@***.***>:

**Comment by azat-badretdin** [comment]
Looking forward to it, Tue!

**Comment by azat-badretdin** [comment]
I got the genomes, Tue, thanks!

**Comment by azat-badretdin** [comment]
Unfortunately, they post output data, not the input data. We need input FASTA files.

**Comment by tuspjo** [comment]
Dear Azat, 
I've sent the input genomes in fasta format, did you receive them? 
Best, 
Tue

**Comment by azat-badretdin** [comment]
Thanks, Tue! Not yet. So far I got only the original package from 4/5. The data goes through a different group, they will notify us when it comes.

**Comment by azat-badretdin** [comment]
Tue, judging by the output you sent us in the first tarball, it looks like you did not use standalone PGAP for these annotation, but  GenBank submission service. Could you please confirm?

**Comment by tuspjo** [comment]
yes, that is correct, the annotation was performed at NCBI, not by the standalone PGAP CLI.

**Comment by azat-badretdin** [comment]
Thank you for confirming, Tue. That explains the confusion.

**Comment by azat-badretdin** [comment]
Since they were submitted via Genbank, we have the input data already. Thanks!

**Comment by tuspjo** [comment]
A quick followup on this, in case anyone stumbles on this bug report: the dnaA genecalling was modified/improved, which resolved all the observed issues by identifying the complete dnaA genes rather than partial genes.

**Comment by azat-badretdin** [comment]
Thank you, Tue!
