### ISSUE TITLE
Host vs image platform issue 

### ISSUE THREAD

**Issue by rssherbo** [ncbi/pgap#253]
I've been attempting to run the pipeline on Mycoplasma after installation to check that everything is working, but instead I get this warning: "WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested". I also get the following errors that I'm guessing are related to that warning: 

Traceback (most recent call last):
  File "/Users/r.sherbo/./pgap.py", line 965, in main
    retcode = p.launch()
              ^^^^^^^^^^
  File "/Users/r.sherbo/./pgap.py", line 477, in launch
    self.record_runtime(f)
  File "/Users/r.sherbo/./pgap.py", line 426, in record_runtime
    settings['cpu model'] = match.group(1)
                            ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

My computer has an Apple M1 chip, and in Docker I've turned on the beta option for using Rosetta for x86/amd64 emulation to try to overcome this issue, but without altering the pgap.py script there seems to be no obvious workaround. Are there any easy alterations to the script that could specify a platform and enable me to run it? 

Thank you! 

**Software versions (please complete the following information):**
 - MacOS Ventura 13.2.1 
 - pgap.py --version: 2022-12-13.build6494
 - Docker (or other container runner) version. [e.g. ``docker --version``]: 4.18.0 (104112)

**Comment by george-coulouris** [comment]
duplicate of https://github.com/ncbi/pgap/issues/166
