### ISSUE TITLE
pgap via conda

### ISSUE THREAD

**Issue by tarunaaggarwal** [ncbi/pgap#254]
Hello,

I'm a new user of PGAP and am looking forward to using it as soon as I can get it to run from inside a script. Out of curiosity, would it be possible to create a conda package for PGAP? I haven't used Docker and/or Singularity so I don't understand how they are different from conda, but the purpose of both seems similar to me. Just wondering is all. 

Thank you!

**Comment by azat-badretdin** [comment]
>  I haven't used Docker and/or Singularity so I don't understand how they are different from conda

Two former are container runners, and `conda` is source package management system.

In other words, two former are about how to run things and the latter is about installing and maintaining things. 

As far as I know, there are no plans to provide PGAP as a `conda` package.

**Comment by tarunaaggarwal** [comment]
Oh, I see! Thank you for the explanation! Appreciate your time. -Taruna
