### ISSUE TITLE
[FEATURE REQUEST] Expected output of test_genomes?

### ISSUE THREAD

**Issue by lxsteiner** [ncbi/pgap#256]
**Is your feature request related to a problem? Please describe.**
I ran PGAP on the test genome (test_genomes-2022-12-13.build6494 MG37), but how do I check if the run behaviour was as expected based on the output files (e.g. whether all features within the genome were found and reported in the individual or annot.gbk output files)?

**Describe the solution you'd like**
Provide corresponding output files.

**Describe alternatives you've considered**
I tried looking for Mycoplasma genitalium MG37 in Genbank/RefSeq but none of the entries correspond to the test genome. Closest I found is https://www.ncbi.nlm.nih.gov/assembly/GCF_000027325.1 but I don't think the test_genome should even match any actual entry, no?

The link on the wiki page https://github.com/ncbi/pgap/wiki/Installation leading to the test_genome archive https://s3.amazonaws.com/pgap-data/test_genomes.tgz provides only more example input files. 

**Additional context**
What should be the expected output of a successful run? Sorry if the information is provided somewhere else and I couldn't find it. Thanks.

**Comment by azat-badretdin** [comment]
Thank you for your request! I opened an internal group discussion to address it.
