### ISSUE TITLE
Error with updating pgap

### ISSUE THREAD

**Issue by stalact** [ncbi/pgap#259]
Hello, 
I installed and used pgap some weeks ago  as recommended in the Quick Start Section . Now I wanted to update the version, because the warning pops up while executing pgap:

The latest version of PGAP is 2023-05-17.build6771, you are using version 2022-12-13.build6494, please update.

I tried to update with the --update option, but it didn't work out. 
Deleting the docker image and pgap files, and installing it again installs the version 2022-12-13.build6494 again. 

Is there a possibility to update the pgap version to 2023-05-17.build6771?

Thanks and best regards! :-)

**Comment by azat-badretdin** [comment]
Thank you, user @stalact  for your report. 

Could you please post what you see on screen?

Thanks!

**Comment by stalact** [comment]
Thanks for your quick response! 

i tried to run the test data: 


$ sudo ./pgap.py -r -o mg37_results -g .pgap/test_genomes/MG37/ASM2732v1.annotation.nucleotide.1.fasta -s 'Mycoplasmoides genitalium'
The latest version of PGAP is 2023-05-17.build6771, you are using version 2022-12-13.build6494, please update.
Output will be placed in: /home/linuxpc/tools/pgap/mg37_results


When I tried to update its downloading the db, but its not used when the program is executed: 

$ sudo ./pgap.py --update
The latest version of PGAP is 2023-05-17.build6771, you are using version 2022-12-13.build6494, please update.
installation directory: /root/.pgap
Dateisystem     1K-Blöcke   Benutzt  Verfügbar Verw% Eingehängt auf
/dev/nvme0n1p2 1967392744 325622112 1541758756   18% /
Downloading (as needed) Docker image ncbi/pgap:2023-05-17.build6771
Downloading and extracting tarball: https://s3.amazonaws.com/pgap/input-2023-05-17.build6771.tgz
2023-05-17.build6771: Pulling from ncbi/pgap
Digest: sha256:6067b42ef74eca02fb754be07c78ca2f40dccb0ca3e48edfe7ec204b2a872ce7
Status: Image is up to date for ncbi/pgap:2023-05-17.build6771
docker.io/ncbi/pgap:2023-05-17.build6771
^CTraceback (most recent call last):ytes (0.25%)
 
I terminated the download in that case
Hope I could explain the problem a bit better? 
best regards

**Comment by azat-badretdin** [comment]
I am not sure why you interrupted the last command, it seems to have been doing the right thing before you interrupted it.

**Comment by stalact** [comment]
I interrupted it just for the screenshot. I tried the same thing several times, and it somehow worked now! Thanks for your help! :-)
