### ISSUE TITLE
[BUG] test example failed

### ISSUE THREAD

**Issue by wangdi2016** [ncbi/pgap#260]
I installed docker image and downloaded input files etc under the user home folder. When I run the test example using the following command

./pgap.py -r -o mg37_results -g .pgap/test_genomes/MG37/ASM2732v1.annotation.nucleotide.1.fasta -s 'Mycoplasmoides genitalium'

I got the following error message saying 

No such file or directory:
                                '/pgap/user_input/.pgap/test_genomes/MG37/ASM2732v1.annotation.nucleotide.1.fasta'

The fasta file is located in the following folder.
/home/wangdi/.pgap/test_genomes/MG37/ASM2732v1.annotation.nucleotide.1.fasta

Thanks.

**Comment by azat-badretdin** [comment]
This is a mistake in documentation. We presume that user's current directory is $HOME, which clearly not the case. 

Could you please try this by specifying full path?

**Comment by wangdi2016** [comment]
Thanks Azat for your response!

I just tried using the full path. It is the same error message. See the log file here and the command.

./pgap.py -r -o mg37_results -g /home/wangdi/.pgap/test_genomes/MG37/ASM2732v1.annotation.nucleotide.1.fasta -s 'Mycoplasmoides genitalium'

[run.log](https://github.com/ncbi/pgap/files/11711389/run.log)

Thanks!

**Comment by azat-badretdin** [comment]
Thank you, Difei!

Copying file locally and running `./pgap.py .... -g ASM2732v1.annotation.nucleotide.1.fasta ` should work

**Comment by wangdi2016** [comment]
Thanks Azat! 

It worked after I copy the fasta file in the local directory and run the command as directed.

Have a great weekend!

**Comment by azat-badretdin** [comment]
I am glad it worked, Difei! 

We will work on fixing the documentation. 

> Have a great weekend!

You too!
