### ISSUE TITLE
Advice on using PGAPs HMMs with another annotation tool

### ISSUE THREAD

**Issue by tarunaaggarwal** [ncbi/pgap#262]
Hi @azat-badretdin - I wanted to get some advice from you about using PGAP's databases with another annotation tool. I don't have genus level resolution for my MAGs so I have been having a hard time using PGAP. Thus, I turned to Prokka. But I was wondering what you think about using NCBI's and TIGRFAM's HMMs for annotation with Prokka which already uses HAMAP. 

I always get confused about which protein family databases to use; so I thought heck I will just try a few at the same time. 

Do you think I'm crazy for doing so?

**Comment by azat-badretdin** [comment]
Thank you for your question, Taruna!

> But I was wondering what you think about using NCBI's and TIGRFAM's HMMs for annotation with Prokka 

This sounds more like a question to prokka creator. 

> Do you think I'm crazy for doing so?

No. Sounds like a valid research direction to me. 

I suspect that the direction here depends on specific goals you are trying to achieve by using different annotation tools.
