### ISSUE TITLE
[FEATURE REQUEST] Add a prefix to the output files of PGAP.

### ISSUE THREAD

**Issue by Dx-wmc** [ncbi/pgap#267]
By default, the output of PGAP is prefixed with "annot" in normal circumstances. When we want to compare and view multiple files generated by PGAP, we need to manually modify the files starting with "annot" to match the input file names. Prokka and other software have corresponding `--prefix `parameters to solve this issue. Although the issue at hand can be readily addressed with manual scripts, I believe the utility of PGAP could be significantly enhanced if an output format option, such as `--prefix`, was incorporated. 

Moreover, PGAP presently incorporates the parameters `-s` and `-g` to autonomously generate a YAML file. However, the nomenclature of this file is static, causing errors when multiple files are run concurrently. Consequently, I propose the integration of a prefix parameter to facilitate automatic naming of YAML files, such as test_submol.yaml and test_generic.yaml, among others. This would proficiently circumvent replication-related errors.

**Comment by azat-badretdin** [comment]
This has been released.
