### ISSUE TITLE
pgap.py not found with docker container ncbi/pgap

### ISSUE THREAD

**Issue by tbazilegith** [ncbi/pgap#268]
Hi Azat,
**Describe the bug**
I pulled the container to run run pgap in nextflow
container = 'ncbi/pgap'

**To Reproduce**
/ERROR ~ Error executing process > 'ani'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name ncbi-pgap-dev.img.pulling.1692838424330 docker://ncbi/pgap-dev > /dev/null
  status : 255
  message:
    FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://ncbi/pgap-dev: reading manifest latest in docker.io/ncbi/pgap-dev: manifest unknown: manifest unknown

**Expected behavior**
Singularity cache directory has not been defined -- Remote image will be stored in the path: my_path/work/singularity

Thanks,
TJ

**Comment by tbazilegith** [comment]
There are several containers on dockerhub. Which one is the right one? 
After pulling the container, how to get executable pgap.py? 
Thanks!

**Comment by thibaudnis** [comment]
Hi TJ - not sure what you are trying to do. Please start with https://github.com/ncbi/pgap/wiki/Quick-Start for getting pgap.py and getting started, and consult our FAQs as needed:  https://github.com/ncbi/pgap/wiki/FAQ. Thanks!

**Comment by tbazilegith** [comment]
Thanks Thilbaudnis,
I emplemented pgap in a nexflow, and I pulled the container from dockerhub, expecting run pgap onces the container is copied.
Based on your recommendation, we don't need to pull container directly from dockerhub, but only follow the github installation?
Thanks

**Comment by azat-badretdin** [comment]
That should be enough
