### ISSUE TITLE
[BUG] pgap.py --update 

### ISSUE THREAD

**Issue by nptgiang0211** [ncbi/pgap#271]
After downloading the file pgap.py from https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py, I attempted to run ./pgap.py --update, but I encountered an issue. Here is the report:

 ./pgap.py --update
Traceback (most recent call last):
  File "/home/molbiolab320/biotools/pgap/scripts/./pgap.py", line 994, in main
    params = Setup(args)
             ^^^^^^^^^^^
  File "/home/molbiolab320/biotools/pgap/scripts/./pgap.py", line 532, in __init__
    self.remote_versions = self.get_remote_versions()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/molbiolab320/biotools/pgap/scripts/./pgap.py", line 606, in get_remote_versions
    response = urlopen('https://api.github.com/repos/ncbi/pgap/releases/latest')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 541, in _open
    return self._call_chain(self.handle_open, 'unknown',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1419, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>

 - OS: Linux
 - Docker: 24.0.5,

Please help me, I cannot fix it :"(((

**Comment by azat-badretdin** [comment]
Thank you for your report, @nptgiang0211!

It looks like you had some kind of Internet connectivity issue. To eliminate this possibility, can you try to download `https://api.github.com/repos/ncbi/pgap/releases/latest` from command line? `curl -nOL https://api.github.com/repos/ncbi/pgap/releases/latest` or using your favorite command line downloader?

**Comment by nptgiang0211** [comment]
> Thank you for your report, @nptgiang0211!
> 
> It looks like you had some kind of Internet connectivity issue. To eliminate this possibility, can you try to download `https://api.github.com/repos/ncbi/pgap/releases/latest` from command line? `curl -nOL https://api.github.com/repos/ncbi/pgap/releases/latest` or using your favorite command line downloader?

Thank you for your reply, but I tried to use the command curl -nOL https://api.github.com/repos/ncbi/pgap/releases/latest, and then ran ./pgap.py again. However, I'm still encountering the same error lines.

**Comment by azat-badretdin** [comment]
It looks like your report is truncated: 

```
File "/usr/local/lib/python3.11/urllib/request.py", line 1419, in unknown_open
raise URLError('unknown url type: %s' % type)
urllib.error.URLError: 
```
This should be followed by a line:
```
unknown url type: <....>
```

could you please post the complete output formatted as "code"?

Thanks!
