### ISSUE TITLE
[FEATURE REQUEST]  Unable to retrieve additional reference data from https://s3.amazonaws.com/pgap/input-[version].tgz.

### ISSUE THREAD

**Issue by Tayvich** [ncbi/pgap#277]
[FEATURE REQUEST]  Unable to retrieve additional reference data from https://s3.amazonaws.com/pgap/input-[version].tgz.

When attempting to install PGAP standalone, I encounter difficulties downloading supplementary reference data from [https://s3.amazonaws.com/pgap/input-[version].tgz](https://s3.amazonaws.com/pgap/input-%5Bversion%5D.tgz). An error is displayed, indicating, 

This XML file does not appear to have any style information associated with it. The document tree is shown below:

Copy code
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>QD7YDBFT2QXYNKRJ</RequestId>
  <HostId>GM3cTBxMy/tkfsB+brdqx3FVnweo0v10PpceTnbYswg1GsFRedXsZNOLqDfBr2imVE/Yy1xu8x0=</HostId>
</Error>

Could you offer advice on this issue and propose any solutions for resolving it?

**Comment by azat-badretdin** [comment]
Thank you for reporting this, user @Tayvich ! We will verify that ASAP. Meanwhile, I am presuming that you are using the latest release as version. Please correct me if I am wrong.
