### ISSUE TITLE
Problem with running pgap annotation

### ISSUE THREAD

**Issue by Subhajeet1997** [ncbi/pgap#278]
When I m trying to run pgap annotation using following command 
"./pgap.py -r -o test_result -g ASM2732v1.annotation.nucleotide.1.fasta -s 'Mycoplasma genitalium G37'"
It is throwing error like below:
PGAP version 2023-10-03.build7061 is up to date.
<urlopen error [Errno 104] Connection reset by peer>
Failed to update ./pgap.py, ignoring
Something has gone wrong, please manually download: https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py
What is this error about?

**Comment by ericjove** [comment]
Please attempt the following:

### Option 1: Completely delete and reinstall PGAP.
Open your terminal.
Execute the command rm -rf ~/.pgap to delete the PGAP directory. This command removes the .pgap directory and all of its contents.

Reinstall PGAP:
Follow the instructions on the https://github.com/ncbi/pgap/wiki/Quick-Start page to download and install the latest version of PGAP.

### Option 2: Set the Environment Variable for PGAP_INPUT_DIR.
In your terminal, set PGAP_INPUT_DIR to a new location using:
For Linux/macOS EG: export PGAP_INPUT_DIR=/path/to/new/directory

Ensure the path you choose is different from the current PGAP installation directory (~/.pgap) as this will force a fresh installation of pgap.

Reinstall PGAP:
Follow the same Quick Start instructions for PGAP installation (https://github.com/ncbi/pgap/wiki/Quick-Start). The script should use the new directory set by PGAP_INPUT_DIR.

After completing either Option 1 or Option 2, try running the PGAP command again to see if the issue has been resolved.

### Unset Proxy Variables (if the issue persists):

If the error continues, execute these commands to remove any proxy settings:
```
unset http_proxy
unset https_proxy
unset HTTP_PROXY
unset HTTPS_PROXY
```
Retry running PGAP:

Please let me know if you have any continued issues.
