### ISSUE TITLE
[FEATURE REQUEST] Any plans about EGAP (Eukaryotic Genome Annotation Pipeline)?

### ISSUE THREAD

**Issue by GRGong** [ncbi/pgap#279]
Just wondering are there any plans about EGAP?

**Comment by thibaudnis** [comment]
Yes! We are planning a very barebone early release for late January. It will produce gene predictions using RNA-Seq and hopefully proteins, but it won't provide any functional annotation, and the results won't be suitable for submission to GenBank. Please email us at cgr@nlm.nih.gov or register at https://www.ncbi.nlm.nih.gov/comparative-genomics-resource/ to get our updates. Thanks!

**Comment by GRGong** [comment]
Thanks!
