### ISSUE TITLE
Error in step passdata when testing the sample files

### ISSUE THREAD

**Issue by edsonmachado** [ncbi/pgap#28]
Hello,

I'm having an issue when testing the sample files provided with pgap. I am running the test locally and I get the following error when following the quick start instructions:

$ python3.6 pgap.py -r -o mg37_results test_genomes/MG37/input.yaml
PGAP version 2019-05-13.build3740 is up to date.
/home/ioc/tools/PGAP/mg37_results
[2019-07-18 18:52:59] [workflow ] start
[2019-07-18 18:52:59] [workflow ] starting step passdata
[2019-07-18 18:52:59] [step passdata] start
[2019-07-18 18:52:59] [step passdata] Output is missing expected field file:///pgap/pgap.cwl#passdata/taxon_db
[2019-07-18 18:52:59] [step passdata] completed permanentFail
[2019-07-18 18:52:59] [workflow ] completed permanentFail
docker exited with rc = 1

$ cat mg37_results/cwltool.log
Original command: pgap.py -r -o mg37_results test_genomes/MG37/input.yaml

Docker command: /usr/bin/docker run -i --user 1000:1000 --volume /home/ioc/tools/PGAP/input-2019-05-13.build3740:/pgap/input:ro,z --volume /home/ioc/tools/PGAP/test_genomes/MG37:/pgap/user_input:z --volume /home/ioc/tools/PGAP/test_genomes/MG37/pgap_input.yaml:/pgap/user_input/pgap_input.yaml:ro,z --volume /home/ioc/tools/PGAP/mg37_results:/pgap/output:rw,z ncbi/pgap:2019-05-13.build3740 cwltool --timestamps --outdir /pgap/output pgap.cwl /pgap/user_input/pgap_input.yaml

[2019-07-18 18:52:44] /usr/bin/cwltool 1.0.20190228155703
[2019-07-18 18:52:44] Resolved 'pgap.cwl' to 'file:///pgap/pgap.cwl'
[2019-07-18 18:52:59] [workflow ] start
[2019-07-18 18:52:59] [workflow ] starting step passdata
[2019-07-18 18:52:59] [step passdata] start
[2019-07-18 18:52:59] [step passdata] Output is missing expected field file:///pgap/pgap.cwl#passdata/taxon_db
[2019-07-18 18:52:59] [step passdata] completed permanentFail
[2019-07-18 18:52:59] [workflow ] completed permanentFail
[2019-07-18 18:52:59] Final process status is permanentFail
{
    "gbent": null,
    "gbk": null,
    "gff": null,
    "input_fasta": {
        "class": "File",
        "location": "file:///pgap/output/ASM2732v1.annotation.nucleotide.1.fasta",
        "size": 588482,
        "basename": "ASM2732v1.annotation.nucleotide.1.fasta",
        "checksum": "sha1$f6129783cc8562db7bca3c87310d57d8dd07ce2c",
        "path": "/pgap/output/ASM2732v1.annotation.nucleotide.1.fasta"
    },
    "input_submol": {
        "class": "File",
        "location": "file:///pgap/output/submol.yaml",
        "size": 1529,
        "basename": "submol.yaml",
        "checksum": "sha1$f9eb1bbbbb1115b94b22b7148647adc3b6107c9f",
        "path": "/pgap/output/submol.yaml"
    },
    "nucleotide_fasta": null,
    "protein_fasta": null,
    "sqn": null
}

Can you help me?

Best regards,

Edson Machado

**Comment by azat-badretdin** [comment]
Thank you for your feedback, Edson! Somebody will look at this in a timely manner. My initial feeling about this is that something must be not right with your system setup.

**Comment by slottad** [comment]
It is possible that the auxiliary data did not download correctly. Check it out with the following commands:

```
~$ du -sh --apparent-size input-2019-05-13.build3740
41G     input-2019-05-13.build3740
~$ ls -R input-2019-05-13.build3740 | wc -l
368
```

Your results should match mine. If they do not, try deleting that subdirectory and downloading it again:

```
~$ rm -rf input  input-2019-05-13.build3740
~$ ./pgap.py --update
```

**Comment by edsonmachado** [comment]
Oh, yes! You are right. Indeed, the auxiliary data did not download correctly.

Now it's working!

Thank you for your support.

Best regards,

Edson Machado
