### ISSUE TITLE
[FEATURE REQUEST] <Turn Off GO annotation>

### ISSUE THREAD

**Issue by greg-harhay** [ncbi/pgap#280]
Could you provide an option/switch to turn off GO annotation?  Such a switch is not described in the output of 

pgap.py --help

Thank you.

Greg

**Comment by azat-badretdin** [comment]
Thank you for you report, Gregory! 

Currently we do not provide an option to turn off the GO annotation. 

I suppose an adventorous  user could try a hacky way to do that by editing away GO lines in our SQLITE3 database of PFM attributes...

**Comment by azat-badretdin** [comment]
>  Bing and Bard searches for turning off the GO annotation in PGAP suggest that this option was available in the past

Thanks for letting us know, Gregory!

**Comment by thibaudnis** [comment]
Can you explain why you would be interested in turning off GO annotation? This is the first time we receive this request. Thanks!

**Comment by greg-harhay** [comment]
Sure, I want to add my own GO annotations and EC numbers and compare to the NCBI annotated genomes.

**Comment by greg-harhay** [comment]
I am developing a custom approach. If it offers advantages to existing annotation, I'll publish it.
