### ISSUE TITLE
[BUG] <title>How to run pgap.py with qsub file.

### ISSUE THREAD

**Issue by wurunbiao162** [ncbi/pgap#284]
**Describe the bug**
Error running pgap in clustered server.

**Running script
$ qsub works.sh 
The following commands are included in the works.sh file.
    #!/bin/sh
    #PBS -N lucky
    #PBS -l nodes=1:ppn=10
    #PBS -q blade
    #PBS -l walltime=1000:00:00
    #PBS -d /public1/home/20240101_Bacteria_Genome 
    #PBS -j oe

    python3 ~/soft/pgap.py  -r -o mg37_results -g ~/.pgap/test_genomes-2023-10- 
   03.build7061/MG37/ASM2732v1.annotation.nucleotide.1.fasta -s 'Mycoplasmoides genitaliu' --no-self-update --no-internet .

**Log Files**
[2024-01-19 19:14:40][INFO][157337.admin] ########################  Job 157337.admin start to execute pre.sh!   ##########################
[2024-01-19 19:14:40][INFO][157337.admin] Goldenable & storageenable both are false, job ran without making reserve!
Fri Jan 19 19:13:29 CST 2024
--no-internet flag enabled, not checking remote versions.
Docker not found.

**Software versions (please complete the following information):**
 - OS: [ CentOS 7]
 - pgap.py --version, or docker image version.  [2023-10-03.build7061]
 - Docker version. [Docker version 24.0.7, build afdd53b]

**Additional context**
Would you like to provide the detail commands to run pgap pipeline.

**Comment by azat-badretdin** [comment]
It says: `Docker not found.` Do you have docker hooked up on your cluster machines?

**Comment by wurunbiao162** [comment]
I have installed docker and pulling pgap.

(base) [jian@login ~]$ docker images
REPOSITORY                        TAG                    IMAGE ID            CREATED             SIZE
docker.io/ncbi/pgap-utils         2023-10-03.build7061   cbaed0b6edfb        3 months ago        11.9 GB

**Comment by azat-badretdin** [comment]
- Did you run this command on one of the cluster machines?
- The docker image you listed is not the image that is used by `pgap.py` is the listing complete? Did you use ./pgap.py to install as in Quick Notes?

**Comment by wurunbiao162** [comment]
Thank you azat， I also run the  ./pgap.py --update，get the files /public1/home/jian/.pgap/input-2023-10-03.build7061, test_genomes-2023-10-03.build7061.

**Comment by azat-badretdin** [comment]
Thanks. Note that the propagation of this installation to the computational server and accessibility of data and docker image from that server is in the hands of the user, NCBI does not support such thing. That's why I ask which server did you use to check your docker status.
