### ISSUE TITLE
[BUG] WARNING Final process status is permanentFail

### ISSUE THREAD

**Issue by snackens** [ncbi/pgap#286]
Thank you for this convenient tool.
I got following error while running pgap.

**Describe the bug**
WARNING Final process status is permanentFail.

**To Reproduce**
Other genomes seemed to be successfully finished. Only this genome was failed. 
[tmp-outdir.zip](https://github.com/ncbi/pgap/files/14257446/tmp-outdir.zip)

command used in this analysis
./pgap.py -r -o pgap/result -g genome.fasta -s 'Helicobacter pylori' --taxcheck -D /opt/pkg/singularity-ce/4.0.0/bin/singularity
(slightly modified for example name of fasta file and output directory.)

**Expected behavior**

**Software versions (please complete the following information):**
 - OS: Ubuntu Linux 22.04LTS
 - pgap.py --version 2023-10-03.build7061
 - singularity

**Log Files**
Please rerun pgap.py with the ``--debug`` flag and attach an archive (e.g. zip or tarball) of the logs in the directory: ``debug/tmp-outdir/*/*.log``.

**Additional context**

Best regards,

**Comment by azat-badretdin** [comment]
Thank you for posting this report, user @snackens ! 

Could you please post `cwltool.log` file as well? Thanks!

**Comment by azat-badretdin** [comment]
The key to reading `cwltool.log` is last part before first `permanentFail` message. Here it goes: 

```
[2024-02-13 16:15:27] INFO [job screen_evaluate] /pgap/output/debug/tmp-outdir/0444mft1$ screen_evaluate \
    -ifmt \
    seq-annot \
    -tab \
    /pgap/output/debug/tmpdir/5zc2p07y/stgcc008c4b-0885-40a4-bed6-6939a95226dc/calls.tab
[2024-02-13 16:15:27] DEBUG Could not collect memory usage, job ended before monitoring began.
[2024-02-13 16:15:27] WARNING [job screen_evaluate] exited with status: 1
[2024-02-13 16:15:27] WARNING [job screen_evaluate] completed permanentFail

```


This means that your input is contaminated. The `calls.tab` file should be in your `output/` directory, as well as in one of the output files in tmp zip you posted.. It will show what contaminates nucleotide sequences and where.

Please let me know how it goes.

**Comment by snackens** [comment]
Thank you!

calls.tab file includes

lcl|genome_030 X - PHG:phiX174 contam_in_prok

This means genome_030 is contaminated something?
So Should I remove this contigs? or not use this genome?
Sorry if this question is not related to this program.

**Comment by azat-badretdin** [comment]
That is up to you. If you curious about annotation, the most straightforward way is to just remove this contig. 

This is also the way to submit the results to GenBank, if I am not mistaken.

**Comment by snackens** [comment]
I see.

Thank you for your kindness.

**Comment by azat-badretdin** [comment]
I was happy to help, user @snackens ! Can we close this issue?

**Comment by snackens** [comment]
Yes, thank you so much.

**Comment by azat-badretdin** [comment]
You are welcome!
