### ISSUE TITLE
Quick Start instructions fail due to 'Missing required input parameter'

### ISSUE THREAD

**Issue by crashfrog** [ncbi/pgap#29]
Version 2019-08-01.build3919

```
Original command: scripts/pgap.py --debug -r -o mg37_results MG37/input.yaml

Docker command: /usr/bin/docker run -i --user 1018:1019 --volume /home/justin.payne/pgap/input-2019-08-01.build3919:/pgap/input:ro,z --volume /home/justin.payne/pgap/MG37:/pgap/user_input:z --volume /home/justin.payne/pgap/MG37/pgap_input.yaml:/pgap/user_input/pgap_input.yaml:ro,z --volume /home/justin.payne/pgap/mg37_results.2:/pgap/output:rw,z --volume /home/justin.payne/pgap/mg37_results.2/debug/log:/log/srv:z ncbi/pgap:2019-08-01.build3919 cwltool --timestamps --disable-color --outdir /pgap/output --tmpdir-prefix /pgap/output/debug/tmpdir/ --leave-tmpdir --tmp-outdir-prefix /pgap/output/debug/tmp-outdir/ --copy-outputs pgap.cwl /pgap/user_input/pgap_input.yaml

--- Start YAML Input ---
submit_block_template:
  class: File
  location: MG37/ASM2732v1.1.template
fasta:
  class: File
  location: MG37/ASM2732v1.annotation.nucleotide.1.fa
taxid: 243273
gc_assm_name: MG37
completeness: complete
supplemental_data: { class: Directory, location: /pgap/input }
report_usage: true
--- End YAML Input ---
[2019-08-13 22:07:12] INFO /usr/bin/cwltool 1.0.20190621234233
[2019-08-13 22:07:12] INFO Resolved 'pgap.cwl' to 'file:///pgap/pgap.cwl'
[2019-08-13 22:07:42] ERROR Workflow error, try again with --debug for more information:
Invalid job input record:
pgap.cwl:26:3: Missing required input parameter 'submol'
```

**Comment by azat-badretdin** [comment]
Thank you for your report! We will look at this issue at the earliest opportunity.

**Comment by wangdi2014** [comment]
check your test_genomes/MG37/ folder and see if the pgap_input.yaml is there.

To me, it seems from 2019-05-13.build3740 version, this input file is missing.

To get this input file, you can download the pgap_input.yaml from the following location and
put it inside the test_genomes/MG37 folder.

wget https://campuscloud.unibe.ch:443/ssf/s/readFile/share/29641/5440512207672247602/publicLink/pgap_input.yaml

This works for me.

**Comment by azat-badretdin** [comment]
>Original command: scripts/pgap.py --debug -r -o mg37_results MG37/input.yaml

Could you please following instructions from https://github.com/ncbi/pgap/wiki/Quick-Start?

The particular command you are referring to seems to be taken from maybe historic runs?

**Comment by crashfrog** [comment]
Hi Azat,

Yes, I'm following the quick start instructions.

My MG37 sample data was missing the pgap_input.yaml file, but adding it hasn't changed the result:

```
Original command: scripts/pgap.py --debug -r -o mg37_results MG37/input.yaml

Docker command: /usr/bin/docker run -i --user 1018:1019 --volume /home/justin.payne/pgap/input-2019-08-01.build3919:/pgap/input:ro,z --volume /home/justin.payne/pgap/MG37:/pgap/user_input:z --volume /home/justin.payne/pgap/MG37/pgap_input.yaml:/pgap/user_input/pgap_input.yaml:ro,z --volume /home/justin.payne/pgap/mg37_results.3:/pgap/output:rw,z --volume /home/justin.payne/pgap/mg37_results.3/debug/log:/log/srv:z ncbi/pgap:2019-08-01.build3919 cwltool --timestamps --disable-color --outdir /pgap/output --tmpdir-prefix /pgap/output/debug/tmpdir/ --leave-tmpdir --tmp-outdir-prefix /pgap/output/debug/tmp-outdir/ --copy-outputs pgap.cwl /pgap/user_input/pgap_input.yaml

--- Start YAML Input ---
submit_block_template:
  class: File
  location: MG37/ASM2732v1.1.template
fasta:
  class: File
  location: MG37/ASM2732v1.annotation.nucleotide.1.fa
taxid: 243273
gc_assm_name: MG37
completeness: complete
supplemental_data: { class: Directory, location: /pgap/input }
report_usage: true
--- End YAML Input ---
[2019-08-15 15:26:59] INFO /usr/bin/cwltool 1.0.20190621234233
[2019-08-15 15:26:59] INFO Resolved 'pgap.cwl' to 'file:///pgap/pgap.cwl'
[2019-08-15 15:27:28] ERROR Workflow error, try again with --debug for more information:
Invalid job input record:
pgap.cwl:26:3: Missing required input parameter 'submol'
```

**Comment by azat-badretdin** [comment]
>Yes, I'm following the quick start instructions.

I do not think you do

command line at https://github.com/ncbi/pgap/wiki/Quick-Start is

```./pgap.py -r -o mg37_results test_genomes/MG37/input.yaml ```

you are running

```scripts/pgap.py --debug -r -o mg37_results MG37/input.yaml```

**Comment by crashfrog** [comment]
Sure, but those are the same command.

**Comment by wangdi2014** [comment]
Try run command without --debug and see if it will run. I suspect the debug mode is for the developers. You can go inside the container and see how the debug mode works.

**Comment by crashfrog** [comment]
I mean I'm running it with `debug` because it didn't work when I followed the quick start instructions, and I'm trying to figure out why. At the suggestion of the error message, I repeated the test with the flag.

Unfortunately I'm not able to continue troubleshooting at this time.

**Comment by azat-badretdin** [comment]
> Sure, but those are the same command (with the addition of the debug flag, since I'm debugging.)

@crashfrog 

The difference is in the path to `input_file.yaml` and in the path to the script `pgap.py`

**Comment by crashfrog** [comment]
Yes, but nevertheless you can plainly see it's the same command.

**Comment by whlavina** [comment]
There is a difference in the Current Working Directory (CWD) between your command line and the one in the documentation. While that shouldn't make a difference in theory (the relative paths should resolve similarly), in practice, it might. (There is significant path-remapping between logical and physical paths, both in Docker and in cwltool.)

**Comment by crashfrog** [comment]
If you can confirm that the tool is not robust to changes in cwd, then I'll
open an issue about the bug. Like I said I can't troubleshoot this anymore.

But you have to be aware that the paths in the quickstart guide can't
literally work, right? ie:

`./pgap.py -r -o mg37_results test_genomes/MG37/input.yaml`

There's no directory that contains both pgap.py and the directory
test_genomes, so it's not possible to run this command literally as written.

**Comment by slottad** [comment]
Are you running this by checking out the code from GitHub?

The quickstart instructions ask you you download pgap.py directly to the cwd using curl or wget, and then use the update command, which places test_genomes in the cwd as well. These command do not create a scripts directory.

You can call pgap.py from any directory, and use an input file located elsewhere, but the input directory containing the supplemental annotation data must be in the cwd.

**Comment by crashfrog** [comment]
I did run update, but it didn't create a test_genomes folder.

Overall that's not a high-quality way to distribute software. If it's
indeed the case that the supplemental data needs to be in cwd, the quick
start guide should say so.
