### ISSUE TITLE
[FEATURE REQUEST] Support for Charlie Cloud Docker compatible (but more secure) container system for HPC

### ISSUE THREAD

**Issue by idlfuente** [ncbi/pgap#291]
Hello.

It would be good if you can add support for CharlieCloud. [CharlieCloud overview](https://hpc.github.io/charliecloud/index.html)
It is docker compatible. It can handle docker images without any changes.
But the commands are different. For that reason, pgap.py doesn't recognized it as installed.

Thanks

**Comment by george-coulouris** [comment]
Hello,

Unfortunately, we do not have the resources to support additional container systems.

If using the -D option is not sufficient, feel free to modify your local pgap.py so that it recognizes CharlieCloud; I'd start with docker_type_alternatives.

Cheers,
George Coulouris
