### ISSUE TITLE
[BUG] -c flag not received: /mnt/shared/scratch/theaven/uncompressed/hogenhout/pgap-s7 

### ISSUE THREAD

**Issue by TCHeaven** [ncbi/pgap#295]
**Describe the bug**
I ran pgap with the flag -c 8, however this run failed, from the output cwltool.log file I could see that pgap was still trying to use 64 cpu cores. When I resubmitted a SLURM job with 64 cores available pgap ran successfully.

**cwltool.log**
Original command: ./pgap.py -c 8 -m 50G -n -d --docker singularity --container-path /home/theaven/scratch/apps/pgap/pgap_2023-10-03.build7061.sif -o /mnt/shared/scratch/theaven/uncompressed/hogenhout/pgap-s7 -g /mnt/shared/scratch/theaven/uncompressed/hogenhout/Liberibacter_v1.fa -s Liberibacter

Docker command: /usr/bin/singularity exec --bind /home/theaven/.pgap/input-2023-10-03.build7061:/pgap/input:ro --bind /mnt/shared/scratch/theaven/apps/pgap:/pgap/user_input --bind /mnt/shared/scratch/theaven/apps/pgap/pgap_input_glv2_m1h.yaml:/pgap/user_input/pgap_input.yaml:ro --bind /tmp/theaven_19264068:/tmp:rw --bind /mnt/shared/scratch/theaven/uncompressed/hogenhout/pgap-s7:/pgap/output:rw --bind /mnt/shared/scratch/theaven/uncompressed/hogenhout/pgap-s7/debug/log:/log/srv --pwd /pgap /home/theaven/scratch/apps/pgap/pgap_2023-10-03.build7061.sif /bin/taskset -c 0-7 cwltool --timestamps --debug --disable-color --preserve-entire-environment --outdir /pgap/output --tmpdir-prefix /pgap/output/debug/tmpdir/ --leave-tmpdir --tmp-outdir-prefix /pgap/output/debug/tmp-outdir/ --copy-outputs pgap/pgap.cwl /pgap/user_input/pgap_input.yaml

--- Start YAML Input ---
fasta:
    class: File
    location: Liberibacter_v1.fa
submol:
    class: File
    location: pgap_submol_216i5n52.yaml
supplemental_data: { class: Directory, location: /pgap/input }
report_usage: false
--- End YAML Input ---

--- Start Runtime Report ---
{
    "CPU cores": 64,
    "Docker image": "/home/theaven/scratch/apps/pgap/pgap_2023-10-03.build7061.sif",
    "cpu flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities",
    "cpu model": "Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz",
    "max user processes": 128379,
    "memory (GiB)": 187.5,
    "memory per CPU core (GiB)": 2.9,
    "open files": 1024,
    "tmp disk space (GiB)": 1318.6,
    "virtual memory": "unlimited",
    "work disk space (GiB)": 202838.8
}
--- End Runtime Report ---

taskset: failed to set pid 0's affinity: Invalid argument

**Comment by azat-badretdin** [comment]
Thank you for your report, Thomas! Glad to see you submitting another Issue!

Have you tried perchance applying a workaround from #289 ?
