### ISSUE TITLE
product protein name issues

### ISSUE THREAD

**Issue by asd1864714** [ncbi/pgap#298]
Some annotated product name seems inaccurate. For example, the protein annotation file is "hypothetical protein", but its RefSeq: WP_017098013.1 shows that it is "RepB family plasmid replication initiator protein".
<img width="597" alt="350899d959fa21c609e4730f5a78e84" src="https://github.com/ncbi/pgap/assets/57427280/9950ac17-1dd7-41e5-ac4f-945998a17d50">

**Comment by azat-badretdin** [comment]
The annotation you see in Refseq is updated by software that runs on live version of reference data and it is updated daily. 

The annotation you get from standalone PGAP is dated by reference data frozen by the time of the release, and current release is October. 

We are currently in preparation of a new release that we are planning to issue in a few days. I suggest to rerun your case with this new release.

**Comment by asd1864714** [comment]
Thank you for your patient answer, it helped me a lot.

**Comment by azat-badretdin** [comment]
Please open a new issue (for clarity) if this happens in the coming release.
