### ISSUE TITLE
container, runscript fails

### ISSUE THREAD

**Issue by ebioman** [ncbi/pgap#3]
Hi
Due to security issues we only run singularity and no docker container on our infrastructure.
I therefore simply tried to convert your docker image into a singularity one but seem to fail a test genome.

```bash
singularity exec -i   --bind $inDir:/pgap/user_input:ro \
                              --bind $(pwd -P)/input-2018-11-07.build3190:/pgap/user_input/input:ro \
                              --bind $(pwd -P)/output:/pgap/output:rw $image \
                                cwltool    --outdir ./outdir    /pgap/wf_pgap_simple.cwl  /pgap/user_input/pgap_input.yaml

/usr/bin/cwltool 1.0.20181102182747
Resolved '/pgap/wf_pgap_simple.cwl' to 'file:///pgap/wf_pgap_simple.cwl'
[workflow ] start
[workflow ] starting step prepare_input_template
[step prepare_input_template] start
[job prepare_input_template] /tmp/tmpci7z9td1$ cat \
    /tmp/tmpddgmgg9w/stgf9b1defa-c3e9-4488-9488-9b0639f67093/submit_block_static.template \
    /tmp/tmpddgmgg9w/stg7785d7c4-7c7b-4836-b0cf-8a590fc25c53/molinfo_wgs.asn > /tmp/tmpci7z9td1/complete.template
[job prepare_input_template] completed success
[step prepare_input_template] completed success
[workflow ] starting step standard_pgap
[step standard_pgap] start
[workflow standard_pgap] start
[workflow standard_pgap] starting step genomic_source
[step genomic_source] start
[workflow genomic_source] start
[workflow genomic_source] starting step Cache_FASTA_Sequences
[step Cache_FASTA_Sequences] start
[job Cache_FASTA_Sequences] /tmp/tmpk7g783sv$ prime_cache \
    -cache \
    sequence_cache \
    -ifmt \
    fasta \
    -i \
    /tmp/tmpwxdd6j43/stgb1219d63-cb5e-40b3-82ca-72dc39188469/SAMN09831750-rid6458073.denovo.assembly.contigs.fasta \
    -oseq-ids \
    oseq-ids.seqids \
    -submit-block-template \
    /tmp/tmpwxdd6j43/stg19a555ec-cc3c-41b9-b651-99d46c39abc8/complete.template \
    -taxid \
    1354 \
    -taxon-db \
    /tmp/tmpwxdd6j43/stg5664216c-bc9f-44b9-bfd4-87f368da638a/taxonomy.sqlite3
'prime_cache' not found
[job Cache_FASTA_Sequences] completed permanentFail
[step Cache_FASTA_Sequences] Output is missing expected field file:///pgap/genomic_source/wf_genomic_source.cwl#Cache_FASTA_Sequences/oseq_ids
[step Cache_FASTA_Sequences] Output is missing expected field file:///pgap/genomic_source/wf_genomic_source.cwl#Cache_FASTA_Sequences/asn_cache
[step Cache_FASTA_Sequences] completed permanentFail
[workflow genomic_source] completed permanentFail
[step genomic_source] completed permanentFail
[workflow standard_pgap] completed permanentFail
[step standard_pgap] completed permanentFail
[workflow ] completed permanentFail
{
    "gbent": null,
    "gbk": null,
    "gff": null,
    "nucleotide_fasta": null,
    "protein_fasta": null
}
Final process status is permanentFail
```

I am wondering whether it might be due to unfullfilled environmental variables.
Would you mind sharing part/the entire singularity recipe file ?
Currently I only added the following section which I fear is not enough:

    %environment
    export PATH=/pgap/:/bin/${PATH}

It adds all binaries into the path, but seem to fail as above shown.
As I am not an active user of your software but only packing it, it might be completely unrelated as well.

**Comment by ebioman** [comment]
thanks a lot, that might be helpful

**Comment by MrTomRod** [comment]
If you manage to make pgap work with Singularity, **please** let us know!

(Docker requires root privileges. Singularity doesn't and can thus be used on clusters.)

**Comment by slottad** [comment]
Note that we (NCBI) are also interested in supporting Singularity and will soon make this a priority. @ebioman, if you have made any progress, please let us know.

**Comment by TheBigFatTony** [comment]
Great to know! Happy New Year!

**Comment by npavlovikj** [comment]
@slottad , many thanks for providing the two Dockerfiles. In `Dockerfile-pgap-utils.txt`, the following archives are extracted `install.tar.gz`, `linked_exe.tar`, `libraries.tar`, and `trnascan.tgz`. Do you know where I can download those files from? Also, I believe those files are make the `/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system` directory? 

I am trying to combine the two Dockerfiles and have PGAP run with Singularity, but the directory from above doesn't exist for me, so any help/direction would be helpful.

**Comment by wangdi2014** [comment]
Hi,

I tried the standalone pipeline using docker image.
It failed at the following step. Any ideas why it failed? Thanks!

=========================================================
...
pilercr v1.02
http://www.drive5.com/piler
Written by Robert C. Edgar
This software is donated to the public domain.
Please visit web site for requested citation.


   0 s       1 Mb (  0%)  Reading sequences from /tmp/ncbi_crisper_wnode.1.3xh5Jh/fasta_by_scaffold.1.nPhKKR/0.fa
^M   0 s       2 Mb (  0%)  100.00%
   0 s       2 Mb (  0%)  1 sequences, total length 580076 bases (1 Mb)
^M   0 s       2 Mb (  0%)    0.00%  Allocating index^M   0 s       4 Mb (  0%)  100.00%  Allocating index
^M   0 s       4 Mb (  0%)    0.00%  Filtering^M   0 s       4 Mb (  0%)    0.00%  Filtering^M   0 s       4 Mb (  0%)   34.48%  Filtering^M   0 s       4 Mb (  0%)   68.96%  Filtering^M   1 s       4 Mb (  0%)  100.00%  Filtering
   1 s       3 Mb (  0%)  16337 filter hits
   1 s       3 Mb (  0%)  Read filter hits
   1 s       3 Mb (  0%)  16337 filter hits
   1 s       3 Mb (  0%)  Merge filter hits
   1 s       4 Mb (  0%)  13144 trapezoids, total length 127098
   1 s       4 Mb (  0%)  Initializing trapezoid alignment
...
   1 s       5 Mb (  0%)  Removing redundant hits
   1 s       4 Mb (  0%)  Sorting hits
   1 s       4 Mb (  0%)  56 DP hits, 53 accepted
   1 s       4 Mb (  0%)  0 discarded hits
   1 s       4 Mb (  0%)  Converting hits to images
   1 s       4 Mb (  0%)  Sorting images
   1 s       4 Mb (  0%)  Finding piles
   1 s       4 Mb (  0%)  85 piles found
   1 s       4 Mb (  0%)  Building graph
   1 s       4 Mb (  0%)  Find connected components
   1 s       4 Mb (  0%)  8 connected components
   1 s       4 Mb (  0%)  Find arrays
   1 s       4 Mb (  0%)  0 arrays found
   1 s       4 Mb (  0%)  Elapsed time 1 secs, peak mem use 5 Mb
=== STDOUT: java -Xmx128m -cp /opt/crispr/1.0/bin//CRT1.2-CLI.jar crt /tmp/ncbi_crisper_wnode.1.3xh5Jh/fasta_by_scaffold.1.nPhKKR/0.fa .14.0.fa.crt.tmp
Error occurred during initialization of VM
Cannot create VM thread. Out of system resources.
FATAL: java -Xmx128m -cp /opt/crispr/1.0/bin//CRT1.2-CLI.jar crt /tmp/ncbi_crisper_wnode.1.3xh5Jh/fasta_by_scaffold.1.nPhKKR/0.fa .14.0.fa.crt.tmp non-zero code 256
check out .14.0.fa.crt.tmp
00001/004/0007/R  7CB30001C3114411 0032/0006 2019-01-05T20:32:02.695039 602e9cd5bb90    UNK_CLIENT      UNK_SESSION              ncbi_crisper_wnode Error: NCBI_CRISPER(CException::eUnknown) "ncbi_crisper_wnode.cpp", line 355: ncbi::CGPX_NcbiCrisperJob::Process() --- ncbi_crisper call failed: /opt/crispr/1.0/bin//ncbi_crisper /tmp/ncbi_crisper_wnode.1.3xh5Jh/fasta_by_scaffold.1.nPhKKR/0.fa
00001/004/0007/R  7CB30001C3114411 0033/0007 2019-01-05T20:32:02.695142 602e9cd5bb90    UNK_CLIENT      UNK_SESSION              ncbi_crisper_wnode Error: NCBI_CRISPER "ncbi_crisper_wnode.cpp", line 393: ncbi::CGPX_NcbiCrisperJob::Process() --- Error in the body of Process: (CException::eUnknown) ncbi_crisper call failed: /opt/crispr/1.0/bin//ncbi_crisper /tmp/ncbi_crisper_wnode.1.3xh5Jh/fasta_by_scaffold.1.nPhKKR/0.fa
00001/004/0007/R  7CB30001C3114411 0034/0008 2019-01-05T20:32:02.695593 602e9cd5bb90    UNK_CLIENT      UNK_SESSION              ncbi_crisper_wnode Error: NCBI_CRISPER(CException::eUnknown) "ncbi_crisper_wnode.cpp", line 355: ncbi::CGPX_NcbiCrisperJob::Process() --- ncbi_crisper call failed: /opt/crispr/1.0/bin//ncbi_crisper /tmp/ncbi_crisper_wnode.1.3xh5Jh/fasta_by_scaffold.1.nPhKKR/0.fa
00001/004/0007/R  7CB30001C3114411 0035/0009 2019-01-05T20:32:02.695628 602e9cd5bb90    UNK_CLIENT      UNK_SESSION              ncbi_crisper_wnode Error: LIB "wn_worker_thread.cpp", line 259: ncbi::CWorkerThread::x_DoJob() --- error processing job: (CException::eUnknown) ncbi_crisper call failed: /opt/crispr/1.0/bin//ncbi_crisper /tmp/ncbi_crisper_wnode.1.3xh5Jh/fasta_by_scaffold.1.nPhKKR/0.fa
00001/004/0007/RE 7CB30001C3114411 0036/0010 2019-01-05T20:32:02.696966 602e9cd5bb90    UNK_CLIENT      UNK_SESSION              ncbi_crisper_wnode request-stop  500 1.057945966 0 0
00001/003/0008/RB 7CB30001C3114411 0037/0001 2019-01-05T20:32:02.697177 602e9cd5bb90    UNK_CLIENT      UNK_SESSION              ncbi_crisper_wnode request-start internal_thread=output&processing_cycle=1&ncbi_app_version=0.0.0&ncbi_app_sc_version=21&ncbi_app_vcs_revision=574109
00001/003/0008/R  7CB30001C3114411 0038/0002 2019-01-05T20:32:02.697220 602e9cd5bb90    UNK_CLIENT      UNK_SESSION              ncbi_crisper_wnode extra         success_jobs=0&fail_jobs=1
00001/003/0008/R  7CB30001C3114411 0039/0003 2019-01-05T20:32:02.697408 602e9cd5bb90    UNK_CLIENT      UNK_SESSION              ncbi_crisper_wnode extra         attempts=1
00001/003/0008/RE 7CB30001C3114411 0040/0004 2019-01-05T20:32:02.697431 602e9cd5bb90    UNK_CLIENT      UNK_SESSION              ncbi_crisper_wnode request-stop  200 0.000261783 0 0
00001/000/0000/P  7CB30001C3114411 0041/0019 2019-01-05T20:32:04.712105 602e9cd5bb90    UNK_CLIENT      7CB30001C3114411_0000SID ncbi_crisper_wnode Error: LIB(CException::eUnknown) "wn_app.cpp", line 357: ncbi::CGPX_WorkerApp::Run() --- 1 jobs failed
00001/000/0000/P  7CB30001C3114411 0042/0020 2019-01-05T20:32:04.712178 602e9cd5bb90    UNK_CLIENT      7CB30001C3114411_0000SID ncbi_crisper_wnode Error: CORELIB(106.16) "ncbiapp.cpp", line 529: ncbi::CNcbiApplication::x_TryMain() --- Application's execution failed (CException::eUnknown) 1 jobs failed
00001/000/0000/PE 7CB30001C3114411 0043/0021 2019-01-05T20:32:04.718195 602e9cd5bb90    UNK_CLIENT      7CB30001C3114411_0000SID ncbi_crisper_wnode extra         ncbi_phid=7CB30001C31144110000000000000001
00001/000/0000/PE 7CB30001C3114411 0044/0022 2019-01-05T20:32:04.718269 602e9cd5bb90    UNK_CLIENT      7CB30001C3114411_0000SID ncbi_crisper_wnode stop          3 3.426879882
[job Execute_CRISPR_wnode] Max memory used: 2453MiB
[job Execute_CRISPR_wnode] completed permanentFail
[step Execute_CRISPR_wnode] completed permanentFail
[workflow bacterial_mobile_elem] completed permanentFail
[step bacterial_mobile_elem] completed permanentFail
[workflow standard_pgap] completed permanentFail
[step standard_pgap] completed permanentFail
[workflow ] completed permanentFail
{
    "gbent": null,
    "gbk": null,
    "gff": null,
    "nucleotide_fasta": null,
    "protein_fasta": null
}
Final process status is permanentFail

**Comment by npavlovikj** [comment]
@ebioman , we noticed that there was a typo in `run_pgap_standalone.sh - it should be `--outdir ./output` instead of `--outdir ./outdir`. Since the output directory doesn't exist, the output files can not be written nor found. Other than that, we were able to use Singularity following the instructions in the PGAP standalone script.

**Comment by slottad** [comment]
Please note that we have just pushed out a new version. The standalone version is the current recommended method for running the pipeline. Please see the updated https://github.com/ncbi/pgap/wiki/Quick-Start.

**Comment by ebioman** [comment]
Thanks a lot, will give it a try the next days

Natasha Pavlovikj <notifications@github.com> schrieb am Do., 28. Feb. 2019,
17:24:
