### ISSUE TITLE
[BUG] Final process status is permanentFail

### ISSUE THREAD

**Issue by namho4577** [ncbi/pgap#300]
Using Windows 11, newest version of Docker Desktop, newest version of PGAP (build7061)
I run this command in Command Prompt:

./pgap.py -r -o E_coli_result5 -g $HOME/.pgap/test_genomes/MG37/E_coli_seq1.fasta -s 'Eschericahi coli' --ignore-all-errors

Docker container starts up and runs for a while and then ends with "WARNING Final process status is permanentFail"
I'm not sure where I might be going wrong.

PGAP version 2023-10-03.build7061 is up to date.
Output will be placed in: /home/namho4577/PGAP/E_coli_result5
WARNING: memory (GiB) is less than the recommended value of 8
WARNING: memory per CPU core (GiB) is less than the recommended value of 2
PGAP failed, docker exited with rc = 1
Printing log starting from failed job:

[2024-05-01 11:30:00] DEBUG [step pgapx_yaml_ctl] job input {
    "file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/ignore_all_errors": true,
    "file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/input": {
        "location": "file:///tmp/6b_9y3_s/submol.json",
        "basename": "submol.json",
        "nameroot": "submol",
        "nameext": ".json",
        "class": "File",
        "checksum": "sha1$556fc658cd60a5504f673333a51469998eb149d5",
        "size": 404,
        "http://commonwl.org/cwltool#generation": 0
    },
    "file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/input_fasta": {
        "class": "File",
        "location": "file:///pgap/user_input/E_coli_seq1.fasta",
        "size": 67004,
        "basename": "E_coli_seq1.fasta",
        "nameroot": "E_coli_seq1",
        "nameext": ".fasta"
    },
    "file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/no_internet": null,
    "file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/taxon_db": {
        "class": "File",
        "location": "file:///pgap/input/uniColl_path/taxonomy.sqlite3",
        "basename": "taxonomy.sqlite3",
        "size": 1112997888,
        "nameroot": "taxonomy",
        "nameext": ".sqlite3"
    }
}
[2024-05-01 11:30:00] DEBUG [step pgapx_yaml_ctl] evaluated job input to {
    "file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/ignore_all_errors": true,
    "file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/input": {
        "location": "file:///tmp/6b_9y3_s/submol.json",
        "basename": "submol.json",
        "nameroot": "submol",
        "nameext": ".json",
        "class": "File",
        "checksum": "sha1$556fc658cd60a5504f673333a51469998eb149d5",
        "size": 404,
        "http://commonwl.org/cwltool#generation": 0
    },
    "file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/input_fasta": {
        "class": "File",
        "location": "file:///pgap/user_input/E_coli_seq1.fasta",
        "size": 67004,
        "basename": "E_coli_seq1.fasta",
        "nameroot": "E_coli_seq1",
        "nameext": ".fasta"
    },
    "file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/no_internet": null,
    "file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/taxon_db": {
        "class": "File",
        "location": "file:///pgap/input/uniColl_path/taxonomy.sqlite3",
        "basename": "taxonomy.sqlite3",
        "size": 1112997888,
        "nameroot": "taxonomy",
        "nameext": ".sqlite3"
    }
}
[2024-05-01 11:30:00] INFO [step pgapx_yaml_ctl] start
[2024-05-01 11:30:00] DEBUG [job pgapx_yaml_ctl] initializing from file:///pgap/pgap/progs/pgapx_yaml_ctl.cwl as part of step pgapx_yaml_ctl
[2024-05-01 11:30:00] DEBUG [job pgapx_yaml_ctl] {
    "ignore_all_errors": true,
    "input": {
        "location": "file:///tmp/6b_9y3_s/submol.json",
        "basename": "submol.json",
        "nameroot": "submol",
        "nameext": ".json",
        "class": "File",
        "checksum": "sha1$556fc658cd60a5504f673333a51469998eb149d5",
        "size": 404,
        "http://commonwl.org/cwltool#generation": 0
    },
    "input_fasta": {
        "class": "File",
        "location": "file:///pgap/user_input/E_coli_seq1.fasta",
        "size": 67004,
        "basename": "E_coli_seq1.fasta",
        "nameroot": "E_coli_seq1",
        "nameext": ".fasta"
    },
    "no_internet": null,
    "taxon_db": {
        "class": "File",
        "location": "file:///pgap/input/uniColl_path/taxonomy.sqlite3",
        "basename": "taxonomy.sqlite3",
        "size": 1112997888,
        "nameroot": "taxonomy",
        "nameext": ".sqlite3"
    },
    "ifmt": "JSON",
    "ofmt": "JSON",
    "output_annotation_name": "input.asn",
    "output_input_asn_type_name": "input_asn_type.txt",
    "output_ltp_name": "genome.ltp.txt",
    "output_taxid_name": "taxid.txt"
}
[2024-05-01 11:30:00] DEBUG [job pgapx_yaml_ctl] path mappings is {
    "file:///tmp/6b_9y3_s/submol.json": [
        "/tmp/6b_9y3_s/submol.json",
        "/tmp/ld3k632o/stg18850ff6-b66f-4136-9523-78cca2f8e426/submol.json",
        "File",
        true
    ],
    "file:///pgap/user_input/E_coli_seq1.fasta": [
        "/pgap/user_input/E_coli_seq1.fasta",
        "/tmp/ld3k632o/stgb125db4e-63e1-45c1-bd6d-7668dfd7fefe/E_coli_seq1.fasta",
        "File",
        true
    ],
    "file:///pgap/input/uniColl_path/taxonomy.sqlite3": [
        "/pgap/input/uniColl_path/taxonomy.sqlite3",
        "/tmp/ld3k632o/stg3d6ce5af-1fb1-43b6-900d-388b5eb499db/taxonomy.sqlite3",
        "File",
        true
    ]
}
[2024-05-01 11:30:00] DEBUG [job pgapx_yaml_ctl] command line bindings is [
    {
        "position": [
            -1000000,
            0
        ],
        "datum": "pgapx_yaml_ctl"
    },
    {
        "prefix": "-ifmt",
        "position": [
            0,
            "ifmt"
        ],
        "datum": "JSON"
    },
    {
        "prefix": "-ignore-all-errors",
        "position": [
            0,
            "ignore_all_errors"
        ],
        "datum": true
    },
    {
        "prefix": "-input",
        "position": [
            0,
            "input"
        ],
        "datum": {
            "location": "file:///tmp/6b_9y3_s/submol.json",
            "basename": "submol.json",
            "nameroot": "submol",
            "nameext": ".json",
            "class": "File",
            "checksum": "sha1$556fc658cd60a5504f673333a51469998eb149d5",
            "size": 404,
            "http://commonwl.org/cwltool#generation": 0,
            "path": "/tmp/ld3k632o/stg18850ff6-b66f-4136-9523-78cca2f8e426/submol.json",
            "dirname": "/tmp/ld3k632o/stg18850ff6-b66f-4136-9523-78cca2f8e426"
        }
    },
    {
        "prefix": "-input-fasta",
        "position": [
            0,
            "input_fasta"
        ],
        "datum": {
            "class": "File",
            "location": "file:///pgap/user_input/E_coli_seq1.fasta",
            "size": 67004,
            "basename": "E_coli_seq1.fasta",
            "nameroot": "E_coli_seq1",
            "nameext": ".fasta",
            "path": "/tmp/ld3k632o/stgb125db4e-63e1-45c1-bd6d-7668dfd7fefe/E_coli_seq1.fasta",
            "dirname": "/tmp/ld3k632o/stgb125db4e-63e1-45c1-bd6d-7668dfd7fefe"
        }
    },
    {
        "prefix": "-ofmt",
        "position": [
            0,
            "ofmt"
        ],
        "datum": "JSON"
    },
    {
        "prefix": "-output-annotation",
        "position": [
            0,
            "output_annotation_name"
        ],
        "datum": "input.asn"
    },
    {
        "prefix": "-output-asn-type",
        "position": [
            0,
            "output_input_asn_type_name"
        ],
        "datum": "input_asn_type.txt"
    },
    {
        "prefix": "-output-ltp",
        "position": [
            0,
            "output_ltp_name"
        ],
        "datum": "genome.ltp.txt"
    },
    {
        "prefix": "-output-taxid",
        "position": [
            0,
            "output_taxid_name"
        ],
        "datum": "taxid.txt"
    },
    {
        "prefix": "-taxon-db",
        "position": [
            0,
            "taxon_db"
        ],
        "datum": {
            "class": "File",
            "location": "file:///pgap/input/uniColl_path/taxonomy.sqlite3",
            "basename": "taxonomy.sqlite3",
            "size": 1112997888,
            "nameroot": "taxonomy",
            "nameext": ".sqlite3",
            "path": "/tmp/ld3k632o/stg3d6ce5af-1fb1-43b6-900d-388b5eb499db/taxonomy.sqlite3",
            "dirname": "/tmp/ld3k632o/stg3d6ce5af-1fb1-43b6-900d-388b5eb499db"
        }
    }
]
[2024-05-01 11:30:00] DEBUG [job pgapx_yaml_ctl] initial work dir {}
[2024-05-01 11:30:00] INFO [job pgapx_yaml_ctl] /tmp/sw3hmub6$ pgapx_yaml_ctl \
    -ifmt \
    JSON \
    -ignore-all-errors \
    -input \
    /tmp/ld3k632o/stg18850ff6-b66f-4136-9523-78cca2f8e426/submol.json \
    -input-fasta \
    /tmp/ld3k632o/stgb125db4e-63e1-45c1-bd6d-7668dfd7fefe/E_coli_seq1.fasta \
    -ofmt \
    JSON \
    -output-annotation \
    input.asn \
    -output-asn-type \
    input_asn_type.txt \
    -output-ltp \
    genome.ltp.txt \
    -output-taxid \
    taxid.txt \
    -taxon-db \
    /tmp/ld3k632o/stg3d6ce5af-1fb1-43b6-900d-388b5eb499db/taxonomy.sqlite3
ignoring failure of pgapx_yaml_input.GetFasta
terminate called after throwing an instance of 'ncbi::CException'
  what():  NCBI C++ Exception:
    Error: CWL(CException::eUnknown) "/export/home/gpipe/TeamCity/Agent3/work/427aceaa834ecbb6/ncbi_cxx/src/internal/gpipe/app/cloud/cwl/pgapx_yaml_ctl.cpp", line 251: CPgapxYamlCtlApplication::Run() --- Unknown organism Eschericahi coli
     Stack trace:
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2023-10-03.build7061/arch/x86_64/bin/pgapx_yaml_ctl :0  offset=0x0 addr=0x41a060
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2023-10-03.build7061/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent3/work/427aceaa834ecbb6/ncbi_cxx/src/corelib/ncbiapp.cpp:711 ncbi::CNcbiApplicationAPI::x_TryMain(ncbi::EAppDiagStream, char const*, int*, bool*) offset=0x0 addr=0x7fd8943a9132
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2023-10-03.build7061/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent3/work/427aceaa834ecbb6/ncbi_cxx/src/corelib/ncbiapp.cpp:1023 ncbi::CNcbiApplicationAPI::AppMain(int, char const* const*, char const* const*, ncbi::EAppDiagStream, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) offset=0x0 addr=0x7fd8943ac78c
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2023-10-03.build7061/arch/x86_64/bin/pgapx_yaml_ctl :0  offset=0x0 addr=0x40c7b9
      /usr/lib64/libc-2.17.so :0  offset=0x0 addr=0x7fd892dd5554
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2023-10-03.build7061/arch/x86_64/bin/pgapx_yaml_ctl :0  offset=0x0 addr=0x40c989
       :0  offset=0x0 addr=0xffffffffffffffff

Stack trace (most recent call last):
#12   Object "", at 0xffffffffffffffff, in
#11   Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2023-10-03.build7061/arch/x86_64/bin/pgapx_yaml_ctl", at 0x40c989, in _start
#10   Object "/usr/lib64/libc-2.17.so", at 0x7fd892dd5554, in __libc_start_main
#9    Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2023-10-03.build7061/arch/x86_64/bin/pgapx_yaml_ctl", at 0x40c7b9, in main
#8    Source "/export/home/gpipe/TeamCity/Agent3/work/427aceaa834ecbb6/ncbi_cxx/src/corelib/ncbiapp.cpp", line 1023, in AppMain [0x7fd8943ac78c]
#7    Source "/export/home/gpipe/TeamCity/Agent3/work/427aceaa834ecbb6/ncbi_cxx/src/corelib/ncbiapp.cpp", line 711, in x_TryMain [0x7fd8943a9132]
#6    Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2023-10-03.build7061/arch/x86_64/bin/pgapx_yaml_ctl", at 0x41a0c0, in CPgapxYamlCtlApplication::Run()
#5    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/eh_throw.cc", line 93, in __cxa_throw [0x7fd893957222]
#4    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/eh_terminate.cc", line 57, in terminate [0x7fd893956fe0]
#3    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/eh_terminate.cc", line 47, in __cxa_begin_catch [0x7fd893956f95]
#2    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/vterminate.cc", line 95, in __verbose_terminate_handler [0x7fd8939591a4]
#1    Object "/usr/lib64/libc-2.17.so", at 0x7fd892deaa77, in abort
#0    Object "/usr/lib64/libc-2.17.so", at 0x7fd892de9387, in raise
Aborted (Signal sent by tkill() 229 1000)
[2024-05-01 11:30:10] INFO [job pgapx_yaml_ctl] Max memory used: 35MiB
[2024-05-01 11:30:10] WARNING [job pgapx_yaml_ctl] was terminated by signal: SIGABRT
[2024-05-01 11:30:10] ERROR [job pgapx_yaml_ctl] Job error:
("Error collecting output for parameter 'input_asn_type': pgap/progs/pgapx_yaml_ctl.cwl:75:13: Did not find output file with glob pattern: ['input_asn_type.txt'].", {})
[2024-05-01 11:30:10] WARNING [job pgapx_yaml_ctl] completed permanentFail
[2024-05-01 11:30:10] DEBUG [job pgapx_yaml_ctl] outputs {}
[2024-05-01 11:30:10] ERROR [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/output_annotation
[2024-05-01 11:30:10] ERROR [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/output_ltp
[2024-05-01 11:30:10] ERROR [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/input_asn_type
[2024-05-01 11:30:10] ERROR [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/taxid
[2024-05-01 11:30:10] DEBUG [step pgapx_yaml_ctl] produced output {}
[2024-05-01 11:30:10] WARNING [step pgapx_yaml_ctl] completed permanentFail
[2024-05-01 11:30:10] DEBUG [job pgapx_yaml_ctl] Removing input staging directory /tmp/ld3k632o
[2024-05-01 11:30:10] DEBUG [job pgapx_yaml_ctl] Removing temporary directory /tmp/6bmhf4xg
[2024-05-01 11:30:10] INFO [workflow prepare_input_template] completed permanentFail
[2024-05-01 11:30:10] DEBUG [workflow prepare_input_template] outputs {
    "input_asn_type": null,
    "locus_tag_prefix": null,
    "output_entries": null,
    "output_seq_submit": null,
    "submol_block_json": {
        "location": "file:///tmp/6b_9y3_s/submol.json",
        "basename": "submol.json",
        "nameroot": "submol",
        "nameext": ".json",
        "class": "File",
        "checksum": "sha1$556fc658cd60a5504f673333a51469998eb149d5",
        "size": 404,
        "http://commonwl.org/cwltool#generation": 0
    },
    "taxid": null
}
[2024-05-01 11:30:10] DEBUG [step prepare_input_template] produced output {
    "file:///pgap/pgap/pgap.cwl#prepare_input_template/output_seq_submit": null,
    "file:///pgap/pgap/pgap.cwl#prepare_input_template/output_entries": null,
    "file:///pgap/pgap/pgap.cwl#prepare_input_template/locus_tag_prefix": null,
    "file:///pgap/pgap/pgap.cwl#prepare_input_template/submol_block_json": {
        "location": "file:///tmp/6b_9y3_s/submol.json",
        "basename": "submol.json",
        "nameroot": "submol",
        "nameext": ".json",
        "class": "File",
        "checksum": "sha1$556fc658cd60a5504f673333a51469998eb149d5",
        "size": 404,
        "http://commonwl.org/cwltool#generation": 0
    },
    "file:///pgap/pgap/pgap.cwl#prepare_input_template/taxid": null
}
[2024-05-01 11:30:10] WARNING [step prepare_input_template] completed permanentFail
[2024-05-01 11:30:10] INFO [workflow ] completed permanentFail
[2024-05-01 11:30:10] DEBUG [workflow ] outputs {
    "calls": {
        "location": "file:///tmp/8r895kud/calls.tab",
        "basename": "calls.tab",
        "nameroot": "calls",
        "nameext": ".tab",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "http://commonwl.org/cwltool#generation": 0
    },
    "cds_nucleotide_fasta": null,
    "cds_protein_fasta": null,
    "checkm_raw": null,
    "fastaval_errors": {
        "location": "file:///tmp/vfqc8wrk/fastaval.xml",
        "basename": "fastaval.xml",
        "nameroot": "fastaval",
        "nameext": ".xml",
        "class": "File",
        "checksum": "sha1$53b6a99a8edd78b64bd27eec6ebf928fa44f75d9",
        "size": 143,
        "http://commonwl.org/cwltool#generation": 0
    },
    "final_asndisc_error_diag": null,
    "final_asnval_error_diag": null,
    "gbk": null,
    "gff": null,
    "gff_enhanced": null,
    "initial_asndisc_error_diag": null,
    "initial_asnval_error_diag": null,
    "input_fasta": {
        "class": "File",
        "location": "file:///pgap/user_input/E_coli_seq1.fasta",
        "size": 67004,
        "basename": "E_coli_seq1.fasta",
        "nameroot": "E_coli_seq1",
        "nameext": ".fasta"
    },
    "input_submol": {
        "class": "File",
        "location": "file:///pgap/user_input/pgap_submol_yogpv0es.yaml",
        "size": 451,
        "basename": "pgap_submol_yogpv0es.yaml",
        "nameroot": "pgap_submol_yogpv0es",
        "nameext": ".yaml"
    },
    "nucleotide_fasta": null,
    "protein_fasta": null,
    "sqn": null
}
[2024-05-01 11:30:10] DEBUG Moving /tmp/8r895kud/calls.tab to /pgap/output/calls.tab
[2024-05-01 11:30:10] DEBUG Moving /tmp/vfqc8wrk/fastaval.xml to /pgap/output/fastaval.xml
[2024-05-01 11:30:10] DEBUG Copying /pgap/user_input/E_coli_seq1.fasta to /pgap/output/E_coli_seq1.fasta
[2024-05-01 11:30:10] DEBUG Copying /pgap/user_input/pgap_submol_yogpv0es.yaml to /pgap/output/pgap_submol_yogpv0es.yaml
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/xc0_bplj
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/ryuo8qxg
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/sw3hmub6
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/6b_9y3_s
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/6gwzbcxa
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/d7hzsw__
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/u25axrc4
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/v3r0astn
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/3vft0pt_
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/rkf4jecx
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/aghzpe_u
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/uzlmf87h
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/vfqc8wrk
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/uut_1wfy
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/c18hgbj1
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/oj3g7feb
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/8r895kud
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/evf773ja
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/oz6shcs3
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/xrpeum2u
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/zlwty7bm
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/whiy5gea
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/_ggjpkdq
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/5ztz53me
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/u7g0x5om
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/vge8di3q
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/5cx4w7nh
[2024-05-01 11:30:10] DEBUG Removing intermediate output directory /tmp/kho11b1a
{
    "calls": {
        "location": "file:///pgap/output/calls.tab",
        "basename": "calls.tab",
        "class": "File",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 0,
        "path": "/pgap/output/calls.tab"
    },
    "cds_nucleotide_fasta": null,
    "cds_protein_fasta": null,
    "checkm_raw": null,
    "fastaval_errors": {
        "location": "file:///pgap/output/fastaval.xml",
        "basename": "fastaval.xml",
        "class": "File",
        "checksum": "sha1$53b6a99a8edd78b64bd27eec6ebf928fa44f75d9",
        "size": 143,
        "path": "/pgap/output/fastaval.xml"
    },
    "final_asndisc_error_diag": null,
    "final_asnval_error_diag": null,
    "gbk": null,
    "gff": null,
    "gff_enhanced": null,
    "initial_asndisc_error_diag": null,
    "initial_asnval_error_diag": null,
    "input_fasta": {
        "class": "File",
        "location": "file:///pgap/output/E_coli_seq1.fasta",
        "size": 67004,
        "basename": "E_coli_seq1.fasta",
        "checksum": "sha1$198ce434adeef2a9749c164edb41e2ecf36d1c3e",
        "path": "/pgap/output/E_coli_seq1.fasta"
    },
    "input_submol": {
        "class": "File",
        "location": "file:///pgap/output/pgap_submol_yogpv0es.yaml",
        "size": 451,
        "basename": "pgap_submol_yogpv0es.yaml",
        "checksum": "sha1$078362e438bc4db768e2ba6fb4fc00b7a26f012a",
        "path": "/pgap/output/pgap_submol_yogpv0es.yaml"
    },
    "nucleotide_fasta": null,
    "protein_fasta": null,
    "sqn": null
}[2024-05-01 11:30:10] WARNING Final process status is permanentFail

**Comment by azat-badretdin** [comment]
Thank you for your report, user @namho4577 !

In the output `cwltool.log` you posted the most important is the first `permanentFail` message and preceding errors.

The key error here is: 

```
Unknown organism Eschericahi coli
```

There is a typo in genus name for `Escherichia`
