### ISSUE TITLE
Get_Proteins_app issues

### ISSUE THREAD

**Issue by asd1864714** [ncbi/pgap#303]
./pgap.py -n -o out_directory -g sequence.fasta -s Staphylococcus

[cwltool.log](https://github.com/ncbi/pgap/files/15212092/cwltool.log)

I don't know what the problem is anymore, the last version worked fine

**Comment by azat-badretdin** [comment]
Thank  you for your report, user @asd1864714 

Could you please provide `sequence.fasta`?

The error in `bacterial_prot_src`

```
Stack trace (most recent call last):
#9    Object "", at 0xffffffffffffffff, in 
#8    Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2024-04-27.build7426/arch/x86_64/bin/bacterial_prot_src", at 0x40812d, in _start
#7    Object "/usr/lib64/libc-2.28.so", at 0x7f25ff460d84, in __libc_start_main
#6    Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2024-04-27.build7426/arch/x86_64/bin/bacterial_prot_src", at 0x407f89, in main
#5    Source "/export/home/gpipe/TeamCity/Agent3/work/427aceaa834ecbb6/ncbi_cxx/src/corelib/ncbiapp.cpp", line 1024, in AppMain [0x7f2600f827ac]
#4    Source "/export/home/gpipe/TeamCity/Agent3/work/427aceaa834ecbb6/ncbi_cxx/src/corelib/ncbiapp.cpp", line 711, in x_TryMain [0x7f2600f7f0d2]
#3    Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2024-04-27.build7426/arch/x86_64/bin/bacterial_prot_src", at 0x40ef41, in CBacterialProtSrcApp::Run()
#2    Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2024-04-27.build7426/arch/x86_64/bin/bacterial_prot_src", at 0x40b970, in CBacterialProtSrcApp::GetProtInfInputSQLite(int, ncbi::CUnicollDumpAccess&, std::__cxx11::list<SDatabase_input, std::allocator<SDatabase_input> >&)
#1    Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2024-04-27.build7426/arch/x86_64/bin/bacterial_prot_src", at 0x409319, in 
#0    Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2024-04-27.build7426/arch/x86_64/bin/bacterial_prot_src", at 0x4128a4, in void ncbi::CDiagBuffer::Put<int>(ncbi::CNcbiDiag const&, int const&)
Segmentation fault (Address not mapped to object [0xfffffffffffffffc])

```
could you please provide the system characteristics as well? They are usually an output on top of `cwltool.log` but not this time.

Thanks.

**Comment by asd1864714** [comment]
I just downloaded a sequence at NCBI as a test, this is my system version：
Ubuntu 20.04.4 LTS
[sequence.zip](https://github.com/ncbi/pgap/files/15212272/sequence.zip)

**Comment by azat-badretdin** [comment]
Thanks. Ubuntu has been a tough nut for us historically, although we seem to be handling it better recently. 

But let me first try to reproduce this locally

**Comment by azat-badretdin** [comment]
I am getting closer to locating the source of error here.

Meanwhile, I recommend to use, as a workaround, the species name instead of just genus.

**Comment by asd1864714** [comment]
Ok thanks, I've tried using species names before but that didn't work either

**Comment by azat-badretdin** [comment]
It should work for this species:

````

$ sqlite3 taxonomy.sqlite3 " select count(*) from taxidinfo where taxid=3051183"
-- Loading resources from /home/badrazat/.sqliterc
count(*)
1

```
it is present in our taxonomy

**Comment by asd1864714** [comment]
Yes, it is Staphylococcus hsinchuensis. Sorry, I am not proficient in coding. I tried reinstalling docker, but the same problem still occurred. I will try to install it on the CentOS machine later.

**Comment by azat-badretdin** [comment]
Note that I reproduce failure with "species" parameter for your case, but the error happens later: when one of our control applications rejects input genome as too small.  In this case `--ignore-errors` helps

**Comment by azat-badretdin** [comment]
This species name was renamed after we prepared release on 4/28 (see the release version). You might have better luck with the old recognized name "Staphylococcus sp. H164"

**Comment by azat-badretdin** [comment]
> You might have better luck with the old recognized name "Staphylococcus sp. H164"

I verified locally that this solution works

**Comment by asd1864714** [comment]
Thanks for your patient answer, it's working fine now

**Comment by azat-badretdin** [comment]
Glad to hear that! We will keep the Issue open. The issue of `-s genus` not working remains.

**Comment by asd1864714** [comment]
Hello, I found that adding “sp.” after the genus can run normally. It may help you find the problem. For example：  ./pgap.py -n -o out_directory -g sequence.fasta -s "Frankia" is changed to  ./pgap.py -n -o out_directory -g sequence.fasta -s "Frankia sp."

**Comment by azat-badretdin** [comment]
Thank you for your help, user @asd1864714 ! We appreciate your input very much.

Yes, we located the code that caused this regression of functionality and we are working on fixing it soon.
