### ISSUE TITLE
Error: Final process status is permanentFail

### ISSUE THREAD

**Issue by sekhwal** [ncbi/pgap#305]
Hi,
I am following my previous issue #304, it has been closed. 

I am already using 'salmonella' in submol.yaml, but I am not able to get the results. When I change the genus_species as 'Escherichia coli' pgap keep running for so long with generating the results. 

topology: 'circular'
location: 'chromosome'
organism:
genus_species: 'salmonella'
strain: 'P1620800_chr'

**Comment by azat-badretdin** [comment]
1/ Salmonella is not "species", it's "genus"
2/ We lost the functionality of supporting "genus" option in this release and we are working on restoring it soon
3/ Case might be important (usually biologists always capitalize genus in binomials, so I am not familiar with this use case).

Please try 

    genus_species: 'Salmonella enterica'

or other legitimate Salmonella species.

**Comment by sekhwal** [comment]
Thank you for the information. 
It works, but when I run it with location: 'plasmid' it generates the same error "Final process status is permanentFail". 

Please let me know what change I should make in the submol.yaml file.
Here is the information of my current submol.yaml file that I am trying to run for plasmid genome.

topology: 'circular'
location: 'plasmids'
organism:
    genus_species: 'Salmonella enterica'
    strain: 'P1122481'

**Comment by sekhwal** [comment]
I tried the following way python3 /scripts/pgap.py -r -o P1122481_results -s 'Salmonella enterica' -g P1122481.fasta

I am using the fasta file with the header 
>1_length=4998493_depth=1.00x_circular=true_[location=chromosome] 

But still generating the issue ""Final process status is permanentFail".

**Comment by sekhwal** [comment]
In another way, I used correctly location: 'plasmid' in in the submol.yaml but it still unable to run.

topology: 'circular'
location: 'plasmid'
organism:
    genus_species: 'Salmonella enterica'
    strain: 'P1122481'

**Comment by thibaudnis** [comment]
> 1_length=4998493_depth=1.00x_circular=true_[location=chromosome]

Please review https://github.com/ncbi/pgap/wiki/Input-Files#Genome-assembly-sequence-file. There are several characters that are not allowed in this SeqID (the SeqID is everything before the first space). You can try SeqID of 1 and add modifiers:
`1 [topology=circular] [location=chromosome]`
Length and depth are not supported modifiers according to: https://www.ncbi.nlm.nih.gov/genbank/mods_fastadefline/

**Comment by azat-badretdin** [comment]
> But still generating the issue ""Final process status is permanentFail".

Could you please post the resulting `cwltool.log` file? Thanks!

**Comment by sekhwal** [comment]
It seems the header line is correct. And it is still showing an error "WARNING Final process status is permanentFail
" with plasmid sequence. However, it works with 'chromosome' even I did not change any in the header ">1 length=4998493 depth=1.00x circular=true".

##used command
python3 /scripts/pgap.py -r -o P1122481_plasmid input_P1122481_plasmid.yaml

##plasmid fasta file header
>contig001 [location = plasmid] [plasmid-name = pPSU1122481] [topology=circular]

##Here is the .yaml file
fasta:
    class: File
    location: P1122481_plasmid.fasta
submol:
    class: File
    location: P1122481_plasmid1_submol.yaml

##
[cwltool.log](https://github.com/ncbi/pgap/files/15264691/cwltool.log)
topology: 'circular'
location: 'plasmid'
organism:
    genus_species: 'Salmonella enterica'
    strain: 'pPSU1122481'

**Comment by sekhwal** [comment]
It seems, it does not work with small genomes like plasmid.

**Comment by azat-badretdin** [comment]
Try `./pgap.py --ignore-errors ....`

**Comment by sekhwal** [comment]
It works when I use both chromosome and plasmid in one fasta file. I think the latest pgap version has issue of having small genome like plasmid. 
##command
python3 /scripts/pgap.py -r -o P2226300_results input_P2226300.yaml
Thank you for your help!

**Comment by vappiah** [comment]
@azat-badretdin I have a similar issue. Please find attached my cwtool.log file
[cwltool.log](https://github.com/ncbi/pgap/files/15299552/cwltool.log)

**Comment by azat-badretdin** [comment]
User @vappiah I am not so sure. It says

```
'contig001[location=chromosome]' is not a valid local ID (m_Pos = 1)

```
which most likely means that you omitted quite crucial space delimiter separating seq-id from the rest of FASTA definition line

It's a different error from the same ballpark "things that users do in FASTA definition line"

**Comment by vappiah** [comment]
Thanks @azat-badretdin . I made the necessary correction and it works now.
