### ISSUE TITLE
PGAP for multiple users

### ISSUE THREAD

**Issue by vappiah** [ncbi/pgap#307]
Hi Developers,
I realized when using PGAP, all the necessary files are created in my $HOME/.pgap  .  Is it possible to create this in a directory where multiple users have access? . This will avoid duplicate downloads.

Please advice.

**Comment by azat-badretdin** [comment]
Thank you for your report, user @vappiah ! 

Indeed, we do provide a mechanism for this. 

`$HOME/.pgap` is a default location for PGAP reference data storage, but it can be modified as it is specified in [Quick Notes](https://github.com/ncbi/pgap/wiki/Quick-Start):

> By default it will install in `$HOME/.pgap`, but this location can be changed by setting environmental variable PGAP_INPUT_DIR.

**Comment by azat-badretdin** [comment]
You can organize a location shared by more than user, adjust permissions to it and point the aforementioned envar to this location before installing `pgap.py`
