### ISSUE TITLE
[BUG] PGAP fails on test genome when PGAP_INPUT_DIR set to other than default

### ISSUE THREAD

**Issue by mdziurzynski** [ncbi/pgap#310]
Hi!

I want to run the PGAP pipeline on my bacterial genome, however the pipeline crashes on the test genome.

I installed the pipeline just as described in the Quick Start in the wiki. The only thing I made different was that I changed the default installation path (I added PGAP_INPUT_DIR variable to my bashrc with appropriate path).  The guide mentions that after installation, its a good idea to run the pipeline on the Mycoplasmoides genitalium genome provided with the installation. Unfortunately the PGAP run ends in 30 seconds with an error.
I tried reinstalling and re-updating but it did not help.

### Update
I reinstalled the pipeline in its default location and now **it works**. However I decided to leave the issue here as there seems to be an issue with directories mounting when the default PGAP installation location is changed.

Below I attach the cwl log.

[cwltool.log](https://github.com/user-attachments/files/15810750/cwltool.log)

**Env**
 - OS: Ubuntu 22.04.3 LTS
 - pgap.py 2024-04-27.build7426
 - Docker version 24.0.5, build ced0996

**Log Files**
The only files in tmp-outdir:
[ncbiapp.log](https://github.com/user-attachments/files/15810791/ncbiapp.log)
[fastaval.xml.txt](https://github.com/user-attachments/files/15810792/fastaval.xml.txt)

**Comment by azat-badretdin** [comment]
Thank you for your report, user @mdziurzynski 

Upon examination of the `cwltool.log` file I concluded that somehow part of reference data is missing. I would recommend to repeat the installation step in Quick Start after cleanup in your .pgap directory as recommended and try again.

**Comment by azat-badretdin** [comment]
Did you manage to try to reinstall PGAP and run it successfully?

**Comment by mdziurzynski** [comment]
Yes, I had to install PGAP without changing the default PGAP_INPUT_DIR. Then it worked.

But just for the reference - I reinstalled multiple times (and redownloaded the data) with different PGAP_INPUT_DIR vars, and it did not work even once.
