### ISSUE TITLE
Species_Requirement_option

### ISSUE THREAD

**Issue by cristoyerenahs** [ncbi/pgap#311]
Genus option requirement

I want to use pgap for structurally annotation. I want to annotate 2,000 genomes from Actinomyces. I have a mixture of species in my file.

Using the -s organism option, I tried only with -s "Actinomyces" (Genus), but I get the error message: "Fall to complete".

The documentation shows the possibility to use only the Genus, but it is false. In order to complete the job, you must complete with Genus and Species.

Could you help me or assistant with that problem?

**Comment by george-coulouris** [comment]
We will soon release an update that will restore the genus-only functionality.

In the interim, you can specify
`--use-version=2023-10-03.build7061`
to use the previous release.
