### ISSUE TITLE
[BUG] Failing to run some sequences

### ISSUE THREAD

**Issue by jmemrava** [ncbi/pgap#312]
I installed PGAP and am running it with the following command. However, I'm encountering issues where the output result files are not generated but specifically for certain sequences.

##running
/opt/Software/pgap.py -r -g ERR4920664.fasta -s 'Pseudescherichia vulneris' -o ERR4920664 --cpus 15

##cwltool.log file
[cwltool.log](https://github.com/user-attachments/files/16069345/cwltool.log)

**Comment by azat-badretdin** [comment]
Thank you for you report, user @jmemrava !

Please have a look at file `calls.tab` you have some contamination in your assembly. You can overcome this by running with `--ignore-all-errors` flag.

**Comment by jmemrava** [comment]
Thanks @azat-badretdin ! I used the --ignore-all-errors flag and it works now.
