### ISSUE TITLE
[BUG] FATAL: "cwltool": executable file not found in $PATH in 2024-04-27.build7426 

### ISSUE THREAD

**Issue by komais** [ncbi/pgap#313]
**Describe the bug**
2024-04-27.build7426  did not contain cwltools in PATH 
**To Reproduce**
singularity exec --pwd /pgap --bind $CWD/input-$DATE.$BUILD:/pgap/input:ro  /work/share/acuhtwkcu9/liutao/sif/sif/microbiom/pgap/pagp.sif which cwltool

/usr/bin/which: no cwltool in (/root/venv/bin/:/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2024-04-27.build7426/arch/x86_64/bin:/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/current/third-party/arch/x86_64/bin:/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/third-party/bin:/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/third-party/hmmer/bin:/usr/local/prodigal/2.6.3/bin:/usr/local/pplacer/1.1a18/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)

**Comment by azat-badretdin** [comment]
Thank you for your report, user @komais 

Could you please post the original command line that was failing?

**Comment by azat-badretdin** [comment]
Also: could you please try most recent version we released?

**Comment by azat-badretdin** [comment]
I verified that we do not have this problem with current release:

```

$ time singularity build pgap-prod.2024-07-18.cif docker://ncbi/pgap-prod:2024-07-18.build7555
real    6m56.993s
user    21m20.905s
sys     0m23.923s

$ singularity exec pgap-prod.2024-07-18.cif which cwltool
/root/venv/bin/cwltool

```

**Comment by komais** [comment]
thank you very much , i try to use  most recent version
