### ISSUE TITLE
PGAP failed on metatranscriptome data

### ISSUE THREAD

**Issue by asifratul** [ncbi/pgap#318]
HI, 

I have some transcriptome data. I have mapped the reads to target bacteria (Wolbachia), and conducted spades assembly (rna-mode) from the mapped reads. Now, I want to annotate the assembly using pgap. I ran the programme using example fasta and it ran successfully. But when I tried to run it on my assembly file, it is failing continuously.

I am using following code -- 
pgap.py -r -o mrna123 -g mRNA_transcripts_Raw_Wolbachia_filtered.fasta -s 'Wolbachia' --ignore-all-errors

and getting following error --
[slurm-58467467.out.txt](https://github.com/user-attachments/files/16871523/slurm-58467467.out.txt)

**Software versions (please complete the following information):**
Linux HPC. 
PGAP version 2024-07-18.build7555

**Comment by azat-badretdin** [comment]
Thank you for reporting this, Asif!

The strategy of finding the errors in failed PGAP runs is to look for the first occurrence of "permanentFail" word in the file and what comes before it.

In this case the log says

```

[2024-09-04 23:32:22] INFO [job Prepare_Seq_entries] /tmp/fwr6b1ro$ prepare_seq_entry_input \
    -nogenbank \
    -ifmt \
    seq-submit \
    -input \
    /tmp/vvmz3pvz/stgca65f1bf-cc72-494c-8ad9-59924fd727cd/cleaned_input.asn \
    -order \
    order.seqids \
    -output \
    entries.asn \
    -pathogen-mode \
    -submit-block \
    submit_block_template.asn \
    -t
Reading input
Validating
Genome size 5.48508e+07 exceeds maximum genome size 3e+07
Writing entries
Writing original order of seqids
Creating submit block output
  Writing submit block
Done.
terminate called after throwing an instance of 'ncbi::CException'
  what():  NCBI C++ Exception:

```

As you can see there is a part that says that your assembly is a little bit larger than typical assembly size for Wolbachia genus.

For this cases we have an option for a user to run pgap as `./pgap.py --ignore-all-errors .....` 

Could you please try that?
