### ISSUE TITLE
Cannot find "genus_species" on NCBI Taxonomy

### ISSUE THREAD

**Issue by nzx9581** [ncbi/pgap#32]
Hello,

I want to annotate the genome of Wolbachia from Spodoptera picta. But I can't find any information about it on NCBI Taxomomy. Does this mean that this organism has not yet been registered? If so, what should I do next?

Thanks a lot for your help,
Zhixin Niu

**Comment by azat-badretdin** [comment]
>Does this mean that this organism has not yet been registered? 

It is possible, yes. 

> If so, what should I do next?

I suggest consulting NCBI Help Desk on https://www.ncbi.nlm.nih.gov/home/about/contact/ (see a link to NCBI Helpdesk Web Form.
