### ISSUE TITLE
[BUG] Installation fails

### ISSUE THREAD

**Issue by mau-olvera** [ncbi/pgap#324]
**Describe the bug**
i want to install the latest version of pgap in my popOS computer, so i use `./pgap.py --update` to download the database . The download progress worked well. However, when the download progress reaches 100% fails.
so, I looked in the issues and found the `./pgap.py --update &>a.log` and the error still occurs.

**Software versions (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS
 - The latest version of PGAP is 2024-07-18.build7555
 - Docker version 24.0.7, build 24.0.7-0ubuntu2~22.04.1

**Log Files**
[pgap_error.tar.gz](https://github.com/user-attachments/files/17233049/pgap_error.tar.gz)

**Additional context**
I have already tried deleting the entire downloaded databaseand downloading again, but the same error still occurs.

**Comment by azat-badretdin** [comment]
Thank you for your report, Mauricio!

it seems that you have some kind of problem with your Docker setup:

```
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=ncbi%2Fpgap&tag=2024-07-18.
build7555": dial unix /var/run/docker.sock: connect: permission denied

```

I would recommend to seek assistance from your local docker experts.

**Comment by mau-olvera** [comment]
I managed to install it using the superuser, however, I found that the gibibytes on my computer are not enough to use the program, but thank you very much for taking my issue.

**Comment by azat-badretdin** [comment]
Glad to here you have achieved that you wanted using superuser privileges, Mauricio! 

You are very welcome!
