### ISSUE TITLE
Is pgap "phoning home" without permission?

### ISSUE THREAD

**Issue by tseemann** [ncbi/pgap#325]
It was recently suggested that PGAP was "phoning home" to NCBI without the user knowing.

https://github.com/ncbi/pgap/blob/4ffbad9ffeab15ec8af5f6f91bd352ef96d1ef77/assemble.cwl#L29C1-L41C39

Can you clarify if this is the case?

It involves this script:
https://github.com/ncbi/osiris/blob/2ab5f25a2538b32b67cf1cc2a00189e2c196510d/osiris/nwx/pinger.sh

Any help appreciated!

**Comment by azat-badretdin** [comment]
... and that is the role of the script you found (pinger.sh), Torsten.

**Comment by azat-badretdin** [comment]
> the role of the script you found 

I was wrong, I did not read carefully and I thought you are pointing to our version of pinger.sh, Torsten.

"Our" pinger.sh could be found inside container by running `docker run <image:version> find / -name pinger.sh` 

That is what we call from `pgap.py` via docker call.
