### ISSUE TITLE
Fastaval error

### ISSUE THREAD

**Issue by alexandrakahn** [ncbi/pgap#35]
Hello, I'm having this error when trying to annotate one of my proprietary genomes. Do you have any idea how to fix it or any suggestions? 
Thanks! 

[2019-08-28 23:33:48] INFO /usr/bin/cwltool 1.0.20190815141648
[2019-08-28 23:33:48] INFO Resolved 'pgap.cwl' to 'file:///pgap/pgap.cwl'
[2019-08-28 23:35:24] INFO [workflow ] start
[2019-08-28 23:35:24] INFO [workflow ] starting step fastaval
[2019-08-28 23:35:24] INFO [step fastaval] start
[2019-08-28 23:35:24] INFO [job fastaval] /tmp/2qpjr8im$ fastaval.sh \
    -check_internal_ns \
    -check_min_seqlen \
    200 \
    -in \
    /tmp/tmpqswdwhd2/stgadd6f7f3-7028-4733-b8b2-df74b381cfa2/XF73.fna \
    -out \
    fastaval.xml
+ POSITIONAL=()
+ [[ 7 -gt 0 ]]
+ key=-check_internal_ns
+ ignore_all_errors=false
+ case "$key" in
+ POSITIONAL+=("$key")
+ shift
+ [[ 6 -gt 0 ]]
+ key=-check_min_seqlen
+ ignore_all_errors=false
+ case "$key" in
+ POSITIONAL+=("$key")
+ shift
+ [[ 5 -gt 0 ]]
+ key=200
+ ignore_all_errors=false
+ case "$key" in
+ POSITIONAL+=("$key")
+ shift
+ [[ 4 -gt 0 ]]
+ key=-in
+ ignore_all_errors=false
+ case "$key" in
+ POSITIONAL+=("$key")
+ shift
+ [[ 3 -gt 0 ]]
+ key=/tmp/tmpqswdwhd2/stgadd6f7f3-7028-4733-b8b2-df74b381cfa2/XF73.fna
+ ignore_all_errors=false
+ case "$key" in
+ POSITIONAL+=("$key")
+ shift
+ [[ 2 -gt 0 ]]
+ key=-out
+ ignore_all_errors=false
+ case "$key" in
+ POSITIONAL+=("$key")
+ shift
+ [[ 1 -gt 0 ]]
+ key=fastaval.xml
+ ignore_all_errors=false
+ case "$key" in
+ POSITIONAL+=("$key")
+ shift
+ [[ 0 -gt 0 ]]
+ set -- -check_internal_ns -check_min_seqlen 200 -in /tmp/tmpqswdwhd2/stgadd6f7f3-7028-4733-b8b2-df74b381cfa2/XF73.fna -out fastaval.xml
+ set +e
+ fastaval -check_internal_ns -check_min_seqlen 200 -in /tmp/tmpqswdwhd2/stgadd6f7f3-7028-4733-b8b2-df74b381cfa2/XF73.fna -out fastaval.xml
+ result=255
+ set -e
+ false
+ exit 255
[2019-08-28 23:35:24] WARNING [job fastaval] completed permanentFail
[2019-08-28 23:35:24] WARNING [step fastaval] completed permanentFail
[2019-08-28 23:35:24] INFO [workflow ] completed permanentFail
[2019-08-28 23:35:24] WARNING Final process status is permanentFail
{
    "gbk": null,
    "gff": null,
    "input_fasta": {
        "class": "File",
        "location": "file:///pgap/output/XF73.fna",
        "size": 2629651,
        "basename": "XF73.fna",
        "checksum": "sha1$dac78d9a49bdf5d4c30f298993809f44e0aa1976",
        "path": "/pgap/output/XF73.fna"
    },
    "input_submol": {
        "class": "File",
        "location": "file:///pgap/output/submol.yaml",
        "size": 646,
        "basename": "submol.yaml",
        "checksum": "sha1$f8a018f47657f575632f81e5ab0786e3087492a5",
        "path": "/pgap/output/submol.yaml"
    },
    "nucleotide_fasta": null,
    "protein_fasta": null,
    "sqn": null
}

**Comment by azat-badretdin** [comment]
Thank you for your report. Someone will look at this today. 

Meanwhile: what kind of input sequence are you submitting? Does it have a lot of Ns? One of the things that fastaval checks is length of the contig sequence and amount of Ns in the sequence....

**Comment by azat-badretdin** [comment]
Update: our experts on `fastaval` gave me the list of things that `fastaval` checks. It is not complete, but it might be helpful to identify what went wrong with your FASTA input:

- seq-ids must be unique
- err if seq has no seq-ids
- err if seq has no residues
- defline source modifier checks (e.g. warning for bad mods or good mods given bad values)
- hyphens are ignored but give warning
- max seq-id length of 50
- error if no seqs in input at all
- bad residues
- warn for multiple primer sets

**Comment by alexandrakahn** [comment]
Is a de novo assembly done with SPAdes. There are 251 contigs of length > 200bp, no Ns in the assembly.

**Comment by azat-badretdin** [comment]
Thanks for checking! What does `fastaval.xml` say?

**Comment by alexandrakahn** [comment]
There is not fastaval.xml output file. The only outputs are cwltool.log, submol.yaml, and the input fasta file.
From the list: all seq-ids (>) are unique and present
                      all of seq-ids have associated residues
                      all sequence ids are length of 35
                      there are no hyphens on the file
                      there does not seem to be any ambiguous residues
                      primers and adapters were previously removed via cutadap
                      not sure how to check for the mods

There are contigs of this form: 
>contig22_lenght222
ctggcgttggcgctgttgtggttgtggatgtcggtatggccaatgctgtgggtggagaaggcttggagtgcctgcggagcggtgctggtgagggcgccgccgttaaattggctatggccgccaacggtgatgtcatagccaccggcaccggcaaataggccgctttggttgcggacgctggcgtagtcttgggtggcgtcttggcggttgcggctgaaggtg

Could that be it?

**Comment by azat-badretdin** [comment]
Is there `>` before `contig22_lenght222` in your input FASTA file?

**Comment by alexandrakahn** [comment]
Yes it just auto formatted in github

**Comment by azat-badretdin** [comment]
>  Yes it just auto formatted in github

I concocted a FASTA file from your seequence snippet: 

```
>contig22_lenght222
ctggcgttggcgctgttgtggttgtggatgtcggtatggccaatgctgtgggtggagaaggcttggagtgcctgcggagcggtgctggtgagggcgccgccgttaaattggctatggccgccaacggtgatgtcatagccaccggcaccggcaaataggccgctttggttgcggacgctggcgtagtcttgggtggcgtcttggcggttgcggctgaaggtg
```

it was processed just fine, with exit code 0, leaving only a message of severity `INFO`

```
$ ~/gpipe-arch-bin/fastaval -in user.1.fasta -check_internal_ns  -check_min_seqlen 200
<?xml version="1.0"?>
<fastaval>
  <message tool="fastaval" severity="INFO" seq_id="contig22_lenght222" fasta_seq_id="lcl|contig22_lenght222" length="222"/>
</fastaval>
```
I am quite puzzled at the absence of `fastaval.xml` under your current directory (actually subdirectories)

I am guessing you tried already to find the file:

```

find . -name fastaval.xml

```
and it was not there...

Could you please post the output of command 

```
docker image ls | grep ncbi

```

**Comment by alexandrakahn** [comment]
I think my coworker is on track to figuring it out! We'll be in touch with any more issues, thank you.

**Comment by azat-badretdin** [comment]
You are welcome! Your issues help us to improve our software. Thank you!
