### ISSUE TITLE
Docker permissions after update

### ISSUE THREAD

**Issue by nclaesnacw** [ncbi/pgap#36]
Installed pgap using the instructions on the wiki
on ubuntu 16.04 with Docker installed
Ran on local genome - brilliant
Came back  a few days later to run and pgap said not upto date and updated
Now into Docker permissions quagmire (added user to docker group with no effect)
running pgap.py exits from Docker with rc=1 (permission denied)
running sudo pgap.py exits with rc=126  
(fails to read pgap_input,yaml - no fasta. The pgap_input,yaml file gets corrupted with all lines but 1 deleted)
Would like to remove Docker and pgap and start again but looks like nightmare
Looks like have to back up data and re-install Ubuntu!!!!
Thanks for any help

**Comment by nclaesnacw** [comment]
p.s 
Docker hello-world runs fine from user, so although the rc=1 error seems to come from docker I think the issue is with my pgap.py
alan@alan-HP-ZBook-15-G2:~$ docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.
......

**Comment by nclaesnacw** [comment]
Resolved
Sorry. I saved my reference copy of input.yaml as pgap_input.yaml
When I re-ran after the update I edited my reference copy (pgap_input.yaml) and saved it as my input yaml file but I kept the name and ran
$ ./pgap.py -o annot pgap_input.yaml
which I guess conflicts with pgap.py 's internal handling
$ ./pgap.py -o annot input.yaml
runs fine!

**Comment by slottad** [comment]
Hmm, yes, it is an obvious name, and a conflict was sure to arise. We'll have to fix that so other don't fall into that trap.

Thanks for letting us know about the problem!
