### ISSUE TITLE
Failed to run the script Error: (302.26)

### ISSUE THREAD

**Issue by Vladislav-Shevtsov** [ncbi/pgap#37]
Dear All,
I have an issue to run the script: `sudo ./pgap.py -r -o ~/Desktop/P-mult-10_results-test3 P-mult-10-test-1-input.yaml` 
An error occured in step called `[job Prepare_Unannotated_Sequences_asnvalidate]`.
Also we could see following errors:
`Error: (302.26) SSOCK#13000[5]@130.14.29.110:443: [SOCK::Connect]  Failed pending connect(): Timeout[10.000000]
Error: (303.7) [URL_Connect; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=TaxService4&address=7deed985b88c(172.17.0.2)&platform=x86_64-unknown-linux-gnu]  Failed to connect: Timeout[10.000000]`

At the end of the run it creates 3 files: .fasta file, .yaml file and log file. Please help to solve the issue or run the script correctly. Thank you!

P.S. Log file is attached.
[cwltool.log](https://github.com/ncbi/pgap/files/3646415/cwltool.log)

**Comment by azat-badretdin** [comment]
This could be related to the docker issue we discovered recently: sometimes docker instances lose connection to the Internet because ipv4 forwarding is not explicitly set. Do you have something like `WARNING: IPv4 forwarding is disabled. Networking will not work.` in your output as well?

**Comment by Vladislav-Shevtsov** [comment]
It correctly works on test genome (MG37), but failed on our assemblies and NCBI complete genomes.

**Comment by Vladislav-Shevtsov** [comment]
We do not have the warning: `WARNING: IPv4 forwarding is disabled. Networking will not work.`

**Comment by azat-badretdin** [comment]
Could be something else then. 

> It correctly works on test genome (MG37), but failed on our assemblies and NCBI complete genomes

Is it reproducible or happened only once for each genome so far?

**Comment by Vladislav-Shevtsov** [comment]
It's happening regularly with all genomes we try to work with. But test genome file works fine.

**Comment by azat-badretdin** [comment]
I just got a chance to have a look at the `cwtool.log` you have posted (thank you very much, very thoughtful of you). 

It looks like in this particular case Error messages you are quoting are red herrings: the step(s) that have them actually `completed success`. 

What was a real problem here is that step `Prepare_Unannotated_Sequences_asnvalidate_evaluate` discovered that our standard validation produced a fatal level diagnostics:

```
<?xml version="1.0" encoding="UTF-8"?>
<message severity="ERROR" seq-id="lcl|Razi_Pm0001" code="SEQ_DESCR_DBLinkBadSRAaccession">Bad Sequence Read Archive format - not</message>
```
Does your `input.yaml` file have by any chance `locus_tag_prefix` set to `Razi_Pm`? 

Meanwhile, I am going to investigate further what exactly might have caused this diagnostics.

**Comment by azat-badretdin** [comment]
Wait, I just noticed `not` in `Bad Sequence Read Archive format - not` message. 

It looks like you intended to use a dummy SRA number. Note that this field is optional and you do not have to include it in your input `submol.yaml` files. 

Please let me know how this works for you. Thanks!

**Comment by Vladislav-Shevtsov** [comment]
Azat thank you so much, you are right, we put a random name in bioproject and biosample fields (because in .yaml test file we noticed not real number for bioproject and biosample ) Do we need to leave them these fields empty? 

We did not fined any SRA field in submol.yaml file

**Comment by azat-badretdin** [comment]
biosample and bioproject fields are indeed optional as indicated here:

https://github.com/ncbi/pgap/wiki/Input-Files

``` bioproject - optional. BioProject ID (PRJXX) for the project, if available
biosample - optional. BioSample ID (SAMXXX) for the sequenced sample, if available
```

There is still something strange: you said that you haven't used an `sra:` field in your input `submol.yaml` files, but the diagnostics mentions specifically SRA: 

```
SEQ_DESCR_DBLinkBadSRAaccession
```
I would suggest to double check if you do not have `sra:` fields in the input `submol.yaml` files  and in case if omitting biosample and bioproject fields still does not help and you get the same diagnostics in your `cwltool.log`, please run `pgap.py` with adding `--debug` option. This will keep intermediate files for further analysis and we would like to see in this case what `sequences.text.asn` (`find . -name sequences.text.asn`) has for BioSample, BioProject or Sequence Read Archive fields in user objects.

**Comment by Vladislav-Shevtsov** [comment]
Dear Azat,
Thank you very much! Everything is working just fine, we left bioproject and biosample fields empty and looks like it works.

**Comment by azat-badretdin** [comment]
You are welcome, Vlad! If you are not aware, now you can submit the results of your calculations to GenBank directly, and it will bypass internal PGAP calculation.
