### ISSUE TITLE
problem about format input files

### ISSUE THREAD

**Issue by Xiaolan89** [ncbi/pgap#40]
Hi,

I tried to use PGAP-1.2.1 based on my metagenome-assemble bins, but error occurred.
I got ffn and faa files from Prokka annotation, then got ptt file from gbk file from Prokka using gb2ptt.pl script. After putting them in one folder, I tried to format them using Converter_draft.pl, but the output .nuc file was empty and message showed in terminal:

Argument ">k_01851" isn't numeric in sort at converter_draft.pl line 237, <F> line 27187.
Argument ">k_01852" isn't numeric in sort at converter_draft.pl line 237, <F> line 27196.
Argument ">k_01853" isn't numeric in sort at converter_draft.pl line 237, <F> line 27203.
Argument ">k_01854" isn't numeric in sort at converter_draft.pl line 237, <F> line 27214.
Argument ">k_01855" isn't numeric in sort at converter_draft.pl line 237, <F> line 27219.
Argument ">k_01856" isn't numeric in sort at converter_draft.pl line 237, <F> line 27226.
Argument ">k_01857" isn't numeric in sort at converter_draft.pl line 237, <F> line 27239.
Argument ">k_01858" isn't numeric in sort at converter_draft.pl line 237, <F> line 27249.
Argument ">k_01859" isn't numeric in sort at converter_draft.pl line 237, <F> line 27270.
Argument ">k_01860" isn't numeric in sort at converter_draft.pl line 237, <F> line 27276.

Could you please help me with it? Did I use the wrong .pl or all these format .pl only suitable for NCBI files?
By the way, I also tried to apply my data on PGAweb Analyze server, but it seemed like stuck forever once I clicked submit.

Thanks in advance!

**Comment by azat-badretdin** [comment]
Looks like this is a Prokka issue.
