### ISSUE TITLE
docker exited with rc = 0 when run test

### ISSUE THREAD

**Issue by fetyj** [ncbi/pgap#41]
Hello, 
I've just finished installing the new release of PGAP, when running test it gives me this message `docker exited with rc = 0` , here is my command and the log file `./pgap.py -r -o mg37_results test_genomes/MG37/input.yaml -c 16 -m 60g -d`
Thanks for your help,

Fety
[cwltool.log](https://github.com/ncbi/pgap/files/3749713/cwltool.log)

**Comment by azat-badretdin** [comment]
What is manifestation of the problem here? The log file indicates normal completion. Do you see output files in the output/ directory?

**Comment by fetyj** [comment]
yes there are output files but in the .fna file there are 588363 bp and the .gbk only 580076 bp ...

**Comment by azat-badretdin** [comment]
Yes, that is expected. Judging by your command line, you are running a test for Micoplasma genitalia - s small genome chosen as a test in our documentation for its small size: 0.5Mb.

**Comment by fetyj** [comment]
Ok, thanks for clarifying!! I'll start some personal data and let you now if everything is ok.

**Comment by azat-badretdin** [comment]
Thanks for checking!

**Comment by fetyj** [comment]
done some analysis and everything is ok :)

**Comment by azat-badretdin** [comment]
Glad to hear that. Happy landings!
