### ISSUE TITLE
ignore-all-errors doesn't seem to ignore all errors

### ISSUE THREAD

**Issue by rfcohen** [ncbi/pgap#49]
I working with a small sequence, ~50kb, and there's no real reference genome.  The pipeline fails when trying to look up the taxonomy information despite setting ignore-all-errors.

` ./pgap.py -r --ignore-all-errors -o outDir test_genomes/sample/input.yaml
`
Here are the lines from the cwltool.log showing that ignore_all_errors is not set:

```
.
.
.
[2019-11-20 16:39:32] INFO [job fastaval] /tmp/9i4l4fg2$ fastaval.sh \
    -check_internal_ns \
    -check_min_seqlen \
    200 \
    -ignore_all_errors \
    -in \
    /tmp/tmpra2z6qx_/stg2f8f5550-4f51-4837-ba13-62c85fba5f8e/sample.fsa \
    -out \
    fastaval.xml
+ POSITIONAL=()
+ ignore_all_errors=false
+ [[ 8 -gt 0 ]]
+ key=-check_internal_ns
+ case "$key" in
+ POSITIONAL+=("$key")
.
.
.
```

And here's the snippet from the cwltool.log where the genus species look up fails:
```
.
.
.
Error: (106.16) Application's execution failed (CException::eUnknown) Unknown organism sample genome
[2019-11-20 16:40:32] INFO [job pgapx_yaml_ctl] Max memory used: 31MiB
[2019-11-20 16:40:32] ERROR [job pgapx_yaml_ctl] Job error:
("Error collecting output for parameter 'input_asn_type':\nprogs/pgapx_yaml_ctl.cwl:75:13: Did not find output file with glob pattern: '['input_asn_type.txt']'", {})
[2019-11-20 16:40:32] WARNING [job pgapx_yaml_ctl] completed permanentFail
[2019-11-20 16:40:32] ERROR [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/output_annotation
[2019-11-20 16:40:32] ERROR [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/output_ltp
[2019-11-20 16:40:32] ERROR [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/input_asn_type
.
.
.
```

**Comment by thibaudnis** [comment]
Thanks for the report!
Are you providing the genus species on input (in the yaml file)? If yes, is the genus species known to NCBI taxonomy? It needs to be, even with the ignore-all-errors flag.

**Comment by rfcohen** [comment]
I am not providing the genus species.  What if I was providing genus/species and it wasn’t known to NCBI Taxonomy, what would be the remedy?  And, it appears that ignore-all-errors doesn’t really mean all.  Further, it appears that that setting the flag defaults to false…

-Rob

**Comment by thibaudnis** [comment]
The pipeline uses the genus species to determine the set of reference proteins to use. Since there is no reference for your organism of interest, as a work-around you could provide any other genus species known to NCBI.
'ignore_all_errors=false' in the log is a bit odd. However I just confirmed that the behavior of the flag is correct, on an input with some all N sequences.

**Comment by rfcohen** [comment]
Thanks.  Will give it a try and let you know.

-Rob

**Comment by thibaudnis** [comment]
Did you try running with an arbitrary genus species? How did it go?
With regards to 'ignore_all_errors=false' in the log. Apparently, cwltool prints out the default options in the log first. If you look further down the log you should see the actual chosen parameter values, including 'ignore_all_errors=true.

**Comment by rfcohen** [comment]
It successfully ran with an arbitrary genus/species.  However, the transl-table selected was incorrect.  My hypothesis is to use a genus/species who’s transl-table is the one I want hoping the pipeline will honor that.  I’ve not had time to try it though.

Thanks for checking.

-Rob

**Comment by thibaudnis** [comment]
One last thing: if you know the genetic code of the organism you have on hand, you can search other species with that genetic code in Entrez Taxonomy. For orgs with genetic code 11, the query is '"translation table 11"[GC]. See: 
https://www.ncbi.nlm.nih.gov/taxonomy?term="translation table 11"[GC]

**Comment by rfcohen** [comment]
That was exactly my plan.

Thanks.

-Rob
