### ISSUE TITLE
Processing more than one genome

### ISSUE THREAD

**Issue by ChristyPeterson** [ncbi/pgap#5]
I want to process more than one genome at a time. Currently the default output of the pipeline is to write the `annot.*` files into the current working directory, which must contain all of the database files within it, aka `pgap-2018-11-07.build3190`. I did try to write out the full paths of each database in the yaml file so that I could set the working directory separate from all the pipeline files, but this resulted in a failed run, the pipeline couldn't find the first databse. I've looked in the help documentation for the .cwl files but the flags available are for the myriad of databases that are required for the pipeline. 
  
As of right now, my only option to run more than one sample is to run one genome out of a copy of the build dir. This is 32G, so it could get a bit crazy if I want to run 100 genomes through the pipeline at once. I'm wondering if there is something I've missed?

**Comment by azat-badretdin** [comment]
cwtool has a solution for that, we recommend that you specify command line parameters:

```
  --tmpdir-prefix ./tmpdir/ \
  --leave-tmpdir \
  --tmp-outdir-prefix ./tmp-outdir/ \
  --copy-outputs \
  --outdir ./outdir \

```
And you can make, of course, all these directories genome-specific, so each genome will have its own set of directories. 

The `outdir` directory will have the output, temporary directories are very handy for post-mortem is something goes wrong during calculation.

**Comment by ChristyPeterson** [comment]
Thank you I will give this a try

**Comment by ChristyPeterson** [comment]
Sorry, I am not familiar at all with cwtool and I'm struggling. If I include the flags you indicated in my command, I'm getting the following error:
command: `./wf_pgap_simple.cwl --tmpdir-prefix ./tmpdir/ --leave-tmpdir  --tmp-outdir-prefix ./tmp-outdir/ --copy-outputs --outdir ./outdir genome_input.yaml`
error: 
> Resolved './wf_pgap_simple.cwl' to 'file:///Path/to/pgap-2018-11-07.build3190/wf_pgap_simple.cwl'
usage: ./wf_pgap_simple.cwl [-h] --16s_blastdb_dir 16S_BLASTDB_DIR
                            --23s_blastdb_dir 23S_BLASTDB_DIR --5s_model_path
                            5S_MODEL_PATH --AntiFamLib ANTIFAMLIB --CDDdata
                            CDDDATA --CDDdata2 CDDDATA2 --asn2pas_xsl
                            ASN2PAS_XSL [--blast_rules_db BLAST_RULES_DB]
                            --blast_rules_db_dir BLAST_RULES_DB_DIR
                            [--completeness COMPLETENESS]
                            --defline_cleanup_rules DEFLINE_CLEANUP_RULES
                            --fasta FASTA --gc_assm_name GC_ASSM_NAME
                            --gene_master_ini GENE_MASTER_INI --genemark_path
                            GENEMARK_PATH --hmm_path HMM_PATH --hmms_tab
                            HMMS_TAB --molinfo_complete_asn
                            MOLINFO_COMPLETE_ASN --molinfo_wgs_asn
                            MOLINFO_WGS_ASN --naming_blast_db NAMING_BLAST_DB
                            --naming_hmms_combined NAMING_HMMS_COMBINED
                            --naming_hmms_tab NAMING_HMMS_TAB --naming_sqlite
                            NAMING_SQLITE --rfam_amendments RFAM_AMENDMENTS
                            --rfam_model_path RFAM_MODEL_PATH --rfam_stockholm
                            RFAM_STOCKHOLM --selenoproteins SELENOPROTEINS
                            --submit_block_template SUBMIT_BLOCK_TEMPLATE
                            --submit_block_template_static
                            SUBMIT_BLOCK_TEMPLATE_STATIC --taxid TAXID
                            --taxon_db TAXON_DB [--tech TECH] --thresholds
                            THRESHOLDS --uniColl_cache UNICOLL_CACHE
                            --univ_prot_xml UNIV_PROT_XML --val_res_den_xml
                            VAL_RES_DEN_XML --wp_hashes WP_HASHES
                            [job_order]
./wf_pgap_simple.cwl: error: the following arguments are required: --16s_blastdb_dir, --23s_blastdb_dir, --5s_model_path, --AntiFamLib, --CDDdata, --CDDdata2, --asn2pas_xsl, --blast_rules_db_dir, --defline_cleanup_rules, --fasta, --gc_assm_name, --gene_master_ini, --genemark_path, --hmm_path, --hmms_tab, --molinfo_complete_asn, --molinfo_wgs_asn, --naming_blast_db, --naming_hmms_combined, --naming_hmms_tab, --naming_sqlite, --rfam_amendments, --rfam_model_path, --rfam_stockholm, --selenoproteins, --submit_block_template, --submit_block_template_static, --taxid, --taxon_db, --thresholds, --uniColl_cache, --univ_prot_xml, --val_res_den_xml, --wp_hashes
   
Do I need to add these flags into a yaml file instead? I'm not sure how to do that as the format is different from what you've included in your example

**Comment by azat-badretdin** [comment]
Unfortunately, that could not be done with running `cwl` file as an executable. Fortunately, there is a way to do that with using `cwltool` explicitly in the command line. 

Similarly to how one can run a BASH script by `./script.sh` pr `bash ./script.sh`, one can also run a CWL script by running `cwltool ./wf_pgap_simple.cwl  your_yaml.yaml` and that is where the command line options I suggested come in.

Just prepend the whole command line with `cwltool` and move CWL file and YAML files to the end of the line, like here:

```
cwltool --tmpdir-prefix ./tmpdir/ --leave-tmpdir --tmp-outdir-prefix ./tmp-outdir/ --copy-outputs --outdir ./outdir ./wf_pgap_simple.cwl  genome_input.yaml

```

**Comment by ChristyPeterson** [comment]
Perfect, that seems to have worked! Though it looks like I also have to include the `--singularity` flag when I use a direct cwltool call.

Appreciate the help!

**Comment by azat-badretdin** [comment]
You are welcome!

**Comment by tbazilegith** [comment]
Hi Azat,
I want to run pgap on several sample_genomes but of different genera (genus or maybe species). Let's say 10 genomes from different organisms.  Should I have an input.yalm and submol.yaml for each of them? 
Thanks,
TJ

**Comment by azat-badretdin** [comment]
>  Should I have an input.yalm and submol.yaml for each of them?

Yes, Tassy. `pgap.py` is designed to run for the use case of "user annotates their favorite assembly", so when several assemblies are involved, there is no provision for scaling....

**Comment by tbazilegith** [comment]
Thanks, Azat! was wondering whether there is a way to process all the various genomes at a time.
Thanks!

**Comment by azat-badretdin** [comment]
I am guessing you will need a BASH script that will take template input and submol YAML files and customize them for each genome on your list.

**Comment by tbazilegith** [comment]
Something like that. That is to avoid making them manually.
Thanks!
