### ISSUE TITLE
[BUG] zero tRNAs 

### ISSUE THREAD

**Issue by MarilyneDebieu** [ncbi/pgap#50]
Hello,
For all the species I analysed with the version 2019-11-08.build4137 including the test genome MG37, I got in the annot.gbk file "zero" tRNAs (see below the results for MG37). Moreover the version is 55.1 I think it should be maybe 5.1. 

So I do not get the number of tRNAs and the number of the version seems to be wrong in annot.gbk

I used Singularity version 3.5.0-rc.2 and I ran PGAP the same way it is described in issue: Feature request: support Singularity #14 because I can't use docker. 
I do not know where is `cwltool.log``

##Genome-Annotation-Data-START##
            Annotation Provider               :: SkyNet consortium
            Annotation Date                   :: 11/20/2019 18:06:39
            Annotation Pipeline               :: NCBI Prokaryotic Genome
                                                 Annotation Pipeline (PGAP)
            Annotation Method                 :: Best-placed reference protein
                                                 set; GeneMarkS-2+
            Annotation Software revision      :: 55.11111123
            Features Annotated                :: Gene; CDS; rRNA; tRNA; ncRNA;
                                                 repeat_region
            Genes (total)                     :: 528
            CDSs (total)                      :: 522
            Genes (coding)                    :: 509
            CDSs (with protein)               :: 509
            Genes (RNA)                       :: 6
            rRNAs                             :: 1, 1, 1 (5S, 16S, 23S)
            complete rRNAs                    :: 1, 1, 1 (5S, 16S, 23S)
            tRNAs                             :: 0
            ncRNAs                            :: 3
            Pseudo Genes (total)              :: 13
            CDSs (without protein)            :: 13
            Pseudo Genes (ambiguous residues) :: 0 of 13
            Pseudo Genes (frameshifted)       :: 9 of 13
            Pseudo Genes (incomplete)         :: 5 of 13
            Pseudo Genes (internal stop)      :: 2 of 13
            Pseudo Genes (multiple problems)  :: 3 of 13

**Comment by thibaudnis** [comment]
Hello, thank you for the report. We are aware of the incorrect Annotation Software revision in the output and already have a fix in our code. We are planning to publish a new release with this fix tomorrow. 
As for the absence of tRNAs, this is not something that we have seen in our tests. Are tRNA features annotated but not reported in the Genome-Annotation-data section, or are they not annotated? I suspect the latter but want to be sure.

**Comment by azat-badretdin** [comment]
> I do not know where is `cwltool.log``

The UNIX command `find . -name cwltool.log` will tell you the path to the file.

**Comment by MarilyneDebieu** [comment]
Hello,
Thank you for your message. I do not see any tRNA in the gff so I think the tRNA were not annotated.
Could you help me to fix this problem?

**Comment by azat-badretdin** [comment]
> Could you help me to fix this problem?

Yes. We need more data from you. Did you locate the `cwltool.log` file?

**Comment by MarilyneDebieu** [comment]
> > Could you help me to fix this problem?
> 
> Yes. We need more data from you. Did you locate the `cwltool.log` file?

No with 
find . -name cwltool.log 
I got nothing

**Comment by azat-badretdin** [comment]
Hmm.... What do you get with `ls -l .`? Feel free to edit out sensitive files from the output

**Comment by MarilyneDebieu** [comment]
> Hmm.... What do you get with `ls -l .`? Feel free to edit out sensitive files from the output

I see my files but not cwltool.log

about the output you mean this:

[2019-11-20 18:06:48] INFO [job Validate_Annotation_xsltproc_asndisc] completed success
[2019-11-20 18:06:48] INFO [step Validate_Annotation_xsltproc_asndisc] completed success
[2019-11-20 18:06:48] INFO [workflow standard_pgap] starting step Validate_Annotation_xsltproc_asnvalidate
[2019-11-20 18:06:48] INFO [step Validate_Annotation_xsltproc_asnvalidate] start
[2019-11-20 18:06:48] INFO [job Validate_Annotation_xsltproc_asnvalidate] /tmp/36_pn4ll$ xsltproc \
    --output \
    var_proc_annot_stats.val.xml \
    /tmp/tmp7uijzvmx/stg682ab109-1c7c-4900-97fc-1ed3c8b776d7/asn2pas.xsl \
    /tmp/tmp7uijzvmx/stg26b440db-6cfc-4b82-bc93-a1cb03084444/annot.val.summary.xml
compilation error: file /tmp/tmp7uijzvmx/stg682ab109-1c7c-4900-97fc-1ed3c8b776d7/asn2pas.xsl line 15 element stylesheet
xsl:version: only 1.0 features are supported
[2019-11-20 18:06:48] INFO [job Validate_Annotation_xsltproc_asnvalidate] completed success
[2019-11-20 18:06:48] INFO [step Validate_Annotation_xsltproc_asnvalidate] completed success
[2019-11-20 18:06:48] INFO [workflow standard_pgap] starting step Validate_Annotation_collect_annot_stats
[2019-11-20 18:06:48] INFO [step Validate_Annotation_collect_annot_stats] start
[2019-11-20 18:06:49] INFO [job Validate_Annotation_collect_annot_stats] /tmp/ex_i6pkv$ collect_annot_stats \
    -input-manifest \
    proc_annot_stats_or_details.mft \
    -o \
    proc_annot_stats.xml
[2019-11-20 18:06:49] INFO [job Validate_Annotation_collect_annot_stats] completed success
[2019-11-20 18:06:49] INFO [step Validate_Annotation_collect_annot_stats] completed success
[2019-11-20 18:06:49] INFO [workflow standard_pgap] completed success
[2019-11-20 18:06:49] INFO [step standard_pgap] completed success
[2019-11-20 18:06:49] INFO [workflow ] completed success
[2019-11-20 18:06:49] INFO Final process status is success

**Comment by azat-badretdin** [comment]
Yes. Thanks. Could you please post the part near trnascan_wnode job output?

**Comment by MarilyneDebieu** [comment]
hello, is it what you need ?

 /tmp/tmpqhf8e9mz/stg824ef399-a968-4107-b4c1-5eac7f2bdf0f/taxonomy.sqlite3
^[[32m[2019-11-22 10:31:36]^[[0m ^[[1;30mINFO^[[0m [job Compute_Gencode_for_trna] completed success
^[[32m[2019-11-22 10:31:36]^[[0m ^[[1;30mINFO^[[0m [step Compute_Gencode_for_trna] completed success
^[[32m[2019-11-22 10:31:36]^[[0m ^[[1;30mINFO^[[0m [workflow bacterial_trna] starting step Compute_Gencode_int_for_trna
^[[32m[2019-11-22 10:31:36]^[[0m ^[[1;30mINFO^[[0m [step Compute_Gencode_int_for_trna] start
^[[32m[2019-11-22 10:31:36]^[[0m ^[[1;30mINFO^[[0m [step Compute_Gencode_int_for_trna] completed success
^[[32m[2019-11-22 10:31:36]^[[0m ^[[1;30mINFO^[[0m [workflow bacterial_trna] starting step Get_TRNA_model
^[[32m[2019-11-22 10:31:36]^[[0m ^[[1;30mINFO^[[0m [step Get_TRNA_model] start
^[[32m[2019-11-22 10:31:36]^[[0m ^[[1;30mINFO^[[0m [step Get_TRNA_model] completed success
^[[32m[2019-11-22 10:31:36]^[[0m ^[[1;30mINFO^[[0m [workflow bacterial_trna] starting step Run_scan_and_dump
^[[32m[2019-11-22 10:31:36]^[[0m ^[[1;30mINFO^[[0m [step Run_scan_and_dump] start
^[[32m[2019-11-22 10:31:36]^[[0m ^[[1;30mINFO^[[0m [workflow Run_scan_and_dump] start
^[[32m[2019-11-22 10:31:36]^[[0m ^[[1;30mINFO^[[0m [workflow Run_scan_and_dump] starting step Run_tRNAScan_wnode
^[[32m[2019-11-22 10:31:36]^[[0m ^[[1;30mINFO^[[0m [step Run_tRNAScan_wnode] start
^[[32m[2019-11-22 10:31:36]^[[0m ^[[1;30mINFO^[[0m [job Run_tRNAScan_wnode] /tmp/wmpfs4rq$ trnascan_wnode \
    -X \
    20 \
    -Q \
    -H \
    -b \
    -q \
    -nogenbank \
    -asn-cache \
    /tmp/wmpfs4rq/sequence_cache \
    -tRNAscan \
    /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/ThirdParty/tRNAscan-SE/production/bin/tRNAscan-SE \
    -B \
    -g \
    /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/ThirdParty/tRNAscan-SE/production/lib/tRNAscan-SE/gcode/gcode.othmito \
    -input-jobs \
    /tmp/tmpk26z9ncm/stgfc796ba0-66bf-47f6-b579-af0f0b198c98/jobsaa.xml \
    -O \
    output \
    -taxid \
    2097 \
    -taxon-db \
    /tmp/tmpk26z9ncm/stg0b011c48-5017-46cb-8d89-4152c0e25c4a/taxonomy.sqlite3
21144/000/0000/PB CE7B5298DD7FF591 0001/0001 2019-11-22T10:31:37.174270 r681.pvt.bridges.psc.edu UNK_CLIENT      UNK_SESSION              trnascan_wnode start         /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2019-11-08.build4137/arch/x86_64/bin/trnascan_wnode -X 20 -Q -H -b -q -nogenbank -asn-cache /tmp/wmpfs4rq/sequence_cache -tRNAscan /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/ThirdParty/tRNAscan-SE/production/bin/tRNAscan-SE -B -g /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/ThirdParty/tRNAscan-SE/production/lib/tRNAscan-SE/gcode/gcode.othmito -input-jobs /tmp/tmpk26z9ncm/stgfc796ba0-66bf-47f6-b579-af0f0b198c98/jobsaa.xml -O output -taxid 2097 -taxon-db /tmp/tmpk26z9ncm/stg0b011c48-5017-46cb-8d89-4152c0e25c4a/taxonomy.sqlite3
21144/000/0000/PB CE7B5298DD7FF591 0002/0002 2019-11-22T10:31:37.175509 r681.pvt.bridges.psc.edu UNK_CLIENT      UNK_SESSION              trnascan_wnode extra         ncbi_app_username=marilyn9&ncbi_app_path=/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2019-11-08.build4137/arch/x86_64/bin/trnascan_wnode&ncbi_app_build_date=Nov++8+2019+10:30:23&ncbi_app_tc_project=PGAP+Branch&ncbi_app_tc_conf=PGAP-Release&ncbi_app_tc_build=4137&ncbi_app_build_id=24509606&ncbi_app_built_as=trnascan_wnode&ncbi_app_version=0.0.4137&ncbi_app_sc_version=23&ncbi_app_vcs_revision=596585

**Comment by azat-badretdin** [comment]
Yes. Thanks, Marilyne. Is this the last line before next boilerplate output: `^[[32m[2019-11-22 10:31:36]^[[0m ^[[1;30mINFO^[[0m `?

**Comment by azat-badretdin** [comment]
Ping
