### ISSUE TITLE
JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by nclaesnacw** [ncbi/pgap#52]
Having installed pgap a couple of times without issues now installing on a more powerful dual xenon running Ubuntu 16.04 with Docker installed and following Quick Start

wget https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py # downloads pgap.py
chmod +x pgap.py                                                                 # makes it executable
./pgap.py --update
the JSON object must be str, not 'bytes'                                # ??????

default python is 2.7.12 though 3.5.2 is installed but

python3 ./pgap.py --update                                                  # same error

and in conda base we have  python 3.7.4 but get the same error

It seems like python might be delivering some input as bytes rather than string but I can't find way to set text=True  for python

Any help gratefully received

**Comment by azat-badretdin** [comment]
Thank you for your report. Someone will look at it soon.

**Comment by nclaesnacw** [comment]
Thanks, probably not directly a pgap issue 🙁 but hoped you would understand what's happening.
________________________________

**Comment by azat-badretdin** [comment]
We want our software to tolerate as much variability in user system setup as possible and we are actively working on it, so your report is very useful. I am trying to investigate it right now on our setup box. 

Meanwhile, a question: did you have more output from `./pgap.py --update`? If yes, would you mind posting it as attachment? Thanks!

**Comment by nclaesnacw** [comment]
Hi
No - I note from pgap.py that the min python version is 3.5. But I get the json string error when I tried to run with python 2,7, before it checked the python version. We are running Ubuntu 16.04 because we are doing nanopore sequencing and the guppy basecaller from nanopore requires 16.04 - and that leaves us with default python 2,7 :-( but the python3 command should deal with that?

**Comment by azat-badretdin** [comment]
The script refers to python3 in shebang (first, `#!` line of the script), so any python2-related considerations are not expected to affect the outcome.

**Comment by slottad** [comment]
Sorry about that. The python version check should be the first error message you see. We'll try and get that fixed. We are mandated to move to Python 3 by our organization because Python 2 will no longer be supported. See https://www.python.org/dev/peps/pep-0373/

Yes, using Python 3.5 or later should fix your error.

**Comment by nclaesnacw** [comment]
Sorry user was not in docker group!!! I was told docker was set up but didn't test :-(
Not sure how that translated into the json error
You were right /bin/usr/env python 3 at !# sets up to use the installed python 3.5 so v.2.7 not the issue
Thanks, it needs a listener sometimes

**Comment by azat-badretdin** [comment]
Feel free to test pgap.py again after you fixed the docker/user issue. I am not sure how this might have translated into the json error either.

**Comment by azat-badretdin** [comment]
We were able to reproduce the problem on one of our systems and fix it (thanks, @evolarjun)

See https://github.com/ncbi/pgap/commit/2529fb0c6bf450daa727801cf1f751fd87b1be0b

Feel free to apply the fix locally to your `pgap.py` script or wait until this commit percolates in official way.
