### ISSUE TITLE
error with version 2019-11-08.build4137 

### ISSUE THREAD

**Issue by MarilyneDebieu** [ncbi/pgap#54]
Hello,

I am still using the version 2019-11-08.build4137 
It was working well but now I get error messages including for MG37. 
Should I use a more recent version ?
If not necessary, please find below the error that I got: 

Critical: (307.10) [NCBI-MESSAGE]  [DISPD#ID2@sutils201] Please make sure your firewall does not block ports 4444-4544 bound for 130.14.29.112
Error: (302.26) SOCK#3000[5]@130.14.29.112:443: [SOCK::Connect]  Failed pending connect(): Timeout[5.000000]
Error: (308.6) [ID2]  Stateful relay connection failure (Closed) usually indicates possible firewall configuration problem(s); please consult <https://www.ncbi.nlm.nih.gov/EB/ToolBox/NETWORK/dispatcher.html#Firewalling>
Error: (301.5) [CONN_Open(ID2/SOCK; 130.14.29.112:443)]  Failed to open connection: Closed
Error: (302.26) SSOCK#4000[5]@130.14.29.110:443: [SOCK::Connect]  Failed pending connect(): Timeout[5.000000]
Error: (303.7) [URL_Connect; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=ID2&address=r692.pvt.bridges.psc.edu&platform=x86_64-unknown-linux-gnu]  Failed to connet: Timeout[5.000000]
Error: (304.5) [ID2]  Unable to create connection with network dispatcher at "https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=ID2&address=r692.pvt.bridges.psc.edu&pltform=x86_64-unknown-linux-gnu": Success
Error: (308.5) [ID2]  Service not found
Error: (315.2) CConn_Streambuf::CConn_Streambuf():  NULL connector: Unknown
Error: (302.26) SSOCK#5000[5]@130.14.29.110:443: [SOCK::Connect]  Failed pending connect(): Timeout[5.000000]
Error: (303.7) [URL_Connect; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=ID2&address=r692.pvt.bridges.psc.edu&platform=x86_64-unknown-linux-gnu]  Failed to connet: Timeout[5.000000]
Error: (304.5) [ID2]  Unable to create connection with network dispatcher at "https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=ID2&address=r692.pvt.bridges.psc.edu&pltform=x86_64-unknown-linux-gnu": Success
Error: (308.5) [ID2]  Service not found
Error: (315.2) CConn_Streambuf::CConn_Streambuf():  NULL connector: Unknown
Critical: (307.10) [NCBI-MESSAGE]  [DISPD#ID2@sutils201] Please make sure your firewall does not block ports 4444-4544 bound for 130.14.29.112
Error: (302.26) SOCK#8000[5]@130.14.29.112:443: [SOCK::Connect]  Failed pending connect(): Timeout[5.000000]
Error: (308.6) [ID2]  Stateful relay connection failure (Closed) usually indicates possible firewall configuration problem(s); please consult <https://www.ncbi.nlm.nih.gov/EB/ToolBox/NETWORK/dispatcher.html#Firewalling>
Error: (301.5) [CONN_Open(ID2/SOCK; 130.14.29.112:443)]  Failed to open connection: Closed
Error: (302.26) SSOCK#10000[5]@130.14.29.110:443: [SOCK::Connect]  Failed pending connect(): Timeout[5.000000]
Error: (303.7) [URL_Connect; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=ID2&address=r692.pvt.bridges.psc.edu&platform=x86_64-unknown-linux-gnu]  Failed to connet: Timeout[5.000000]
Error: (301.5) [CONN_Open(ID2; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi)]  Failed to open connection: Timeout[5.000000]
Error: (CLoaderException::eConnectionFailed) cannot open connection: ID2 -> https://www.ncbi.nlm.nih.gov/Service/dispd.cgi
Error: (106.16) Application's execution failed (CLoaderException::eNoConnection) cannot open initial connection
[2020-01-02 15:04:27] INFO [job Resolve_Annotation_Conflicts] Max memory used: 31MiB
[2020-01-02 15:04:28] ERROR [job Resolve_Annotation_Conflicts] Job error:
("Error collecting output for parameter 'annotation':\nprogs/bacterial_resolve_conflicts.cwl:69:13: Did not find output file with glob pattern: '['accept.asn']'", {})
[2020-01-02 15:04:28] WARNING [job Resolve_Annotation_Conflicts] completed permanentFail
[2020-01-02 15:04:28] ERROR [step Resolve_Annotation_Conflicts] Output is missing expected field file:///pgap/bacterial_annot/wf_bacterial_annot_pass1.cwl#Resolve_Annotatio_Conflicts/protein_aligns
[2020-01-02 15:04:28] ERROR [step Resolve_Annotation_Conflicts] Output is missing expected field file:///pgap/bacterial_annot/wf_bacterial_annot_pass1.cwl#Resolve_Annotatio_Conflicts/annotation
[2020-01-02 15:04:28] WARNING [step Resolve_Annotation_Conflicts] completed permanentFail
[2020-01-02 15:04:28] INFO [workflow bacterial_annot] completed permanentFail
[2020-01-02 15:04:28] WARNING [step bacterial_annot] completed permanentFail
[2020-01-02 15:04:28] INFO [workflow standard_pgap] completed permanentFail
[2020-01-02 15:04:28] WARNING [step standard_pgap] completed permanentFail
[2020-01-02 15:04:28] INFO [workflow ] completed permanentFail
[2020-01-02 15:04:28] WARNING Final process status is permanentFail

**Comment by azat-badretdin** [comment]
>Should I use a more recent version ?

**Comment by MarilyneDebieu** [comment]
Hello, I just used the version 2019-11-25.build4172

For MG37 it was running for 27 minutes but at the end I got an error message. It looks like a connection problem (see below).  Do I need a special firewall configuration ?

Error: (302.26) SSOCK#1000[5]@130.14.29.110:443: [SOCK::Connect]  Failed pending connect(): Timeout[5.000000]
Error: (303.7) [URL_Connect; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=ID2&address=r653.pvt.bridges.psc.edu&platform=x86_64-unknown-linux-gnu]  Failed to connect: Timeout[5.000000]
Error: (304.5) [ID2]  Unable to create connection with network dispatcher at "https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=ID2&address=r653.pvt.bridges.psc.edu&platform=x86_64-unknown-linux-gnu": Success
Error: (308.5) [ID2]  Service not found
Error: (315.2) CConn_Streambuf::CConn_Streambuf():  NULL connector: Unknown
Critical: (307.10) [NCBI-MESSAGE]  [DISPD#ID2@sutils101] Please make sure your firewall does not block ports 4444-4544 bound for 130.14.29.112
Error: (302.26) SOCK#4000[5]@130.14.29.112:443: [SOCK::Connect]  Failed pending connect(): Timeout[5.000000]
Error: (308.6) [ID2]  Stateful relay connection failure (Closed) usually indicates possible firewall configuration problem(s); please consult <https://www.ncbi.nlm.nih.gov/IEB/ToolBox/NETWORK/dispatcher.html#Firewalling>
Error: (301.5) [CONN_Open(ID2/SOCK; 130.14.29.112:443)]  Failed to open connection: Closed
Critical: (307.10) [NCBI-MESSAGE]  [DISPD#ID2@sutils101] Please make sure your firewall does not block ports 4444-4544 bound for 130.14.29.112
[2020-01-03 12:49:30] INFO [job retrieve_cached_hits_2] Max memory used: 26MiB
[2020-01-03 12:49:30] INFO [job retrieve_cached_hits_2] completed success
[2020-01-03 12:49:30] INFO [step retrieve_cached_hits_2] completed success
[2020-01-03 12:49:30] INFO [workflow Find_Naming_Protein_Hits] starting step gpx_qsubmit_6
[2020-01-03 12:49:30] INFO [step gpx_qsubmit_6] start
invalid field `nameroot`, expected one of: 'class', 'location', 'path', 'basename', 'listing'
invalid field `nameext`, expected one of: 'class', 'location', 'path', 'basename', 'listing'
[2020-01-03 12:49:30] INFO [job gpx_qsubmit_6] /tmp/54mj2kaq$ gpx_qsubmit \
    -affinity \
    subject \
    -asn-cache \
    /tmp/54mj2kaq/sequence_cache,/tmp/54mj2kaq/cache \
    -db \
    /tmp/54mj2kaq/blast_dir/blastdb,/tmp/54mj2kaq/blast_dir/blast_rules_db \
    -ids-manifest \
    ids.mft \
    -lds2 \
    /tmp/tmp93ofvp0f/stg19fce31f-7ce7-450f-b39d-c927fb1a5dd5/LDS2 \
    -max-batch-length \
    10000 \
    -o \
    jobs.xml
Error: (302.26) SSOCK#1000[5]@130.14.29.110:443: [SOCK::Connect]  Failed pending connect(): Timeout[5.000000]
Error: (303.7) [URL_Connect; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=ID2&address=r653.pvt.bridges.psc.edu&platform=x86_64-unknown-linux-gnu]  Failed to connect: Timeout[5.000000]
Error: (304.5) [ID2]  Unable to create connection with network dispatcher at "https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=ID2&address=r653.pvt.bridges.psc.edu&platform=x86_64-unknown-linux-gnu": Success
Error: (308.5) [ID2]  Service not found
Error: (315.2) CConn_Streambuf::CConn_Streambuf():  NULL connector: Unknown
Error: (302.26) SSOCK#2000[5]@130.14.29.110:443: [SOCK::Connect]  Failed pending connect(): Timeout[5.000000]
Error: (303.7) [URL_Connect; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=ID2&address=r653.pvt.bridges.psc.edu&platform=x86_64-unknown-linux-gnu]  Failed to connect: Timeout[5.000000]
Error: (304.5) [ID2]  Unable to create connection with network dispatcher at "https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=ID2&address=r653.pvt.bridges.psc.edu&platform=x86_64-unknown-linux-gnu": Success
Error: (308.5) [ID2]  Service not found
Error: (315.2) CConn_Streambuf::CConn_Streambuf():  NULL connector: Unknown
Critical: (307.10) [NCBI-MESSAGE]  [DISPD#ID2@sutils201] Please make sure your firewall does not block ports 4444-4544 bound for 130.14.29.112
Error: (302.26) SOCK#5000[5]@130.14.29.112:22: [SOCK::Connect]  Failed pending connect(): Timeout[5.000000]
Error: (308.6) [ID2]  Stateful relay connection failure (Closed) usually indicates possible firewall configuration problem(s); please consult <https://www.ncbi.nlm.nih.gov/IEB/ToolBox/NETWORK/dispatcher.html#Firewalling>
Error: (301.5) [CONN_Open(ID2/SOCK; 130.14.29.112:22)]  Failed to open connection: Closed
Error: (302.26) SSOCK#7000[5]@130.14.29.110:443: [SOCK::Connect]  Failed pending connect(): Timeout[5.000000]
Error: (303.7) [URL_Connect; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=ID2&address=r653.pvt.bridges.psc.edu&platform=x86_64-unknown-linux-gnu]  Failed to connect: Timeout[5.000000]
Error: (301.5) [CONN_Open(ID2; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi)]  Failed to open connection: Timeout[5.000000]
Error: (302.26) SSOCK#8000[5]@130.14.29.110:443: [SOCK::Connect]  Failed pending connect(): Timeout[5.000000]
Error: (303.7) [URL_Connect; https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=ID2&address=r653.pvt.bridges.psc.edu&platform=x86_64-unknown-linux-gnu]  Failed to connect: Timeout[5.000000]
Error: (304.5) [ID2]  Unable to create connection with network dispatcher at "https://www.ncbi.nlm.nih.gov/Service/dispd.cgi?service=ID2&address=r653.pvt.bridges.psc.edu&platform=x86_64-unknown-linux-gnu": Success
Error: (308.5) [ID2]  Service not found
Error: (315.2) CConn_Streambuf::CConn_Streambuf():  NULL connector: Unknown
Error: (CLoaderException::eConnectionFailed) cannot open connection: ID2
Error: (106.16) Application's execution failed (CLoaderException::eNoConnection) cannot open initial connection
[2020-01-03 12:50:04] INFO [job gpx_qsubmit_6] Max memory used: 26MiB
[2020-01-03 12:50:04] ERROR [job gpx_qsubmit_6] Job error:
("Error collecting output for parameter 'jobs':\nprogs/gpx_qsubmit.cwl:124:7: Did not find output file with glob pattern: '['jobs.xml']'", {})
[2020-01-03 12:50:04] WARNING [job gpx_qsubmit_6] completed permanentFail
[2020-01-03 12:50:04] ERROR [step gpx_qsubmit_6] Output is missing expected field file:///pgap/task_types/tt_blastp_wnode_naming.cwl#gpx_qsubmit/jobs
[2020-01-03 12:50:04] WARNING [step gpx_qsubmit_6] completed permanentFail
[2020-01-03 12:50:04] INFO [workflow Find_Naming_Protein_Hits] completed permanentFail
[2020-01-03 12:50:04] WARNING [step Find_Naming_Protein_Hits] completed permanentFail
[2020-01-03 12:50:04] INFO [workflow bacterial_annot_4] completed permanentFail
[2020-01-03 12:50:04] WARNING [step bacterial_annot_4] completed permanentFail
[2020-01-03 12:50:04] INFO [workflow standard_pgap] completed permanentFail
[2020-01-03 12:50:04] WARNING [step standard_pgap] completed permanentFail
[2020-01-03 12:50:04] INFO [workflow ] completed permanentFail
[2020-01-03 12:50:04] WARNING Final process status is permanentFail

**Comment by MarilyneDebieu** [comment]
Hello,

The problem of connection is solved.
But I got a new error message it is about docker whereas I am using singularity, can I still use singularity with the version 2019-11-25.build4172?

see the error message below:

INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
FATAL:   Unable to handle docker://ncbi/pgap:2019-11-25.build4172 uri: unable to build: conveyor failed to get: pinging docker registry returned: error pinging registry registry-1.docker.io, response code 408 (Request Timeout)
FATAL:   Unable to handle docker://ncbi/pgap:2019-11-25.build4172 uri: failed to get SHA of docker://ncbi/pgap:2019-11-25.build4172: pinging docker registry returned: error pinging registry registry-1.docker.io, response code 408 (Request Timeout)

**Comment by azat-badretdin** [comment]
Unfortunately we can't do much about this problem.

**Comment by ap1438** [comment]
> Hello,
> 
> The problem of connection is solved. But I got a new error message it is about docker whereas I am using singularity, can I still use singularity with the version 2019-11-25.build4172?
> 
> see the error message below:
> 
> INFO: Converting OCI blobs to SIF format INFO: Starting build... FATAL: Unable to handle docker://ncbi/pgap:2019-11-25.build4172 uri: unable to build: conveyor failed to get: pinging docker registry returned: error pinging registry registry-1.docker.io, response code 408 (Request Timeout) FATAL: Unable to handle docker://ncbi/pgap:2019-11-25.build4172 uri: failed to get SHA of docker://ncbi/pgap:2019-11-25.build4172: pinging docker registry returned: error pinging registry registry-1.docker.io, response code 408 (Request Timeout)

Hi,
Can you please explain how you sloved the problem of connection please.

**Comment by azat-badretdin** [comment]
@MarilyneDebieu .  I wonder if you comment on this to Akash (@ap1438 )
