### ISSUE TITLE
Validation test failing with version 2019-11-25.build4172

### ISSUE THREAD

**Issue by dbayles** [ncbi/pgap#55]
Running PGAP version 2019-11-25.build4172 according to the Quick Start instructions fails.  The environment is RHEL7 and Docker version 1.13.1.

The validation test was rerun using the debug option as follows:
$ ./pgap.py --debug -r -o mg37_results test_genomes/MG37/input.yaml
The job appears to be failing at the "job Prepare_Unannotated_Sequences_asnvalidate" job step.  I've attached the cwltool.log output file generated by the debug command.
[cwltool.log](https://github.com/ncbi/pgap/files/4032376/cwltool.log)

**Comment by azat-badretdin** [comment]
Thank you for your report! Could you please attach `debug/tmp-outdir/2hsw97d9/sequences.asn`?

Thanks!

**Comment by dbayles** [comment]
Since Github doesn’t support the *.asn filetype (preventing uploading), I’ve attached it to this email.

Regards,

Darrell

==========================================
Darrell O. Bayles, M.S., Ph.D.
USDA, ARS, National Animal Disease Center
Infectious Bacterial Diseases Research Unit
1920 Dayton Ave, Bldg 24
P.O. Box 70
Ames, IA  50010
Tel: (515) 337-7165
==========================================

**Comment by azat-badretdin** [comment]
Thanks for quick response! Unfortunately the attachment did not go through as well. Could you please rename it to `sequences.asn.txt` and try to upload again? Thanks!

**Comment by dbayles** [comment]
Yes.  Please see the attached file.
[sequences.asn.txt](https://github.com/ncbi/pgap/files/4036214/sequences.asn.txt)

**Comment by azat-badretdin** [comment]
Thank you, Darrell! I will have a look at it at earliest opportunity!

**Comment by azat-badretdin** [comment]
Darrel, could you please provide the output of `cat /proc/cpuinfo`. Also: long shot question: have you tried to run it on the same hardware but with a different OS?

**Comment by dbayles** [comment]
I haven't tried any other OS on this particular server.  I've attached the output of /proc/cpuinfo.
[pgap_troubleshooting.txt](https://github.com/ncbi/pgap/files/4054740/pgap_troubleshooting.txt)

**Comment by azat-badretdin** [comment]
Thanks! We will have a look at it at the first opportunity!

**Comment by whlavina** [comment]
Darrel, it looks like you have an older CPU, which is unsupported by our binaries (require SSE4.2). We will evaluate the value of supporting older CPU architectures, but in the short term, can you try on more recent hardware? If that is possible, works, and there is no objection, we'll formally close this ticket without a fix.

**Comment by whlavina** [comment]
In follow-up, we don't see enough user demand for supporting older CPU architectures to justify the additional complexity in delivering software. We will make note of this in our documentation, and perhaps improve error messages to make it more obvious when the hardware is unsupported.

If you disagree with our assessment, please speak up and we may re-evaluate. Hopefully, this isn't much of an inconvenience. We thank you for your interest.

**Comment by dbayles** [comment]
Thanks for looking into this problem.  At a minimum, it would be helpful to provide the minimum system requirements needed to run the pipeline.  I did set up the pipeline on a server with more recent hardware and the validation test completed without problems.
