### ISSUE TITLE
[FEATURE REQUEST] option to specify PGAP database location

### ISSUE THREAD

**Issue by erinyoung** [ncbi/pgap#56]
When I run pgap.py, the PGAP database always builds where I begin running the command. 

I find this annoying.

I would like pgap.py to have a command-line argument that can be used to specify the database location, and then that location will mounted to the PGAP docker image.

**Comment by slottad** [comment]
The problem is you'd have to either use the same command line argument each time or we'd have to maintain a config file in a way that works with all three platforms.

We'll take your suggestion under advisement.
