### ISSUE TITLE
[BUG] installation with Singularity of 2020-02-06.build4373

### ISSUE THREAD

**Issue by emmaver** [ncbi/pgap#58]
Hello,

Thank you for making Singularity supported for PGAP. It is very convenient for running on cluster, where I can't use Docker. I noticed a problem to install it through the pgap.py script, though. 

When running ``./pgap.py -D singularity`` for the first time (in order to download the image and all needed files), I got the following message: 
```The latest version of PGAP is 2020-02-06.build4373, you have nothing installed locally.
Downloading (as needed) Docker image ncbi/pgap:2020-02-06.build4373
FATAL:    While pulling library image: image ncbi/pgap:2020-02-06.build4373 (amd64) does not exist in the library
name 'CalledProcessError' is not defined
```

When looking into `pgap.py` I noticed that upon installation, it executes ``singularity pull ncbi/pgap:2020-02-06.build4373`` instead of ``singularity pull docker://ncbi/pgap:2020-02-06.build4373`` and this caused the error.
When adding a few lines to the Python script, I could install it and download all auxiliary data. For running the pipeline itself after successful installation, the original Python script worked great.

Thanks in advance for fixing this,
Emma

**Comment by max1c** [comment]
Same issue here.

**Comment by slottad** [comment]
Have either of you two updated your [pgap.py](https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py) scripts from the github prod branch, as instructed in the [QuickStart](https://github.com/ncbi/pgap/wiki/Quick-Start)?

**Comment by emmaver** [comment]
Yes, I did. I used the wget command from QuickStart first and also tried ``./pgap.py --update -D singularity``, which gave the same error as above.

**Comment by slottad** [comment]
I'm going to guess that you are using an earlier version of singularity, such as 2.4.x. We developed and tested using a later version, 3.5.x.

We are checking for the type of the container running software by using the `--version` option and parsing the result. This works for docker, podman, and later versions of singularity which include their names as part of the string, but not for Singularity 2.4.2, which does not:

```
~$ singularity --version
2.4.2-dist
```

I can try and make the software a bit smarter about detecting earlier versions, or I can add a special singularity flag that will just do the right thing, but assumes singularity is in your path. What do you think?

**Comment by nclaesnacw** [comment]
Thanks for all the work on this. I get the same issue but I'm not clever enough to follow all the indirection to find the singularity pull command and change it
but my 
[nacw pgap]$singularity version
3.4.2-1

**Comment by nclaesnacw** [comment]
Sorry
[nacw pgap]$ singularity --version
singularity version 3.4.2-1

**Comment by slottad** [comment]
Okay, It looks like I will just add a special flag for singularity.

**Comment by max1c** [comment]
> Have either of you two updated your [pgap.py](https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py) scripts from the github prod branch, as instructed in the [QuickStart](https://github.com/ncbi/pgap/wiki/Quick-Start)?

Yes, this is using the latest pgap.py. I tried master, prod, and dev all with the same result.


> I'm going to guess that you are using an earlier version of singularity, such as 2.4.x. We developed and tested using a later version, 3.5.x.

$ singularity --version
singularity version 3.5.2

**Comment by slottad** [comment]
Okay, I believe I have fixed it for singularity greater than version 3.x

You can update your pgap.py script manually, or let the new auto-update function do it for you.

**Comment by max1c** [comment]
> Okay, I believe I have fixed it for singularity greater than version 3.x
> 
> You can update your pgap.py script manually, or let the new auto-update function do it for you.

Can confirm the fix is working correctly. Ran the following commands and the download started without issues. Thanks!
$ ./pgap.py --update -D singularity
$ ./pgap.py -D singularity

**Comment by nclaesnacw** [comment]
Thank you. Worked for me

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nclaesnacw** [comment]
I don't get that error now. But I have. When I tried to modify pgap.py to follow the work-around first proposed, the auto-update feature kicked in, recognised pgap.py wasn't the same as the latest version and tried to do an update, but wouldn't overwrite the sif file already present and quit with this error message.

I'm a user on a hpc system - so I don't have full access to all singularity commands  :-( I guess pgap tries to use some? 

Output will be placed in: /mnt/storage/nobackup/proj/jems/nanopore/progs/pgap/mg37_results
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
WARNING: container does not have /.singularity.d/actions/exec, calling bash directly
PGAP failed, docker exited with rc = 1

On my standalone machine it puts cwltool in /us/bin ? On the hpc,  pgap.py doesn't complain during installation but I can't find cwltool (which isn't on our system) - if I put cwltool in nacw/bin which is on the PATH will pgap find it?

Thanks

**Comment by slottad** [comment]
sif file? pgap.py only auto-updates pgap.py.

The only singularity command we use are pull and exec.

cwltool is part of the image, and runs the pipeline within the container. We do not install any software into the local system.

**Comment by max1c** [comment]
> sif file? pgap.py only auto-updates pgap.py.
> 
> The only singularity command we use are pull and exec.
> 
> cwltool is part of the image, and runs the pipeline within the container. We do not install any software into the local system.

So am I doing something wrong or? 

$ ./pgap.py -D singularity -o mg37_results test_genomes/MG37/input.yaml
PGAP version 2020-02-06.build4373 is up to date.
Downloading (as needed) Docker image docker://ncbi/pgap:2020-02-06.build4373
FATAL:   Image file already exists: "pgap_2020-02-06.build4373.sif" - will not overwrite
name 'CalledProcessError' is not defined

**Comment by slottad** [comment]
Oh singularity, how I hate you so. I understand why you won't overwrite, but why is that a fatal error? Why must my script have to figure out if you failed for this stupid error, or because something bad actually happened?

So yeah, I didn't test re-running it on the same system. I'll see if I can fix this.

**Comment by max1c** [comment]
@slottad Thanks for all your hard work. We all really appreciate it :)

**Comment by nclaesnacw** [comment]
Second that thank you 😊 sorry about singularity, I only want because my IT restricts my choices, Pgap works well, but slowly, on my standalone machine. But I want to do lots of runs on my draft assemblies for error prone long reads as I error correct, much better than BUSCO and we are trying to do 100 x 8-10Mb genomes.
The info about what it is supposed to do very helpful. I get this sif file with pgap.py -D singpath --update
and if I do
singularity pull docker://ncbi/pgap/:2020-02-06.build4373
It stays in the download dir after installation completes - should we omit the -D for --update? I haven't tried 😕

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by slottad** [comment]
Okay, I have a new version up, 14th time is the charm.

You should use the the same `-D` option for update and running.

**Comment by max1c** [comment]
> Okay, I have a new version up, 14th time is the charm.
> 
> You should use the the same `-D` option for update and running.

$ ./pgap.py -D singularity -o mg37_results test_genomes/MG37/input.yaml
PGAP version 2020-02-06.build4373 is up to date.
Singularity sif files exists, not updating.
Downloading and extracting tarball: https://s3.amazonaws.com/pgap/input-2020-02-06.build4373.pgap.tgz
Downloaded 797809152 of 15961048894 bytes (5.00%)

Seems to be working.

**Comment by nclaesnacw** [comment]
Yes - sorry. 
[cwltool.log](https://github.com/ncbi/pgap/files/4230262/cwltool.log)
--update downloads the singularity image - so the pull command works
when you then run  
$./pgap.py -D singularity -r -o mg37_results test_genomes/MG37/input.yaml
does pgap try and pull the singularity image again? That seems to be the point at which I get the start of the error - immediately after the Runtime Report

**Comment by slottad** [comment]
This is weird. The error in the file says that you did not choose to either report usage, or not report usage. You command above does have the <-r> option, which should report usage, but the copy of the input yaml created by pgap.py, which is included in the log does not.

Also, the lines in your <cwltool.log> file are strangely truncated. Did you cut-n-paste them from a terminal window?

**Comment by max1c** [comment]
@slottad It's the same error I'm getting. I edited my comment yesterday right after you updated the script.

**Comment by slottad** [comment]
@max1c, I'm trying to recreate the problem here, and I'm not having much luck. Could I see a copy of your cwltool.log?

**Comment by max1c** [comment]
> @max1c, I'm trying to recreate the problem here, and I'm not having much luck. Could I see a copy of your cwltool.log?

Of course. 
[cwltool.log](https://github.com/ncbi/pgap/files/4231868/cwltool.log)

**Comment by slottad** [comment]
@max1c, According to your log this is the command you used:

`./pgap.py -D singularity -o mg37_results test_genomes/MG37/input.yaml`

Which does not include a `-r` (or a `-n` either, but we prefer a `-r`)

**Comment by nclaesnacw** [comment]
You are right - trying to shortcut scp'ing twice across domains :-(
[cwltool.log](https://github.com/ncbi/pgap/files/4231996/cwltool.log)

**Comment by nclaesnacw** [comment]
My command didn't include -r either
When I first started the input.yaml given as an example in the wiki had
report_usage: TRUE
and having that and -r gave a duplicate key error. So I've always left report_usage:TRUE in the yaml
I assumed the input.yaml for MG37 had that in - but didn't check :-(
But surely that's not the error.
Do you get more useful info if one of us re-runs with -r set?

**Comment by slottad** [comment]
Surely it is the error.

So the `-r` and `-n` flags are for convenience. You must either have that line in the input yaml, or use one of the options to have it done for you. But not both, as you said. Whichever fits in best with your workflow.

This is a subtle point where we are trying to provide the most flexibility for our users, but just wind up confusing them.  I'll see if I can make the documentation clearer. Of course then we have the problem that if the documentation is too long, then people don't read it.

**Comment by max1c** [comment]
> @max1c, According to your log this is the command you used:
> 
> `./pgap.py -D singularity -o mg37_results test_genomes/MG37/input.yaml`
> 
> Which does not include a `-r` (or a `-n` either, but we prefer a `-r`)

Thanks, I guess you are right. That seems strange because I re-ran without -r just see what happens after it originally failed but now that I've started it again with -r it's been running for the past 10-15 minutes now. Will report back once it hopefully successfully completes.

**Comment by nclaesnacw** [comment]
Thanks
Despite lots of complaints while pulling the singularity image and about too little RAM, too few open files and too little hdd space, on my old i7-4710HQ CPU @ 2.50GHz laptop with 16Gb RAM, it completed MG37 successfully
Original command: ./pgap.py -D /usr/local/bin/singularity -r -o mg37_results test_genomes/MG37/input.yaml

On our hpc system it fails
[hpc_cwltool.log](https://github.com/ncbi/pgap/files/4232928/hpc_cwltool.log)
looks like it is the way singularity is setup on the hpc, not your problem I think.
In case Newcastle have setup their hpc like everyone else and you have an interest in pgap on hpc, this is for info.
I know singularity exec works on our system I use it quite a bit and singularity pull but e.g. singularity build isn't accessible to users
the key warning I think (but my track record not good) from cwltoo.log
[33mWARNING:[0m container does not have /.singularity.d/actions/exec, calling cwltool directly
If that makes sense and there's any info I can pass on to our systems guys that would be good - but maybe I have to just get them to install at system level, if I can.
But thanks again for making a great program accessible

**Comment by azat-badretdin** [comment]
>But thanks again for making a great program accessible
