### ISSUE TITLE
Getting error while running the current version of the tool on test sample data.

### ISSUE THREAD

**Issue by Mayankguptai** [ncbi/pgap#64]
Getting the following error when I tried to run the current version of the tool.

PGAP version 2020-02-06.build4373 is up to date.
/storage1/PGAP_NCBI_Annotation_tool/mg37_results
docker exited with rc = 1

OS: CentOS 7
PGAP version 2020-02-06.build4373 is up to date.

**Log Files**

Original command: ./pgap.py -r -o mg37_results test_genomes/MG37/input.yaml

Docker command: /usr/bin/docker run -i --user 1000:1000 --volume /storage1/PGAP_NCBI_Annotation_tool/input-2020-02-06.build4373:/pgap/input:ro,z --volume /storage1/PGAP_NCBI_Annotation_tool/test_genomes/MG37:/pgap/user_input:z --volume /storage1/PGAP_NCBI_Annotation_tool/test_genomes/MG37/pgap_input.yaml:/pgap/user_input/pgap_input.yaml:ro,z --volume /storage1/PGAP_NCBI_Annotation_tool/mg37_results:/pgap/output:rw,z ncbi/pgap:2020-02-06.build4373 cwltool --timestamps --disable-color --outdir /pgap/output pgap.cwl /pgap/user_input/pgap_input.yaml

--- Start YAML Input ---
fasta:
  class: File
  location: ASM2732v1.annotation.nucleotide.1.fasta
submol:
  class: File
  location: submol.yaml
supplemental_data: { class: Directory, location: /pgap/input }
report_usage: true
--- End YAML Input ---
[2020-03-01 15:45:09] INFO /usr/local/bin/cwltool 2.0.20200126090152
Traceback (most recent call last):
  File "/usr/local/bin/cwltool", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/cwltool/main.py", line 1234, in run
    sys.exit(main(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/cwltool/main.py", line 873, in main
    fetcher_constructor=loadingContext.fetcher_constructor,
  File "/usr/local/lib/python3.6/site-packages/cwltool/load_tool.py", line 97, in resolve_tool_uri
    raise ValidationException("Not found: '%s'" % argsworkflow)
schema_salad.exceptions.ValidationException: Not found: 'pgap.cwl'

Thanks,
Mayank

**Comment by azat-badretdin** [comment]
Internal report PGAPX-745 was created. Someone will look at this problem shortly.

**Comment by slottad** [comment]
Hmm, I'm not sure what is going on here. Have you downloaded the latest version of `pgap.py`?

**Comment by Mayankguptai** [comment]
I was using older version of pgap.py, after downloading and running the new script the run with test data shows no error but when I tried to run on a bacterial draft genome data its shows the following error even though the annotation files are generating.

GAP version 2020-02-06.build4373 is up to date.
Output will be placed in: /storage1/PGAP_NCBI_Annotation_tool/MO2_2020_results

PGAP failed, docker exited with rc = 1
Printing log starting from failed job:

[2020-03-03 16:35:14] INFO [step Final_Bacterial_Package_asndisc_evaluate] start
[2020-03-03 16:35:14] INFO [job Final_Bacterial_Package_asndisc_evaluate] /pgap/output/debug/tmp-outdir/46y6f4a8$ xml_evaluate \
    -input \
    /tmp/tmpbj8w_x6u/stg80d5a81f-3356-428a-ab26-b6ea1aef8580/annot.disc \
    -xpath-fail \
    '//*[@severity="FATAL"]' > /pgap/output/debug/tmp-outdir/46y6f4a8/stdout
[2020-03-03 16:35:14] WARNING [job Final_Bacterial_Package_asndisc_evaluate] completed permanentFail
[2020-03-03 16:35:14] WARNING [step Final_Bacterial_Package_asndisc_evaluate] completed permanentFail
[2020-03-03 16:35:14] INFO [workflow standard_pgap] completed permanentFail
[2020-03-03 16:35:14] WARNING [step standard_pgap] completed permanentFail
[2020-03-03 16:35:14] INFO [workflow ] completed permanentFail
{
    "gbk": {
        "location": "file:///pgap/output/annot.gbk",
        "basename": "annot.gbk",
        "class": "File",
        "checksum": "sha1$a1713c8002164260dbd2627d78dded7ae5a545c1",
        "size": 14416794,
        "path": "/pgap/output/annot.gbk"
    },
    "gff": {
        "location": "file:///pgap/output/annot.gff",
        "basename": "annot.gff",
        "class": "File",
        "checksum": "sha1$bc46db7870932b4d9a9e51c41a692ed8568d4a99",
        "size": 2504099,
        "path": "/pgap/output/annot.gff"
    },
    "input_fasta": {
        "class": "File",
        "location": "file:///pgap/output/MO2_out_no_PHG_phiX174.fna",
        "size": 6128717,
        "basename": "MO2_out_no_PHG_phiX174.fna",
        "checksum": "sha1$6886842e87adae1148a7dbe99368d1ca009d22f3",
        "path": "/pgap/output/MO2_out_no_PHG_phiX174.fna"
    },
    "input_submol": {
        "class": "File",
        "location": "file:///pgap/output/submol.yaml",
        "size": 1025,
        "basename": "submol.yaml",
        "checksum": "sha1$6b4dcdb4739a729a6633d99f0c929a86f1de0704",
        "path": "/pgap/output/submol.yaml"
    },
    "nucleotide_fasta": {
        "location": "file:///pgap/output/annot.fna",
        "basename": "annot.fna",
        "class": "File",
        "checksum": "sha1$77d1f2fe6d5663ad39e414f07764788144311898",
        "size": 6137737,
        "path": "/pgap/output/annot.fna"
    },
    "protein_fasta": {
        "location": "file:///pgap/output/annot.faa",
        "basename": "annot.faa",
        "class": "File",
        "checksum": "sha1$30c50f924c1e7f64f5c0a2eff934ea63f0863427",
        "size": 2091993,
        "path": "/pgap/output/annot.faa"
    },
    "sqn": {
        "location": "file:///pgap/output/annot.sqn",
        "basename": "annot.sqn",
        "class": "File",
        "checksum": "sha1$a2959a19afd20f9e212c86eff03cf1915b3b8b2e",
        "size": 32028715,
        "path": "/pgap/output/annot.sqn"
    }
}
[2020-03-03 16:35:14] WARNING Final process status is permanentFail

**Comment by azat-badretdin** [comment]
Could you please rerun it with `pgap.py -d` option and post the results of `debug/tmp-outdir/*/stdout`

**Comment by Mayankguptai** [comment]
stdout :- 

Failer nodes:
<?xml version="1.0" encoding="UTF-8"?>
<test name="RNA_CDS_OVERLAP" description="CDS RNA Overlap" severity="FATAL" cardinality="6">
    <details message="## coding regions overlap RNA features" severity="FATAL" cardinality="3" unit="coding region">
      <details message="## coding regions are completely contained in RNAs" severity="WARNING" cardinality="1" unit="coding region">
        <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="rRNA" product="23S ribosomal RNA" location="lcl|sc217_sz5123:2040-4937" locus_tag="pgaptmp_001995" label="rRNA 23S ribosomal RNA lcl|sc217_sz5123:2040-4937 pgaptmp_001995"/>
        <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="CDS" product="hypothetical protein" location="lcl|sc217_sz5123:3438-3626" locus_tag="pgaptmp_001996" label="CDS hypothetical protein lcl|sc217_sz5123:3438-3626 pgaptmp_001996"/>
      </details>
      <details message="## coding regions completely contain tRNAs" severity="FATAL" cardinality="1" unit="coding region">
        <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="tRNA" product="Leu" location="lcl|sc101_sz22132:17651-17732" locus_tag="pgaptmp_000038" label="tRNA Leu lcl|sc101_sz22132:17651-17732 pgaptmp_000038"/>
        <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="CDS" product="hypothetical protein" location="lcl|sc101_sz22132:c17823-17644" locus_tag="pgaptmp_000037" label="CDS hypothetical protein lcl|sc101_sz22132:c17823-17644 pgaptmp_000037"/>
      </details>
      <details message="## coding regions overlap RNAs (no containment)" severity="WARNING" cardinality="1" unit="coding regions overlap RNA">
        <details message="## coding regions overlap RNAs on the same strand (no containment)" severity="WARNING" cardinality="1" unit="coding region">
          <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="tRNA" product="Leu" location="lcl|sc104_sz21297:c7370-7288" locus_tag="pgaptmp_000086" label="tRNA Leu lcl|sc104_sz21297:c7370-7288 pgaptmp_000086"/>
          <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="CDS" product="M48 family metallopeptidase" location="lcl|sc104_sz21297:c8224-7349" locus_tag="pgaptmp_000087" label="CDS M48 family metallopeptidase lcl|sc104_sz21297:c8224-7349 pgaptmp_000087"/>
        </details>
      </details>
    </details>
  </test>

<?xml version="1.0" encoding="UTF-8"?>
<details message="## coding regions overlap RNA features" severity="FATAL" cardinality="3" unit="coding region">
      <details message="## coding regions are completely contained in RNAs" severity="WARNING" cardinality="1" unit="coding region">
        <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="rRNA" product="23S ribosomal RNA" location="lcl|sc217_sz5123:2040-4937" locus_tag="pgaptmp_001995" label="rRNA 23S ribosomal RNA lcl|sc217_sz5123:2040-4937 pgaptmp_001995"/>
        <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="CDS" product="hypothetical protein" location="lcl|sc217_sz5123:3438-3626" locus_tag="pgaptmp_001996" label="CDS hypothetical protein lcl|sc217_sz5123:3438-3626 pgaptmp_001996"/>
      </details>
      <details message="## coding regions completely contain tRNAs" severity="FATAL" cardinality="1" unit="coding region">
        <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="tRNA" product="Leu" location="lcl|sc101_sz22132:17651-17732" locus_tag="pgaptmp_000038" label="tRNA Leu lcl|sc101_sz22132:17651-17732 pgaptmp_000038"/>
        <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="CDS" product="hypothetical protein" location="lcl|sc101_sz22132:c17823-17644" locus_tag="pgaptmp_000037" label="CDS hypothetical protein lcl|sc101_sz22132:c17823-17644 pgaptmp_000037"/>
      </details>
      <details message="## coding regions overlap RNAs (no containment)" severity="WARNING" cardinality="1" unit="coding regions overlap RNA">
        <details message="## coding regions overlap RNAs on the same strand (no containment)" severity="WARNING" cardinality="1" unit="coding region">
          <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="tRNA" product="Leu" location="lcl|sc104_sz21297:c7370-7288" locus_tag="pgaptmp_000086" label="tRNA Leu lcl|sc104_sz21297:c7370-7288 pgaptmp_000086"/>
          <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="CDS" product="M48 family metallopeptidase" location="lcl|sc104_sz21297:c8224-7349" locus_tag="pgaptmp_000087" label="CDS M48 family metallopeptidase lcl|sc104_sz21297:c8224-7349 pgaptmp_000087"/>
        </details>
      </details>
    </details>

<?xml version="1.0" encoding="UTF-8"?>
<details message="## coding regions completely contain tRNAs" severity="FATAL" cardinality="1" unit="coding region">
        <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="tRNA" product="Leu" location="lcl|sc101_sz22132:17651-17732" locus_tag="pgaptmp_000038" label="tRNA Leu lcl|sc101_sz22132:17651-17732 pgaptmp_000038"/>
        <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="CDS" product="hypothetical protein" location="lcl|sc101_sz22132:c17823-17644" locus_tag="pgaptmp_000037" label="CDS hypothetical protein lcl|sc101_sz22132:c17823-17644 pgaptmp_000037"/>
      </details>

**Comment by Mayankguptai** [comment]
Yeah sure, attaching non-empty stdout file here. PFA.

[stdout.txt](https://github.com/ncbi/pgap/files/4293058/stdout.txt)

**Comment by azat-badretdin** [comment]
Excellent! Thank you. 

`<?xml version="1.0" encoding="UTF-8"?>
<test name="RNA_CDS_OVERLAP" description="CDS RNA Overlap" severity="FATAL" cardinality="6">
    <details message="## coding regions overlap RNA features" severity="FATAL" cardinality="3" unit="coding region">
      <details message="## coding regions are completely contained in RNAs" severity="WARNING" cardinality="1" unit="coding region">
        <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="rRNA" product="23S ribosomal RNA" location="lcl|sc217_sz5123:2040-4937" locus_tag="pgaptmp_001995" label="rRNA 23S ribosomal RNA lcl|sc217_sz5123:2040-4937 pgaptmp_001995"/>
        <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="CDS" product="hypothetical protein" location="lcl|sc217_sz5123:3438-3626" locus_tag="pgaptmp_001996" label="CDS hypothetical protein lcl|sc217_sz5123:3438-3626 pgaptmp_001996"/>
      </details>
      <details message="## coding regions completely contain tRNAs" severity="FATAL" cardinality="1" unit="coding region">
        <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="tRNA" product="Leu" location="lcl|sc101_sz22132:17651-17732" locus_tag="pgaptmp_000038" label="tRNA Leu lcl|sc101_sz22132:17651-17732 pgaptmp_000038"/>
        <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="CDS" product="hypothetical protein" location="lcl|sc101_sz22132:c17823-17644" locus_tag="pgaptmp_000037" label="CDS hypothetical protein lcl|sc101_sz22132:c17823-17644 pgaptmp_000037"/>
      </details>
      <details message="## coding regions overlap RNAs (no containment)" severity="WARNING" cardinality="1" unit="coding regions overlap RNA">
        <details message="## coding regions overlap RNAs on the same strand (no containment)" severity="WARNING" cardinality="1" unit="coding region">
          <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="tRNA" product="Leu" location="lcl|sc104_sz21297:c7370-7288" locus_tag="pgaptmp_000086" label="tRNA Leu lcl|sc104_sz21297:c7370-7288 pgaptmp_000086"/>
          <object type="feature" file="/tmp/tmp17jbkpa5/stg7d5c0c80-b615-4833-bb3a-cfac7e2f9fe1/annot-wo-checksum.sqn" feature_type="CDS" product="M48 family metallopeptidase" location="lcl|sc104_sz21297:c8224-7349" locus_tag="pgaptmp_000087" label="CDS M48 family metallopeptidase lcl|sc104_sz21297:c8224-7349 pgaptmp_000087"/>
        </details>
      </details>
    </details>
  </test>`

Your input genome (with our annotation) failed a RNA_CDS_OVERLAP test (see `test[@name]`) 

Judging by locations (see `object[@label]` attributes) you have 3 different overlaps like that. Only two of them are FATAL: 

- you have a 23S ribosomal RNA at location `lcl|sc217_sz5123:2040-4937` that completely contains a hypothetical protein `lcl|sc217_sz5123:3438-3626`  on the same strand
- you have a tRNA for Leucine (`lcl|sc101_sz22132:17651-17732`) that is contained completely by a hypothetical protein on the other strand: `lcl|sc101_sz22132:c17823-17644`

To investigate further we would need your test case input in our hands. Alternatively, you can have a closer look at the sequence you have and the annotation that is in the output `output/annot.sqn`. 

Would you be able to locate aforementioned locations in the output file  `output/annot.sqn` or  `output/annot.gbk` or post any of the files (minus nucleotide sequence)? Note that if you post complete `output/annot.sqn`  you will expose your input sequence to public if you post it here. 

It could be easier for you to post relevant snippets from `output/annot.gbk` (but it has less information).

**Comment by Mayankguptai** [comment]
Ok, I am attaching annotation file of these two scaffolds in the attachment. PFA.
I also checked the annotation file generated by an older version (2019-08-01.build3919) on the same genome assembly file, these hypothetical proteins lcl|sc217_sz5123:3438-3626 and lcl|sc101_sz22132:c17823-17644 are not there.

[annot_new.zip](https://github.com/ncbi/pgap/files/4293557/annot_new.zip)

**Comment by azat-badretdin** [comment]
Thanks for the data! Apologies for not replying earlier. I tried to reproduce the problem given the data you posted, unfortunately, turned out we can't go past Genemark training stage with small data like this. Any chance we can get the complete genome for testing?

**Comment by azat-badretdin** [comment]
> turned out we can't go past Genemark training stage with small data like this.

**Comment by Mayankguptai** [comment]
How can I send/share the full genome without making it public?

**Comment by Mayankguptai** [comment]
> 
> 
> How can I send/share the full genome without making it public?

Can I send it through email?

**Comment by azat-badretdin** [comment]
Let me check

**Comment by azat-badretdin** [comment]
Could you please post `ls -ltr` in your directory?

**Comment by Mayankguptai** [comment]
> 
> 
> Could you please post `ls -ltr` in your directory?
@azat-badretdin, is it for me?

**Comment by Mayankguptai** [comment]
> 
> 
> > Could you please post `ls -ltr` in your directory?
> > @azat-badretdin, is it for me?

total 94M
-rw-rw-r-- 1 mayank mayank 5.9M Aug 27  2019 MO2_out.fna
-rw-rw-r-- 1 mayank mayank 1023 Mar 17 19:35 submol.yaml
drwxrwxr-x 5 mayank mayank   65 Mar 17 19:38 debug
-rw-r--r-- 1 mayank mayank  31M Mar 17 22:39 annot.sqn
-rw-r--r-- 1 mayank mayank 5.9M Mar 17 22:39 annot.fna
-rw-r--r-- 1 mayank mayank 2.0M Mar 17 22:39 annot.faa
-rw-r--r-- 1 mayank mayank 2.4M Mar 17 22:39 annot.gff
-rw-r--r-- 1 mayank mayank  14M Mar 17 22:39 annot.gbk
-rw-rw-r-- 1 mayank mayank  33M Mar 17 22:39 cwltool.log

**Comment by azat-badretdin** [comment]
My apologies, indeed, too many tickets at once, criss crossed the questions.

**Comment by azat-badretdin** [comment]
Let's try this:

Could you please send your genome here: prokaryote-tools@nih.gov and add the url of this page into the text?

Thanks!

**Comment by Mayankguptai** [comment]
> 
> 
> Let's try this:
> 
> Could you please send your genome here: [prokaryote-tools@nih.gov](mailto:prokaryote-tools@nih.gov) and add the url of this page into the text?
> 
> Thanks!

Yeah sure. Just sent.

**Comment by azat-badretdin** [comment]
Could you please post here or send `submol.yaml` file? Thanks!

**Comment by Mayankguptai** [comment]
> Could you please post here or send `submol.yaml` file? Thanks!

Yeah sure, PFA.

[submol.yaml.txt](https://github.com/ncbi/pgap/files/4481452/submol.yaml.txt)

**Comment by azat-badretdin** [comment]
The original sequence you posted:

```>sc217_sz5123 Kamptonema formosum strain BDU30603, whole genome shotgun sequence```

was successfully processed with July version of PGAPX
