### ISSUE TITLE
how to run PGAP in local machine

### ISSUE THREAD

**Issue by shakti83kumar** [ncbi/pgap#65]
Hello Sir,
I am Shakti Kumar trying to annotate some assemble genomes by PGAP by installing it in my local machine.
I followed the Quick Start to download all required packages. I also installed some others for softwares and databases as mentioned in bellow links.
https://www.ncbi.nlm.nih.gov/genome/annotation_prok/release_notes/
After that I went through the test_genomes in which various examples are there. I have chosen SAMN09839044 directory that is suitable to my data. Then I have edited yml file in which I have mentioned my assembled genome name that I have attached bellow.
[CHME20200106.zip](https://github.com/ncbi/pgap/files/4297225/CHME20200106.zip)
After running I am getting following error.
************ERROR**************************
sudo ./pgap.py -r -o mg37_results ~/test_genomes/CHME20200106/input.yaml
[sudo] password for adapt: 
PGAP version 2020-02-06.build4373 is up to date.
Output will be placed in: /home/adapt/Softwares/pgap-master/scripts/mg37_results.4
PGAP failed, docker exited with rc = 1
Printing log starting from failed job:

[2020-03-06 07:04:54] INFO [step pgapx_yaml_ctl] start
[2020-03-06 07:04:54] INFO [job pgapx_yaml_ctl] /tmp/uoyx0xl5$ pgapx_yaml_ctl \
    -ifmt \
    JSON \
    -input \
    /tmp/tmppqmyiqwh/stg9c0af480-aaf0-4c2a-99ec-5eaec525003d/submol.json \
    -input-fasta \
    /tmp/tmppqmyiqwh/stga2584957-b391-471b-971d-f2fa3670e720/CHME20200106_R3_REPEAT_Lactobacillus_S1_L001_assembly_454Scaffolds.fna \
    -ofmt \
    JSON \
    -output-annotation \
    input.asn \
    -output-asn-type \
    input_asn_type.txt \
    -output-ltp \
    genome.ltp.txt \
    -output-taxid \
    taxid.txt \
    -taxon-db \
    /tmp/tmppqmyiqwh/stg61e08e09-7c74-4435-8f32-512bfe40d385/taxonomy.sqlite3
terminate called after throwing an instance of 'ncbi::CSerialException'
  what():  NCBI C++ Exception:
    Error: SERIAL(CSerialException::eFormatError) "/export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/objistrjson.cpp", line 201: ncbi::CObjectIStreamJson::Expect() --- line 1: '}' expected ( at JsonValue.organism)
     Stack trace:
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/corelib/ncbi_stack_libbackward.cpp:82 ncbi::CStackTraceImpl::CStackTraceImpl() offset=0x0 addr=0x7f80e18141f9
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/corelib/ncbi_stack.cpp:79 ncbi::CStackTrace::CStackTrace(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) offset=0x0 addr=0x7f80e18150e6
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/corelib/ncbiexpt.cpp:583 ncbi::CException::x_GetStackTrace() offset=0x0 addr=0x7f80e18a2220
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/corelib/ncbiexpt.cpp:208 ncbi::CException::CException(ncbi::CDiagCompileInfo const&, ncbi::CException const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ncbi::EDiagSev, int) offset=0x0 addr=0x7f80e18a1dd4
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/lib/libtaxon1.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/exception.hpp:67 ncbi::CSerialException::CSerialException(ncbi::CDiagCompileInfo const&, ncbi::CException const*, ncbi::CSerialException::EErrCode, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ncbi::EDiagSev) offset=0x0 addr=0x7f80e8be9575
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/objistr.cpp:832 ncbi::CObjectIStream::ThrowError1(ncbi::CDiagCompileInfo const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) offset=0x0 addr=0x7f80e2233843
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/objistrjson.cpp:201 ncbi::CObjectIStreamJson::Expect(char, bool) offset=0x0 addr=0x7f80e22aa2c0
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/objistrjson.cpp:424 ncbi::CObjectIStreamJson::EndBlock(char) offset=0x0 addr=0x7f80e22acd56
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/objistr.cpp:1374 ncbi::CObjectIStream::ReadClassRandom(ncbi::CClassTypeInfo const*, void*) offset=0x0 addr=0x7f80e2235d64
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/objistr.inl:95 ReadData offset=0x0 addr=(nil)
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/objistr.cpp:1148 ReadObject offset=0x0 addr=(nil)
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/typeinfo.inl:69 ncbi::CObjectIStream::ReadPointer(ncbi::CTypeInfo const*) offset=0x0 addr=0x7f80e22387ba
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/ptrinfo.cpp:225 ncbi::CPointerTypeInfo::ReadPointer(ncbi::CObjectIStream&, ncbi::CTypeInfo const*, void*) offset=0x0 addr=0x7f80e2219e2f
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/objistr.inl:95 ReadData offset=0x0 addr=(nil)
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/member.cpp:727 ReadObject offset=0x0 addr=(nil)
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/typeinfo.inl:69 ncbi::CMemberInfoFunctions::ReadSimpleMember(ncbi::CObjectIStream&, ncbi::CMemberInfo const*, void*) offset=0x0 addr=0x7f80e222434d
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/objistr.cpp:1367 ReadMember offset=0x0 addr=(nil)
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/member.inl:104 ncbi::CObjectIStream::ReadClassRandom(ncbi::CClassTypeInfo const*, void*) offset=0x0 addr=0x7f80e2235c11
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/objistr.inl:95 ReadData offset=0x0 addr=(nil)
       /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/objistr.cpp:944 ReadObject offset=0x0 addr=(nil)
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/include/serial/impl/typeinfo.inl:69 ncbi::CObjectIStream::Read(void*, ncbi::CTypeInfo const*, ncbi::CObjectIStream::ENoFileHeader) offset=0x0 addr=0x7f80e223c669
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/lib/libxser.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/serialobject.cpp:781 ncbi::ReadObject(std::istream&, void*, ncbi::CTypeInfo const*) offset=0x0 addr=0x7f80e22b1b95
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/bin/pgapx_yaml_ctl :0  offset=0x0 addr=0x417a49
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/corelib/ncbiapp.cpp:626 ncbi::CNcbiApplicationAPI::x_TryMain(ncbi::EAppDiagStream, char const*, int*, bool*) offset=0x0 addr=0x7f80e18281b2
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/lib/libxncbi.so /export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/corelib/ncbiapp.cpp:893 ncbi::CNcbiApplicationAPI::AppMain(int, char const* const*, char const* const*, ncbi::EAppDiagStream, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) offset=0x0 addr=0x7f80e182a4ac
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/bin/pgapx_yaml_ctl :0  offset=0x0 addr=0x40c773
      /usr/lib64/libc-2.17.so :0  offset=0x0 addr=0x7f80e055c504
      /panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/bin/pgapx_yaml_ctl :0  offset=0x0 addr=0x40c914
       :0  offset=0x0 addr=0xffffffffffffffff

Stack trace (most recent call last):
#14   Object "", at 0xffffffffffffffff, in 
#13   Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/bin/pgapx_yaml_ctl", at 0x40c914, in _start
#12   Object "/usr/lib64/libc-2.17.so", at 0x7f80e055c504, in __libc_start_main
#11   Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/bin/pgapx_yaml_ctl", at 0x40c773, in main
#10   Source "/export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/corelib/ncbiapp.cpp", line 893, in AppMain [0x7f80e182a4ac]
#9    Source "/export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/corelib/ncbiapp.cpp", line 626, in x_TryMain [0x7f80e18281b2]
#8    Object "/panfs/pan1.be-md.ncbi.nlm.nih.gov/gpipe/bacterial_pipeline/system/2020-02-06.build4373/arch/x86_64/bin/pgapx_yaml_ctl", at 0x417a49, in CPgapxYamlCtlApplication::Run()
#7    Source "/export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/serialobject.cpp", line 781, in ReadObject [0x7f80e22b1b95]
#6    Source "/export/home/gpipe/TeamCity/Agent1/work/87e607601d01cc4f/ncbi_cxx/src/serial/objistr.cpp", line 948, in Read [0x7f80e223c7cc]
#5    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/eh_throw.cc", line 131, in __cxa_rethrow [0x7f80e0ddc2b5]
#4    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/eh_terminate.cc", line 57, in terminate [0x7f80e0ddc020]
#3    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/eh_terminate.cc", line 47, in __cxa_begin_catch [0x7f80e0ddbfd5]
#2    Source "../../../../gcc-7.3.0/libstdc++-v3/libsupc++/vterminate.cc", line 95, in __verbose_terminate_handler [0x7f80e0dde1e4]
#1    Object "/usr/lib64/libc-2.17.so", at 0x7f80e0571a27, in abort
#0    Object "/usr/lib64/libc-2.17.so", at 0x7f80e0570337, in raise
Aborted (Signal sent by tkill() 246 0)
[2020-03-06 07:04:55] ERROR [job pgapx_yaml_ctl] Job error:
("Error collecting output for parameter 'input_asn_type':\npgap/progs/pgapx_yaml_ctl.cwl:75:13: Did not find output file with glob pattern: '['input_asn_type.txt']'", {})
[2020-03-06 07:04:55] WARNING [job pgapx_yaml_ctl] completed permanentFail
[2020-03-06 07:04:55] ERROR [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/output_annotation
[2020-03-06 07:04:55] ERROR [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/output_ltp
[2020-03-06 07:04:55] ERROR [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/input_asn_type
[2020-03-06 07:04:55] ERROR [step pgapx_yaml_ctl] Output is missing expected field file:///pgap/pgap/prepare_user_input2.cwl#pgapx_yaml_ctl/taxid
[2020-03-06 07:04:55] WARNING [step pgapx_yaml_ctl] completed permanentFail
[2020-03-06 07:04:55] INFO [workflow prepare_input_template] completed permanentFail
[2020-03-06 07:04:55] WARNING [step prepare_input_template] completed permanentFail
[2020-03-06 07:04:55] INFO [workflow ] completed permanentFail
[2020-03-06 07:04:55] WARNING Final process status is permanentFail
{
    "gbk": null,
    "gff": null,
    "input_fasta": {
        "class": "File",
        "location": "file:///pgap/output/CHME20200106_R3_REPEAT_Lactobacillus_S1_L001_assembly_454Scaffolds.fna",
        "size": 1955365,
        "basename": "CHME20200106_R3_REPEAT_Lactobacillus_S1_L001_assembly_454Scaffolds.fna",
        "checksum": "sha1$300b84297a5ed14017a11c64c53145b1ee548d86",
        "path": "/pgap/output/CHME20200106_R3_REPEAT_Lactobacillus_S1_L001_assembly_454Scaffolds.fna"
    },
    "input_submol": {
        "class": "File",
        "location": "file:///pgap/output/submol.yaml",
        "size": 1515,
        "basename": "submol.yaml",
        "checksum": "sha1$bfbad5a1de842401459c45115e28ae3ff8c8e3e4",
        "path": "/pgap/output/submol.yaml"
    },
    "nucleotide_fasta": null,
    "protein_fasta": null,
    "sqn": null

**Comment by azat-badretdin** [comment]
Could you please post `submol.yaml` file?

**Comment by shakti83kumar** [comment]
Sir..
I have sent it in zip file.

**Comment by azat-badretdin** [comment]
Thanks, Shakti. Do you have by any chance `find . -name submol.json` in your local directory? 

If not, would you mind rerunning with `pgap.py -d` option?

Thanks.

**Comment by shakti83kumar** [comment]
I have to look then I will tell you... Thanks for prompt reply

**Comment by azat-badretdin** [comment]
Any updates?

**Comment by shakti83kumar** [comment]
Dear azat-badretdin,
Sorry for not respond at right time due to some problem in my institute's internet.
I run 
find . -name submol.json
OUTPUT is 
./test_genomes-2020-02-06.build4373/pathogen/submol.json
find: ‘./mg37_results.6/debug/tmp-outdir/jwt233ah’: Permission denied
find: ‘./mg37_results.6/debug/tmp-outdir/yzmp4j1q’: Permission denied
find: ‘./mg37_results.6/debug/tmp-outdir/kij0qlba’: Permission denied
find: ‘./mg37_results.6/debug/tmp-outdir/717klq5c’: Permission denied
find: ‘./mg37_results.6/debug/tmp-outdir/ciacsab1’: Permission denied
find: ‘./mg37_results.6/debug/tmp-outdir/4wazrnmf’: Permission denied
find: ‘./mg37_results.6/debug/tmp-outdir/i1o3uji5’: Permission denied
find: ‘./mg37_results.6/debug/tmp-outdir/oczaiuin’: Permission denied

**Comment by azat-badretdin** [comment]
Could you please post `./test_genomes-2020-02-06.build4373/pathogen/submol.json` to this ticket?

**Comment by shakti83kumar** [comment]
![Screenshot from 2020-03-16 20-21-19](https://user-images.githubusercontent.com/47470792/76770314-bf0ff880-67c3-11ea-8fe7-d031fdeeadfd.png)
Sir, this is submol.json that present in test_genomes-2020-02-06.build4373/pathogen/ folder
{
   "authors" : [
      {
         "author" : {
            "middle_initial" : "T",
            "last_name" : "Schwarzenegger",
            "first_name" : "Arnold"
         }
      },
      {
         "author" : {
            "last_name" : "Hamilton",
            "first_name" : "Linda"
         }
      }
   ],
   "contact_info" : {
      "country" : "Lappland",
      "department" : "Department of Using NCBI",
      "street" : "1234 Main St",
      "phone" : "301-555-0245",
      "last_name" : "Doe",
      "email" : "jane_doe@gmail.com",
      "city" : "Docker",
      "postal_code" : "12345",
      "organization" : "NCBI",
      "first_name" : "Jane"
   }
}

**Comment by azat-badretdin** [comment]
Thanks! Looking at this now.

**Comment by azat-badretdin** [comment]
This part of your input `submol.yaml` file is outdated:

```
organism:
    taxon:  1578
    strain: 'replaceme'
```
This is correct one:

```
organism:
    genus_species: 'Mycoplasma genitalium' 
    strain: 'replaceme'

```

**Comment by shakti83kumar** [comment]
Hi Azat Sir,
But I have confirmed that the genome belong to Lactobacillus genus by 16S based analysis. 
Now How can I edit submol.yaml file if species has not indentified

**Comment by azat-badretdin** [comment]
>if species has not indentified

**Comment by shakti83kumar** [comment]
OK Sir, I will run then tell you

**Comment by shakti83kumar** [comment]
Dear Sir,
I ran, I got following error:
sudo ./pgap.py -r -o mg37_results ~/test_genomes/CHME20200106/input.yaml
[sudo] password for adapt: 
PGAP version 2020-02-06.build4373 is up to date.
Output will be placed in: /home/adapt/Softwares/pgap-master/scripts/mg37_results.7
PGAP failed, docker exited with rc = 1
Printing log starting from failed job:

[2020-03-17 11:21:47] INFO [step Prepare_Unannotated_Sequences_pgapx_input_check] start
[2020-03-17 11:21:47] INFO [job Prepare_Unannotated_Sequences_pgapx_input_check] /tmp/jerf0fnt$ pgapx_input_check \
    -nogenbank \
    -input \
    /tmp/tmpqcx7gayl/stgc4bb9a09-f860-436f-83cc-5de1e2aa48b9/sequences.asn \
    -max-size \
    15000000 \
    -min-size \
    300 \
    -species-genome-size \
    /tmp/tmpqcx7gayl/stg2ad1017e-9377-4c97-9d67-237c4f624dc4/species_genome_size.txt \
    -taxon-db \
    /tmp/tmpqcx7gayl/stg501a43aa-d053-46a7-b8e4-cbb032cd732d/taxonomy.sqlite3
choosing min/max for populated genome for species: 1582, ngenomes = 26
min = 2360000
max = 3642000
genome_size = 1922496
genome size check: fail
verify-only-n-sequences check: pass
[2020-03-17 11:21:47] WARNING [job Prepare_Unannotated_Sequences_pgapx_input_check] completed permanentFail
[2020-03-17 11:21:47] WARNING [step Prepare_Unannotated_Sequences_pgapx_input_check] completed permanentFail
[2020-03-17 11:21:47] INFO [workflow standard_pgap] completed permanentFail
[2020-03-17 11:21:47] WARNING [step standard_pgap] completed permanentFail
[2020-03-17 11:21:47] INFO [workflow ] completed permanentFail
[2020-03-17 11:21:47] WARNING Final process status is permanentFail
{
    "gbk": null,
    "gff": null,
    "input_fasta": {
        "class": "File",
        "location": "file:///pgap/output/CHME20200106_R3_REPEAT_Lactobacillus_S1_L001_assembly_454Scaffolds.fna",
        "size": 1955365,
        "basename": "CHME20200106_R3_REPEAT_Lactobacillus_S1_L001_assembly_454Scaffolds.fna",
        "checksum": "sha1$300b84297a5ed14017a11c64c53145b1ee548d86",
        "path": "/pgap/output/CHME20200106_R3_REPEAT_Lactobacillus_S1_L001_assembly_454Scaffolds.fna"
    },
    "input_submol": {
        "class": "File",
        "location": "file:///pgap/output/submol.yaml",
        "size": 1539,
        "basename": "submol.yaml",
        "checksum": "sha1$eda8564919a68b6ad160f82669b9ae1f764a3521",
        "path": "/pgap/output/submol.yaml"
    },
    "nucleotide_fasta": null,
    "protein_fasta": null,
    "sqn": null
}

**Comment by azat-badretdin** [comment]
It says that your genome is too short for this taxonomy:

```choosing min/max for populated genome for species: 1582, ngenomes = 26
min = 2360000
max = 3642000
genome_size = 1922496
genome size check: fail```

The range of sizes for species 1582 is from 2360000 to 3642000 and the genome is too short: 1922496

**Comment by shakti83kumar** [comment]
OK Sir ..
I will check it

**Comment by shakti83kumar** [comment]
Dear Sir,
I ran after editing submol.yaml by adding following Lactobacillus acidophilus which genome size is similar to my sequence. 
After running I got following error:
sudo ./pgap.py -r -o mg37_results ~/test_genomes/CHME20200106/input.yaml
PGAP version 2020-02-06.build4373 is up to date.
Output will be placed in: /home/adapt/Softwares/pgap-master/scripts/mg37_results.9
PGAP failed, docker exited with rc = 1
Printing log starting from failed job:

[2020-03-17 11:40:17] INFO [step Prepare_Unannotated_Sequences_asnvalidate_evaluate] start
[2020-03-17 11:40:17] INFO [job Prepare_Unannotated_Sequences_asnvalidate_evaluate] /tmp/4uaixog6$ xml_evaluate \
    -input \
    /tmp/tmp6n0lndaf/stgac48cab1-452a-43ac-b910-07f3c81400bc/sequences.val \
    -xpath-fail \
    '//*[
    ( @severity="ERROR" or @severity="REJECT" )
    and not(contains(@code, "SEQ_DESCR_UnwantedCompleteFlag")) 
    and not(contains(@code, "SEQ_PKG_NucProtProblem")) 
    and not(contains(@code, "SEQ_INST_InternalNsInSeqRaw")) 
    and not(contains(@code, "GENERIC_MissingPubRequirement")) 
    and not(contains(@code, "SEQ_INST_ProteinsHaveGeneralID")) 
    and not(contains(@code, "SEQ_PKG_ComponentMissingTitle")) 
    and not(contains(@code, "SEQ_DESCR_ChromosomeLocation")) 
    and not(contains(@code, "SEQ_DESCR_MissingLineage")) 
    and not(contains(@code, "SEQ_DESCR_NoTaxonID")) 
    and not(contains(@code, "SEQ_FEAT_ShortIntron")) 
    and not(contains(@code, "SEQ_DESCR_OrganismIsUndefinedSpecies"))
    and not(contains(@code, "SEQ_DESCR_StrainWithEnvironSample"))
    and not(contains(@code, "SEQ_DESCR_BacteriaMissingSourceQualifier"))
]
' > /tmp/4uaixog6/stdout
[2020-03-17 11:40:17] WARNING [job Prepare_Unannotated_Sequences_asnvalidate_evaluate] completed permanentFail
[2020-03-17 11:40:17] WARNING [step Prepare_Unannotated_Sequences_asnvalidate_evaluate] completed permanentFail
[2020-03-17 11:40:17] INFO [workflow standard_pgap] completed permanentFail
[2020-03-17 11:40:17] WARNING [step standard_pgap] completed permanentFail
[2020-03-17 11:40:17] INFO [workflow ] completed permanentFail
{
    "gbk": null,
    "gff": null,
    "input_fasta": {
        "class": "File",
        "location": "file:///pgap/output/CHME20200106_R3_REPEAT_Lactobacillus_S1_L001_assembly_454Scaffolds.fna",
        "size": 1955365,
        "basename": "CHME20200106_R3_REPEAT_Lactobacillus_S1_L001_assembly_454Scaffolds.fna",
        "checksum": "sha1$300b84297a5ed14017a11c64c53145b1ee548d86",
        "path": "/pgap/output/CHME20200106_R3_REPEAT_Lactobacillus_S1_L001_assembly_454Scaffolds.fna"
    },
    "input_submol": {
        "class": "File",
        "location": "file:///pgap/output/submol.yaml",
        "size": 1545,
        "basename": "submol.yaml",
        "checksum": "sha1$1edb6a29e28b25f00eb14f089bf1fb215e5a1cea",
        "path": "/pgap/output/submol.yaml"
    },
    "nucleotide_fasta": null,
    "protein_fasta": null,
    "sqn": null
}
[2020-03-17 11:40:17] WARNING Final process status is permanentFail

**Comment by azat-badretdin** [comment]
Could you please rerun it with additional `pgap.py -d` option? This will save the error output files you can find by looking through `find . -name xml_evaluate.\*`

**Comment by shakti83kumar** [comment]
I ran pgap with -d option as you mentioned.
I again got error as following
PGAP version 2020-02-06.build4373 is up to date.
Output will be placed in: /home/adapt/Softwares/pgap-master/scripts/mg37_results.11
PGAP failed, docker exited with rc = 1
Printing log starting from failed job:

[2020-03-17 12:26:10] INFO [step Prepare_Unannotated_Sequences_asnvalidate_evaluate] start
[2020-03-17 12:26:11] INFO [job Prepare_Unannotated_Sequences_asnvalidate_evaluate] /pgap/output/debug/tmp-outdir/8qb0o2sd$ xml_evaluate \
    -input \
    /tmp/tmpxcv36ayd/stg16936cee-2efc-41c8-bbd1-8dd46aa678a0/sequences.val \
    -xpath-fail \
    '//*[
    ( @severity="ERROR" or @severity="REJECT" )
    and not(contains(@code, "SEQ_DESCR_UnwantedCompleteFlag")) 
    and not(contains(@code, "SEQ_PKG_NucProtProblem")) 
    and not(contains(@code, "SEQ_INST_InternalNsInSeqRaw")) 
    and not(contains(@code, "GENERIC_MissingPubRequirement")) 
    and not(contains(@code, "SEQ_INST_ProteinsHaveGeneralID")) 
    and not(contains(@code, "SEQ_PKG_ComponentMissingTitle")) 
    and not(contains(@code, "SEQ_DESCR_ChromosomeLocation")) 
    and not(contains(@code, "SEQ_DESCR_MissingLineage")) 
    and not(contains(@code, "SEQ_DESCR_NoTaxonID")) 
    and not(contains(@code, "SEQ_FEAT_ShortIntron")) 
    and not(contains(@code, "SEQ_DESCR_OrganismIsUndefinedSpecies"))
    and not(contains(@code, "SEQ_DESCR_StrainWithEnvironSample"))
    and not(contains(@code, "SEQ_DESCR_BacteriaMissingSourceQualifier"))
]
' > /pgap/output/debug/tmp-outdir/8qb0o2sd/stdout
[2020-03-17 12:26:11] WARNING [job Prepare_Unannotated_Sequences_asnvalidate_evaluate] completed permanentFail
[2020-03-17 12:26:11] WARNING [step Prepare_Unannotated_Sequences_asnvalidate_evaluate] completed permanentFail
[2020-03-17 12:26:11] INFO [workflow standard_pgap] completed permanentFail
[2020-03-17 12:26:11] WARNING [step standard_pgap] completed permanentFail
[2020-03-17 12:26:11] INFO [workflow ] completed permanentFail
[2020-03-17 12:26:11] WARNING Final process status is permanentFail
{
    "gbk": null,
    "gff": null,
    "input_fasta": {
        "class": "File",
        "location": "file:///pgap/output/CHME20200106_R3_REPEAT_Lactobacillus_S1_L001_assembly_454Scaffolds.fna",
        "size": 1955365,
        "basename": "CHME20200106_R3_REPEAT_Lactobacillus_S1_L001_assembly_454Scaffolds.fna",
        "checksum": "sha1$300b84297a5ed14017a11c64c53145b1ee548d86",
        "path": "/pgap/output/CHME20200106_R3_REPEAT_Lactobacillus_S1_L001_assembly_454Scaffolds.fna"
    },
    "input_submol": {
        "class": "File",
        "location": "file:///pgap/output/submol.yaml",
        "size": 1546,
        "basename": "submol.yaml",
        "checksum": "sha1$a629856eaa25d70eb9974dde684b7f54d9fcdaf4",
        "path": "/pgap/output/submol.yaml"
    },
    "nucleotide_fasta": null,
    "protein_fasta": null,
    "sqn": null
}

I got a cwltool.log.
[cwltool.log](https://github.com/ncbi/pgap/files/4343431/cwltool.log)

**Comment by azat-badretdin** [comment]
What about this step:

```you can find by looking through find . -name xml_evaluate.\*```

Could you please run this command?

**Comment by mriglobal** [comment]
I am having a similar issue running PGAP on an assembly of mine. I am getting this exact error as seen in an above post, which makes me wonder if it is an issue with my assembly or config files.

find . -name xml* or xml_evaluate.\* returns nothing, though I've run pgap with the -d flag. What information can I provide to better resolve this?

( @Severity="ERROR" or @Severity="REJECT" )
and not(contains(@code, "SEQ_DESCR_UnwantedCompleteFlag"))
and not(contains(@code, "SEQ_PKG_NucProtProblem"))
and not(contains(@code, "SEQ_INST_InternalNsInSeqRaw"))
and not(contains(@code, "GENERIC_MissingPubRequirement"))
and not(contains(@code, "SEQ_INST_ProteinsHaveGeneralID"))
and not(contains(@code, "SEQ_PKG_ComponentMissingTitle"))
and not(contains(@code, "SEQ_DESCR_ChromosomeLocation"))
and not(contains(@code, "SEQ_DESCR_MissingLineage"))
and not(contains(@code, "SEQ_DESCR_NoTaxonID"))
and not(contains(@code, "SEQ_FEAT_ShortIntron"))
and not(contains(@code, "SEQ_DESCR_OrganismIsUndefinedSpecies"))
and not(contains(@code, "SEQ_DESCR_StrainWithEnvironSample"))
and not(contains(@code, "SEQ_DESCR_BacteriaMissingSourceQualifier"))
]

**Comment by azat-badretdin** [comment]
Would you mind repeating this with a newest release (2020-07-09.build...)?

**Comment by mriglobal** [comment]
I have pulled the latest docker and codebase and receive the same messages.

**Comment by azat-badretdin** [comment]
Could you please run `find . -name initial_asnval_diag.xml`?

**Comment by mriglobal** [comment]
It reads:

> Failer nodes:
<?xml version="1.0" encoding="UTF-8"?>
<message severity="ERROR" seq-id="lcl|1" code="SEQ_DESCR_DBLinkBadSRAaccession">Bad Sequence Read Archive format - Not yet assigned</message>
<?xml version="1.0" encoding="UTF-8"?>
<message severity="ERROR" seq-id="lcl|2" code="SEQ_DESCR_DBLinkBadSRAaccession">Bad Sequence Read Archive format - Not yet assigned</message>
<?xml version="1.0" encoding="UTF-8"?>
<message severity="ERROR" seq-id="lcl|3" code="SEQ_DESCR_DBLinkBadSRAaccession">Bad Sequence Read Archive format - Not yet assigned</message>
<?xml version="1.0" encoding="UTF-8"?>
<message severity="ERROR" seq-id="lcl|4" code="SEQ_DESCR_DBLinkBadSRAaccession">Bad Sequence Read Archive format - Not yet assigned</message>

**Comment by azat-badretdin** [comment]
It is supposed to have an XML format. Could you please open a new ticket for this problem? Please post your input and output, including the file (please attach it). Thanks!
