### ISSUE TITLE
[BUG] ./pgap.py --update SyntaxError: invalid syntax Line 155

### ISSUE THREAD

**Issue by nfellaby** [ncbi/pgap#66]
I appear to be unable to run the update command to download the required files, as explained in the quick start wiki guide. Using Python 3.5.2 and Docker version 19.03.8, build afacb8b7f0 on Ubuntu.

> ./pgap.py --update

Returned:
>   File "./pgap.py", line 155
>     self.cwlfile = f"pgap/{pipeline}.cwl"
>                                         ^
> SyntaxError: invalid syntax

I was expecting the script to download the appropriate files.

**Software versions (please complete the following information):**
 - OS: Linux os3 4.4.0-171-generic #200-Ubuntu SMP Tue Dec 3 11:04:55 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - pgap.py --version, downloaded as of today (2020-03-25)
 - Docker (or other container runner) version. Docker version 19.03.8,

**Log Files**
Unable to produce any log files.

**Comment by slottad** [comment]
I just tried this on a generic Linux machine and had no trouble. Was this a fresh download of `pgap.py`?

**Comment by slottad** [comment]
Oh, sorry, you said it was.  Perhaps it got corrupted, maybe try and download it again?

**Comment by nfellaby** [comment]
I have tried it quite a few times. Honestly I usually find answers to this sort of errors, but there was nothing out there. What version of python are you using?

**Comment by nfellaby** [comment]
So I've tried this on a separate, local, machine and it appears to work fine. But that was using python 3.6+.

**Comment by slottad** [comment]
Ah, sorry, this is entirely my fault. We are now using features which require Python 3.6. While we are deciding whether to require Python 3.6 or change the script, the quickest fix for you would be to use a newer version of Python.

**Comment by slottad** [comment]
Looks like our responses crossed (with you slightly beating me).

**Comment by nfellaby** [comment]
Ah okay that makes sense. Guess you just need to update the requirements in the wiki.

**Comment by slottad** [comment]
Yes, since Python 3.5 will come to its End Of Life this year, it looks that is what we'll do.

Thank you for bringing this to our attention, and sorry for the inconvenience.

**Comment by gilmahu** [comment]
I have been trying to run PGAP from my Mac with Docker enabled and so far I get only permanentFail results including with the M27 example in the installation files. 
 
My machine is 8-core intel core 9 with a RAM of 16 GB 
Is there anything you can advise? 
I will really appreciate your help.

**Comment by azat-badretdin** [comment]
I am 90% sure that this machine is too weak to run PGAP. 

See https://github.com/ncbi/pgap/wiki/Quick-Start/Requirements:

...
- and 2GB-4GB of memory available per CPU used by your container.
...

16Gb barely fits the requirement. Could you please please post a snippet from your log with the first permanentFail? Is it cluster_blastp_wnode step?

**Comment by gilmahu** [comment]
[cwltool.log](https://github.com/ncbi/pgap/files/5118301/cwltool.log)
Thank you so much sir for the very fast response. 
I honestly am new to the pipeline but found it to be much useful. 
Attached in the cwl log fo the run maybe it can help you to guide me more?? 
And in this case with my RAM being lower what do you suggest I could do to circumvent this?

**Comment by azat-badretdin** [comment]
> cwltool.log

Yep, my hypothesis confirmed, first permafail came from this job:

> [2020-08-24 13:56:24] WARNING [job cluster_blastp_wnode] completed permanentFail

This is an indication to "machine is too small". Looks like you are in a very beginning of testing PGAP given that you are running a Quick Start example (MG37 is one of the smallest prokaryotic genomes).  Do you have access to larger machines? Department UNIX cloud maybe? It does not have to be your personal computer, given that PGAP is quite heavy beast with dozens of gigabytes of reference data to provide robust and modern annotation by reference, personal computers are basically borderline given that reference data size noticeably grew since the beginning of the development of cloud version of PGAP.

**Comment by gilmahu** [comment]
Okay. Bad news for me. 
I have heard of a computerroam availability at the Faculty but I will ask around and then see how that can be of help. 
Thank you very much for the promptitude.
Best regards

**Comment by whlavina** [comment]
On a Mac, you should be able to reduce the apparent CPU via Docker Preferences (effectively increasing the memory per CPU). You may wish to try that. If it works, please let us know.

**Comment by gilmahu** [comment]
@whlavina How is that done? I first change the CPU in docker or?

**Comment by azat-badretdin** [comment]
Maybe this will help? https://docs.docker.com/docker-for-mac/

**Comment by gilmahu** [comment]
Great. Would you advise any specific CPU and memories for these exercises? I reduced cpu to 2 and brought memory to 8 then restarted and when I go to my terminal to run PGAP i get the same memory warnings

**Comment by azat-badretdin** [comment]
Warnings or errors? Do you get `permanentFail` messages?

**Comment by gilmahu** [comment]
Not yet it's still running. But the "warning: memory per CPU is less than the recommended value of 2" is the first message that I got below the command and I'm sure it is going to fail. 
Or was I not supposed to run it on the mac's terminal? I'm quite new to the whole thing so maybe there is a separate terminal for the docker instead?

**Comment by azat-badretdin** [comment]
I am 90% sure this has nothing to do with terminals.

**Comment by gilmahu** [comment]
Okay. I asked earlier if I want to modify the parameters in docker to see if it works what CPU and memory do you think can work?

**Comment by azat-badretdin** [comment]
I do not know. That's why I suggested to wait until your execution reaches conclusion (either completes successfully or permafails)

**Comment by gilmahu** [comment]
Hi @whlavina and @azat-badretdin It was successful. after modifying the parameters in my docker to 4 CPUs and 8 GB. It took almost 3hrs to complete that. But I will try to play around that more to see which is the best so I can be able to run a full Vibrio cholerae genome. Thanks a lot for your supports.

**Comment by azat-badretdin** [comment]
You are welcome! Happy landings!

**Comment by gilmahu** [comment]
Indeed. Do you have any advice about how to run more than one sample at a time?

**Comment by azat-badretdin** [comment]
I do not think it's a good idea, given hefty hardware reqs of PGAP. Currently we are mostly focusing on supporting "one genome at a time per machine" case.

**Comment by gilmahu** [comment]
Thanks for the response. 
After a successful run of the test genomes, I have now tried my own sample; a 4MB Vibrio cholerae genome and I got a permanentFail (this time there was no warning about memory because I fixed that with the docker preferences since yesterday). 
Please see the attached log file and help me diagnose what could be the problem. 
[cwltool.log](https://github.com/ncbi/pgap/files/5129134/cwltool.log)

Best regards

**Comment by azat-badretdin** [comment]
The first permafail is on this job

```[2020-08-26 10:05:22] WARNING [job fastaval] completed permanentFail```

That means that something is wrong with input sequence. Please rerun with `--debug` option and then `find . -name fastaval.xml` it will tell you what exactly is wrong with the input FASTA. Another alternative is try to use `--ignore-all-errors` option of `pgap.py`

**Comment by gilmahu** [comment]
Hello!
I tried with the option --ignore-all-errors and since yesterday it seems to be running well but it's been almost 24hrs cz i left it overnight but as i write now it's running and it has not finished. 
I'm just wondering if I should just terminate the process. 
With the attached "current status of the log" would you suggest?
[cwltool.log](https://github.com/ncbi/pgap/files/5134848/cwltool.log)

**Comment by azat-badretdin** [comment]
It's running now second cluster_blastp_wnode for the last 20 hours. It's interesting that the first cluster_blastp_wnode is usually more demanding computationally.  The fact that the second one is stuck probably indicates that heavy swapping is going on. We had this in the past and it indicates to memory insufficiency.  I would suggest to terminate it.

**Comment by gilmahu** [comment]
Okay! And in this case, is there any other alternative when I want to redo on another genome so as to avoid this same problem?

**Comment by azat-badretdin** [comment]
You can try to play with these options:

```  -c CPUS, --cpus CPUS  Limit the number of CPUs available for execution by
                        the container
  -m MEMORY, --memory MEMORY
                        Memory limit; may add an optional suffix which can be
                        one of b, k, m, or g
```
FAQ says that it does not work right now, but at this point I am out of the options. More powerful computer would be the best advice here (more memory)
