### ISSUE TITLE
Process seems stalled

### ISSUE THREAD

**Issue by gdp3** [ncbi/pgap#67]
**Describe the bug**
After successfully running with the test genome, I started my own 2020-03-30 20:45:06. The last entry in the cwltool.log was 2020-03-31 21:49:06, and yet the process has not ended. Is there any way to capture what has been completed, or should I just kill the process and start over? I am attaching the cwltool.log.
[cwltool.log](https://github.com/ncbi/pgap/files/4421798/cwltool.log)

**Comment by gdp3** [comment]
Since posting, Docker itself crashed. Will update and retry.

**Comment by azat-badretdin** [comment]
Meanwhile, we just released new version of software feel free to try it.

**Comment by gdp3** [comment]
I tried again with 2020-03-30.build4489, which --update reports as up to date. I ran in debug mode, and based on the additional logs it hung at the cluster_blastp_wnode step. There are 95586 lines containing "UNK_CLIENT      UNK_SESSION ". If any of the logs are useful let me know.

**Comment by azat-badretdin** [comment]
What are the machine specs? Number of processors is a huge number one factor for duration of the run since two major steps (blastp) are parallelized to use maximum number of processors.

**Comment by gdp3** [comment]
Host hardware specs: Mac Pro (Mid 2010), 3.33 GHz 6-Core Intel Xeon, 48 GB 1333 MHz DDR3
Docker resources: 6 CPUs. 18 GB RAM, 2 GB Swap

The test genome (0.5 Mbp) succeeded; the one that failed was ~7.2 Mbp

**Comment by azat-badretdin** [comment]
Your machine is a bit on a tight side of this. Ideally we are comfortable running genomes on 16-core machines with 64G of memory. Is there any indication that memory is used to the brim? It is hard to say why it is hanging in your case.

**Comment by gdp3** [comment]
Memory did not seem to be used to the brim, but maybe that is the issue. Earlier versions did complete on a ~5 Mbp genome, FWIW.

**Comment by azat-badretdin** [comment]
Sorry to hear about that.

**Comment by gdp3** [comment]
If it really looks like memory issues, I guess you folks could add some comments to the Quick Start and close out this case. I had real hopes, but I'm retiring the end of the year so ...

**Comment by azat-badretdin** [comment]
Thanks for the advice! We are trying here to pinpoint the borderline cases that will define the scope of machines that are OK. We are using hefty cloud units on our end to do our testing for now. Good luck with your retirement!

**Comment by thibaudnis** [comment]
Given that your machine has 48 GB of memory, you could try increasing the memory allocated to Docker to 24 GB or even higher depending on whether you want to run other processes on your machine at the same time. We recommend 2 to 4 GB per CPU in the FAQs (see third item in https://github.com/ncbi/pgap/wiki/FAQ), but your genome is on the high end of the size spectrum, so more will probably help.

**Comment by stemicha** [comment]
same issue for me:

my iMAC:
i7 4 Ghz
32 GB

I even limited the memory:
./pgap.py -r -c 6 -m 24g -o MYoutput MYinput.yaml

it stalls at:

43172/000/0000/P 738FA8A4E900B9B1 0007/0007 2020-04-10T06:00:59.049990 dab85ce0f40e UNK_CLIENT UNK_SESSION cluster_blastp_wnode Info: LIB "wn_app.cpp", line 273: ncbi::CGPX_WorkerApp::Run() --- output path: /tmp/5pccboas/output

thanks for your help

**Comment by gdp3** [comment]
I tried again after bumping the Docker memory to 36 GB. The process is hung at the exact same step, cluster_blastp_wnode. I also not that despite having allotted 36 GB of RAM to the Docker process, it never utilized even 3 GB is my frequent monitoring of the Activity Monitor over the past 24 hours (see screenshot). It actually seems that either pgap, or Docker itself, is not using all allotted memory.

![image](https://user-images.githubusercontent.com/41906520/79049408-22395300-7be9-11ea-81f1-cfc18c89f9ca.png)

**Comment by gdp3** [comment]
UPDATE: the process seems to still be running, and is now at 
[2020-04-11 16:57:10] INFO [job Get_Proteins] /tmp/2uw500pb$ bacterial_prot_src \
    -no-phage \
    -nogenbank \
    -fallback-taxonomy \
    -ouniversal-clusters \
    universal_clusters.inf \
    -unicoll_sqlite \
    /tmp/tmp56pruzy8/stg5edc8592-78f2-4d27-aa37-47255f49abba/naming.sqlite \
    -oall \
    all_prots.seqid \
    -taxon-db \
    /tmp/tmp56pruzy8/stgca20f721-802b-4e96-b9de-20230d8fd0f9/taxonomy.sqlite3 \
    -taxid \
    1821 \
    -asn-cache \
    /tmp/2uw500pb/cache
DB cmd = select gi, clade_id, cluster_tag, 0, 0, 1, 0, 0, gi, 500 from ReferenceProteins where     taxid = ?1 order by cluster_tag, gi 
DB param  1 genus = 1817
DB cmd = select cluster_tag FROM UniversalProteins where superkingdom_id = ?1
DB param  1 superkingdom = 2
selected 0	proteins from the database
         0	clades
         0	universal proteins
         0	reference proteins
         0	core proteins
         0	conserved (not core) proteins
         0	phage proteins
         0	plasmid proteins

It is also using 3.6 GB of RAM at present ... I'll let it keep going and see if it completes.

**Comment by azat-badretdin** [comment]
>UPDATE: the process seems to still be running, and is now at

That stage should not be taking a lot of time. The most voluminous stages are two cluster_blastp_wnode stages. In total they take about 80-90% of wallclock time.

**Comment by thibaudnis** [comment]
Did the process ever finish? Related to your comment about cluster_blastp_wnode not using more than 3 GB memory: yes, we have observed this, but also very brief peaks in memory usage for which the extra memory is needed. We trying to find resources to look at this in more details.

**Comment by gdp3** [comment]
It hung again at [2020-04-11 17:10:28] INFO [job Sort_Seed_Hits] 
I killed it after another 48 hours with the last entries in the log being unchanged, and Memory Usage stuck at ~17.3 GB but CPU usage at 0.03%. The last lines of the log read:
...performing merge sort...
  processed 100000 alignments (3313.04 alignments/sec)
  processed 200000 alignments (2854.42 alignments/sec)
  freeing volume: /tmp/tmptk49jc0b/align_sort_6878304588306567y4vqm.66
  freeing volume: /tmp/tmptk49jc0b/align_sort_6878304588306567y4vqm.71
  freeing volume: /tmp/tmptk49jc0b/align_sort_6878304588306567y4vqm.50
  processed 300000 alignments (3077.98 alignments/sec)
  freeing volume: /tmp/tmptk49jc0b/align_sort_6878304588306567y4vqm.34
  freeing volume: /tmp/tmptk49jc0b/align_sort_6878304588306567y4vqm.55

**Comment by stemicha** [comment]
> **same issue for me:**
> 
> my iMAC:
> i7 4 Ghz
> 32 GB
> 
> **docker settings:**
> 
> 8 CPUs
> 32 GB
> 3GB swap
> 300GB disk space
> 
> **I limited the memory:**
> ./pgap.py -r -c 6 -m 24g -o MYoutput MYinput.yaml
> 
> **it stalls at:**
> 
> 43172/000/0000/P 738FA8A4E900B9B1 0007/0007 2020-04-10T06:00:59.049990 dab85ce0f40e UNK_CLIENT UNK_SESSION cluster_blastp_wnode Info: LIB "wn_app.cpp", line 273: ncbi::CGPX_WorkerApp::Run() --- output path: /tmp/5pccboas/output
> 
> thanks for your help

In the mean time I set up a VirtualBox with Ubuntu Linux on it. Installed Docker and all requirements for PGAP and  PGAP itself. (4cores and 16GB RAM)
I run my my bacterial genome of 2,821,288 bp length again. It took nearly 3 days and it is done.
Most time consumed by clustering. 

I hope that helps as a work around. And please increase the performance since nearly 3 days for a small genome is quit long.

**Comment by azat-badretdin** [comment]
>Most time consumed by clustering.

**Comment by stemicha** [comment]
> > Most time consumed by clustering.
> 
> You are probably talking about `cluster_blastp_wnode`. Just a clarification: the `cluster` here does not refer to clustering of proteins, it refers to technological details of doing `blastp` in that application.
> 
> This is just `blastp` optimized for certain in house system configuration.

that is correct I was talking about the` cluster_blastp_wnode` sorry for that. 
But still why is the process so time consuming and can't be speed up?

**Comment by wangdi2014** [comment]
Same here. 

From my experience, cluster_blastp_wnode step in the latest version need at least ~ 32GB memory. Otherwise, it will use some virtual memory (write to hard disk) which would slow it down very significantly. I have tested it on machines running linux with 16G and 32G memory. On 32G, it took ~ 3hr for annotating ONE 1-2 M base genome but took days on 16G memory machine. 2019-08-22 version is much better in term of memory. Even a machine with 8GB memory can run without any problems. 

So my question is what has changed in term of memory usage between 2019-08-22 version and the current version (2020-03-30)?

**Comment by thibaudnis** [comment]
Thanks for the additional reporting. We do the bulk of our testing on 8 CPU 32 GB memory machines. In our hands, the Mycoplasma genitalium genome (0.58 Mb) distributed with the software takes about 1.5 hour, and a 5.7 Mb E. coli genome takes about 6.75 hours on a AWS m5.2xlarge instance (8 CPU and 32 GB RAM), definitely faster than the three days that you mention. We will take a second look at what could be causing a slow-down with the most current software, but at this point we do not have an obvious culprit.

**Comment by jllavin77** [comment]
I'm experiencing the same issues in a server with 192Gb Ram, 64 processors and 20 Tb HD.
It worked smoothly with the test but continuously fails with my genome of interest which expected size is about 4,5 Mb.
Besides, docker seems to be quickly filling my HD due to all the runs that failed for several reasons (yaml misconfiguration, hung up processes,  etc)
Are you releasing a functional version soon, or even replaced the current one with the older version mentioned in this post that seemed to be completely functional?
Remember that a service like this one should never be unavailable as is the current required method to annotate genomes by NCBI in order to upload them to their database...
Please apologize me if I sound a little harsh, but I have been trying to annotate my genome for days without success, and it seems the same is happening to other people as well.

**Comment by azat-badretdin** [comment]
> Besides, docker seems to be quickly filling my HD due to all the runs that failed for several reasons (yaml misconfiguration, hung up processes, etc)

FYI: Typical 5Mb genome occupies a footprint of about 5-10Gb. If it helps for your planning.

**Comment by thibaudnis** [comment]
> Remember that a service like this one should never be unavailable as is the current required method to annotate genomes by NCBI in order to upload them to their database.

No, it is not "the" required method to annotate genomes by NCBI. You can and are welcome to request NCBI to annotate the genome for you, at submission.

**Comment by jllavin77** [comment]
> 
> 
> > Besides, docker seems to be quickly filling my HD due to all the runs that failed for several reasons (yaml misconfiguration, hung up processes, etc)
> 
> FYI: Typical 5Mb genome occupies a footprint of about 5-10Gb. If it helps for your planning.

Thank you for this valuable info.

**Comment by jllavin77** [comment]
> 
> 
> > Remember that a service like this one should never be unavailable as is the current required method to annotate genomes by NCBI in order to upload them to their database.
> 
> No, it is not "the" required method to annotate genomes by NCBI. You can and are welcome to request NCBI to annotate the genome for you, at submission.

Thank you for the advice, I didn't know that, otherwise I wouldn't spend a week trying to make PGAP work...
Now that I know this I will surely do it that way.

Best
