### ISSUE TITLE
Run doesn't start analyzing the genome data: Not found: 'pgap.cwl'

### ISSUE THREAD

**Issue by Matteopaluh** [ncbi/pgap#68]
**Describe the bug**
As in Issue #64 , the pipeline doesn't start analyzing the genome data in input, even for test genomes, I'm thinking because it doesn't find some necessary file for it to run.

**Software versions:**
 - OS: Ubuntu 16.04
 - pgap.py version 2020-03-30.build4489

**Log Files**

Original command: ./pgap.py -r -o mg37_results test_genomes/MG37/input.yaml

Docker command: /usr/bin/docker run -i --user 1000:1000 --volume /mnt/data_HDD/programs/pgap/input-2020-03-30.build4489:/pgap/input:ro,z --volume /mnt/data_HDD/programs/pgap/test_genomes/MG37:/pgap/user_input:z --volume /mnt/data_HDD/programs/pgap/test_genomes/MG37/pgap_input.yaml:/pgap/user_input/pgap_input.yaml:ro,z --volume /mnt/data_HDD/programs/pgap/mg37_results.1:/pgap/output:rw,z ncbi/pgap:2020-03-30.build4489 cwltool --timestamps --disable-color --outdir /pgap/output pgap.cwl /pgap/user_input/pgap_input.yaml

--- Start YAML Input ---
fasta:
  class: File
  location: ASM2732v1.annotation.nucleotide.1.fasta
submol:
  class: File
  location: submol.yaml
supplemental_data: { class: Directory, location: /pgap/input }
report_usage: true
--- End YAML Input ---
[2020-04-03 16:56:48] INFO /usr/local/bin/cwltool 3.0.20200324120055
Traceback (most recent call last):
  File "/usr/local/bin/cwltool", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/cwltool/main.py", line 1240, in run
    sys.exit(main(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/cwltool/main.py", line 881, in main
    fetcher_constructor=loadingContext.fetcher_constructor,
  File "/usr/local/lib/python3.6/site-packages/cwltool/load_tool.py", line 98, in resolve_tool_uri
    raise ValidationException("Not found: '%s'" % argsworkflow)
schema_salad.exceptions.ValidationException: Not found: 'pgap.cwl'

It worked well until the first days of March, then I thought it was something that an update could resolve, but it didn't.
I'm getting this same result from the test genomes and from my lab's data.

Will be so glad if you could help me,
Thanks,
Matteo

**Comment by azat-badretdin** [comment]
Could you please post `ls -l` in your current directory?

**Comment by Matteopaluh** [comment]
There it is, sorry if I answered with some delay, I managed to get a ls from the last time I tried to lauch the pipeline..
I'm attaching a plain text file of the results.

[ls_for_pgap.txt](https://github.com/ncbi/pgap/files/4476429/ls_for_pgap.txt)

**Comment by azat-badretdin** [comment]
Your input still points to the old version supplemental data: 
```
lrwxrwxrwx  1 stefano stefano      54 nov 20 11:54 input -> /mnt/data_HDD/programs/pgap/input-2019-11-08.build4137
```

I recommend to cleanup old versions of input.* and input symlink and try to run `pgap.py -update ....` (as in Quick Start, do not remember other switched)
