### ISSUE TITLE
[BUG] singularity / pgap.py : /pgap/user_input/pgap_input.yaml: Not a directory

### ISSUE THREAD

**Issue by bwakely** [ncbi/pgap#70]
I'm attempting to run pgap.py on a RHEL6 HPC cluster,
using singularity 3.5.3 / installed from epel,
running against the test genome produces an error:
```
PGAP failed, docker exited with rc = 1
Unable to find error in log file.
```

**Issue / reproduction**
- download pgap.py script as per quick start:
   curl -OL https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py

- invoke pgap on test genome:
  python3 ./pgap.py -v -D /usr/bin/singularity -n -o mg37_results test_genomes/MG37/input.yaml

- process performs setup and download of data correctly, builds .sif container from docker container correctly, runs, then aborts with:
    PGAP failed, docker exited with rc = 1
    Unable to find error in log file.

- digging into cwltool.log shows further logs:
    INFO /usr/local/bin/cwltool 3.0.20200324120055
    INFO Resolved 'pgap/pgap.cwl' to 'file:///pgap/pgap/pgap.cwl'
    ERROR Tool definition failed validation:
    '/pgap/user_input/pgap_input.yaml'

**Expected behavior**
    pgap to process the test genome correctly without aborting.

**Software versions:**

 - OS: RHEL6 / x86_64
 - pgap.py --version: 2020-03-30.build4489
 - singularity (docker) image: docker://ncbi/pgap:2020-03-30.build4489
 - singularity version: 3.5.3-1.1.el6

**Additional analysis**

Stepping through this, I can break it down to an Odd singularity behavior/interaction.
Running the singularity exec command:
```
/usr/bin/singularity exec \  
--bind /data/group/ictlab/home/user1/pgap/input-2020-03-30.build4489:/pgap/input:ro \
--bind /data/group/ictlab/home/user1/pgap/test_genomes/MG37:/pgap/user_input \
--bind /data/group/ictlab/home/user1/pgap/test_genomes/MG37/pgap_input_nllj24t6.yaml:/pgap/user_input/pgap_input.yaml:ro \
--bind /data/group/ictlab/home/user1/pgap/mg37_results:/pgap/output:rw \
--pwd /pgap \
docker://ncbi/pgap:2020-03-30.build4489 \
cwltool --timestamps --disable-color --preserve-entire-environment --outdir /pgap/output pgap/pgap.cwl /pgap/user_input/pgap_input.yaml
```
reproduces the error successfully,
if I fire up the container using '/bin/bash' rather the last cwltool... command,
attempting to interact with '/pgap/user_input/pgap_input.yaml' in any way produces the error:
`Not a directory`

I believe it's a singularity Weirdness to do with bind-mapping:
```pgap_input_nllj24t6.yaml:/pgap/user_input/pgap_input.yaml```

Here's what the bind-mapped 'pgap_input.yaml' file looks like from inside the singularity container:

```
Singularity> stat /pgap/user_input/pgap_input.yaml 
	Access: (0644/-rw-r--r--)
```

```
Singularity> ls -lthr /pgap/user_input/pgap_input.yaml
	-rw-r--r-- 1 user1 user1 202 Apr 24 16:32 /pgap/user_input/pgap_input.yaml
```

```
Singularity> cd /pgap/user_input/pgap_input.yaml
	bash: cd: /pgap/user_input/pgap_input.yaml: Not a directory
```

```
Singularity> cat /pgap/user_input/pgap_input.yaml
	cat: /pgap/user_input/pgap_input.yaml: Not a directory
```

```
Singularity> less /pgap/user_input/pgap_input.yaml
	/pgap/user_input/pgap_input.yaml: Not a directory
```

If I run the following from within the container:
```
cd /pgap
cwltool --timestamps --disable-color --preserve-entire-environment --outdir /pgap/output pgap/pgap.cwl /pgap/user_input/pgap_input.yaml
```
It fails as expected (it can't read pgap_input.yaml correctly)

If I copy the source file (pgap_input_qg9uehzr.yaml) outside the container to another file (1.yaml),
it kicks off the workflow correctly when running:
```
cd /pgap
cwltool --timestamps --disable-color --preserve-entire-environment --outdir /pgap/output pgap/pgap.cwl /pgap/user_input/pgap_input.yaml
```

**Comment by azat-badretdin** [comment]
Thanks for the comprehensive and professional report!

I opened an internal ticket (see labels).

It seems that we are binding files as well as directories. Obviously it works in Docker (our go-to image runner at home), we need to figure out what to do with it in Singularity.

**Comment by thibaudnis** [comment]
The bulk of our testing is done in Docker, and we have limited experience with Singularity. However, we have successfully annotated a couple genomes with 2020-03-30.build4489 in Singularity. Unfortunately, I don't think we can provide any more support at the moment for this issue, so I recommend closing it.

**Comment by bwakely** [comment]
Can this be changed to an an enhancement request?
It looks like it could be relatively simple to change the docker/singularity invocation from:
```
  --bind <userdir>/pgap/test_genomes/MG37/pgap_input_nllj24t6.yaml:/pgap/user_input/pgap_input.yaml:ro 
```
to:
```
--bind <userdir>/pgap/test_genomes/MG37:/pgap/user_input:ro \
```
and have as one of the first subsequent arguments:
```
ln -s /pgap/user_input/pgap_input_nllj24t6.yaml /pgap/user_input/pgap_input.yaml
```
