### ISSUE TITLE
fungal GAP

### ISSUE THREAD

**Issue by sjanssen2** [ncbi/pgap#71]
This is most likely the wrong place, but I didn't know where to post/ask elsewhere:

I very much like the publicly available PGAP pipeline, as I can that way reproduce results en detail and understand how to set each parameter. I am about to annotate some in-house fungal genomes and thus would love to execute NCBI's pipeline that is used for the existing reference fungal genomes. Is this pipeline also publicly available?

Many thanks and sorry again for abusing this repo for posting my questions.

**Comment by thibaudnis** [comment]
Hello @sjanssen2, this is absolutely the place to ask questions! PGAP is designed to annotate archaeal and bacterial genomes. It does not handle Fungi. Unfortunately, NCBI does not have a pipeline for the annotation of fungal assemblies. This is something that we have discussed several times, but, at the moment, there are no firm plans for building a process.
