### ISSUE TITLE
[BUG] PGAP produces cryptic error messages

### ISSUE THREAD

**Issue by TheBigFatTony** [ncbi/pgap#72]
As described by others (e.g. bug #60 "Problem with screen_evaluate"), if PGAP fails with `WARNING [job screen_evaluate] completed permanentFail`:

- PGAP failed because of contaminations, but this is not clear from the message
- PGAP has to be re-run (takes a few hours!) in debug mode to get a file called `calls.tab`
- which is hidden somewhere -> `find . -name calls.tab -type f`
- then, the contaminated scaffolds have to be removed from the assembly and PGAP has to be run again

**Expected behavior**
When PGAP fails on screen_evaluate:

- the temporary file `/tmp/tmp?/?/calls.tab` should be copied into the output directory or appended to `cwltool.log` before it is deleted.
- there should be a clear error message.
- similar steps should be taken for other common errors (if there are other common errors)

Currently, I have to run every annotation with `--debug` because I don't want to re-run twice in case of contamination. This produces a lot of data (and is probably slower because `/tmp` is faster storage than my output dir).

**Comment by TheBigFatTony** [comment]
If it is hard to improve the error messages, a simple workaround would be to write something like this at the end of `cwltool.log`:
```
Please refer to https://github.com/ncbi/pgap/wiki/error-messages to understand what went wrong.
```
There, you could explain how to interpret the log and how to fix common errors.

**Comment by azat-badretdin** [comment]
Thank you for your report! I opened an internal ticket to assess this and decide what to do here. 

Your recommendations seem fair to me.
