### ISSUE TITLE
Docker not found.

### ISSUE THREAD

**Issue by lz870718** [ncbi/pgap#73]
Hi, I am trying to update pgap with ./pgap.py --update but got the following error. I am pretty sure dock is installed in my desktop. Is there a way I can fix it?

The latest version of PGAP is 2020-03-30.build4489, you have nothing installed locally.
Docker not found.

Thank you!

**Comment by azat-badretdin** [comment]
>got the following error

**Comment by azat-badretdin** [comment]
Could you please provide an error log? Thanks!

**Comment by lz870718** [comment]
./pgap.py --update
The latest version of PGAP is 2020-03-30.build4489, you have nothing installed locally.
Docker not found.

**Comment by azat-badretdin** [comment]
Thanks!

**Comment by azat-badretdin** [comment]
What does output of `which docker` say?

**Comment by lz870718** [comment]
/usr/local/bin/docker

**Comment by azat-badretdin** [comment]
Interesting. `which docker` is essentially what Python code of `pgap.py` does. I am starting to shoot in the dark here: what is the output of `/usr/bin/env python3 --version`?

**Comment by azat-badretdin** [comment]
Also: what is your OS?

**Comment by azat-badretdin** [comment]
**Software versions (please complete the following information):**
 - OS: [e.g. CentOS 7, Windows 10, etc.]
 - pgap.py --version, or docker image version.
 - Docker (or other container runner) version. [e.g. ``docker --version``]

**Comment by lz870718** [comment]
OS: macOS High Sierra
Docker Version:          19.03.8
I was running ./pgap.py --version to get the version info.  But got following error:
./pgap.py --update
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>

**Comment by azat-badretdin** [comment]
Could you please check certificates on the Mac?

**Comment by lz870718** [comment]
I tried to include below line in pgap.py to fix it and it worked yesterday.

import os, ssl
if (not os.environ.get('PYTHONHTTPSVERIFY', '') and getattr(ssl, '_create_unverified_context', None)):
    ssl._create_default_https_context = ssl._create_unverified_context

But it is not working anymore.

I have very limited knowledge to know how/which Mac certificate to check. Your input is greatly appreciated.

**Comment by azat-badretdin** [comment]
I understand. Personally, I have very little system knowledge  (I am an application developer). Thanks for the snippet of code in `pgap.py` I hope someone on our side will consider it.

**Comment by whlavina** [comment]
Your Python installation may be incomplete. Apparently, the versions of Python that ship with macOS, as well as the standard distribution, no longer install certificates and do not have access to the operating system's certificates. At least 3 options may exist:
1. Make sure to follow the Python installation instructions carefully, as you may have missed a critical step. According to Python installation instructions for macOS, there should have been guidance on installing certificates. Look for a file such as `Install Certificates.command`
2.  Install a different distribution of Python, one that comes with certificates pre-installed. For example, try to install Python from Anaconda.
3. Explicitly install certificates, e.g. via `sudo pip3 install certifi`

Regarding any changes you may be making to the `pgap.py` script, beware that the script will auto-update itself if modified, discarding your changes. Use the `--no-self-update` option to disable this feature.

For the Docker error, please provide the output of:
```
echo $PATH
python3 -c 'import shutil; print(shutil.which("docker"))'
```

My apologies, but we do not have much macOS expertise or the resources to diagnose Python or Docker installation issues. We can improve error messages to help identify such problems, but you may need to seek out help from the Python community, in your particular case.
