### ISSUE TITLE
[BUG] Unclear how to submit to GenBank

### ISSUE THREAD

**Issue by TheBigFatTony** [ncbi/pgap#74]
I wanted to publish a genome that I annotated myself using PGAP.

However, it was not clear to me what to choose on several steps of the process, for example here:

![image](https://user-images.githubusercontent.com/24833908/82182003-dbbfce00-98e3-11ea-9bcd-e0b9c8000b1e.png)

This helper text should be a lot more ... helpful!

I opted to upload the .sqn file here:

![image](https://user-images.githubusercontent.com/24833908/82182770-17a76300-98e5-11ea-8867-a07636db80bf.png)

But I didn't know **when** to upload the sqn file, so I tried uploading both the fna and the sql file on step 6, but I got this error:

![image](https://user-images.githubusercontent.com/24833908/82182305-57ba1600-98e4-11ea-8448-3ac49525b56f.png)

With ASN.1 files, I assume they mean the .sqn file, which is in this format. So I tried uploading the .sqn-file only, since it contains the sequence. Then, I got this:

![image](https://user-images.githubusercontent.com/24833908/82183096-a61be480-98e5-11ea-93e7-ad8293f977bf.png)

In the end, I only uploaded the .fna, selected "No" in "Annotate using PGAP?" and contacted NCBI support. I wasted a lot of time here! Please improve this process!

A good first step would be to add a walk-through to the wiki here on GitHub, if the submission pipeline can't easily be changed.

**Comment by azat-badretdin** [comment]
It looks like it's better to ask this question elsewhere. I am not familiar with the Web Page which screenshot you posted here: maybe there is a URL for helpdesk?

**Comment by TheBigFatTony** [comment]
I am already in contact with the helpdesk, I just thought it might be relevant for you guys as well.

this is where i tried to submit: https://submit.ncbi.nlm.nih.gov/subs/genome/

**Comment by azat-badretdin** [comment]
Thanks, Tony! It is relevant exactly at the level you made it relevant: you posted the problem, you closed the ticket.  Thanks!
