### ISSUE TITLE
<urlopen error [Errno 111] Connection refused>

### ISSUE THREAD

**Issue by nzx9581** [ncbi/pgap#75]
Hi!

It has been a month or two since I last used PGAP which version is build4456. Today I want to reannotate my bacteria genome. Then I use `./pgap.py --update` to update my pgap. However  I get back this big error message.

`The latest version of PGAP is 2020-03-30.build4489, you have nothing installed locally.
<urlopen error [Errno 111] Connection refused>
Failed to update ./pgap.py, ignoring
Something has gone wrong, please manually download: https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py`

Then I copy the newest pgap.py to my server and the error still exist. In addition, my server is on the intranet, I just use frp for intranet penetration. My network is normal and I have never set up a proxy. And I can't download `pgap.py` by `wget` or `curl`. The error message is `failed: connection refused`.

Could you give me some advices for these problems? Thank you so much for your help!

**Comment by nzx9581** [comment]
I have solved this problem. Thanks

**Comment by whlavina** [comment]
Would you mind giving a brief explanation of how you resolved the problem? If it was a configuration issue with your system, there's no need to give excessive details, but a hint for what to look for, or how to improve the diagnostics is appreciated. Thanks!

**Comment by thibaudnis** [comment]
@nzx9581 : another user reports the same error in https://github.com/ncbi/pgap/issues/85. Would you be willing to help by describing how you solved the problem?

**Comment by ericjove** [comment]
Closing this issue out per this solution https://github.com/ncbi/pgap/issues/85#issuecomment-664177965
