### ISSUE TITLE
topology reporting issue in gbk file?

### ISSUE THREAD

**Issue by kneubehl** [ncbi/pgap#78]
I am indicating that a contig is circular by not providing "topology" in the metadata file and putting the topology after each seqID (e.g. >cp28 topology=circular) however in the .gbk file it indicates that this locus is linear. The number of genes overall decreases between topology=linear (decrease of 2 genes overall and an increase of 1 for pseudogenes from the remaining genes, total of 3 genes perturbed) and indicating topology individually for the contigs. The new pseudogene is not found on the circular contig but is found on one of the linear contigs. I am not sure what really changes between indicating something is circular at the seqID level vs the metadata file. Any insight would be appreciated. Thanks.

**Comment by thibaudnis** [comment]
Thank you for writing to us and reporting the issue. Have you tried using brackets around topology=circular, i.e. make the def line of the fasta: `>cp28 [topology=circular]`? I will run a test with and without brackets and report back.

**Comment by kneubehl** [comment]
Brackets fixed it for me thanks! The gbk output had the right topology for the contigs by changing the def line of fasta from: `>cp28 topology=circular`  to `>cp28 [topology=circular]`
