### ISSUE TITLE
Plasmid annotation

### ISSUE THREAD

**Issue by gchalmer** [ncbi/pgap#79]
Is there a way to specify that the sequence you're trying to annotate is a plasmid, so it doesn't fail the genome size test? I've done copy-paste-paste-etc to get the size up to what is expected for an E. coli genome (and I put 'Escherichia coli' in the meta yaml file), but that seems a bit crude. Any help would be great!

**Comment by thibaudnis** [comment]
Hi! Please try running `pgap.py` with the `--ignore-all-errors` flag. That should override the genome size check results and allow the process to continue.

**Comment by azat-badretdin** [comment]
We have generic flag in `pgap.py` to ignore all errors. It's quite good for exploratory runs.

**Comment by gchalmer** [comment]
Thank you!
