### ISSUE TITLE
Quick Start instructions fail due to 'report_usage'

### ISSUE THREAD

**Issue by pbieberstein** [ncbi/pgap#8]
When running the Quickstart commands:

```
$ chmod +x pgap.py
$ ./pgap.py --update # required files are downloaded and extracted
$ ./pgap.py test_genomes/MG37/input.yaml # watch the progress reports and wait for some time.]
```

I get this error: 

```
/usr/bin/cwltool 1.0.20181217162649
Resolved 'pgap.cwl' to 'file:///pgap/pgap.cwl'
Workflow error, try again with --debug for more information:
Invalid job input record:
pgap.cwl:22:3: Missing required input parameter 'report_usage'
Traceback (most recent call last): ...
```

It seems to work when I include the additional parameter '-n' to set report_usage to "False"

```
./pgap.py test_genomes/MG37/input.yaml -n
```

So I thought you may want to update the quickstart command or set report_usage to False on default so that future users don't have the same problems?

Thank you for making this pipeline available!!!

**Comment by slottad** [comment]
Yes, that was an oversight on our part, we will add that.

Although we'd really prefer that you'd use the '-r' parameter, which sets the report_usage flag to "True".  :)

The other option you have is to add the report_usage flag to your input YAML (for custom genomes), and then you need not use either command line option.

**Comment by pbieberstein** [comment]
good point, thanks for the quick comment!

**Comment by slottad** [comment]
Done.
