### ISSUE TITLE
Running PGAP not from installation directory

### ISSUE THREAD

**Issue by juliofdiaz** [ncbi/pgap#80]
If I run pgap from a directory other than the installation directory, then pgap reinstalls again in the current directory. 

I have pgap installed in `~/bin/pgap/` . When I run `~/bin/pgap/pgap.py -r -o TEST test.yaml` from `~/sandbox/pgap/`, I get the following message `The latest version of PGAP is 2020-06-10.build4646, you have nothing installed locally`. Then it downloads pgap in the `~/sandbox/pgap/ directory`.

Is there a way to run pgap calling it from a directory other than the current directory? BTW, I have successfully tested the installation with the test genome.

Full message:
```
The latest version of PGAP is 2020-06-10.build4646, you have nothing installed locally.
Downloading (as needed) Docker image ncbi/pgap:2020-06-10.build4646
2020-06-10.build4646: Pulling from ncbi/pgap
Digest: sha256:e4d75534f9fa2c83b93343edd84b102e4704352609a9eec03ce58cefbda50e6e
Status: Image is up to date for ncbi/pgap:2020-06-10.build4646
docker.io/ncbi/pgap:2020-06-10.build4646
Downloading and extracting tarball: https://s3.amazonaws.com/pgap/input-2020-06-10.build4646.tgz
```

**Comment by azat-badretdin** [comment]
Please try to run it with `pgap.py --no-self-update` option

**Comment by juliofdiaz** [comment]
Thanks I tried that and got:
```
The latest version of PGAP is 2020-06-10.build4646, you have nothing installed locally.
Not trying to update self, because the --no-self-update flag is enabled.
Downloading (as needed) Docker image ncbi/pgap:2020-06-10.build4646
2020-06-10.build4646: Pulling from ncbi/pgap
Digest: sha256:e4d75534f9fa2c83b93343edd84b102e4704352609a9eec03ce58cefbda50e6e
Status: Image is up to date for ncbi/pgap:2020-06-10.build4646
docker.io/ncbi/pgap:2020-06-10.build4646
Downloading and extracting tarball: https://s3.amazonaws.com/pgap/input-2020-06-10.build4646.tgz
^Cwnloaded 28713472 of 16563008943 bytes (0.17%)
```

**Comment by azat-badretdin** [comment]
Did the execution stopped after that?

**Comment by juliofdiaz** [comment]
No it doesn't stop. It continues trying to install pgap in the current directory.

**Comment by azat-badretdin** [comment]
I see what you mean now. It installs reference files in current directory. 

This is an existing limitation of current scripts. 

You can have input files to PGAP (FASTA and submol.yaml) specified in a separate directory and you can specify output directory in a separate directory, so the only limitation you have is the `cwd` at the time of `pgap.py` run.
