### ISSUE TITLE
PGAP (`pilercr`) fails on Debian 10 because of `vsyscall`

### ISSUE THREAD

**Issue by pvstodghill** [ncbi/pgap#81]
I recently encountered the same failure with `pilercr` that others have observed (https://github.com/ncbi/pgap/issues/42) when trying to annotate the test genome. In my case, the failure is caused by the fact the some component of pilercr` was compiled on an older Linux distribution and is being run on a more recent Linux distribution.

Look for the following message in the syslog (or dmesg):

```
[1047445.926201] pilercr[4985] vsyscall attempted with vsyscall=none ip:ffffffffff600400 cs:33 sp:7ffcca8b0ca8 ax:ffffffffff600400 si:710a60 di:0
```

`vsyscall` has been obsolete for awhile, but older toolchains, even currently supported versions of Centos still generate code that uses it. Recent versions of Debian (from Stretch on I believe) have disabled the use of `vsyscall` for security reasons. Recent versions of Ubuntu have _re-enabled_ `vsyscall` support for compatibility reasons. :-/

And this is the part that really stinks: Running the compiled code natively, under Docker, under Singularity, etc., makes no difference; if the host OS doesn't support `vsyscall`, then the code will fail.

Here are the steps to reproduce the problem:

1. Setup a machine with Debian Buster (10.x). I think that a VM machine will work, but I have only tested this on real hardware.
2. 

```
curl -OL https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py
./pgap.py --update
./pgap.py -r -o mg37_results test_genomes/MG37/input.yaml
```

Here are some work-arounds for users:

1. Rebuild your machine with Centos or Ubuntu(?) :-(
2. Add `vsyscall=emulate` to your kernel parameters and reboot. WARNING: this does disable some small piece of the total security for your machine, so BEWARE.

Here is how the developers can fix the problem:

1. Recompile everything using a more recent toolchain.

Admittedly, I have not tested this solution with PGAP.

If anyone is aware of other workarounds or solutions, I would love to know what they are; I have several other packages (e.g., the Mauve release) the exhibit the same problem.

HTH.

**Comment by azat-badretdin** [comment]
> Recompile everything using a more recent toolchain

Unfortunately, `piler-cr` is a third party software that we currently do not maintain (we only use it).
