### ISSUE TITLE
[BUG] exiting with a NoneType error

### ISSUE THREAD

**Issue by awalling** [ncbi/pgap#82]
**Describe the bug**
Hello, 

I am currently trying to run PGAP on a queued shared memory server. I have successfully annotated the test genome per instructions but am receiving an error message I'm struggling to understand shortly after attempting a first run on my own data:

**Software versions (please complete the following information):**
 - OS: CentOS Linux 7
 - PGAP version 2020-06-10.build4646
 - Docker version 19.03.5, build 633a0ea

```
(base) [awalling@amnh-gen-001 (cuvier):~/array1/PGAP] $ ./pgap.py -r -o Curated_Eryth_DB/A_aerius/Outputs Curated_Eryth_DB/A_aerius/input.yaml
PGAP version 2020-06-10.build4646 is up to date.
Output will be placed in: /array1/awalling/PGAP/Curated_Eryth_DB/A_aerius/Outputs.2
PGAP failed, docker exited with rc = 1
Unable to find error in log file.
(base) [awalling@amnh-gen-001 (cuvier):~/array1/PGAP] $ 
```

The cwltool.log file is short and looks like this:

```
--- Start YAML Input ---
#this is a yaml file for PGAP specifying the input files
report_usage: true
fasta:
        class: File
        location: ~/array1/PGAP/Curated_Eryth_DB/A_aerius/A_aerius_GCFA_aerius_GCF_009827495.1_ASM982749v1_genomic.fasta
submol:
        class: File
 location: pgap_submol_ai2_ks9y.yaml
supplemental_data: { class: Directory, location: /pgap/input }
report_usage: true
--- End YAML Input ---

--- Start Runtime Report ---
{
    "CPU cores": 128,
    "Docker image": "ncbi/pgap:2020-06-10.build4646",
    "cpu flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb intel_ppin tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm xsaveopt cqm_llc cqm_occup_llc ibpb ibrs stibp dtherm ida arat pln pts spec_ctrl intel_stibp",
    "cpu model": "Intel(R) Xeon(R) CPU E7-8867 v3 @ 2.50GHz",
    "max user processes": "unlimited",
    "memory (GiB)": 1007.6,
    "memory per CPU core (GiB)": 7.9,
    "open files": 1048576,
    "tmp disk space (GiB)": 2029.5,
    "virtual memory": "unlimited",
    "work disk space (GiB)": 34485.2
}
--- End Runtime Report ---

[2020-06-22 21:56:28] INFO /usr/local/bin/cwltool 3.0.20200530110633
[2020-06-22 21:56:28] INFO Resolved 'pgap/pgap.cwl' to 'file:///pgap/pgap/pgap.cwl'
[2020-06-22 21:56:28] ERROR I'm sorry, I couldn't load this CWL file, try again with --debug for more information.
The error was: 'NoneType' object has no attribute 'name'
```

When I run with the debug flag an empty directory is created with nothing written to it.

Would appreciate any guidance on what the cause of this error is.

Thanks!

Alexandra

**Comment by azat-badretdin** [comment]
Thank you for your report, Alexandra. Could you please try to rerun it with adding `--debug` parameter to the command line?

**Comment by azat-badretdin** [comment]
Developer note: your machine seems to be very powerful, so we can eliminate "insufficient resources" hypothesis.

**Comment by azat-badretdin** [comment]
Another thing to try is to eliminate tilda in your `input.yaml` file: 
```
        location: ~/array1/PGAP/Curated_Eryth_DB/A_aerius/A_aerius_GCFA_aerius_GCF_009827495.1_ASM982749v1_genomic.fasta
```
and fully resolve it. This probably won't affect anything, just to 100% eliminate this idiosyncrasy (we have never tried using that BASH shortcut in our tests, to my knowledge)

**Comment by awalling** [comment]
Hello, 

I edited the input.yaml file to contain the absolute path. I also added the --debug tag again. The run exited with the same error status and created empty directories within Output: /Output/debug/log/ -- the log directory does not contain anything.

Best,

Alexandra

**Comment by azat-badretdin** [comment]
Thanks, Alexandra. 

I presume you cleaned up output directories before rerunning since originally you had this snippet: ```/array1/awalling/PGAP/Curated_Eryth_DB/A_aerius/Outputs.2``` which indicates usually to repeated attempts to run it and last run was just `/Output`

were there any other directories created under `/Output/`? 

But first, let's look at this:```
#this is a yaml file for PGAP specifying the input files
report_usage: true
fasta:
        class: File
        location: ~/array1/PGAP/Curated_Eryth_DB/A_aerius/A_aerius_GCFA_aerius_GCF_009827495.1_ASM982749v1_genomic.fasta
submol:
        class: File
 location: pgap_submol_ai2_ks9y.yaml
```

Could you please check if the lines in input.yaml file are aligned correctly? 

In the posted snippet `submol.location` is supposed to have the same ident as `submol.class`. Sometimes some editors present tabs and spaces in the same way, but the file parser in cwltool generally should not be able to determine what is the tabsize of the original editor.

**Comment by awalling** [comment]
Hello, 

No other directories were created under Outputs; the only thing it contained other than the empty /debug/log/ directory was the cwltool.log file, which again ended with:

```
--- End Runtime Report ---

[2020-06-23 12:45:02] INFO /usr/local/bin/cwltool 3.0.20200530110633
[2020-06-23 12:45:02] INFO Resolved 'pgap/pgap.cwl' to 'file:///pgap/pgap/pgap.cwl'
[2020-06-23 12:45:02] ERROR I'm sorry, I couldn't load this CWL file, try again with --debug for more information.
The error was: 'NoneType' object has no attribute 'name'
```

I have also checked the indentation in the .yaml file and all indents are tabs.

**Comment by azat-badretdin** [comment]
>I have also checked the indentation in the .yaml file and all indents are tabs.

**Comment by azat-badretdin** [comment]
Let me ask around about these white spaces.

**Comment by azat-badretdin** [comment]
Looks like YAML file spec does not like tabs: https://stackoverflow.com/questions/19975954/a-yaml-file-cannot-contain-tabs-as-indentation#19976827 most editors support easy conversion of tabs to spaces. Could you please try that?
