### ISSUE TITLE
[BUG] error creating overlay mount to.. invalid argument

### ISSUE THREAD

**Issue by koper86** [ncbi/pgap#83]
**Describe the bug**
I have encountered a strange bug when trying to start test run: ./pgap.py -r -o mg37_results test_genomes/MG37/input.yaml
sudo ./pgap.py --debug -r -o mg37_results test_genomes/MG37/input.yaml
PGAP version 2020-06-10.build4646 is up to date.
Output will be placed in: /mnt/solid_raid/Koper/pgap/mg37_results.14
/usr/bin/docker: Error response from daemon: error creating overlay mount to /mnt/solid_raid/docker_data/overlay2/768195dfb801bc912660fcc63d1f2bd760de99ad2c0615a828cca6b31dc39d97-init/merged: invalid argument.
See '/usr/bin/docker run --help'.
Traceback (most recent call last):
  File "./pgap.py", line 839, in <module>
    main()
  File "./pgap.py", line 820, in main
    retcode = p.launch()
  File "./pgap.py", line 421, in launch
    self.record_runtime(f)
  File "./pgap.py", line 364, in record_runtime
    result = subprocess.run(cmd, check=True, stdout=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/docker', 'run', '-i', '-v', '/mnt/solid_raid/Koper/pgap:/cwd', 'ncbi/pgap:2020-06-10.build4646', 'bash', '-c', 'df -k /cwd /tmp ; ulimit -a ; cat /proc/{meminfo,cpuinfo}']' returned non-zero exit status 125.

cwltool.log:
Original command: ./pgap.py --debug -r -o mg37_results test_genomes/MG37/input.yaml

Docker command: /usr/bin/docker run -i --rm --user 0:0 --volume /mnt/solid_raid/Koper/pgap/input-2020-06-10.build4646:/pgap/input:ro,z --volume /mnt/solid_raid/Koper/pgap/test_genomes/MG37:/pgap/user_input:z --volume /mnt/solid_raid/Koper/pgap/test_genomes/MG37/pgap_input_hgst7wqx.yaml:/pgap/user_input/pgap_input.yaml:ro,z --volume /mnt/solid_raid/Koper/pgap/mg37_results.14:/pgap/output:rw,z --volume /mnt/solid_raid/Koper/pgap/mg37_results.14/debug/log:/log/srv:z ncbi/pgap:2020-06-10.build4646 cwltool --timestamps --disable-color --preserve-entire-environment --outdir /pgap/output --tmpdir-prefix /pgap/output/debug/tmpdir/ --leave-tmpdir --tmp-outdir-prefix /pgap/output/debug/tmp-outdir/ --copy-outputs pgap/pgap.cwl /pgap/user_input/pgap_input.yaml

--- Start YAML Input ---
fasta:
  class: File
  location: ASM2732v1.annotation.nucleotide.1.fasta
submol:
  class: File
  location: pgap_submol_tze9k_nq.yaml
supplemental_data: { class: Directory, location: /pgap/input }
report_usage: true
--- End YAML Input ---

--- Start Runtime Report ---
(base) 

**Software versions (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - pgap.py --versios: PGAP version 2020-06-10.build4646
 - Docker (or other container runner) version: Docker version 19.03.6, build 369ce74a3c

**Comment by azat-badretdin** [comment]
Unfortunately, we can't do much on our side on docker problems. What is your system memory size?
