### ISSUE TITLE
HTTP Error 403: rate limit exceeded

### ISSUE THREAD

**Issue by juliofdiaz** [ncbi/pgap#84]
When I run pgap I get the following error:
`HTTP Error 403: rate limit exceeded`

I have successfully run the test genome and my own assembled genome in the past. I have tried using the `--no-internet flag`, but the same error shows up. Is this error because I use pap too much? I want to annotate hundreds of genomes, would this be a problem?

Thanks for your help.

**Comment by azat-badretdin** [comment]
Julio, we probably need more information on this. What is your system, when exactly this error is returned, at what point of execution it is returned. This is probably something specific to your internet setup which we have limited capabilities to help with

**Comment by juliofdiaz** [comment]
Yes, sorry for not including it earlier. I don't get this error anymore, but just in case it is useful:

The error occurred at ~ 18:00 BST
I was running it from: Ubuntu 16.04.6 LTS
I was using PGAP version: 2020-03-30.build4489
The only message I got was `HTTP Error 403: rate limit exceeded`, and it occurred right at the beginning of the execution(it didn't even create the output folder). 

Thanks for your response
