### ISSUE TITLE
BUG: <urlopen error [Errno 111] Connection refused> for 2020-06-10.build4646

### ISSUE THREAD

**Issue by chenmlRice** [ncbi/pgap#85]
The installed system:

1. - The docker image has been updated to 2020-06-10.build4646 (docker pull ncbi/pgap-utils:2020-06-10.build4646)
2. - The python is 3.7.3
3. - The supplementary data has also been updated to 2020-06-10.build4646 (input-2020-06-10.build4646.tgz)
4. - CWL code has been updated to 2020-06-10.build4646 (2020-06-10.build4646.tar.gz).

Commands:
1.  ./pgap.py                                   
<urlopen error [Errno 111] Connection refused>
2. ./pgap.py -r -o mg37_results MG37/input.yaml
<urlopen error [Errno 111] Connection refused>
3. ./pgap.py --no-internet -r -o mg37_results MG37/input.yaml
<urlopen error [Errno 111] Connection refused>
4. ./pgap.py -d
The latest version of PGAP is 2020-06-10.build4646, you have nothing installed locally.
<urlopen error [Errno 111] Connection refused>
Failed to update ./pgap.py, ignoring
Something has gone wrong, please manually download: https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py

The pgapy.py is manually created with copy and paste. And 'chmod 755 pgapy.py' to make it excuteable.

What is wrong with the PGAP system that I intalled in my linux?
![docker_update](https://user-images.githubusercontent.com/39790997/85969543-8acee980-b9fa-11ea-8544-ebd60ee1dbdb.jpg)
![internet_test](https://user-images.githubusercontent.com/39790997/85969571-a508c780-b9fa-11ea-8967-5402558b8174.jpg)

[pgap.zip](https://github.com/ncbi/pgap/files/4843614/pgap.zip)

**Comment by thibaudnis** [comment]
A user reported a similar issue in https://github.com/ncbi/pgap/issues/75 and was able to fix it. I asked again if he/she can explain how.

**Comment by chenmlRice** [comment]
How to solve this issue?

**Comment by azat-badretdin** [comment]
Please contact your local system support

**Comment by chenmlRice** [comment]
Does it cause by our local internet setup problem? But I can download supplementary data, which means that it is ok for internet connection.

Can you explain more detail? Thank you very much!

**Comment by azat-badretdin** [comment]
Unfortunately, we do not know how to fix this. That's why Françoise requested assistance from another PGAPX user on a different ticket. Did you see Python stack produced in the console when you got urlopen error?

**Comment by chenmlRice** [comment]
The urlopen refused error may be cause by the function of get_remote_versions (urlopen('https://api.github.com/repos/ncbi/pgap/releases/latest')  or url = 'https://registry.hub.docker.com/v1/repositories/ncbi/{}/tags'.format(self.repo)). I have replaced a default version rather than that derived from url. I think this may be the reason of internet access. Because the commands also do not work in our system (curl -OL https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py        &
wget https://github.com/ncbi/pgap/raw/prod/scripts/pgap.py).

**Comment by azat-badretdin** [comment]
>Because the commands also do not work in our system

**Comment by chenmlRice** [comment]
It's a pity they can't solve it. We can access supplementary file from amazon (https://s3.amazonaws.com/pgap/input-{self.use_version}.{suffix}tgz), which means our international internet access is ok.

**Comment by azat-badretdin** [comment]
>It's a pity they can't solve it.

**Comment by nzx9581** [comment]
Hi, 
Previously, I encountered the problem same with yours. I think you can try following commands even if you have never set up your proxy. 
`unset http_proxy`
`unset https_proxy`
`unset HTTP_PROXY`
`unset HTTPS_PROXY`
I don't know what is the difference between uppercase and lowercase, but it is always worked.

**Comment by chenmlRice** [comment]
> Previously, I encountered the problem same with yours. I think you can try following commands even if you have never set up your proxy.
Thank you for your kind! I will try it.

**Comment by mateus-werneck** [comment]
Just want to say I had this problem when blocking "google.video" domain ob my Pihole. Solved it by removing it from the blacklist

**Comment by tsucheta** [comment]
We had updated pgap and it ran only once with the test data. After that it had series of errors :

/pgap.py -n -o test1 -g ASM2732v1.annotation.nucleotide.1.fasta -s 'Mycoplasma genitalium G37'
PGAP version 2023-10-03.build7061 is up to date.
<urlopen error [Errno 104] Connection reset by peer>
Failed to update ./pgap.py, ignoring

However,
unset http_proxy
unset https_proxy
unset HTTP_PROXY
unset HTTPS_PROXY

This is what worked for us!!

Many thanks!!

**Comment by ericjove** [comment]
> We had updated pgap and it ran only once with the test data. After that it had series of errors :
> 
> /pgap.py -n -o test1 -g ASM2732v1.annotation.nucleotide.1.fasta -s 'Mycoplasma genitalium G37' PGAP version 2023-10-03.build7061 is up to date. <urlopen error [Errno 104] Connection reset by peer> Failed to update ./pgap.py, ignoring
> 
> However, unset http_proxy unset https_proxy unset HTTP_PROXY unset HTTPS_PROXY
> 
> This worked for us the first time. When I am trying again it is not working. Any suggestions?

This reported issue is a slightly different error that originally opened this ticket. Please see https://github.com/ncbi/pgap/issues/278#issuecomment-1841523497
