### ISSUE TITLE
[BUG] --cpus option ignored when using singularity container

### ISSUE THREAD

**Issue by dsommer** [ncbi/pgap#86]
**Describe the bug**
When running pgap.py with singularity as the Docker-compatible executable command the `--cpus` option is ignored. The singularity container will use all available cpus on the machine. For machines with a high number of hyperthreads this causes the blast jobs to run out of memory because too many on spawned.

**To Reproduce**
You can reproduce using the Mycoplasma genitalium test example that comes with pgap.py.

**Expected behavior**
`--cpus` should limit the number of cpus used and jobs spawned.

**Software versions (please complete the following information):**
 - OS: Centos 7 and Ubuntu 18
 - pgap.py --version, or docker image version.
pgap version 2020-06-10.build4646
Singularity version 3.5.3

**Comment by dsommer** [comment]
https://github.com/ncbi/pgap/blob/6ac47e5703d8c8cdac698de91143829b3911e9b2/scripts/pgap.py#L206
In functions make_docker_cmd() and make_podman_cmd() there is a section where self.params.args.cpus is checked and the cpus option is set when running the containers.
  

In the function make_singularity_cmd(), self.param.args.cpus is never checked or added to cmd setup.
https://github.com/ncbi/pgap/blob/6ac47e5703d8c8cdac698de91143829b3911e9b2/scripts/pgap.py#L246

**Comment by whlavina** [comment]
At the time of initial implementation, our version of Singularity lacked an option on the command line to limit the number of CPU. This is why we _intentionally_ omitted passing down the option.

As I look now, it seems Singularity 3.1 (release April 2019) added a new option, `--vm-cpu`, which may be appropriate. If so, expect us to make a fix in a timely manner, although issue #77 means the feature won't yet work as desired.

We do not have developers with Singularity experience, so please feel free to provide some guidance if `--vm-cpu` is not the correct command line option.

**Comment by whlavina** [comment]
Upon further research, it appears that the 2 Singularity command line options require hypervisor VM virtualization enabled in the OS kernel. This is unlike Docker, which uses `cgroups` to implement the CPU and memory limits.

We invite the community to provide feedback on whether that requirement is problematic, and/or provide a recommendation on how to specify the limits to an invocation using Singularity.

**Comment by standage** [comment]
The capability of a software tool to automatically detect the number of processors on the machine and utilize them all can certainly be useful. But it’s even more common for bioinformatics software to have the *user* explicitly specify the number of processors to use—and accept the consequences of over- or under-subscribing if they so choose.

Whether or not Singularity allows one to control how many processors are visible or available to the image is somewhat irrelevant. If PGAP has a `--cpus` option, what is stopping PGAP from limiting the number of processors it uses? If a user has a machine with 8 processors but only wants PGAP to use 4, what is stopping PGAP from running `blastp`, `hmmscan`, and every other tool with 4 threads?

**Comment by whlavina** [comment]
Thank you for your feedback. If you are interested in more flexible customization of PGAP, the CWL workflow files are available for direct use and embedding in other workflows (subject to license restrictions for third party tools).

For the majority of our community, we are aiming to provide an easy-to-use tool, with a suitable balance of configuration flexibility.

**Comment by standage** [comment]
> If you are interested in more flexible customization of PGAP, the CWL workflow files are available for direct use and embedding in other workflows

Thank you, I will have to check this out!

> For the majority of our community, we are aiming to provide an easy-to-use tool, with a suitable balance of configuration flexibility.

If there won't be any support for limiting the number of threads PGAP uses in the near future, might I suggest that the `--cpus` parameter be removed from `pgap.py` and the documentation updated to make it clear that PGAP will always use all available processors?

**Comment by whlavina** [comment]
Thanks. We are actively investigating how to address the CPU issue, including the option of formally dropping support depending on priorities. We're hopeful about finding a proper solution.

**Comment by whlavina** [comment]
We have adopted a solution for limiting CPU that works with all container runners (Docker, PodMan, and Singularity), via the CPU affinity mask. This is not an ideal solution, but it should be workable. The fix is in the dev branch, to be tested.

Meanwhile, we are also documenting that the command line option for restricting memory usage is limited to Docker and PodMan: a solution via native Singularity options would be brittle (unsupported in older versions of Singularity, and requires a hypervisor in current versions). A container-runner-agnostic solution, relying on cgroups, would add complexity. High memory usage can be mitigated by reducing parallelism, via the CPU option, now that it should work. If community feedback identifies a need to support explicit memory restrictions, we can revisit this ticket.

**Comment by standage** [comment]
> High memory usage can be mitigated by reducing parallelism, via the CPU option, now that it should work.

This is wonderful, thanks!

> If community feedback identifies a need to support explicit memory restrictions, we can revisit this ticket.

I think that limiting memory usage by limiting CPU usage is reasonable, and that more explicit memory controls wouldn't be a high priority (for our usage at least).

**Comment by hdore** [comment]
Hello,

Sorry for commenting on a closed issue, but I'm still having the same problem with the latest release of pgap (--cpus is still ignored when using singularity container). I'm trying to run pgap on a HPC where I don't have root privileges. Is there any required configuration of singularity for --cpus to work?

Thank you,
Hugo Doré
