### ISSUE TITLE
[BUG] Bas Sequence Read Archive Format in initial_asnval_diag.xml

### ISSUE THREAD

**Issue by mriglobal** [ncbi/pgap#87]
**Describe the bug**
Attempting to run PGAP locally on an assembly is being met with a series of errors in the cwltools.log. Note, this is not an issue on MG37 test data.
( @Severity="ERROR" or @Severity="REJECT" )
and not(contains(@code, "SEQ_DESCR_UnwantedCompleteFlag"))
and not(contains(@code, "SEQ_PKG_NucProtProblem"))
and not(contains(@code, "SEQ_INST_InternalNsInSeqRaw"))
and not(contains(@code, "GENERIC_MissingPubRequirement"))
and not(contains(@code, "SEQ_INST_ProteinsHaveGeneralID"))
and not(contains(@code, "SEQ_PKG_ComponentMissingTitle"))
and not(contains(@code, "SEQ_DESCR_ChromosomeLocation"))
and not(contains(@code, "SEQ_DESCR_MissingLineage"))
and not(contains(@code, "SEQ_DESCR_NoTaxonID"))
and not(contains(@code, "SEQ_FEAT_ShortIntron"))
and not(contains(@code, "SEQ_DESCR_OrganismIsUndefinedSpecies"))
and not(contains(@code, "SEQ_DESCR_StrainWithEnvironSample"))
and not(contains(@code, "SEQ_DESCR_BacteriaMissingSourceQualifier"))
]

These can presumably be traced to the initial_asnval_diag.xml file which reads 
Failer nodes:
<?xml version="1.0" encoding="UTF-8"?>
<message severity="ERROR" seq-id="lcl|1" code="SEQ_DESCR_DBLinkBadSRAaccession">Bad Sequence Read Archive format - Not yet assigned</message>

<?xml version="1.0" encoding="UTF-8"?>
<message severity="ERROR" seq-id="lcl|2" code="SEQ_DESCR_DBLinkBadSRAaccession">Bad Sequence Read Archive format - Not yet assigned</message>

<?xml version="1.0" encoding="UTF-8"?>
<message severity="ERROR" seq-id="lcl|3" code="SEQ_DESCR_DBLinkBadSRAaccession">Bad Sequence Read Archive format - Not yet assigned</message>

<?xml version="1.0" encoding="UTF-8"?>
<message severity="ERROR" seq-id="lcl|4" code="SEQ_DESCR_DBLinkBadSRAaccession">Bad Sequence Read Archive format - Not yet assigned</message>

I am running on CentOS7 and using the 2020-07-09 build.

[submol.yaml.txt](https://github.com/ncbi/pgap/files/4933010/submol.yaml.txt)
[input.yaml.txt](https://github.com/ncbi/pgap/files/4933011/input.yaml.txt)

**Comment by azat-badretdin** [comment]
Thanks, we will have a look at this at earliest possiblity

**Comment by azat-badretdin** [comment]
That's the same imput genome you posted on the previous ticket, correct?

**Comment by mriglobal** [comment]
That's right

**Comment by azat-badretdin** [comment]
Please post input FASTA file

**Comment by mriglobal** [comment]
It's too large to submit through github. Can I email it to you?

**Comment by azat-badretdin** [comment]
Is it publicly available by any chance?

**Comment by mriglobal** [comment]
You can access it at ftp://bioinformatics.mriglobal.org/
It is labeled mtb67.fasta. Please let me know if you have any problems connecting.

**Comment by azat-badretdin** [comment]
Thanks. I will check it out.

**Comment by azat-badretdin** [comment]
I reproduced the error. For some reason XML file output was not displayed properly in your copy paste. Here is actual XML output: ```Failer nodes:
<?xml version="1.0" encoding="UTF-8"?>
<message severity="ERROR" seq-id="lcl|1" code="SEQ_DESCR_DBLinkBadSRAaccession">Bad Sequence Read Archive format - Not yet assigned</message>

<?xml version="1.0" encoding="UTF-8"?>
<message severity="ERROR" seq-id="lcl|2" code="SEQ_DESCR_DBLinkBadSRAaccession">Bad Sequence Read Archive format - Not yet assigned</message>

<?xml version="1.0" encoding="UTF-8"?>
<message severity="ERROR" seq-id="lcl|3" code="SEQ_DESCR_DBLinkBadSRAaccession">Bad Sequence Read Archive format - Not yet assigned</message>

<?xml version="1.0" encoding="UTF-8"?>
<message severity="ERROR" seq-id="lcl|4" code="SEQ_DESCR_DBLinkBadSRAaccession">Bad Sequence Read Archive format - Not yet assigned</message>```

**Comment by azat-badretdin** [comment]
I reproduced the output. Unfortunately, copy pasting XML output does not work here, so I am attaching it for posterity

[initial_asnval_diag.xml.txt](https://github.com/ncbi/pgap/files/4949065/initial_asnval_diag.xml.txt)

**Comment by azat-badretdin** [comment]
The cause of error: incorrect format for SRA accession in `sra:` field of the input `submol.yaml` file

When I removed it locally computation passed beyond the original point of breakage.
