### ISSUE TITLE
fail to annotate my file

### ISSUE THREAD

**Issue by shakti83kumar** [ncbi/pgap#88]
Hi SIr,
I herewith attach input.ymal, submol.ymal and sequence file in zip. I modified ymals file as mentioned in manual, but I got following output massage. Please help me to rid of this problem

[input_files.zip](https://github.com/ncbi/pgap/files/4959208/input_files.zip)
regards
Shakti Kumar
THSTI, India
  
I ran this command:
sudo ./pgap.py -r -D /usr/bin/docker -o LACT_result test_genomes/LACTO/input.yaml

Output :

PGAP version 2020-07-09.build4716 is up to date.
Output will be placed in: /home/drbhabatoshdas/Softwares/pgap/scripts/LACT_result.2
PGAP failed, docker exited with rc = 1
Printing log starting from failed job:

[2020-07-22 09:21:00] INFO [step fastaval] start
[2020-07-22 09:21:00] INFO [job fastaval] /tmp/btg4f5dj$ fastaval.sh \
    -check_internal_ns \
    -check_min_seqlen \
    200 \
    -in \
    /tmp/tmpkge_fmpl/stgadcee4a4-e0f8-47fe-86ce-e1393bd1fdfe/Lactobacillus_S1_L001_scaffolds.fasta \
    -out \
    fastaval.xml
+ POSITIONAL=()
+ ignore_all_errors=false
+ [[ 7 -gt 0 ]]
+ key=-check_internal_ns
+ case "$key" in
+ POSITIONAL+=("$key")
+ shift
+ [[ 6 -gt 0 ]]
+ key=-check_min_seqlen
+ case "$key" in
+ POSITIONAL+=("$key")
+ shift
+ [[ 5 -gt 0 ]]
+ key=200
+ case "$key" in
+ POSITIONAL+=("$key")
+ shift
+ [[ 4 -gt 0 ]]
+ key=-in
+ case "$key" in
+ POSITIONAL+=("$key")
+ shift
+ [[ 3 -gt 0 ]]
+ key=/tmp/tmpkge_fmpl/stgadcee4a4-e0f8-47fe-86ce-e1393bd1fdfe/Lactobacillus_S1_L001_scaffolds.fasta
+ case "$key" in
+ POSITIONAL+=("$key")
+ shift
+ [[ 2 -gt 0 ]]
+ key=-out
+ case "$key" in
+ POSITIONAL+=("$key")
+ shift
+ [[ 1 -gt 0 ]]
+ key=fastaval.xml
+ case "$key" in
+ POSITIONAL+=("$key")
+ shift
+ [[ 0 -gt 0 ]]
+ set -- -check_internal_ns -check_min_seqlen 200 -in /tmp/tmpkge_fmpl/stgadcee4a4-e0f8-47fe-86ce-e1393bd1fdfe/Lactobacillus_S1_L001_scaffolds.fasta -out fastaval.xml
+ set +e
+ fastaval -check_internal_ns -check_min_seqlen 200 -in /tmp/tmpkge_fmpl/stgadcee4a4-e0f8-47fe-86ce-e1393bd1fdfe/Lactobacillus_S1_L001_scaffolds.fasta -out fastaval.xml
+ result=255
+ set -e
+ false
+ exit 255
[2020-07-22 09:21:01] WARNING [job fastaval] completed permanentFail
[2020-07-22 09:21:01] WARNING [step fastaval] completed permanentFail
[2020-07-22 09:21:01] INFO [workflow ] completed permanentFail
[2020-07-22 09:21:01] WARNING Final process status is permanentFail
{
    "calls": null,
    "final_asndisc_error_diag": null,
    "final_asnval_error_diag": null,
    "gbk": null,
    "gff": null,
    "initial_asndisc_error_diag": null,
    "initial_asnval_error_diag": null,
    "input_fasta": {
        "class": "File",
        "location": "file:///pgap/output/Lactobacillus_S1_L001_scaffolds.fasta",
        "size": 2331305,
        "basename": "Lactobacillus_S1_L001_scaffolds.fasta",
        "checksum": "sha1$b3a2448c1e48ec700c97ef3378d8ef1e306fa0cf",
        "path": "/pgap/output/Lactobacillus_S1_L001_scaffolds.fasta"
    },
    "input_submol": {
        "class": "File",
        "location": "file:///pgap/output/pgap_submol_10rqumoo.yaml",
        "size": 1523,
        "basename": "pgap_submol_10rqumoo.yaml",
        "checksum": "sha1$56232059911a484fb9b83acc57c8e7312e8dd92d",
        "path": "/pgap/output/pgap_submol_10rqumoo.yaml"
    },
    "nucleotide_fasta": null,
    "protein_fasta": null,
    "sqn": null
}

**Comment by azat-badretdin** [comment]
I looked at your input FASTA file. Most likely the problem is in having an internal gap (stretch of N's) inside a contig. You have this.

Options

1/ you can edit your sequence and convert this contig into two, splitting it by the gap and try again
2/ OR you can rerun the same command with `--debug` options and then run the command `find . -name fastaval.xml` and attach it to this ticket
3/ you can rerun the same command with `--ignore-all-errors` flag to ignore this error.

**Comment by azat-badretdin** [comment]
Your input sequence FASTA contains 120 contigs shorter than 200 nucleotides. cf https://github.com/ncbi/pgap/wiki/Input-Files

**Comment by shakti83kumar** [comment]
Dear Azat Sir,
As per your suggestion, I remove the those fasta seq whose length is less than 200 bp. After that I ran 
sudo ./pgap.py -r -D /usr/bin/docker -o LACT_result test_genomes/LACTO/input.yaml --debug
then 'find . -name fastaval.xml' command.
then I got following output

find . -name fastaval.xml
find: ‘./LACT_result/debug/tmp-outdir/tp0y04b4’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/0xutcvl2’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/ml1l59t_’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/b2ghod6j’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/bye5p5es’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/u2p37_0j’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/9bken7fl’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/ktzqei7c’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/2m1foi7k’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/y2f55kom’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/zfrt75qm’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/1guuv1fw’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/uv8dsi7y’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/wgjd6x0n’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/1prd176v’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/15opsj14’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/rzqc8ycv’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/vy0jeh49’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/xvweqkyd’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/sr6o1e91’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/497cbdt6’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/4hv6tf__’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/3x2b27q0’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/1vqxs6pv’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/znnmln7p’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/uq0mwhn3’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/6v45cq45’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/18vcpel_’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/vkqw4fml’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/3teacuba’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/qxvbtx60’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/ssik8sci’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/_ixkp1yz’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/zdskk927’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/42qrc6e9’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/sanny9l3’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/6yjjybp6’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/jw304n9c’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/yr5e44p1’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/cld4vgbu’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/bdtng6v9’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/ee5rwga_’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/rfjj9wfk’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/tvk8q88n’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/ex050bfe’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/yi9hkrie’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/_0k08ehb’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/_bfmpfke’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/dzk5nyro’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/c3exuu3p’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/w6p3_b4e’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/ew96dgna’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/qjmchaw3’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/w9o_yyrs’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/o8_qmcv4’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/2e0fx9ad’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/kckpkejt’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/4chihb8t’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/sw1r7ev0’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/rtlnmyr2’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/jwjaribl’: Permission denied
find: ‘./LACT_result/debug/tmp-outdir/bwcu23n9’: Permission denied

**Comment by azat-badretdin** [comment]
Did it stop with the same result, at fastaval node?

**Comment by azat-badretdin** [comment]
Since you had to run pgap.py with sudo, you also need to run `find` with `sudo`: `sudo find . -name fastaval.xml'  you can also change ownership of your local files to yourself as well using `sudo chown -R .... ` command

**Comment by shakti83kumar** [comment]
Ok Sir..
Let me try
