### ISSUE TITLE
Any success under MacOS?

### ISSUE THREAD

**Issue by gdp3** [ncbi/pgap#9]
Before I waste any additional time trying what is known not to work ... a quick try under MacOS 10.13.6 with Anaconda fails before anything is actually installed (see below). Is it even worth pursuing?

guy@thermopylae/usr/local/ncbi: sudo ./pgap.py --update
Password:
Updating PGAP to version 2019-02-11.build3477 (previous version was None)
Downloading (as needed) PGAP Docker image version 2019-02-11.build3477
Traceback (most recent call last):
  File "./pgap.py", line 275, in <module>
    main()
  File "./pgap.py", line 261, in main
    version = setup(args.update, args.local_runner)
  File "./pgap.py", line 174, in setup
    install_docker(latest)
  File "./pgap.py", line 88, in install_docker
    subprocess.check_call([docker, 'pull', get_docker_image(version)])
  File "/Users/guy/anaconda2/lib/python2.7/subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/Users/guy/anaconda2/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/Users/guy/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/Users/guy/anaconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by slottad** [comment]
While our support for non-Linux hosts is nascent, we have gotten it to run successfully on both Windows and OSX. Not without some tribulations however. The next version should support both as first class citizens.

Your specific problem here is that you don't appear to have docker installed, or at least is not in your path. You'll need to install it and enable Linux container support.

**Comment by gdp3** [comment]
I have now successfully installed on two different Macs (both macOS 10.13) and run the test genome. Running some other genomes now. One machine had a lot of tools already installed, but on the other all I did was install Xcode, Docker, and Python 3.7 from python.org.

**Comment by whlavina** [comment]
We have run tests on a Mac with only Docker and Python 3 installed (Xcode shouldn't be required). Our FAQ  includes the question "Can I run under MacOS or Windows?" clarifying that Linux is our primary development platform, but that the other platforms should work.

Therefore, let's close this issue; feel free to reopen as necessary.
