### ISSUE TITLE
[BUG] Potential Syntax Issue?

### ISSUE THREAD

**Issue by DMcClung17** [ncbi/pgap#90]
Hello,

I've been having trouble running PGAP on my genome. I tested the mg37 data, and it annotated fine. I had a few syntax errors in my .yaml files, which I fixed. But I can't seem to understand what the next error is. I've attached my input .yaml files as .txt files below, with the cwltool.log file. I can send my genome .fasta file over, too, if needed.

I'm not an experienced coder, so this may be a really simple issue. Please let me know how to proceed.

Software versions
 - OS: macOS High Sierra 10.13.6
 - pgap.py is the most recent update ("PGAP version 2020-07-09.build4716 is up to date")
 - Docker version 19.03.8, build afacb8b

Best,
Dylan

[cwltool.log](https://github.com/ncbi/pgap/files/5004221/cwltool.log)
[Couch_T094.txt](https://github.com/ncbi/pgap/files/5004230/Couch_T094.txt)
[pgap_Annotation.txt](https://github.com/ncbi/pgap/files/5004231/pgap_Annotation.txt)

**Comment by thibaudnis** [comment]
Hi! I suspect that the brackets and parentheses in your yaml file Couch_T094.txt are causing the issue. Check also that you are using spaces rather than tabs for indentation. Please see the example yaml file in https://github.com/ncbi/pgap/wiki/Input-Files. Good luck!

**Comment by DMcClung17** [comment]
Hi,
I've removed those brackets and parentheses, and changed tabs to spaces. However, I've gotten a new error that I can't figure out: [cwltool_4.00pm.log](https://github.com/ncbi/pgap/files/5011391/cwltool_4.00pm.log)

I've also run the program with dashes/hyphens in for the author list in the submol.yaml file (as shown on your Input Files page), but I keep getting an error for the hyphens, so I removed them. Here is the updated .yaml file that I'm using (in addition to the same pgap_Annotation.yaml file that I uploaded previously).
[Couch_T094v2.txt](https://github.com/ncbi/pgap/files/5011393/Couch_T094v2.txt)

Best,
Dylan

**Comment by thibaudnis** [comment]
YAML is finicky with indentation. Try two-space indents:
```
authors:
  - author:
      last_name: 'McClung'
      first_name: 'Dylan'
      middle_initial: 'J'
  - author:
      last_name: 'Traxler'
      first_name: 'Matthew'
      middle_initial: 'F'
```

**Comment by DMcClung17** [comment]
I already have two spaces before last_name, first_name, etc. Do you mean two indents before "- author:" ?

**Comment by whlavina** [comment]
May I suggest you try a YAML validator. Unfortunately, several of the online ones I tried appear to be incomplete and identify invalid YAML as valid, so you may need to try more than one. I cannot make an informed recommendation at this time, but I did have success identifying errors with these two:
* https://onlineyamltools.com/validate-yaml
* https://yamlchecker.com/

**Comment by DMcClung17** [comment]
It seems to be running! Thank you for all your help!
