### ISSUE TITLE
[Error] Unable to run MG37 test

### ISSUE THREAD

**Issue by JuantonioMS** [ncbi/pgap#91]
I run:
sudo ./pgap.py -r -o results test_genomes/MG37/input.yaml

Shell Output:
PGAP version 2020-07-09.build4716 is up to date.
Output will be placed in: /home/lab/pgap/results
PGAP failed, docker exited with rc = 1
Unable to find error in log file.

Log Output:
Original command: ./pgap.py -r -o results test_genomes/MG37/input.yaml

Docker command: /usr/bin/docker run -i --rm --user 0:0 --volume /home/lab/pgap/input-2020-07-09.build4716:/pgap/input:ro,z --volume /home/lab/pgap/test_genomes/MG37:/pgap/user_input:z --volume /home/lab/pgap/test_genomes/MG37/pgap_input_8h26awfm.yaml:/pgap/user_input/pgap_input.yaml:ro,z --volume /home/lab/pgap/results:/pgap/output:rw,z ncbi/pgap:2020-07-09.build4716 cwltool --timestamps --disable-color --preserve-entire-environment --outdir /pgap/output pgap/pgap.cwl /pgap/user_input/pgap_input.yaml

--- Start YAML Input ---
fasta:
  class: File
  location: ASM2732v1.annotation.nucleotide.1.fasta
submol:
  class: File
  location: pgap_submol_vgnhnih7.yaml
supplemental_data: { class: Directory, location: /pgap/input }
report_usage: true
--- End YAML Input ---

--- Start Runtime Report ---
{
    "CPU cores": 32,
    "Docker image": "ncbi/pgap:2020-07-09.build4716",
    "cpu flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d",
    "cpu model": "Intel(R) Xeon(R) CPU E5-4610 v2 @ 2.30GHz",
    "max user processes": "unlimited",
    "memory (GiB)": 251.9,
    "memory per CPU core (GiB)": 7.9,
    "open files": 1048576,
    "tmp disk space (GiB)": 233.8,
    "virtual memory": "unlimited",
    "work disk space (GiB)": 233.8
}
--- End Runtime Report ---

[2020-08-10 12:30:13] INFO /usr/local/bin/cwltool 3.0.20200706173533
[2020-08-10 12:30:13] INFO Resolved 'pgap/pgap.cwl' to 'file:///pgap/pgap/pgap.cwl'
[2020-08-10 12:30:13] ERROR Tool definition failed validation:
[Errno 21] Is a directory: '/pgap/user_input/pgap_input.yaml'

**Comment by azat-badretdin** [comment]
Thanks for your report.

We had a similar issue https://github.com/ncbi/pgap/issues/21 in the past. It seemed to be related to not "clean" initial directory.

**Comment by JuantonioMS** [comment]
Hi!
I solved the problem. The problem is using PGAP Docker image within a Ubuntu Docker image. It is an external problem.
Thanks!

**Comment by azat-badretdin** [comment]
Thanks for posting this comment. It's very useful to know how our software is used.
