### ISSUE TITLE
what does --no-internet do?

### ISSUE THREAD

**Issue by MrTomRod** [ncbi/pgap#92]
What is the effect of the `--no-internet` flag? In FAQ, it says "It will disable internet access for all programs in the pipeline.", but will this have an effect on the quality of the output?

**Comment by azat-badretdin** [comment]
It should have no effect on the quality of the output.

**Comment by MrTomRod** [comment]
thanks for the immediate reply!

**Comment by azat-badretdin** [comment]
You are welcome!
