### ISSUE TITLE
missing passdata folder and three files name "taxon_db", "adaptor_fasta" and "contam_in_prok_blastdb_dir" 

### ISSUE THREAD

**Issue by panbei2014** [ncbi/pgap#93]
Hi, I run pgap in docker environment. Please see commond as bellow: 

cwltool  pgap.cwl /pgap/user_input/input.yaml --fasta /pgap/user_input/MG37/ASM2732v1.annotation.nucleotide.1.fa --report_usage --submol /pgap/user_input/MG37/submol.yaml  --ignore_all_errors

And, there are some errors emerged, which indicated that some files couldn't find. I know this forlder should generate in the process , but  I couldn't find the key folder "passdata" anywhere in the end. Could anyone help me to resolve this problem? Many Thanks!

Please see the error as bellow:

INFO [workflow ] starting step passdata
INFO [step passdata] start
ERROR [step passdata] Output is missing expected field file:///pgap/pgap/pgap.change.cwl#passdata/taxon_db
ERROR [step passdata] Output is missing expected field file:///pgap/pgap/pgap.change.cwl#passdata/adaptor_fasta
ERROR [step passdata] Output is missing expected field file:///pgap/pgap/pgap.change.cwl#passdata/contam_in_prok_blastdb_dir
WARNING [step passdata] completed permanentFail
INFO [workflow ] completed permanentFail
{
    "calls": null,

**Comment by gracem97** [comment]
Hi,
I am wondering how did you generate the .yaml file? Is it the input_simple.yaml from the main github page with your file locations added in?

Ty

**Comment by azat-badretdin** [comment]
This is not really a supported way to run PGAP right now. We specifically created `pgap.py` to make the life of the end-user easier. Advanced users can call cwltool directly, but they are responsible to provide all the input to `pgap.cwl` correctly

In this case you most likely missing files from input/ directory, you need to extract files from both reference data tarballs, for pgap and for ani.

**Comment by gracem97** [comment]
Hi Azat,

I am running the pipeline from the youtube tutorial, [NCBI Minute: Running the NCBI PGAP on Your Own Data](https://www.youtube.com/watch?v=pNn_-_46lpI), and it requires a .yaml file.

pgap.py uses the .yaml file, and the docker image that gives the reference data.

The example says to run pgap.py -r -o K_pneu_results K_pneu.yaml

Do you suggest I run it like pgap.py -r -o output_dir input.fa ?

Grace

**Comment by thibaudnis** [comment]
Grace, please look at the Wiki, in particular: https://github.com/ncbi/pgap/wiki/Input-Files

**Comment by panbei2014** [comment]
Hi, Grace
     Actually, I changed some points in  templet  yaml files, which try to adjusted the temple files to my data. But, there are some mistakes when I run with changed templete files. So, sorry for not being able to provide more help information about yaml file making.
Hi, Azat 
    Thanks for your reply. Due to our Company Service couldn't support download/update software or files from the weblink which used in PAGP (My Company located in China).  So , I select the second plane that run PGAP in docker environment. 
   I will try to check the input file, Thanks.
