### ISSUE TITLE
[FEATURE REQUEST] named containers

### ISSUE THREAD

**Issue by MrTomRod** [ncbi/pgap#94]
#### PROBLEM:
It's hard to see which docker container belongs to which genome assembly, especially if many containers are running at the same time.

#### SOLUTION:
Additional optional argument for `pgap.py`: `--container-name`

The docker_cmd and podman_cmd would have to be adapted like this:

```python
if (self.params.container_name):
    self.cmd.extend(['--name', self.params.container_name])
```
I don't know how it works with singularity.

**Comment by MrTomRod** [comment]
Even better: allow custom additional arguments for docker!

Additional optional argument for `pgap.py`: `--docker-args`.

Argparse would read it like this:

```python
parser.add_argument('--docker-args', type=ast.literal_eval)
```

The docker_cmd, podman_cmd and singularity_cmd would have to be adapted like this:
```python
if (self.params.docker_args):
    assert type(self.params.docker_args) is list, "parameter --docker-args must be a list, for example like this: --docker-args=\"['--network', 'host']\""
    self.cmd.extend(self.params.docker_args)
```


Run `pgap.py` as follows, for example:
`./pgap.py --docker-args="['--name', 'NameOfDockerContainer', '--network', 'host']" (...)`

**Comment by thibaudnis** [comment]
Thank you for the suggestion! We are considering it, but currently have other priorities. Maybe in the fall.
