### ISSUE TITLE
ERROR: Unknown option: -v692177 bytes (100.00%)

### ISSUE THREAD

**Issue by clavia96** [ncbi/pgap#95]
Hi, 

I ran PGAP on the test genome provided. The output folder was created, however, the only file there is a cwltool. log. Upon checking my output log file, i found the error below. I used version 2020-07-09.build4716

ERROR: Unknown option: -v692177 bytes (100.00%)

Any idea what might be causing this error?

**Comment by azat-badretdin** [comment]
Could you please post your `cwltool.log`?

**Comment by clavia96** [comment]
here it is

Original command: ./pgap.py -D singularity -r -o mg37_results test_genomes/MG37/input.yaml

Docker command: /tools/singularity-2.6.1/bin/singularity run -i --rm --volume /gpfs01/scratch/oluchi/PGAP/input-2020-07-09.build4716:/pgap/input:ro,z --volume /gpfs01/s
cratch/oluchi/PGAP/test_genomes/MG37:/pgap/user_input:z --volume /gpfs01/scratch/oluchi/PGAP/test_genomes/MG37/pgap_input_esn532vc.yaml:/pgap/user_input/pgap_input.yaml
:ro,z --volume /gpfs01/scratch/oluchi/PGAP/mg37_results:/pgap/output:rw,z ncbi/pgap:2020-07-09.build4716 cwltool --timestamps --disable-color --preserve-entire-environm
ent --outdir /pgap/output pgap/pgap.cwl /pgap/user_input/pgap_input.yaml

--- Start YAML Input ---
fasta:
  class: File
  location: ASM2732v1.annotation.nucleotide.1.fasta
submol:
  class: File
  location: pgap_submol__is3sej9.yaml
supplemental_data: { class: Directory, location: /pgap/input }
report_usage: true
--- End YAML Input ---

--- Start Runtime Report ---

**Comment by azat-badretdin** [comment]
I do not see the error line. Could you please attach the file?

**Comment by clavia96** [comment]
The error line is in output log file - i am running PGAP on my schools supercomputer.

The beginnig of the file looks like this

ERROR: pull is only supported for shub URIs
Downloaded 143872 of 16363164574 bytes (0.00%)
Downloaded 287232 of 16363164574 bytes (0.00%)
Downloaded 430592 of 16363164574 bytes (0.00%)
Downloaded 584192 of 16363164574 bytes (0.00%)

while the last line shows

ERROR: Unknown option: -v692177 bytes (100.00%)

**Comment by azat-badretdin** [comment]
Could you please save this output by redirecting: `pgap.py ..... &> output.log.txt` and post it?

**Comment by clavia96** [comment]
I just did that and got the output below.

PGAP version 2020-07-09.build4716 is up to date.
WARNING: 2.6.1-dist support as Docker alternative has not been tested
Output will be placed in: /gpfs01/scratch/oluchi/PGAP/mg37_results
Command '['/tools/singularity-2.6.1/bin/singularity', 'run', '-i', '-v', '/gpfs01/scratch/oluchi/PGAP:/cwd', 'ncbi/pgap:2020-07-09.build4716', 'bash', '-c', 'df -k /cwd
 /tmp ; ulimit -a ; cat /proc/{meminfo,cpuinfo}']' returned non-zero exit status 1.

**Comment by whlavina** [comment]
Those are the wrong command line arguments for Singularity (existence of `-v` option). Did you still include `-D singularity` in that execution? Maybe our script is identifying the runner as Docker, by mistake (code in `get_docker_info`). What's the output of `singularity --version`?

**Comment by clavia96** [comment]
Yes , i did include -D singularity in the execution. The version of singularity is 2.4.2-dist

**Comment by whlavina** [comment]
We need the exact output from `singularity --version`. Can you please provide it?

Our script is looking for the string `"singularity"` (exact case-sensitive string match) as the first word of the output, i.e. something like `singularity 2.6.1-dist`. From the `Warning` message in your log above, the first word of the output is the version number, `2.6.1-dist`. We weren't expecting that. If you are comfortable editing `pgpap.py`, try changing the logic in `get_docker_info`, and run it again, adding `--no-self-update` (otherwise it will overwrite your script edits).

**Comment by clavia96** [comment]
The singularity --version output is 2.6.1-dist, there is no string before it.
Just to be clear, where in the get_docker_info part of the script should i add --no-self-update. 
Below is what that part of the script looks like in my end.

self.get_docker_info()                                                                                                                                                                                                                       if (self.local_version != self.use_version) or not self.check_install_data():                                                                                                                                                                    self.update()

**Comment by clavia96** [comment]
The singularity --version output is 2.6.1-dist, there is no string before it.
Just to be clear, where in the get_docker_info part of the script should i add --no-self-update.
Below is what that part of the script looks like in my end.

self.get_docker_info() 
if (self.local_version != self.use_version) or not self.check_install_data(): 
self.update()

**Comment by azat-badretdin** [comment]
> where in the get_docker_info part of the script should i add --no-self-update.

**Comment by whlavina** [comment]
If you're not a Python developer and can wait, I think we can implement a fix in a reasonable timeframe. The information you provided clarified the immediate problem.

**Comment by clavia96** [comment]
I am not a developer, any idea how long it will take to fix this?

**Comment by whlavina** [comment]
Easiest tweak you can try right now, edit `pgap.py` around line 577, just before the WARNING line, to indicate `singularity` instead of `docker`:

```
            self.docker_type = 'singularity'
            print('WARNING: {} support as Docker alternative has not been tested'.format(docker_alternative))
```

Then run:
```
./pgap.py --no-self-update -D singularity -r -o mg37_results test_genomes/MG37/input.yaml
```

**Comment by clavia96** [comment]
I did that and i got this errors in my output log file

The first few lines shows this:
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
ERROR: You must install squashfs-tools to build images
ABORT: Aborting with RETVAL=255
ERROR: pulling container failed!
Downloaded 205312 of 16363164574 bytes (0.00%)

while the last lines shows this:
tar: var/lib/yum/yumdb/t/2bd9840006c8c4dec80e3cdee59ad0b3c516bbbb-trousers-0.3.14-2.el7-x86_64/.wh..wh..opq: implausibly old time stamp 1969-12-31 18:00:00
tar: var/lib/yum/yumdb/u/22d3f39031111377e27dce84aa62328410135a16-unzip-6.0-21.el7-x86_64/.wh..wh..opq: implausibly old time stamp 1969-12-31 18:00:00
tar: var/lib/yum/yumdb/u/75adbd0ecb01c50bba42243fc16684df390cbca4-util-linux-2.23.2-63.el7-x86_64/.wh..wh..opq: implausibly old time stamp 1969-12-31 18:00:00
tar: var/lib/yum/yumdb/y/4a36daed3e710fd273c0cf5b41d36929fca225b7-yum-utils-1.1.31-54.el7_8-noarch/.wh..wh..opq: implausibly old time stamp 1969-12-31 18:00:00
tar: var/lib/yum/yumdb/y/589cc1da1ce3d7a71b73de98ef0e3c876388ed2b-yum-3.4.3-167.el7.centos-noarch/.wh..wh..opq: implausibly old time stamp 1969-12-31 18:00:00
tar: var/lib/yum/yumdb/y/9819fbb16bdd52de5732405cfb88b4cffeedfca6-yum-plugin-ovl-1.1.31-54.el7_8-noarch/.wh..wh..opq: implausibly old time stamp 1969-12-31 18:00:00
tar: var/lib/yum/yumdb/y/de6bdc73eecf230839ee5408e50c1b987e695606-yum-plugin-fastestmirror-1.1.31-54.el7_8-noarch/.wh..wh..opq: implausibly old time stamp 1969-12-31 18:00:00
tar: var/lib/yum/yumdb/z/ccee29b0ebdbefdec09bb543d7ef43882836c1da-zip-3.0-11.el7-x86_64/.wh..wh..opq: implausibly old time stamp 1969-12-31 18:00:00
tar: Exiting with failure status due to previous errors
Warning: Permanently added 'node062,192.168.10.62' (RSA) to the list of known hosts.

**Comment by whlavina** [comment]
It looks like your version of Singularity is either incomplete or may be too old. Unfortunately, we don't have the resources to help you with Singularity setup. Please try:
```
singularity pull docker://ncbi/pgap:2020-07-09.build4716
```

If that produces an error, then you will need to resolve the issue before we can provide any further help.
